### ISSUE TITLE
hammer organization add-smart-proxy

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1015]
hammer organization add-smart-proxy --help
Usage:
    hammer organization add-smart-proxy [OPTIONS]

Options:
    --id ID                        
    --name NAME                   Name to search by
    --smart-proxy SMART_PROXY_NAME  
    --smart-proxy-id SMART_PROXY_ID  
    -h, --help                    print help

**Comment by tkolhar** [comment]
sent pr : https://github.com/SatelliteQE/robottelo/pull/2085

**Comment by oshtaier** [comment]
Already covered
