### ISSUE TITLE
[Failed-AutoCherryPick] - GHA: Added support to handle auto-cherry-pick failure & create issue

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10222]
#### Auto-Cherry-Pick WorkFlow Failure:
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3362809313)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10211)

**Comment by omkarkhatavkar** [comment]
https://github.com/SatelliteQE/robottelo/pull/10223
