### ISSUE TITLE
[Failed-AutoCherryPick] - [6.11.z] Host content ownership

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10238]
#### Auto-Cherry-Pick WorkFlow Failure:
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3386822582)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10235)

**Comment by jyejare** [comment]
@shweta83  Please do the manual cherrypick as the auto-cherrypicking is failed !

**Comment by jyejare** [comment]
Ping @shweta83 !

**Comment by jyejare** [comment]
Closing this issue as dependent PR is merged!
