### ISSUE TITLE
[Failed-AutoCherryPick] - Do not install dogfood certs as we use CDN

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10247]
#### Auto-Cherry-Pick WorkFlow Failure:
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3409290021)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10239)

**Comment by jyejare** [comment]
@lpramuk Please do the manual cherrypick as the auto-cherrypicking is failed !

**Comment by lpramuk** [comment]
@jyejare heh I've done it 10mins before you have commented ;-)

**Comment by jyejare** [comment]
@lpramuk Wow! Feel free to close this issue mentioning that PR. OR you can always mention this issue in PR to auto close this.

**Comment by jyejare** [comment]
@lpramuk And seems you did it !

**Comment by Gauravtalreja1** [comment]
Closing this issue as PR https://github.com/SatelliteQE/robottelo/pull/10248 fixing this is already merged
