### ISSUE TITLE
[Failed-AutoCherryPick] - [6.11.z] Companion to Broker #170

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10253]
#### Auto-Cherry-Pick WorkFlow Failure:
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3417382004)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10244)

**Comment by jyejare** [comment]
Ping @JacobCallahan
