### ISSUE TITLE
[Failed-AutoCherryPick] - Parametrizing provisioning tests[BIOS/UEFI]

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#10267]
[Failed Action](https://github.com/SatelliteQE/robottelo/actions/runs/3435813474/jobs/5728617680)
[Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10237)

**Comment by jyejare** [comment]
Ping @shubhamsg199 !

**Comment by jyejare** [comment]
Ping @shubhamsg199 !

**Comment by shubhamsg199** [comment]
@jyejare There is another PR opened in the master with some changes(https://github.com/SatelliteQE/robottelo/pull/10273).
I would like to have that PR merged and cherry-pick that since it involves the same file changes. We can close this issue.

**Comment by jyejare** [comment]
@shubhamsg199 when that auto-cherrypick PRs opens, tag this issue there as `fixes #10267` to auto close this.

**Comment by jyejare** [comment]
@shubhamsg199 Looks like even cherrypick of https://github.com/SatelliteQE/robottelo/pull/10273 gone wrong so that means anyways we are missing these changes in 6.11 and below branches if needed.

Could you please manually Cherrypick the changes to 6.11 ?

**Comment by Gauravtalreja1** [comment]
PR https://github.com/SatelliteQE/robottelo/pull/10555 merged already
