### ISSUE TITLE
[Failed-AutoCherryPick] - RHSSO Helper Refactor

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#10268]
[Failed Action](https://github.com/SatelliteQE/robottelo/actions/runs/3431855605/jobs/5720479311)
[Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/9778)

**Comment by Gauravtalreja1** [comment]
Closing this issue as PR https://github.com/SatelliteQE/robottelo/pull/10290 fixing this is already merged
