### ISSUE TITLE
[Failed-AutoCherryPick] - [6.11.z] Cherrypick of Helpers Refactor (part2) and Utility modules movement

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10278]
#### Auto-Cherry-Pick WorkFlow Failure:
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3446554299)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10277)

**Comment by jyejare** [comment]
This is for cherrypicking to 6.10.z and TBH there is lot to be cherry-picked to 6.10.z so just cherry-picking this wouldn't be sufficient. We need to find  framework changes and cherry-pick things from 6.11.z/master to 6.10.z to support the PIT run.
