### ISSUE TITLE
[Failed-AutoCherryPick] fixing auto assigning to correct user rather SATQE bot

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#10270]
[Failed Action](https://github.com/SatelliteQE/robottelo/actions/runs/3410383178/jobs/5673281858)
[Parent PR](https://github.com/SatelliteQE/robottelo/pull/10241)

**Comment by Gauravtalreja1** [comment]
Closing this issue as PR https://github.com/SatelliteQE/robottelo/pull/10250 fixing this is already merged
