### ISSUE TITLE
[Failed-AutoCherryPick] - Fix Create Issue failing for sequence not expected

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10275]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3439316924)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10274)

**Comment by Gauravtalreja1** [comment]
Closing this issue as PR https://github.com/SatelliteQE/robottelo/pull/10250 fixing this is already merged
