### ISSUE TITLE
[Failed-AutoCherryPick] - Add marker and select initial end-to-end tests

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10283]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3459390187)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10281)

**Comment by Gauravtalreja1** [comment]
Closing this issue as PR https://github.com/SatelliteQE/robottelo/pull/10291 fixing this is already merged
