### ISSUE TITLE
hammer puppet-class sc-params 

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1028]
hammer puppet-class sc-params --help
Usage:
    hammer puppet-class sc-params [OPTIONS]

Options:
    --environment ENVIRONMENT_NAME  
    --environment-id ENVIRONMENT_ID  
    --host HOST_NAME               
    --host-id HOST_ID              
    --hostgroup HOSTGROUP_NAME     
    --hostgroup-id HOSTGROUP_ID    
    --id ID                        
    --name NAME                   Name to search by
    --order ORDER                 sort results
    --page PAGE                   paginate results
    --per-page PER_PAGE           number of entries per request
    --puppetclass PUPPETCLASS_NAME  
    --puppetclass-id PUPPETCLASS_ID  
    --search SEARCH               Filter results
    -h, --help                    print help

**Comment by pondrejk** [comment]
Currently:

```
hammer puppet-class sc-params --help
Usage:
    hammer puppet-class sc-params [OPTIONS]

Options:
 --order ORDER                     sort results
 --page PAGE                       paginate results
 --per-page PER_PAGE               number of entries per request
 --puppet-class PUPPET_CLASS_NAME  Puppet class name
 --puppet-class-id PUPPET_CLASS_ID ID of Puppet class
 --search SEARCH                   filter results
 -h, --help                        print help
```

Also:

```
hammer puppet-class smart-variables --help
Usage:
    hammer puppet-class smart-variables [OPTIONS]

Options:
 --order ORDER                     sort results
 --page PAGE                       paginate results
 --per-page PER_PAGE               number of entries per request
 --puppet-class PUPPET_CLASS_NAME  Puppet class name
 --puppet-class-id PUPPET_CLASS_ID ID of Puppet class
 --search SEARCH                   filter results
 -h, --help                        print help
```
