### ISSUE TITLE
[Failed-AutoCherryPick] - Cleaning up Libvirt Discovery tests

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10294]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3468290302)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10187)

**Comment by jyejare** [comment]
Ping @Griffin-Sullivan !

**Comment by Griffin-Sullivan** [comment]
@jyejare I ended up cherry-picking two commits together https://github.com/SatelliteQE/robottelo/pull/10299/commits.

**Comment by jyejare** [comment]
@Griffin-Sullivan Thats for good. You should be able to close 2 PRs in one go :)
