### ISSUE TITLE
[Failed-AutoCherryPick] - Port/refactor of f-m service tests from testfm

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10307]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3478719951)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10231)

**Comment by Gauravtalreja1** [comment]
Closing this issue as dependant PR https://github.com/SatelliteQE/robottelo/pull/10312 is merged
