### ISSUE TITLE
[Failed-AutoCherryPick] -  Add f-m upgrade tests to robottelo with capsule parametrization

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10300]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3472430441)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10227)

**Comment by Gauravtalreja1** [comment]
Closing this issue, as dependent PR is merged
