### ISSUE TITLE
[Failed-AutoCherryPick] - Bump actions/stale from 5 to 6

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10330]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3521479224)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10329)

**Comment by jyejare** [comment]
This does not need cherrypicking , wrong label was marked ! So closing this issue now!
