### ISSUE TITLE
[Failed-AutoCherryPick] - updating the bot user to satqe bot

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10358]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3564784227)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10357)

**Comment by ogajduse** [comment]
resolved by https://github.com/SatelliteQE/robottelo/pull/10359
