### ISSUE TITLE
[Failed-AutoCherryPick] - Skip manifest import when running test against stage console.redhat.com

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10352]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3548897592)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10351)

**Comment by ogajduse** [comment]
Resolved, PR was merged.
