### ISSUE TITLE
Use factory for exception handling to avoid issues with generic exceptions.

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#1036]
As per comments in PR 1003..

--
We should start thinking on more specialized exceptions. This will avoid unwanted behaviour. This will require a big refactor, but we can start thinking and even start implementing and changing when a PR request touch some file that have generic exception.

For example https://github.com/omaciel/robottelo/blob/master/robottelo/factory.py#L63

**Comment by elyezer** [comment]
This is done on #2070, closing this.
