### ISSUE TITLE
[Failed-AutoCherryPick] - Fix pxeloader parametrization

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10380]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3591412947)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10273)

**Comment by jyejare** [comment]
@shubhamsg199 Could you please manually cherrypick this change if not already else close this with correct PR mentioned here.

**Comment by ogajduse** [comment]
@shubhamsg199 Do you have this issue on your radar?

**Comment by shubhamsg199** [comment]
yes @ogajduse I have, was having some issues with 6.12  locally. I will manually cherrypick this .
