### ISSUE TITLE
[Failed-AutoCherryPick] - Manifest helper refactor

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10409]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3646767806)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10232)

**Comment by jyejare** [comment]
@shweta83  Could you please manually cherrypick this change if not already else close this with correct PR mentioned here.

**Comment by shweta83** [comment]
> @shweta83 Could you please manually cherrypick this change if not already else close this with correct PR mentioned here.
I will manually cherrypick it.

**Comment by ogajduse** [comment]
Reopening as this issue is a blocker for #10627.
@shweta83 could you please take some time to cherry-pick this one as @jyejare requested above?

**Comment by shweta83** [comment]
Failed CP is address in PR https://github.com/SatelliteQE/robottelo/pull/11810
