### ISSUE TITLE
[Failed-AutoCherryPick] - [6.11.z] Add basic tests for dependencies

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10406]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.10.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3642349614)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10405)

**Comment by jyejare** [comment]
The manual PR is merge so closing it now !
