### ISSUE TITLE
[Failed-AutoCherryPick] - Moved manifest clone to robottelo.utils.manifest

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10416]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3657539140)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10415)

**Comment by jyejare** [comment]
@shweta83  Could you please manually cherrypick this change if not already else close this with correct PR mentioned here.

**Comment by shweta83** [comment]
> @shweta83 Could you please manually cherrypick this change if not already else close this with correct PR mentioned here.

I will manually cherrypick it.
