### ISSUE TITLE
[Failed-AutoCherryPick] - No-Cherrypick by default

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10437]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3713147481)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10436)

**Comment by jyejare** [comment]
Raised manual Cherrypick to Fix it https://github.com/SatelliteQE/robottelo/commit/28964726555de50829e7c1c90a737bb369d5f671 !
