### ISSUE TITLE
Set API version in request headers, not URL

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/robottelo#1043]
Currently, the [requests](http://docs.python-requests.org/en/latest/) wrapper in module `robottelo.api.client` is very thin. It differs from the wrapped client in the following ways:

* It logs information about HTTP requests which go out and the HTTP responses received back.
* It sets the content-type to application/json by default.
* It automatically encodes request data if the content-type is set to application/json.

One other change should be made:

* It sets the "version" header to "2" by default.

Doing this would allow us to change which version of the API is being tested without altering numerous URLs in module `robottelo.entities`.

Inspired by discussions in #966. Related to #979.

**Comment by elyezer** [comment]
Closing this in favor of https://github.com/SatelliteQE/nailgun/issues/102.

**Comment by Ichimonji10** [comment]
Thank you for migrating this bug.
