### ISSUE TITLE
Add CLI smoke/end to end test

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1056]
This should be a suite of tests to be run immediately after installing and configuring an instance.

Basic Smoke Test Scenario
=========================

First, check that default data is in place:

[x] - There is one organization called "Default_Organization".
[x] - There is one location called "Default_Location"
[x] - There is one capsule, whose name is equal to the hostname of the server.

Second, create some entities, with the following dependency tree:

 [x] - Organization
   [x] - Lifecycle Environment (name: "Library")
     [x] - Lifecycle Environment (name: random)
     [x] -  Lifecycle Environment (name: random)
   [x] - Product
   [x] - Repository (yum)
   [x] - Content View

The repository should be a "real" repository, pointing to actual yum
repositories.

Third, perform some additional actions:

[x] - Associate repository to content view
[x] - Publish the content view and promote it to all lifecycle
  environments

BONUS x 1
---------
[ ] - Check that the ``ping`` command is working
[ ] - Create a compute resource
[ ] - Create a subnet
[ ] - Create a domain
[ ] - Create a hostgroup with CV from above
[ ] - Create a host (baremetal, but never actually provisioned.  Just ensuring that the record can be setup)

BONUS x 2
---------
[ ] - Import a manifest
[ ] - Enable RHEL repos

**Comment by elyezer** [comment]
CLI smoke tests are already in place, closing this.
