### ISSUE TITLE
[Failed-AutoCherryPick] - Fix rh_cloud tests failing because of sca enabled manifest

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10655]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4126840811)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10646)

**Comment by jameerpathan111** [comment]
fix not required for 6.12.
