### ISSUE TITLE
[Failed-AutoCherryPick] - API utils helpers refactor:Part2

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10706]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4182954719)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10052)

**Comment by ogajduse** [comment]
@shweta83 Can you please cherry-pick #10052 to 6.12.z?

**Comment by shweta83** [comment]
Failed CP is address in PR https://github.com/SatelliteQE/robottelo/pull/11810
