### ISSUE TITLE
[Failed-AutoCherryPick] - API utils helpers refactor:Part2

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10705]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4182954719)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10052)

**Comment by ogajduse** [comment]
@shweta83 Could you take a look at this one? Changes from #10052 are missing in 6.11.z branch.

**Comment by shweta83** [comment]
Failed CP is address in PR https://github.com/SatelliteQE/robottelo/pull/11810
