### ISSUE TITLE
[Failed-AutoCherryPick] - [client, sync_plan, role] upgrade scenarios refactor

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10716]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4193901677)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10577)

**Comment by omkarkhatavkar** [comment]
https://github.com/SatelliteQE/robottelo/pull/10717 will fix this issue
