### ISSUE TITLE
[Failed-AutoCherryPick] - Bump python-box from 7.0.0 to 7.0.1

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10778]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4255426755)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10754)

**Comment by Gauravtalreja1** [comment]
Closing this issue as https://github.com/SatelliteQE/robottelo/pull/11167 is merged
