### ISSUE TITLE
[Failed-AutoCherryPick] - Implement retry logic in ohsnap helper methods using wait-for library

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10814]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4301919460)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10795)

**Comment by rplevka** [comment]
manual backports:
- [6.12.z](https://github.com/SatelliteQE/robottelo/pull/10817)
- [6.11.z](https://github.com/SatelliteQE/robottelo/pull/10818)
