### ISSUE TITLE
[Failed-AutoCherryPick] - Tests fixes using helper methods from api_factory

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10847]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4313629517)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10796)

**Comment by ogajduse** [comment]
@shweta83 Could you please take a bit of time to address this missing cherry-pick?

**Comment by ogajduse** [comment]
@shweta83 ping

**Comment by shweta83** [comment]
Failed CP is address in PR https://github.com/SatelliteQE/robottelo/pull/11810
