### ISSUE TITLE
[Failed-AutoCherryPick] - Fix and extend ansible_collection install test

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10905]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4353511106)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10857)

**Comment by adarshdubey-star** [comment]
Hey, @Gauravtalreja1 can you please do a manual cherry-pick for this.

**Comment by Gauravtalreja1** [comment]
Closing this issue as #11004 is already merged
