### ISSUE TITLE
[Failed-AutoCherryPick] - [RFE] SAT-11254 Test Automation

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10956]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.10.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4420992851)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10836)

**Comment by ogajduse** [comment]
@damoore044 Are you sure by cherry-picking the change to 6.10? We do not maintain 6.10 as it is EOL already.

**Comment by damoore044** [comment]
@ogajduse Ahh I see, thank you. This bz was in 6.10 but it looks like the fix wasn't deployed to the latest 6.10.z, let's keep these changes out of 6.10 if not maintained
