### ISSUE TITLE
[Failed-AutoCherryPick] - Adapt to the current API endpoint path for client repos

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10985]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4467711334)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10983)

**Comment by Gauravtalreja1** [comment]
Closing this issue as PR https://github.com/SatelliteQE/robottelo/pull/10987 is already merged
