### ISSUE TITLE
[Failed-AutoCherryPick] - Bump actions/stale from 7 to 8

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11065]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4529164831)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11048)

**Comment by Gauravtalreja1** [comment]
Closing this issue as https://github.com/SatelliteQE/robottelo/pull/11167 is merged
