### ISSUE TITLE
Phoenix Team to move Errata scenario to the REX based

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#11101]
We are leaving this for @vsedmik Team to move this scenario to the REX based because:
- We are running out of time to do this scenario refactor. 
- The component-specific improvements is not part of upgrade scenarios refactor
- The Teams can better do the component specific refactor as experts than any JPL member.

_Originally posted by @jyejare in https://github.com/SatelliteQE/robottelo/pull/10930#discussion_r1152061336_

**Comment by ogajduse** [comment]
fixed by #10930
