### ISSUE TITLE
[Failed-AutoCherryPick] - [virt-who-config]-upgrade scenario refactor

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11115]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4573353030)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11107)

**Comment by ogajduse** [comment]
@yanpliu If you run virt-who tests from the `6.11.z` branch, could you please take some time to cherry-pick #11107 to `6.11.z`?

**Comment by yanpliu** [comment]
@ogajduse satellite6.11 sca mode is not sca mode disabled default, so it is not need to update the cherry-pick for satellite6.11.z

**Comment by ogajduse** [comment]
Closing due to above mentioned.
