### ISSUE TITLE
[Failed-AutoCherryPick] - Test for katello-tracer install through New Host UI

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11121]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4578272343)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11090)

**Comment by ogajduse** [comment]
@sambible Can you take a look at this one and cherry-pick it?
