### ISSUE TITLE
[Failed-AutoCherryPick] - Bump mheap/github-action-required-labels from 3 to 4

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11124]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4593906693)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11123)

**Comment by Gauravtalreja1** [comment]
Closing this issue as https://github.com/SatelliteQE/robottelo/pull/11167 is merged
