### ISSUE TITLE
[Failed-AutoCherryPick] - [6.12.z] add delay for errata check and fix wait_for parameters

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11156]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4609954402)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11149)

**Comment by ogajduse** [comment]
Closing as 6.11 is soon to be EOL
