### ISSUE TITLE
[Failed-AutoCherryPick] - [errata] - Upgrade scenario refactor

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11172]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4628020117)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10930)

**Comment by ogajduse** [comment]
linked PR was merged, closing
