### ISSUE TITLE
[Failed-AutoCherryPick] - New Hosts UI - Manage columns test

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11218]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4675601910)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11077)

**Comment by pnovotny** [comment]
Closing, PR #11235 merged.
