### ISSUE TITLE
[Failed-AutoCherryPick] - [Host]-Refactor upgrade tests for Host

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11227]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4679651634)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11120)

**Comment by omkarkhatavkar** [comment]
closing this as PR is merged
