### ISSUE TITLE
[Failed-AutoCherryPick] - added e2e markers to tests

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11340]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4796787680)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11271)

**Comment by Gauravtalreja1** [comment]
@ColeHiggins2 Are you going to cpick this to 6.13.z? 
e2e marks are not much useful for branches other than master

**Comment by ColeHiggins2** [comment]
Not needed in 6.13.
