### ISSUE TITLE
[Failed-AutoCherryPick] - webhook bz coverage added

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11413]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4885071610)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11399)

**Comment by pondrejk** [comment]
The target test changed a lot from 6.11, the scale of the needed amendments kind of lowers the value of doing the cp, hence decided to close this one
