### ISSUE TITLE
[Failed-AutoCherryPick] - [6.13.z] Cherrypick ad 2019

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11421]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4892037182)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11398)

**Comment by ogajduse** [comment]
@lhellebr Do you plan to cherry-pick this one to `6.11.z`? If so, could you take some time to cherry-pick it?

**Comment by ogajduse** [comment]
This issue was created due to CherryPick label being present in the parrent PR at the time when it was merged. It should have had NoCherryPick label assigned instead.
