### ISSUE TITLE
[Failed-AutoCherryPick] - virt-who config cases add create & delete to virtwho_config fixture for CLI/API/UI

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11449]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4935505919)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11245)

**Comment by ogajduse** [comment]
@yanpliu would you like #11245 to be cherry-picked to 6.12.z branch? If so, could you please raise a PR that cherry-picks the change?
