### ISSUE TITLE
[Failed-AutoCherryPick] - Add closed loop for BZ#1607706

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11440]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4926754031)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11432)

**Comment by Gauravtalreja1** [comment]
@shubhamsg199 are you planning to cpick this to 6.11.z?

**Comment by ogajduse** [comment]
PR closed
