### ISSUE TITLE
[Failed-AutoCherryPick] - Run Autocherrypick on merged PRs

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11489]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5025576376)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11379)

**Comment by jyejare** [comment]
Closing as PR #11508 merged
