### ISSUE TITLE
[Failed-AutoCherryPick] - Fix incorrect repos set for RHEL 8+ causing ValueError

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11499]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5042665982)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11446)

**Comment by ogajduse** [comment]
Linked PR was merged.
