### ISSUE TITLE
[Failed-AutoCherryPick] - Use pre_configured_capsule fixture to ensure we get the correct Capsule

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11493]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5028430189)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11406)

**Comment by ogajduse** [comment]
Linked PR was merged.
