### ISSUE TITLE
[Failed-AutoCherryPick] - Test case updated for RHEL6 client registration

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11554]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5119027657)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11538)

**Comment by Gauravtalreja1** [comment]
@shweta83 Are you planning to fix this?
