### ISSUE TITLE
[Failed-AutoCherryPick] - Remove @stream decorator

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11598]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5185749847)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11596)

**Comment by vsedmik** [comment]
Resolved
