### ISSUE TITLE
[Failed-AutoCherryPick] - Convert remaining tests to manifester

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11721]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5333281381)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11669)

**Comment by ogajduse** [comment]
@synkd Is the 6.11 cherry-pick worth the effort considering that we do not plan to run 6.11 in the future?

**Comment by synkd** [comment]
@ogajduse Kind of a toss-up, I think. I expect the level of effort would be quite low, but since the benefit could well be zero, I'm fine with closing this just issue.
