### ISSUE TITLE
C2R: This `register_host` function call should be replaced with `centos_host.register()`

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/robottelo#11876]
non-blocking: This could be replaced with `centos_host.register()`

_Originally posted by @ogajduse in https://github.com/SatelliteQE/robottelo/pull/10840#discussion_r1236975537_

**Comment by Gauravtalreja1** [comment]
`register()` uses hammer command to generate registration command, where as sat.api.RegistrationCommand() will be more appropriate I presume as this are API tests, updating in https://github.com/SatelliteQE/robottelo/pull/13236
