### ISSUE TITLE
[Failed-AutoCherryPick] - Fix the indent of `test_positive_allow_reregistration_when_dmi_uuid_changed`

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11883]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5545017343)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11880)

**Comment by ogajduse** [comment]
6.11 is not going to be utilized in the future
