### ISSUE TITLE
[Failed-AutoCherryPick] - Remove e2e flag from failing UI test, and apply it to 2 api tests

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11896]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5552753280)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11886)

**Comment by Gauravtalreja1** [comment]
e2e marks don't make any sense in zstream branches, so we could close this issue.
