### ISSUE TITLE
[Failed-AutoCherryPick] - Ansible test fixes for selecting only the used role in the test case

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11903]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5573143411)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11894)

**Comment by Gauravtalreja1** [comment]
@adarshdubey-star Do you think we need this issue to be cherrypicked?

**Comment by ogajduse** [comment]
@adarshdubey-star gentle ping on this.
