### ISSUE TITLE
A new marker to skip tests if manifester's conf requirements are not in place? If so, that sounds reasonable, but let's leave that work for a separate PR.

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#11934]
@jyejare I assume you're talking about creating a new marker to skip tests if manifester's conf requirements are not in place? If so, that sounds reasonable, but let's leave that work for a separate PR.

_Originally posted by @synkd in https://github.com/SatelliteQE/robottelo/pull/10394#discussion_r1239838128_

**Comment by synkd** [comment]
Closing this issue as it is resolved by https://github.com/SatelliteQE/robottelo/pull/14270.
