### ISSUE TITLE
[Failed-AutoCherryPick] - Remove Python 3.9 support from robottelo

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11956]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5642252341)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11953)

**Comment by ogajduse** [comment]
We can live with 3.9 checks in 6.11, I believe.
