### ISSUE TITLE
[Failed-AutoCherryPick] - Adding wait_for to test_positive_service_enable_disable

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#11978]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: CherryPick
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5656878844)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11952)

**Comment by omkarkhatavkar** [comment]
this is no more a valid issue, this was created because of the GHA issue. It is now resolved
