### ISSUE TITLE
[Failed-AutoCherryPick] - dashboard test fix

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12076]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5725258625)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11100)

**Comment by pondrejk** [comment]
nope, the cp was successful https://github.com/SatelliteQE/robottelo/pull/12075
