### ISSUE TITLE
[Failed-AutoCherryPick] - [6.14.Z] - Support the --local-files oscap argument

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12095]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5738635626)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11836)

**Comment by Gauravtalreja1** [comment]
Looks like this has been already cherrypicked in https://github.com/SatelliteQE/robottelo/pull/11837, closing this issue
