### ISSUE TITLE
Add clean_properties() method which really clear cached properties of contenthost class from robottelo/hosts.py

### ISSUE THREAD

**Issue by vijaysawant** [SatelliteQE/robottelo#12115]
**Problem:**

- `contenthost.os_version` returns the value of the RHEL _major.minor_ version. When working with scenarios like upgrading Rhel version we use `os_version`, but due to the `@cached_property` decorator, the older Rhel version value is returning.

- This issue is created to implement a method that would clear cached properties of the content host class from `robottelo/hosts.py` module

**Comment by jyejare** [comment]
We should stop the caching the version OR lru_cache with rhel version parameter that would cache the value per rhel version !

Later option is best !

**Comment by ogajduse** [comment]
`os_version` is being used a lot in fact. I believe that `cached_property` saves time if it is used tens of times in one test session. I would strongly advise against changing it to `property`.

@JacobCallahan Could you chime in?

**Comment by JacobCallahan** [comment]
We should definitely keep catching. However, if an upgrade is performed, that upgrade method should handle cache invalidation post-upgrade.

**Comment by ogajduse** [comment]
0f46497bf5c55890319de50edd7ee75f3c01f727
