### ISSUE TITLE
[Failed-AutoCherryPick] - Update test Contentcredentials for 6.13.z 6.14.z

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12116]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5753464639)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/11736)

**Comment by damoore044** [comment]
#12140 
#12146
