### ISSUE TITLE
Method `enable_tools_repo` should be re-written to support Satellite Client repo

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/robottelo#12147]
Satellite Tools repo is no longer a thing, we should re-write it to use Satellite Client repo instead.

https://github.com/SatelliteQE/robottelo/blob/4338e28b5307f8f019b9f85e0fbcdfcff6973b75/robottelo/host_helpers/contenthost_mixins.py#L95-L113

**Comment by Gauravtalreja1** [comment]
@ogajduse Currently, this helper is not in use by any tests or fixtures and its prefered to use client repo so we don't use tools repo anyway, so can we remove this instead?
