### ISSUE TITLE
Method `enable_rhel_repo` should be able to enable system repos for RHEL 8+

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/robottelo#12148]
The current implementation of `enable_rhel_repo` enables RHEL 7 style system repository. It does not allow BaseOS and AppStream repos enablement.

https://github.com/SatelliteQE/robottelo/blob/4338e28b5307f8f019b9f85e0fbcdfcff6973b75/robottelo/host_helpers/contenthost_mixins.py#L105-L113

**Comment by Gauravtalreja1** [comment]
@ogajduse Currently, this helper is not in use by any tests or fixtures, so can we remove this instead or do you still consider this to extend for baseos or appstream repos?
