### ISSUE TITLE
[Failed-AutoCherryPick] - remove delete org and create a new location for virt-who upgrade scenarios

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12188]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5806358561)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12092)

**Comment by yanpliu** [comment]
Satellite6.12 sca mode is not enable defaultly, so this PR is not suitable for Satellite6.12

**Comment by yanpliu** [comment]
Fixed by #12193
