### ISSUE TITLE
[Failed-AutoCherryPick] - Deprecating api/utils.py module

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12327]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/5956816831)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12175)

**Comment by jyejare** [comment]
Related PR is merged!
