### ISSUE TITLE
Automate hammer content-host pkg mgmt

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#1234]
80 test cases are documented here: http://cfse-qe.etherpad.corp.redhat.com/126

**Comment by sghai** [comment]
This issue can be closed as content-host is no longer support pkg management, Its being done host cmd now. We do have coverage around pkg management. Please feel free open a specific issue to cover something which is not done yet.

**Comment by sthirugn** [comment]
If the package management is already covered in host tests, I am okay with closing this issue.

**Comment by abalakh** [comment]
@sthirugn although package management is covered in host tests, there're only few of such tests (and definitely not 80). Maybe it's worth reopening the issue for host or remaining cases aren't important and not worth covering?

**Comment by sthirugn** [comment]
The etherpad has all the scenarios listed, please feel free to review them and open new issues as needed.
