### ISSUE TITLE
[Failed-AutoCherryPick] - Small Adjustment to Virt-card Assert Statements

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12409]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6015771710)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12405)

**Comment by ogajduse** [comment]
Resolved in #12410
