### ISSUE TITLE
Replace wait_for logic with a helper function

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/robottelo#12430]
Please replace it with 
```suggestion
    custom_leapp_host.wait_for_connection()
```

_Originally posted by @ogajduse in https://github.com/SatelliteQE/robottelo/pull/11553#discussion_r1311332141_

**Comment by vijaysawant** [comment]
Updated part of test module can be seen here https://github.com/SatelliteQE/robottelo/pull/11553/files#diff-22533d183099fdbb3c3070a86cc26b50b384780f0544d6b2d8c1e53e077a1b5aR368
