### ISSUE TITLE
[Failed-AutoCherryPick] - fixes for [RFE] test_positive_installable_errata

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12434]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6043609094)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12411)

**Comment by jyejare** [comment]
The linked PR is merged!
