### ISSUE TITLE
Boundary testing for parameters under settings menu

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#1250]
TASK- Boundary testing for Settings submenus (not provisioning-specific per say, could possibly be broken out into its own section.

[P1] Provisioning ( Partially done)
[P2] Bootdisk
[P2] Discovered
[P2] Puppet

Assure proper positive and negative testing of each field

Referencing this task with #986 as few sub-tabs are already automated there.

**Comment by elyezer** [comment]
@sghai can you please revisit this issue?

**Comment by sghai** [comment]
we need to write boundary tests for the tabs mentioned in issue description..  I've idea around discovery and Bootdisk and can be don easily. thanks

**Comment by elyezer** [comment]
@sghai thank you.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
