### ISSUE TITLE
[Failed-AutoCherryPick] - change in upgrade marks for hammer tests

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12635]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6196651736)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12584)

**Comment by Gauravtalreja1** [comment]
PR already merged https://github.com/SatelliteQE/robottelo/pull/12634
