### ISSUE TITLE
Update pre-commit hooks

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/robottelo#12650]
Can you also run `pre-commit autoupdate; pre-commit run -a` to update the available pre-commit hooks and code changes?
              
#12621 needs to go in first

_Originally posted by @Gauravtalreja1 in https://github.com/SatelliteQE/robottelo/pull/12621#discussion_r1327493385_

**Comment by Gauravtalreja1** [comment]
Thanks to @ogajduse for including pre-commit-ci, which will now auto-update pre-commit hooks regularly, for example - https://github.com/SatelliteQE/robottelo/pull/15051, so we are good to close this issue.
