### ISSUE TITLE
[Failed-AutoCherryPick] - update Insights test to use new host page

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12699]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6272455616)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12582)

**Comment by mstrlc** [comment]
Error in cherrypick logic, the cherry-pick to 6.14.z worked. See https://github.com/SatelliteQE/robottelo/commit/4d632fca1edabc5f59fb18003ff19e39ff1aca22. Closing
