### ISSUE TITLE
No possibility to ignore dynaconf vault

### ISSUE THREAD

**Issue by dosas** [SatelliteQE/robottelo#12816]
Since this [PR](https://github.com/SatelliteQE/robottelo/pull/12378) I have no option to run robottelo tests without configuring the vault.

```
  File "robottelo/robottelo/utils/vault.py", line 31, in export_vault_addr
    vaulturl = re.findall('VAULT_URL_FOR_DYNACONF=(.*)', envdata)[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

or

```
File "robottelo/robottelo/utils/vault.py", line 37, in export_vault_addr
    if re.findall('VAULT_ENABLED_FOR_DYNACONF=(.*)', envdata)[0] == 'true':
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

I have tried the following without success:

1. Using env var form pull request template `export VAULT_SECRET_ID_FOR_DYNACONF=somesecret`
2. Trying to disable the plugin `pytest -p no:auto_vault`
3. Putting some nonsense values into .env file

```
echo VAULT_URL_FOR_DYNACONF=asdf >> .env
echo VAULT_ENABLED_FOR_DYNACONF=true/false >> .env
```
yields

```
ERROR - Error! Vault CLI in not installed in your system, refer link https://learn.hashicorp.com/tutorials/vault/getting-started-install to install vault CLI as per your system spec!
```

The only workaround for me so far is deleting `auto_vault` from [conftest.py](https://github.com/SatelliteQE/robottelo/blob/master/conftest.py#L6)

@jyejare any help would be greatly appreciated

**Comment by ogajduse** [comment]
@dosas #12822 aims to address this issue. Please feel free to comment on it.

**Comment by dosas** [comment]
https://github.com/SatelliteQE/robottelo/pull/12822
