### ISSUE TITLE
[Failed-AutoCherryPick] - fixture support for virt-who config api : data_form deploy_type virtwho_config

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12864]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6466148297)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12620)

**Comment by Gauravtalreja1** [comment]
Looks like 6.12.z wasn't intended branch for this cherrypick, 6.12.z label was added while merging (not by @yanpliu ), so we can close this out
