### ISSUE TITLE
[Failed-AutoCherryPick] - Fixing loadbalancer e2e test

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12874]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6471481881)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12838)

**Comment by Griffin-Sullivan** [comment]
This test fix isn't needed for 6.12.z
