### ISSUE TITLE
[Failed-AutoCherryPick] - [Repository Rewrite] Added test for publishing invalid repository

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12894]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6495865119)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12322)

**Comment by ColeHiggins2** [comment]
https://github.com/SatelliteQE/robottelo/pull/13201

**Comment by ColeHiggins2** [comment]
https://github.com/SatelliteQE/robottelo/pull/13200
