### ISSUE TITLE
[Failed-AutoCherryPick] - Fix typo for organization field in global registration

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#12907]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6507818166)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12902)

**Comment by Gauravtalreja1** [comment]
https://github.com/SatelliteQE/robottelo/pull/12905
