### ISSUE TITLE
[Failed-AutoCherryPick] - improved webhook event trigger test

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13072]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6825445920)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13048)

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_webhook.py -k triggered
pod_resources_size: large
