### ISSUE TITLE
[Failed-AutoCherryPick] - Add UEFI HTTP Boot provisioning test

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13135]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6929843322)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12908)

**Comment by Gauravtalreja1** [comment]
https://github.com/SatelliteQE/robottelo/pull/13134
