### ISSUE TITLE
[Failed-AutoCherryPick] - recording ui-session-id for report portal logging

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13185]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6978554291)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13055)

**Comment by omkarkhatavkar** [comment]
This will https://github.com/SatelliteQE/robottelo/pull/13188 fix this
