### ISSUE TITLE
[Failed-AutoCherryPick] - fixture support for virt-who config cli : data_form deploy_type virtwho_config delete_host& manifest content move

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13230]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7047931668)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12619)

**Comment by yanpliu** [comment]
Fixed by #13239
