### ISSUE TITLE
Create a reliable way to mock smart proxies 

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#1325]
Robottelo needs a way to mock smart proxies to allow creation of proxies on the server without the need of another machine.

SSH tunnels have been proven to work for this by redirecting ports. However, creating a tunnel in the foreground causes paramiko to hang, and creating a tunnel in the background (using the `-f` flag) means there is no simple way to kill that tunnel if needed.

For more info check #1313

**Comment by elyezer** [comment]
This will need more research, will assign it again when I have a better plan to solve this.

**Comment by abalakh** [comment]
Resolved in #3302 and SatelliteQE/automation-tools#287
