### ISSUE TITLE
[Failed-AutoCherryPick] - Added SCA enabled manifest in activation key and removed duplicate fixture

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13392]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7178468815)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13082)

**Comment by shweta83** [comment]
Addressed in PR: https://github.com/SatelliteQE/robottelo/pull/13394 so closing this.
