### ISSUE TITLE
[Failed-AutoCherryPick] - Added SCA enabled manifest in activation key and removed duplicate fixture

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13391]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7178468815)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13082)

**Comment by shweta83** [comment]
Closing this as not going to cherrypick to 6.12.z
