### ISSUE TITLE
[Failed-AutoCherryPick] - [6.14] bz1699188

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13420]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7192188710)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13398)

**Comment by lhellebr** [comment]
https://github.com/SatelliteQE/robottelo/issues/12489
