### ISSUE TITLE
[Failed-AutoCherryPick] - Configurable Ignore list of markers test field in polarion tests

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13514]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7266122009)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13492)

**Comment by jyejare** [comment]
Merged https://github.com/SatelliteQE/robottelo/commit/d97bb894810968634519bbec7b8bfd5ce5a63ca0 directly into 6.13.z branch!
