### ISSUE TITLE
[Failed-AutoCherryPick] - Markers as test property in reports

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13590]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7396744771)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13043)

**Comment by jyejare** [comment]
This is already resolved with https://github.com/SatelliteQE/robottelo/pull/13601 hence closing the PR.
