### ISSUE TITLE
[Failed-AutoCherryPick] - Add coverage for HTTP Proxy capsule install

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13608]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7412845397)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13507)

**Comment by Griffin-Sullivan** [comment]
This file is missing lots of cherry-picks for 6.13. Not worth the effort for automation so I am closing this.
