### ISSUE TITLE
[Failed-AutoCherryPick] - Test capsule without registration module

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13610]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7412876984)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13583)

**Comment by Gauravtalreja1** [comment]
@shweta83 I'd request to add some comment going forward while closing any issues, it'll really help us in future to track issues created, and its not good practice to close issues without any word
