### ISSUE TITLE
[Failed-AutoCherryPick] - Change team to pheonix-subscriptions to match the Hosts-Content team

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13619]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.15.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7422832231)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13618)

**Comment by Gauravtalreja1** [comment]
@sambible is this change required for 6.15.z?
