### ISSUE TITLE
[Failed-AutoCherryPick] - Test capsule without registration module

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13613]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7412876984)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13583)

**Comment by Gauravtalreja1** [comment]
@shweta83 Are you planning to add this test?

**Comment by shweta83** [comment]
Yes. Will cherrypick this manually to 6.13.z
