### ISSUE TITLE
[Failed-AutoCherryPick] - Correct Casecomponent in upgrades/test_classparameter.py

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13626]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.15.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7424101244)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13621)

**Comment by Gauravtalreja1** [comment]
PR exists already https://github.com/SatelliteQE/robottelo/pull/13625
