### ISSUE TITLE
[Failed-AutoCherryPick] - fixing a forgotten make_job_invocaiton call

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13660]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.15.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7451208026)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13648)

**Comment by pondrejk** [comment]
merged here https://github.com/SatelliteQE/robottelo/pull/13659
