### ISSUE TITLE
[Failed-AutoCherryPick] - Removing changes associated with Bugbear rule B019

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13719]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7479150564)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13715)

**Comment by Gauravtalreja1** [comment]
Already cherrypicked https://github.com/SatelliteQE/robottelo/pull/13723
