### ISSUE TITLE
[Failed-AutoCherryPick] - Fix registration test cases

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#13991]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7788237642)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/13974)

**Comment by shweta83** [comment]
This is addressed in PR https://github.com/SatelliteQE/robottelo/pull/14026.
