### ISSUE TITLE
[Failed-AutoCherryPick] - [6.14.z Cherrypick PR#13450] Move Registration test cases

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14059]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/7886651617)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14052)

**Comment by Gauravtalreja1** [comment]
@shweta83 bump
