### ISSUE TITLE
[Failed-AutoCherryPick] - correct component names and description

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14182]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8050537869)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14179)

**Comment by vsedmik** [comment]
https://github.com/SatelliteQE/robottelo/pull/14189 merged
