### ISSUE TITLE
[Failed-AutoCherryPick] - remove unexpected tokens from ui test_eol_banner.py

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14197]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.15.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8065505005)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14196)

**Comment by vijaysawant** [comment]
No longer applicable as orignial PR doesn't have any label `6.15.z` and no need to CP other than master.
CC: @Gauravtalreja1
