### ISSUE TITLE
[Failed-AutoCherryPick] - Fix server_config in subscription test

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14234]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8110086487)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14226)

**Comment by vsedmik** [comment]
Fix already present in `6.14.z`.
