### ISSUE TITLE
[Failed-AutoCherryPick] - Fix pytest deprecation warning

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14282]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8187676392)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14205)

**Comment by Gauravtalreja1** [comment]
6.12.z is now absolute hence closing this
