### ISSUE TITLE
[Failed-AutoCherryPick] - Skip orphan cleanup case for n_minus scenario

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14407]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8280869618)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14371)

**Comment by vsedmik** [comment]
Done
