### ISSUE TITLE
[Failed-AutoCherryPick] - Test fixes for the Endeavour team

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14516]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8424937425)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14512)

**Comment by Gauravtalreja1** [comment]
Already cherrypicked by @LadislavVasina1 in https://github.com/SatelliteQE/robottelo/pull/14518
