### ISSUE TITLE
Automate Errata Management Test Cases

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1466]
Needs API/CLI/UI tests.

**Comment by elyezer** [comment]
I have updated the title to be more specific.

**Comment by sthirugn** [comment]
The test stubs are already added to robottelo, automation can be started.

**Comment by elyezer** [comment]
I will close this issues in favor of creating more specific ones. We have already in the coverage sheet that this area have no tests and we will start working on errata stuff once we complete the pending issues.

**Comment by sthirugn** [comment]
:+1:
