### ISSUE TITLE
[Failed-AutoCherryPick] - Assert installer status when enabling OpenSCAP

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14756]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8659917210)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14755)

**Comment by lpramuk** [comment]
`tests/foreman/api/test_capsule.py` doesn't exist in `6.12.z`
