### ISSUE TITLE
[Failed-AutoCherryPick] - host edit: test correct page redirection

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14913]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8878707722)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14844)

**Comment by pnovotny** [comment]
Fixed in https://github.com/SatelliteQE/robottelo/pull/14918 and merged.
