### ISSUE TITLE
[Failed-AutoCherryPick] - CV Eval - Deletion

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14948]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8940689437)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14678)

**Comment by ogajduse** [comment]
Test of the Phoenix team alias...

@SatelliteQE/phoenix, can someone pick this one up?

**Comment by sambible** [comment]
aye aye captain

**Comment by sambible** [comment]
https://github.com/SatelliteQE/robottelo/pull/15036

**Comment by sambible** [comment]
https://github.com/SatelliteQE/robottelo/pull/15037
