### ISSUE TITLE
[Failed-AutoCherryPick] - CV Eval - Deletion

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14947]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.15.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8940689437)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14678)

**Comment by sambible** [comment]
https://github.com/SatelliteQE/robottelo/pull/15036
