### ISSUE TITLE
[Failed-AutoCherryPick] - Copy config files for FAM to server

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#14973]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/8969682764)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/14866)

**Comment by Griffin-Sullivan** [comment]
Current test refactor for FAM is not present in 6.13.z
