### ISSUE TITLE
[Failed-AutoCherryPick] - Add Phoenix team based codeowners

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#15061]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/9080503162)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15048)

**Comment by vsedmik** [comment]
Closing since no `CODEOWNERS` exists in `6.14.z`
