### ISSUE TITLE
Automate Activation Key Test Cases

### ISSUE THREAD

**Issue by JacobCallahan** [SatelliteQE/robottelo#1520]

**Comment by JacobCallahan** [comment]
#1802

**Comment by JacobCallahan** [comment]
#1815

**Comment by elyezer** [comment]
@JacobCallahan I've updated the issue title to be more clear. Feel free to change it is necessary.

**Comment by JacobCallahan** [comment]
@elyezer that makes more sense without the context of the milestone it is part of.

**Comment by elyezer** [comment]
@JacobCallahan indeed. I got an email about this issue being updated but just seeing the title on it was not enough.

**Comment by JacobCallahan** [comment]
#1849

**Comment by JacobCallahan** [comment]
#1936 merged.
```
"""@Test: Positive content override

@Feature: Activation key copy

@Steps:

1. Create activation key and add content
2. Get the first product's label
3. Override the product's content enablement
4. Verify that the command succeeded

@Assert: Activation key content override was successful

"""
```

**Comment by elyezer** [comment]
Closing this, separate issues for the remaining activation keys stubs will be created under demand.
