### ISSUE TITLE
[Failed-AutoCherryPick] - Updates for CV component eval

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#15239]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/9306212418)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15043)

**Comment by vsedmik** [comment]
Manual CP has been raised.
