### ISSUE TITLE
[Failed-AutoCherryPick] - Check Hypervisor host subscription status and hypervisor host and virtual guest mapping in UI

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#15401]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/9497760581)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15288)

**Comment by yanpliu** [comment]
fixed in https://github.com/SatelliteQE/robottelo/pull/15406
