### ISSUE TITLE
Automate --clear-puppet-environments flag. (CLI)

### ISSUE THREAD

**Issue by cswiii** [SatelliteQE/robottelo#1548]
<pre>
"""
@Feature: Clear Puppet Environments flag (CLI)
@Test: Assure ability to use the --clear-puppet-environments flag from the installer
@Setup: Assure you have an instance installed with puppet environments created
@Steps:
 1.  View contents of  /etc/puppet/environments
 2.  run the katello-installer with the --clear-puppet-environments flag
 3.  View contents of /etc/puppet/environments
@Assert: contents have been removed.
@BZ: #1118102
@Status: Manual 
"""
</pre>

**Comment by kbidarkar** [comment]
The plan is to run `katello-installer` related tests and destructive testing using openstack. currently this needs investigation and proper infrastructure setup to test such testcases.

**Comment by rochacbruno** [comment]
@kbidarkar is this still valid or we can close this issue?

**Comment by kbidarkar** [comment]
Yes, this scenario is still valid and we should be testing it.

**Comment by JacobCallahan** [comment]
@devendra104 can you look into this?

**Comment by devendra104** [comment]
This issue is not valid for the current release, so I am closing this issue.
