### ISSUE TITLE
For upstream bug verification process we need default_organization with data

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#1549]
After upstream installation, automation should update (Default_Organization?)
1. import manifest
2. enable rhel6 or rhel7 repos
3. sync content
This would save a lot of time since this bug process is happening once a week now.

**Comment by elyezer** [comment]
@cswiii have crafter a great list of what data should be populated here https://github.com/SatelliteQE/robottelo/issues/1622#issuecomment-60432977

**Comment by rochacbruno** [comment]
@sthirugn @kbidarkar still an issue or we can close?

**Comment by sthirugn** [comment]
satellite-populate can be used to do this now. Lets close this and open a new issue, if this is needed.
