### ISSUE TITLE
[Failed-AutoCherryPick] - Add tests for facts component

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#15515]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/9680455916)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15265)

**Comment by shweta83** [comment]
Manual cherrypicked in https://github.com/SatelliteQE/robottelo/pull/16619/files
