### ISSUE TITLE
[Failed-AutoCherryPick] - Update API endpoint for host facts

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#15602]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/9856839297)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15546)

**Comment by shweta83** [comment]
This changed has been reverted in the master so closing this PR.
