### ISSUE TITLE
[Failed-AutoCherryPick] - Add a test case for purge of pulp tasks

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#15636]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.15.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/9895324665)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15631)

**Comment by vsedmik** [comment]
Done
