### ISSUE TITLE
[Failed-AutoCherryPick] - FAM: don't set a password for auth_source_ldap tests

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#15656]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/9940531931)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15647)

**Comment by Griffin-Sullivan** [comment]
Forgot we don't cherry-pick to 6.13.z for FAM
