### ISSUE TITLE
[Failed-AutoCherryPick] - Harden docker/podman asserts a bit

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#15781]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.15.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/10113326486)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15779)

**Comment by vsedmik** [comment]
ManualCP PR raised.
