### ISSUE TITLE
[Failed-AutoCherryPick] - passing ipv6 params valued for direct Host calls

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#15978]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/10463310222)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15964)

**Comment by omkarkhatavkar** [comment]
Not a valid one as Ipv6 changes won't be applicable beyond 6.15 for now.
