### ISSUE TITLE
[Failed-AutoCherryPick] - adding the support for ipv4 and ipv6 parameterization for Container and VM

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#16006]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/10479111872)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15881)

**Comment by omkarkhatavkar** [comment]
Not a valid one as Ipv6 changes won't be applicable beyond 6.15 for now.
