### ISSUE TITLE
[Failed-AutoCherryPick] - Fix AK tests assertion errors

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#16262]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.15.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/10739693914)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/16220)

**Comment by vsedmik** [comment]
Resolved by https://github.com/SatelliteQE/robottelo/pull/16273
