### ISSUE TITLE
[Failed-AutoCherryPick] - avoiding host details will be seen in the test result

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#16565]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/11168666554)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/16553)

**Comment by omkarkhatavkar** [comment]
The test here in 6.14.Z is not parameterized, So it is not required t apply changes
