### ISSUE TITLE
Cherry-pick fixes on to satellite-6.0.z.1

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/robottelo#1659]
The satellite-6.0.z.1 branch should have some fixes cherry-picked on to it. The cherry-picked fixes should help the tests in that branch run more reliably. Here's some pull requests that should be considered:

- [ ] #1425
- [ ] #1426
- [ ] #1436
- [x] #1489
- [x] #1491
- [ ] #1625
- [ ] #1637

Bonus:

- [ ] #1446

**Comment by sthirugn** [comment]
@Ichimonji10 is this issue still valid? if not, can you please close this?

**Comment by Ichimonji10** [comment]
@sthirugn, I suspect that this issue isn't valid. No work has been done on the 6.0.z.1 branch in about three months, and efforts spent on the master branch will have more payback over time than efforts spent on the 6.0.z.1 branch. That said, this may still be worth pursuing if we have more upcoming 6.0.z releases.

**Comment by sthirugn** [comment]
@Ichimonji10 I agree.  Lets go ahead and close this issue and open a new issue in future if we pursue the path of making z-stream branch better.

**Comment by elyezer** [comment]
:+1:

**Comment by Ichimonji10** [comment]
Closing.
