### ISSUE TITLE
Validate the rerunning an installation of requirements 

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#16749]
@jyejare The pip freeze output in artifacts still shows broker==0.5.7. Additionally, log lines don't match up with their correct position in Broker 0.6.2. Can we verify that we are actually re-running an install of requirements.txt?

_Originally posted by @JacobCallahan in https://github.com/SatelliteQE/robottelo/pull/16691#issuecomment-2430269881_

**Comment by JacobCallahan** [comment]
This was likely an error on my part with the artifacts being pulled from the latest job instead of the specific run I was interested in.
Closing for now
