### ISSUE TITLE
[Failed-AutoCherryPick] - Satellite version validation skip for nightly

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#16757]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/11498217464)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/16754)

**Comment by jyejare** [comment]
Closed as PR opened and merged.
