### ISSUE TITLE
[Failed-AutoCherryPick] - prepare puppet classes needed for FAM tests in setup_fam

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#16761]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/11502180463)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/16728)

**Comment by evgeni** [comment]
6.13.z doesn't have the "new" FAM tests, so that's why it failed to pick.

Closing as "not needed"
