### ISSUE TITLE
[Failed-AutoCherryPick] - [6.14.z] avoiding the ohsnap repo url incase of nightly

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#16783]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/11515258706)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/16677)

**Comment by Gauravtalreja1** [comment]
Closing as the cherrypick is not required
