### ISSUE TITLE
[Failed-AutoCherryPick] - Refactor ipv6 http_proxy code

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#16977]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.16.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/11953740454)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/16928)

**Comment by ogajduse** [comment]
PR merged
