### ISSUE TITLE
Fix the possiblity of UI moving ahead even if entitiy creation fails.

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#1699]
Currently submitting an entity creation via the UI after clicking the submit button, simply moves ahead searching for the entity, even if some value was missed on the page.

May be we can add a function to the ui/base module which validates that the submit button is no longer exists on the page, before moving to searching it.

May also require checking for locators[has_error] and similar error locators, which are used in negative/boundary tests.

**Comment by elyezer** [comment]
@kbidarkar this issue still valid?

**Comment by oshtaier** [comment]
Doesn't seem as valid anymore as our test automation scripts built in a way that necessary validation things will fail in case any required field is omitted.
