### ISSUE TITLE
[Failed-AutoCherryPick] - Fix expected user name

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#17200]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/12394633968)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/17161)

**Comment by lhellebr** [comment]
https://github.com/SatelliteQE/robottelo/pull/17203
