### ISSUE TITLE
Add CLI test for repository-set available-repositories

### ISSUE THREAD

**Issue by JacobCallahan** [SatelliteQE/robottelo#1731]
```
hammer repository-set available-repositories --help

Usage:
    hammer repository-set available-repositories [OPTIONS]

Options:
 --id ID                                 ID of the repository set
 --name NAME                             Repository set name to search by
 --organization ORGANIZATION_NAME        Organization name to search by
 --organization-id ORGANIZATION_ID       organization ID
 --organization-label ORGANIZATION_LABEL Organization label to search by
 --product PRODUCT_NAME                  Product name to search by
 --product-id PRODUCT_ID                 product numeric identifier
 -h, --help                              print help
```

**Comment by omaciel** [comment]
The workflow would be:

* Import a valid manifest into your organization
* Enable a **Red Hat** repository for your organization
* Check that the repository is listed

One thing to check is, does ``repository-set available-repositories`` show you what's been enabled for a product OR what's available to be enabled?

Knowing the answer to this will dictate whether you want to check how many repository sets are enabled before you enable something (should be zero) and after.
