### ISSUE TITLE
UI: Create and automate some basic content search testcases. 

### ISSUE THREAD

**Issue by cswiii** [SatelliteQE/robottelo#1735]
It has become evident to me that test (cases, activity) within content search has been... lacking.  Here are a few testcases to start with, though there are surely more. 

<pre>

"""
@Feature: Login
@Test: Log in as a valid user
@Setup: Navigate to abc.com
@Steps:
 1.  Launch the url
 2.  Log in with valid user credentials
@Assert: Log in successful
@BZ: #1234567
@Status: Manual (REMOVE this field once automated)
"""

"""
@Feature: Content Search - Content Views  (basic search)
@Test: Search within content views using a valid query
@Setup: Create a content view containing a variety of content
@Steps:
 1. Go to content search and seach Content Views for a variety of different valid strings:  alpha (lower), alpha (upper), numeric.
@Assert: Successful results
@Status: 
"""

"""
@Feature: Content Search - Products (basic search)
@Test: Search within products using a valid query
@Setup:  Create/enable a variety of products containing different repositories: RHEL, custom content repos, puppet repos (?) 
@Steps:
 1. Go to content search and seach Products for a variety of different valid strings:  alpha (lower), alpha (upper), numeric.
@Assert: Successful results
@Status:  Manual
"""

"""
@Feature: Content Search - Repositories (basic search)
@Test: Search within repositories using a valid query
@Setup:  Create/enable a variety of repositories: RHEL, custom content repos, puppet repos (?) 
@Steps:
 1. Go to content search and seach repositories for a variety of different valid strings:  alpha (lower), alpha (upper), numeric.  Possibly multibyte? UNSURE.
@Assert: Successful results
@Status: Manual
"""

"""
@Feature: Content Search - Packages (basic search)
@Test: Search within repositories using a valid query
@Setup:  Create/enable a variety of repositories: RHEL, custom content repos, puppet repos (?) 
@Steps:
 1. Go to content search and seach Packages for a variety of different valid strings:  alpha (lower), alpha (upper), numeric.
@Assert: Successful results
@BZ: 1165470
@Status: Manual
"""

"""
@Feature: Content Search - Errata
@Test: Search within errata using a valid query
@Setup: Sync content containing errata (preferably rhel content)
@Steps:
 1. Go to content search and seach Errata for a variety of different valid strings:  alpha (lower), alpha (upper), numeric.
@Assert: Successful results
@Status: Manual
"""

"""
@Feature: Content Search - Puppet Modules
@Test: Search within Puppet Modules using a valid query
@Setup: Products/repos containing puppet content are synced
@Steps:
 1. Go to content search and seach Puppet Modules for a variety of different valid strings:  alpha (lower), alpha (upper), numeric.
@Assert: Successful results
@Status: Manual
"""

"""
@Feature: Content Search  Results Subpane - Can add environments
@Test: Attempt to add an existing environment to the view
@Setup: Create more than one environment outside of library (i.e., dev, qe, etc.)
@Steps:
 1. Go to content view and search; await results
 2.  Click the "+" and select one or more environments.
@Assert: Environments get added to results subpane.
@BZ: #1234567
@Status: Manual
"""

"""
@Feature: Content Search - Content Views (autocomplete)
@Test: query autocomplete works
@Setup: Create a content view containing a variety of content, b
@Steps:
 1. Go to content search for views and begin a search that would match a query (i.e., "R" for RHEL)
@Assert: Autocomplete takes place
@Status: 
"""

"""
@Feature: Content Search - Products (autocomplete)
@Test: query autocomplete works
@Setup: Create a content view containing a variety of content
@Steps:
 1. Go to content search for Products and begin a search that would match a query (i.e., "R" for RHEL)
@Assert: Autocomplete takes place
@Status: 
"""

"""
@Feature: Content Search - repositories (autocomplete)
@Test: query autocomplete works
@Setup: Create/sync a variety of repo types
@Steps:
 1. Go to content search for repositories, select the auto-complete box, and begin a search that would match a query (i.e., "R" for RHEL)
@Assert: Autocomplete takes place
@Status: 
"""

"""
@Feature: Content Search - Products (basic search)
@Test: Search within products using a valid query
@Setup:  Create/enable a variety of products containing different repositories: RHEL, custom content repos, puppet repos (?) 
@Steps:
 1. Go to content search and seach Products for a variety of different valid strings:  alpha (lower), alpha (upper), numeric.
@Assert: Successful results
@Status:  Manual
"""

"""
@Feature: Content Search - Content Views (compare)
@Test: CV compare works
@Setup: Create multiple contents view containing a variety of content
@Steps:
 1. Go to content search for views and begin a search that would match a query
 2. Select two or more content views and click the compare button
@Assert: Results are returned.
@BZ: 1166307
@Status: Manual
"""

"""
@Feature: Content Search - Content Views (result details hover)
@Test: result details exist on hover for content views
@Setup: Create multiple contents view containing a variety of content
@Steps:
 1. Go to content search for views and begin a search that would match a query
 2. Hover over the fields for any given environment
@Assert: x/y/z results appear
@Assert: tooltip can be clicked/hovered to see further details.
@Status: Manual
"""

"""
@Feature: Content Search - Products (result details hover)
@Test: result details exist on hover for products
@Setup: Create multiple contents view containing a variety of content
@Steps:
 1. Go to content search for products and begin a search that would match a query
 2. Hover over the fields for any given environment
@Assert: x/y/z results appear
@Assert: tooltip can be clicked/hovered to see further details.
@Status: Manual
"""

"""
@Feature: Content Search - Repositories (result details hover)
@Test: result details exist on hover for repos
@Setup: Create multiple contents view containing a variety of content
@Steps:
 1. Go to content search for repositories and begin a search that would match a query
 2. Hover over the fields for any given environment
@Assert: x/y/z results appear
@Assert: tooltip can be clicked/hovered to see further details.
@Status: Manual
"""

"""
@Feature: Content Search  Results Subpane - Can remove environments
@Test: Attempt to add an existing environment to the view
@Setup: Create more than one environment outside of library (i.e., dev, qe, etc.)
@Steps:
 1. Go to content view and search; await results
 2.  Click the "+" and deselect one or more environments.
@Assert: Environments get removed from results subpane.
@Status: Manual 
"""
</pre>

**Comment by oshtaier** [comment]
Issue is not actual anymore. Closed in favor of #3494, #3495 and #3496
