### ISSUE TITLE
Update UI puppet-classes testcases via the API.

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#1814]
1) Creation of puppet-classes is no longer possible as there is no "New Puppet Class" button available.
2) updating and deleting may be possible but needs to be investigated and tests need to be added accordingly using the API's.

**Comment by elyezer** [comment]
@kbidarkar as #1813 is merged, could this be closed?

**Comment by kbidarkar** [comment]
confirmed on #sat6 and #foreman-dev channels on IRC. puppet-classes can now only be created via the API's.

**Comment by kbidarkar** [comment]
This issue is for updating the existing tests related to 
a) update and
b) delete 
puppet-classes if they are still possible.

**Comment by elyezer** [comment]
@kbidarkar thanks for the clarification.

**Comment by kbidarkar** [comment]
For the sake of clarity, will be more explicit here.

Creation of puppet-classes via UI is not possible.
So, the plan here for update and delete test-cases should be to 
a) create pupper-classes via API
b) Then update or  delete the puppet-classes via UI only.

**Comment by jyejare** [comment]
The Creation, deletion and updation from API end has been taken care into PR #2103 .

**Comment by jyejare** [comment]
Working on Deleting, updating of Puppet class from UI end. Creating of Puppet class is done from API.
- The deletion of Puppet class is working from UI end.
- But updating of puppet class from UI is not possible as name field is of puppet class is not editable. And there are no others fields(other than name) we can add from API while creating puppet class. so its really complex situation for update puppet class UI test. So Please help me here.

**Comment by kbidarkar** [comment]
Using a dummy puppet-class to create from API may be indeed difficult to update.
We have 2 options here
a) Create a puppet-repo using puppet-module ( which brings in a puppet-class) , sync it , publish it promote it and then import it for the puppet-class to be visible on the UI.
b) Alternately, OSCAP brings in a puppet RPM (puppet-foreman_scap_client) currently, installing which simply populates a puppet-class without having to do all the stuff mentioned in step a). 
c) So now, we need to decide how we need to install the above mentioned puppet RPM, whether 
i) automation-tools project should bring it in 
ii) or do we to install it via the testcase itself.

I think adding it as part of the automation-tools for quickly populating the puppet-class will be more helpful.

Thought ?

**Comment by elyezer** [comment]
All required package should be installed on the automation-tools task. Ping me if you need more information on how to add the RPM installation there.

**Comment by elyezer** [comment]
API support for puppet classes was added in last sprint, missing the tests which should be done in the current sprint. Moving this issue to the current sprint.
