### ISSUE TITLE
CLI: Automate host-collection errata install

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#1816]
Prerequisites:
1. Install sat6
2. Upload manifest, sync rhel6 content
3. Register/Subscribe content-hosts
4. Create host-collection

Test cases:
1: host-collection erratum install --errata <errata> --id <id> --organization-id <orgid>
2: host-collection erratum install --errata <errata> --id <id> --organization <org name>
3: host-collection erratum install --errata <errata> --id <id> --organization-label <org label>
4: host-collection erratum install --errata <errata> --name <name> --organization-id <orgid>
5: host-collection erratum install --errata <errata> --name <name> --organization <org name>
6: host-collection erratum install --errata <errata> --name <name> --organization-label <org label>
Negatives:
<No errata data>
7: host-collection erratum install --id ID --organization-id <orgid>
8: host-collection erratum install --name <name> --organization-id <orgid>
<No host-collection data>
9: host-collection erratum install --errata <errata> --organization-id <orgid>
10: host-collection erratum install --errata <errata> --organization-id <orgid>
<No org data>
11: host-collection erratum install --errata <errata> --id <id>
12: host-collection erratum install --errata <errata> --name <name>

**Comment by tkolhar** [comment]
filing this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1179565

**Comment by tkolhar** [comment]
repo enable is failing : https://bugzilla.redhat.com/show_bug.cgi?id=1213275

**Comment by sghai** [comment]
All these should be covered with #3774

**Comment by sthirugn** [comment]
:100:   ty so much for doing this.

**Comment by JacobCallahan** [comment]
This is already in current automation.

**Comment by sthirugn** [comment]
phew thank you @JacobCallahan for closing this :+1:
