### ISSUE TITLE
Implement capturing screenshots for the UI

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#1822]
1) Tests fails while working with jenkins, but passes locally.
2) Capturing screenshot may help investigate the issue as to why the failures.
3) @elyezer suggested we could try using https://github.com/RedHatQE/python-selenium-wrapper

**Comment by elyezer** [comment]
:+1:

**Comment by kbidarkar** [comment]
Also I tried looking at the below link:
https://github.com/SatelliteQE/robottelo/issues/1822

But as per my current understanding, looks like we would need to tweak our existing automation heavily at the webdriver level. I wish we could just `pip install` it. :-)
I think we need to look into robottelo/test.py module.
Please do comment and suggest about it's approach , if anyone has some better ideas.

**Comment by kbidarkar** [comment]
Adding `screenshots base_path to robottelo.properties file as config param` will be tracked under this issue here.
https://github.com/SatelliteQE/robottelo/issues/1824

**Comment by kbidarkar** [comment]
Fixed in https://github.com/SatelliteQE/robottelo/pull/1823
