### ISSUE TITLE
Add screenshots base_path to robottelo.properties file as config param.

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#1824]
can you please add the base path to where save screenshots as a config in properties file? Maybe we can use /tmp/robottelo as the default value

**Comment by Ichimonji10** [comment]
@omaciel, this is definitely one of those problems that will benefit from the availability of StapleGun. The `XDG_DATA_HOME` or `XDG_CACHE_HOME` directories would be a great fit for this.

**Comment by elyezer** [comment]
Btw we still need a way to configure the path, to easily allow jenkins store them for every UI run.

**Comment by Ichimonji10** [comment]
#1823 includes a method that [creates a directory](https://github.com/SatelliteQE/robottelo/pull/1823/files#diff-d73d98ec04810dd23021a3d4294833afR258).

Also, `os.path.join(xdg.BaseDirectory.save_data_path('staplegun'), 'screenshots')` should work quite well.

**Comment by elyezer** [comment]
@Ichimonji10 interesting, thanks for the info.

**Comment by kbidarkar** [comment]
Will probably integrate stuff from staplegun and base_path stuff once StapleGun is ready to use.
For now, the below patch should help.

https://github.com/SatelliteQE/robottelo/pull/1834
