### ISSUE TITLE
Remove all editor config comment line.

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#1827]
Enforcing a editor config is not good and that line is better suited for files which the editor does not recognize by default its filetype.

All lines like below should be dropped.

```
# vim: ts=4 sw=4 expandtab ai
```

**Comment by Ichimonji10** [comment]
:+1:

I'm mainly annoyed by the `ai` (autoindent) part of those configurations, but am fine with dropping the `# vim:` lines entirely too. Which text editor to use is totally up to the individual developer, and I see no reason to include editor-specific comments in a project as large as Robottelo.

**Comment by elyezer** [comment]
Agreed
