### ISSUE TITLE
Write CLI test for https://bugzilla.redhat.com/show_bug.cgi?id=1189289

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1888]
The **hammer cli** command to display `info` for a docker repository does not return its `upstream name` attribute. I would expect that this information should be displayed/returned via the CLI since it is returned via the API.

Please add a CLI test to specifically test this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1189289

**Comment by elyezer** [comment]
#2025 is merged closing this.
