### ISSUE TITLE
Add a test for content view version deletion

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/robottelo#1905]
Create a test that does the following:

1. Create a content view.
2. Publish and promote that content view.
3. Delete a content view version.

Using API, CLI and UI.

This should help us avoid [BZ 1192573](https://bugzilla.redhat.com/show_bug.cgi?id=1192573).

**Comment by sghai** [comment]
Issue has been covered via UI/CLI/API in referenced PR's

**Comment by elyezer** [comment]
All PRs are merged, closing this.
