### ISSUE TITLE
SAM: Creation of test stubs for help page

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1914]
hammer --help
Usage:
    hammer [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 activation-key                Manipulate activation keys.
 auth                          Foreman connection login/logout.
 auth-source                   Manipulate auth sources.
 bootdisk                      Download boot disks
 content-host                  Manipulate content hosts on the server
 docker                        Manipulate docker content
 filter                        Manage permission filters.
 host-collection               Manipulate host collections
 import                        Import data exported from a Red Hat Satellite 5 instance
 organization                  Manipulate organizations
 ping                          Get the status of the server
 product                       Manipulate products.
 repository                    Manipulate repositories
 repository-set                Manipulate repository sets on the server
 role                          Manage user roles.
 shell                         Interactive shell
 subscription                  Manipulate subscriptions.
 sync-plan                     Manipulate sync plans
 task                          Tasks related actions.
 user                          Manipulate users.
 user-group                    Manage user groups.

Options:
 --autocomplete LINE           Get list of possible endings
 --csv                         Output as CSV (same as --output=csv)
 --csv-separator SEPARATOR     Character to separate the values
 --interactive INTERACTIVE     Explicitly turn interactive mode on/off
                               One of true/false, yes/no, 1/0.
 --output ADAPTER              Set output format. One of [csv, silent, json, yaml, table, base]
 --show-ids                    Show ids of associated resources
 --version                     show version
 -c, --config CFG_FILE         path to custom config file
 -d, --debug                   show debugging output
 -h, --help                    print help
 -p, --password PASSWORD       password to access the remote system
 -r, --reload-cache            force reload of Apipie cache
 -s, --server SERVER           remote system address
 -u, --username USERNAME       username to access the remote system
 -v, --verbose                 be verbose

**Comment by sthirugn** [comment]
No action needed on this for now
