### ISSUE TITLE
SAM: Creation of test stubs for host-collection 

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1915]
hammer host-collection --help
Usage:
    hammer host-collection [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 add-content-host              Add content host to the host collection
 content-hosts                 List content hosts in the host collection
 copy                          Make copy of a host collection
 create                        Create a host collection
 delete                        Destroy a host collection
 erratum                       Manipulate errata for a host collection
 info                          Show a host collection
 list                          List host collections
 package                       Manipulate packages for a host collection
 package-group                 Manipulate package-groups for a host collection
 remove-content-host           Remove content hosts from the host collection
 update                        Update a host collection

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action needed on this for now
