### ISSUE TITLE
SAM: Creation of test stubs for import

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1916]
hammer import --help
Usage:
    hammer import [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 activation-key                Import Activation Keys (from spacewalk-report activation-keys).
 all                           Load ALL data from a specified directory that is in spacewalk-export format.
 config-file                   Create puppet-modules from Configuration Channel content (from spacewalk-report config-files-latest).
 content-host                  Import Content Hosts (from spacewalk-report system-profiles).
 content-view                  Create Content Views based on local/cloned Channels (from spacewalk-export-channels).
 host-collection               Import Host Collections (from spacewalk-report system-groups).
 organization                  Import Organizations (from spacewalk-report users).
 repository                    Import repositories (from spacewalk-report repositories).
 repository-enable             Enable any Red Hat repositories accessible to any Organization (from spacewalk-report channels).
 template-snippet              Import template snippets (from spacewalk-report kickstart-scripts).
 user                          Import Users (from spacewalk-report users).

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action needed on this for now
