### ISSUE TITLE
SAM: Creation of test stubs for organization

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1917]
hammer organization --help
Usage:
    hammer organization [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 add-user                      Associate an user
 create                        Create organization
 delete                        Delete an organization
 info                          Show organization
 list                          List all organizations
 remove-user                   Disassociate an user
 update                        Update organization

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action needed on this for now
