### ISSUE TITLE
SAM : Creation of test stubs for product

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1919]
hammer product --help
Usage:
    hammer product [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 info                          Show a product
 list                          List products
 remove-sync-plan              Delete assignment sync plan and product.
 set-sync-plan                 Assign sync plan to product.
 synchronize                   Sync a repository

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action needed on this for now
