### ISSUE TITLE
SAM: Creation of test stubs for repository

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1920]
hammer repository --help
Usage:
    hammer repository [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 info                          Show a custom repository
 list                          List of enabled repositories
 remove-content                 
 synchronize                   Sync a repository

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action needed on this for now
