### ISSUE TITLE
SAM : Creation of test stubs for role

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1921]
hammer role --help
Usage:
    hammer role [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 create                        Create a role
 delete                        Delete a role
 filters                       List all filters
 list                          List all roles
 update                        Update a role

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action needed on this for now
