### ISSUE TITLE
SAM: Creation of test stubs for subscription

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1922]
hammer subscription --help
Usage:
    hammer subscription [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 delete-manifest               Delete manifest from Red Hat provider
 list                          List organization subscriptions
 manifest-history              obtain manifest history for subscriptions
 refresh-manifest              Refresh previously imported manifest for Red Hat provider
 upload                        Upload a subscription manifest

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action needed on this for now
