### ISSUE TITLE
SAM : Writing test stubs for sync-plan

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1923]
hammer sync-plan --help
Usage:
    hammer sync-plan [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 create                        Create a sync plan
 delete                        Destroy a sync plan
 info                          Show a sync plan
 list                          List sync plans
 update                        Update a sync plan

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action needed on this for now
