### ISSUE TITLE
SAM : Creation of test stubs for task

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1924]
hammer task --help
Usage:
    hammer task [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 progress                      Show the progress of the task

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action needed on this for now
