### ISSUE TITLE
SAM : Creation of test stubs for user

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1925]
hammer user --help
Usage:
    hammer user [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 add-role                      Assign a user role
 create                        Create a user
 delete                        Delete a user
 info                          Show a user
 list                          List all users
 remove-role                   Remove a user role
 update                        Update a user

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action need on this for now
