### ISSUE TITLE
SAM : Creation of test stubs for user-group

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1926]
hammer user-group --help
Usage:
    hammer user-group [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 add-role                      Assign a user role
 add-user                      Associate an user
 add-user-group                Associate an user group
 create                        Create a user group
 delete                        Delete a user group
 external                      View and manage user group's external user groups
 info                          Show a user group
 list                          List all user groups
 remove-role                   Remove a user role
 remove-user                   Disassociate an user
 remove-user-group             Disassociate an user group
 update                        Update a user group

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action need on this for now
