### ISSUE TITLE
SAM: Creation of test stubs for activation-key

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1927]
hammer activation-key --help
Usage:
    hammer activation-key [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 add-host-collection           Associate a resource
 add-subscription              Add subscription
 content-override              Override product content defaults
 copy                          Copy an activation key
 create                        Create an activation key
 delete                        Destroy an activation key
 host-collections              List associated host collections
 info                          Show an activation key
 list                          List activation keys
 product-content               List associated products
 remove-host-collection        Disassociate a resource
 remove-subscription           Remove subscription
 subscriptions                 List associated subscriptions
 update                        Update an activation key

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action need on this for now
