### ISSUE TITLE
SAM :  Creation of test stubs for auth

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1928]
hammer auth --help
Usage:
    hammer auth [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 login                         Set credentials
 logout                        Wipe your credentials
 status                        Information about current connections

Options:

**Comment by sthirugn** [comment]
No action need on this for now
