### ISSUE TITLE
SAM :  Creation of test stubs for auth-source

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1929]
hammer auth-source --help
Usage:
    hammer auth-source [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 ldap                          Manage LDAP auth sources.

Options:
 -h, --help                    print help
[root@cisco-b200m1-03 ~]#

**Comment by sthirugn** [comment]
No action need on this for now
