### ISSUE TITLE
SAM : Creation of test stubs for boot-disk

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1930]
hammer bootdisk --help
Usage:
    hammer bootdisk [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 generic                        
 host                           

Options:
 -h, --help                    print help

**Comment by sthirugn** [comment]
No action need on this for now
