### ISSUE TITLE
CLI and API smoke tests may require fix for overriding the repos via product-content

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#1937]
1) Currently the CLI and API test_end_to_end uses 'sub-man repos --enable=REPOID' to fix instead of product-content override for repo.

2) Investigate the right approach and fix if needed.

Earlier[during sat6.0]  there was no need to enable the repo via the product-content.
Now we need to override the content.

> From: Tom McKay
> 
> There is a change: If the activation key has auto-attach on, then the subs
> are used as a list to auto-subscribe from; they are not all forced to attach
> to the content host. Turn auto-attach off for 6.0 behaviour where all subs
> are applied.
> 
> We need to change this.

More info from https://bugzilla.redhat.com/show_bug.cgi?id=1192106

**Comment by JacobCallahan** [comment]
It actually is a pretty easy fix. Instead of dealing with product-content enablement, we must simply turn off auto-attach for the activation key being used.

**Comment by kbidarkar** [comment]
NOTE: The behaviour will change in future, that's what I get from Tom McKay's  comments.

**Comment by elyezer** [comment]
I have edited the issue description to remove Tom's email address, there is no need to leave it public available.

**Comment by JacobCallahan** [comment]
I believe I have fixed the problem, but am having difficulty running the smoke tests. If I push the changes to my repo, would one of you run the tests on your end?

**Comment by JacobCallahan** [comment]
The current method is valid, but not the preferred way of overriding product content. I will file a new issue so I can make the changes later.
