### ISSUE TITLE
Create test stubs for content view version removal

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#1938]
Create test stubs for API, CLI and UI considering the scenarios listed on https://github.com/SatelliteQE/robottelo/issues/1938#issuecomment-75859826.

**Comment by sthirugn** [comment]
**Test Scenario 1**
1. Create a content view
2. Add a yum repo to it
3. Publish it
4. Remove the new version from library

**Test Scenario 2**
Same as *Test Scenario 1*, but use puppet modules repo

**Test Scenario 3**
Same as *Test Scenario 1*, but use docker repo

**Test Scenario 4**
Same as *Test Scenario 1*, but use yum, puppet modules, docker repos together

**Test Scenario 5**
1. Create a content view
2. Add a yum repo to it
3. Publish it
4. Promote it to from Library to QE environment
5. Attempt to remove the new version from QE alone

**Test Scenario 6**
1. Same as *Test Scenario 5*
2. Attempt to promote again to QE environment

**Test Scenario 7**
1. Create a content view
2. Add a yum repo to it
3. Publish it
4. Promote it to from Library to QE environment
5. Attempt to delete the content view which should delete the published versions from enviroments.

**Test Scenario 8**
1. Same as *Test Scenario 7*
2. Attempt to delete the content view which should delete the published versions from enviroments.

**Comment by jlsherrill** [comment]
Content view version 'removal' allows you three workflows:

a) removing a cv from one or more environments
b) completely deleting the version (assuming the version is in no more environments)
c) a) and b) at the same time

i believe you are missing testing c) and missing removing it from more than one environment at the same time.  

I would also test removing a version from an environment that has content hosts and activation keys assigned

**Comment by sthirugn** [comment]
Final version:
UI and CLI cases (and API too):

**Test Scenario 1**
1. Create a content view
2. Add a yum repo to it
3. Publish it
4. Remove the cv version from library

**Test scenario 1.1** - Attempt to remove a content view that has been renamed.
1. Create a content view cv1
2. Add a yum repo to it
3. Publish it
4. Rename the content cv1 to cv2
5. Remove the content view

**Test Scenario 2**
1. Create a content view
2. Add puppet module(s) to it
3. Publish it
4. Promote from Library -> DEV
5. Remove the cv version from library
6. Assert that cv version exists only in DEV and not in Library
7. Assert that puppet module(s) repo exists? (not necessary, just an additional assert - we can keep this)

**Test Scenario 3**
1. Create a content view
2. Add docker repos to it
3. Publish it
4. Promote from Library -> DEV -> QE
5. Remove the cv version from library
6. Assert that cv version exists only in DEV, QE and not in Library

**Test Scenario 4**
1. Create a content view
2. Add repos containing yum, puppet modules, docker repos to it
3. Publish it
4. Promote from Library -> DEV -> QE -> PROD
5. Remove the cv version from library
6. Assert that cv version exists only in DEV, QE, PROD and not in Library

**Test Scenario 5**
1. Create a content view
2. Add a yum repo and a puppet module to it
3. Publish it
4. Promote it to mulitple environments. Library -> DEV -> QE -> STAGE -> PROD
5. Attempt to remove the cv version from PROD
6. Assert that cv version exists only in Library, DEV, QE, STAGE and not in PROD
7. Attempt to promote again from STAGE to PROD environment
8. Assert that cv version exists in Library, DEV, QE, STAGE, PROD

**Test Scenario 6**
Same as Test Scenario 5 Steps 1 through 4 and
5. Attempt to remove the cv version from QE, STAGE and PROD
6. Assert that cv version exists in Library, DEV

**Test Scenario 7**
1. Create a content view cv1
2. Add a yum repo and a puppet module to it
3. Publish it
4. Promote it to mulitple environments. Library -> DEV -> QE -> STAGE -> PROD
5. Attempt to delete the content view cv1 which should delete the content view and its published versions from all enviroments.
6. Assert that cv1 doesn't exist

**Test Scenario 8**
1. Create a content view
2. Add a yum repo and a puppet module to it
3. Publish it
4. Promote it to mulitple environments. Library -> DEV -> QE
5. Create an Activation key with the above QE environment
6. Register content-host(s) using this Activation key
7. Attempt to remove the cv version from QE
8. Verify if the affected Activation key and Content-hosts are functioning ok
9. Assert:
    - Activation key still exists
    - Content-hosts still exists
    - ContentView does not exist in Activation Key and Content-host association

**Test Scenario 9**
1. Create a content view cv1
2. Add a yum repo and a puppet module to it
3. Publish it
4. Promote it to mulitple environments. Library -> DEV -> QE
5. Create an Activation key with the above QE environment
6. Register content-host(s) using this Activation key
7. Attempt to remove the content view cv1
8. Verify if the affected Activation key and Content-hosts are functioning ok
9. Assert:
   - Activation key still exists
   - Content-hosts still exists
   - ContentView does not exist in Activation Key and Content-host associations

**Test Scenario 10** (Online Capsule)
1. Create a content view cv1
2. Setup satellite to use a capsule c1 and to sync all lifecycle environments
3. Add repos containing yum, puppet modules, docker repos to cv1
4. Publish it
5. Promote from Library -> DEV -> QE -> PROD
6. Remove the cv version from library
7. Make sure the capsule is updated
    - Assert that Content-view version in capsule is removed from Library and exists only in DEV, QE, PROD

**Test Scenario 10** (Disconnected Capsule)
1. Create a content view cv1
2. Setup satellite to use a capsule c1 and to sync all lifecycle environments
3. Add repos containing yum, puppet modules, docker repos to cv1
4. Publish it
5. Promote from Library -> DEV -> QE -> PROD
6. Disconnect capsule
7. Remove the cv version from library, DEV - Make sure that this is completed
8. Bring capsule back online and verify if the task is completed in capsule
7. Make sure the capsule is updated
    - Assert that Content-view version in capsule is removed from Library, DEV and exists only in QE, PROD

**Comment by sghai** [comment]
Lets stub these tests in robottelo and see how much of these we can cover as some of these required capsule server as well. Adding this in next sprint.
