### ISSUE TITLE
Implement separate "LETS" suite exclusive of normal test/smoke suites

### ISSUE THREAD

**Issue by cswiii** [SatelliteQE/robottelo#1950]
I hate acronyms but let's... use **LETS** - Long-Executing Test Suite

**Problem:**  We have, or want to have tests that can perform long-running actions. Generally these revolve around sync (content sync, sync plans, capsule sync). However, getting asserts on these sorts of tests, 
* (a) are problematic as the time can vary greatly in when they complete, making asserts a bit more difficult to ascertain
* (b) executing serially, would come at the expense of completion of other parts of the suite.

**Solution:**  Create a separate suite where long-executing tests go to live.  These can be launched in parallel with the standard tests, but do not interrupt actual execution thereof.  Furthermore, errors that occur in this suite -- and we inevitably will see more, spurious failures due to timeouts, etc -- will not pollute our other test results.

**Implementation:**
_partial, subject to change_
* These tests should be done, when possible, in the CLI.  Probably much easier to assert against CLI than wait for myriad UI elements.
* These tests will require some sort of sleep/wait between execution and assert that watches, or periodically wakes up, to see if the assertion can be made or not.

**Questions:**
* Do we need to run these as often?  As they are long running, there is the chance they won't complete in a timely fashion.  We need to figure out how often these should be executed
* How will we implement a failure to assert?  If a sync fails, how do we know it's a fail and we're not just waiting?  i'm not sure we can capture every single expected error and know what it is.  Should we look for an errorcode to make a final determination?

**Comment by elyezer** [comment]
Our current test suite runs in a reasonable time. If in the future we find that some tests should be migrate and treated as a long running one we can separate it in a different package and improve the automation to run them after other tests or in parallel.

As we will need a set of issues not just for robottelo I will close this issue as it is not critical now. Updated and specific issues will be open if needed.
