### ISSUE TITLE
Upgrade Test: Upgrade completes successfully.

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1985]
@Test: Server: Upgrade completes successfully.
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
 1.  Attempt to upgrade to latest version/compose of product; observe logs while/after doing so
@Assert: Upgrade is successful; all services start; logs show no ERRORs upon install or restart
@Status: Manual

**Comment by lhellebr** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1205668
https://bugzilla.redhat.com/show_bug.cgi?id=1205693

**Comment by sghai** [comment]
This is already covered with automation-tools and we do have upgrade triggers and standalone upgrade job. so closing this now.
