### ISSUE TITLE
Upgrade Test: Upgraded Satellite loses no data upon upgrade.

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1986]
@Test: Server: Upgraded Satellite loses no data upon upgrade.
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
1.  Via $method (manual examination, automated comparison, db forensics/health-check), assure that all populated data remains exposed to user; any newly opened ports that might exist on upgraded instance do in fact get opened on an upgrade.
   @Assert: No lost and/or irretrievable data.
   @Status: Manual

**Comment by lhellebr** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1204228
https://bugzilla.redhat.com/show_bug.cgi?id=1205737

**Comment by sghai** [comment]
A data population & validation script is required to populate the contents and  once upgrade is done same data should be validated.

**Comment by sghai** [comment]
@rochacbruno : Could you please see if you can take this up and help us on upgrade automation task.

**Comment by rochacbruno** [comment]
Tool for populate released to https://github.com/SatelliteQE/satellite-populate
Now the goal is to write a YAML file to cover upgrade tests.

**Comment by ntkathole** [comment]
We have existence tests for it now. Please feel free to re-open, if this still needs fixing.
