### ISSUE TITLE
Upgrade Test: Delta functionality between old version and latest release/compose works in upgraded system

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1987]
@Test: Server:  Delta functionality between old version and latest release/compose works in upgraded system
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
1.  Attempt to perform functionality critical to latest release in an updated system
   @Assert: All new functionality is available and works as expected.
   @Status: Manual

**Comment by sghai** [comment]
I think this issue and #1992 are same..If so, we can close one of them ?

**Comment by sghai** [comment]
Closing this as its similar to #1992.
