### ISSUE TITLE
Upgrade Test: katello-agent: Upgrade completes successfully.

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1988]
@Test: katello-agent: Upgrade completes successfully.
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
1.  Attempt to upgrade to latest version/compose of product; observe logs while/after doing so
   @Assert: Upgrade is successful; all services start; logs show no ERRORs upon install or restart
   @Status: Manual

**Comment by sghai** [comment]
@jyejare : Are we covering this in our client automation testing. If not then we may need to cover this. Assigning directly to you and adding it to next sprint.

**Comment by jyejare** [comment]
@omaciel and @sghai :
In Client Upgrade, We have implemented following things:
1. Create Clients of the previous version registered to the satellite.
2. Upgrade The Clients.
3. Check if the new katello-agent package is been installed.

Not Implemeted:
1. Services(goferd) status
2. Logs of katello-agent package upgrade.

**Comment by omaciel** [comment]
@jyejare please file issues for any required steps that need to be ready before we tackle this issue?

**Comment by jyejare** [comment]
We want satellite images to get ready to test the new code for not implemented tasks mentioned in my previous comment.

Issue #444 has been created for creating images already.

**Comment by ntkathole** [comment]
It is part of satellte6-upgrade now. Please feel free to re-open, if this still needs fixing.
