### ISSUE TITLE
Upgrade Test: Capsule: Old capsule communicating with upgraded server

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1989]
@Test: Capsule: Old capsule communicating with upgraded server
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
1.  Attempt to sync content/communicate with upgraded host
   @Assert: **UNSURE** At a minimum, capsule handles situation gracefully and does not cause disruption on parent server using older functionality; newer, unavailable functionality does not trigger issues in capsule.
   @Status: Manual

**Comment by sghai** [comment]
@omaciel : I think old capsule won't be able to communicate once Satellite is upgrade to newer version. So I think we should close this out but before that I wanted to double check with you.

**Comment by omaciel** [comment]
@sghai hmmm why not? The capsule is registered to the Satellite, right? I think the test case needs to be updated (it's a bit old) but:

> Given that you have a Satellite and a Capsule fully configured...
> And the Capsule is fully registered and configured for synchronization
> When I upgrade my Satellite system I should be able to re-trigger a synchronization for the Capsule
> And the synchronization should succeed

**Comment by sghai** [comment]
@omaciel: Sync from upgraded Satellite to old capsule won't happen directly. We need to upgrade the old capsule first then only we can re-sync contents. We can talk about this case in our weekly meeting today.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
