### ISSUE TITLE
Upgrade Test: Capsule: Upgrade can communicate with upgraded server.

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1990]
@Test: Capsule: Upgraded capsule can communicate with upgraded server.
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system and an associated external capsule.
1.  Attempt to sync content from upgraded host
   @Assert: Functionality remains in upgraded capsule when connecting to upgraded server.
   @Status: Manual

**Comment by cswiii** [comment]
Examples of functionality that should remain:

* Ability to sync content to capsule
* Ability to pull content (via yum) from capsule
* Ability to push content (packages, errata, puppet content) via Satellite through capsule.

**Comment by sghai** [comment]
@jyejare : I think upgrade automation covers this. Could you please re-check and confirm so that we can close this issue ?

**Comment by jyejare** [comment]
@omaciel and @sghai :
In Satellite/Capsule Upgrade, We have implemented following things:
1. Images Populated with previous Satellite/Capsule Version with contents of katello and foreman.
2. Upgrade The Satellite and associated Capsule.

Manual:
1. Capsule Sync after upgrade.
2. Pull content (via yum) from capsule
3. push content (packages, errata, puppet content) via Satellite through capsule.

The all above Manual Tests needs to be automated.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
