### ISSUE TITLE
Upgrade Test: Capsule: Upgrade completes successfully.

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1991]
@Test: Capsule: Upgrade completes successfully.
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
1.  Attempt to upgrade to latest version/compose of product; observe logs while/after doing so
   @Assert: Upgrade is successful; all services start; logs show no ERRORs upon install or restart
   @Status: Manual

**Comment by sghai** [comment]
@jyejare  : I think upgrade automation covers this. Could you please re-check and confirm so that we can close this issue ?

**Comment by jyejare** [comment]
@omaciel and @sghai :
In Satellite Upgrade, We have implemented following things:
1. Images Populated with previous Satellite Version with contents of katello and foreman.
2. Upgrade The Satellite.
3. Logs been collected by foreman-debug and downloading these logs to local system.
4. Check the services are active after upgrade.

Not Implemeted:
Real Time log analyzing is not been automated yet , and this is been planned for improvements in recent future.
The new issue https://github.com/SatelliteQE/automation-tools/issues/447 is been raised.
