### ISSUE TITLE
Upgrade Test: Server:  Delta functionality between old version and latest release/compose works in upgraded system

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1992]
@Test: Server:  Delta functionality between old version and latest release/compose works in upgraded system
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
1.  Attempt to perform functionality critical to latest release in an updated system
   @Assert: All new functionality is available and works as expected.
   @Status: Manual

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
