### ISSUE TITLE
Upgrade Test: katello-agent: Upgraded agent can communicate with upgraded server.

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1993]
@Test: katello-agent: Upgraded agent can communicate with upgraded server.
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system and install upgraded agent.
1.  Attempt to communicate with upgraded host
   @Assert: Functionality remains in upgraded agent when connecting to upgraded server; system remains "registered" to upgraded host and can (??) consume content
   @Status: Manual

**Comment by cswiii** [comment]
Examples of functionality that should remain in katello-agent
* Ability for system to "check-in" with server
* Ability for system to receive content push from Sat (pkgs, errata, puppet)

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
