### ISSUE TITLE
Upgrade Test: katello-agent: Old katello-agent communicating with upgraded server

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1994]
@Test: katello-agent: Old katello-agent communicating with upgraded server
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
1.  Attempt to sync content/communicate with upgraded host
   @Assert: **UNSURE** At a minimum, agent handles situation gracefully and does not cause disruption on parent server using older functionality; newer, unavailable functionality does not trigger issues in agent.
   @Status: Manual

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
