### ISSUE TITLE
Upgrade Test: katello-agent: Old katello-agent communicating with upgraded server

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1995]
@Test: katello-agent: Old katello-agent communicating with upgraded server
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
1.  Attempt to sync content/communicate with upgraded host
   @Assert: **UNSURE** katello-agent should be notified of new version and upgraded on the fly?
   @Status: Manual

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
