### ISSUE TITLE
Upgrade Test: puppet-agent: Upgrade completes successfully.

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1996]
@Test: puppet-agent: Upgrade completes successfully.
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
1.  Attempt to upgrade to latest version/compose of product; observe logs while/after doing so
   @Assert: Upgrade is successful; all services start; logs show no ERRORs upon install or restart
   @Status: Manual

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
