### ISSUE TITLE
Upgrade Test: puppet-agent: Upgrade can communicate with upgraded server.

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1997]
@Test: puppet-agent: Upgrade can communicate with upgraded server.
@Setup: Follow procedures to populate a previous GA version with selected content; upgrade this system.
1.  Attempt to communicate with upgraded host
   @Assert: Functionality remains in upgraded capsule when connecting to upgraded server.
   @Status: Manual

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
