### ISSUE TITLE
Fix the timeout issue related to  tests.foreman.ui.test_sync.Sync.test_sync_rh_repos

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#2032]
At times enabling repos via UI timesout. Why?  I believe we need to increase the timeout even further.

**Comment by kbidarkar** [comment]
Reasons for this failure: 
uploading a manifest for the first time throws "error  importing manifest", later on the same manifest which is cloned gets uploaded without any issue.

**Comment by kbidarkar** [comment]
The screenshots from sesame shows this output.
![no_subscriptions_seen_test_sync_rh_repos](https://cloud.githubusercontent.com/assets/373096/7141360/bc473af0-e2ee-11e4-84b9-b17e7004cd5f.png)

**Comment by kbidarkar** [comment]
From /var/log/production/foreman.log, we see the below traceback.

2015-04-14 21:25:30 [E] Error during manifest import: {"displayMessage"=>"Manifest import failed", "conflicts"=>[]}
2015-04-14 21:25:30 [E] Katello::Resources::Candlepin::Owner: Request Timeout  (POST /candlepin/owners/aa959e63-d464-409c-817f-691de3e6ddb4/imports) (RestClient::RequestTimeout)
/opt/rh/ruby193/root/usr/share/gems/gems/rbovirt-0.0.29/lib/restclient_ext/request.rb:56:in `rescue in transmit'
/opt/rh/ruby193/root/usr/share/gems/gems/rbovirt-0.0.29/lib/restclient_ext/request.rb:11:in `transmit'
/opt/rh/ruby193/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'

**Comment by kbidarkar** [comment]
As per the suggestions from sat6-list mailing list,

```
You can adjust rest_client_timeout in /etc/foreman/plugins/katello.yaml,
that might help things.  Try upping it to 300 maybe.
```

**Comment by kbidarkar** [comment]
The automation uses the below manifest.
```
http://sesame.lab.eng.rdu2.redhat.com/manifests/manifest-latest.zip
```
It just has the subscription:  `Red Hat Employee Subscription`

**Comment by kbidarkar** [comment]
Currently there is no subscription which can be used apart from `Employee SKU` and `Red Hat Employee Subscription` and it appears that both of them have same products.

**Comment by elyezer** [comment]
On the current build the test is failing because another issue. With that said the timeout is not the issue anymore since the test have passed some builds ago. Closing this.
