### ISSUE TITLE
Update tests that rely on localized notifications for assertions

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2071]
The following assertions rely on the web ui being localized in english, which not only is very brittle but blocks us from trying to run their associated tests under different locales. 

Example:

``` python
            self.assertEqual(context.exception.message,
                             'Could not find tab to add puppet_modules')
```

We should reconsider these assertions and rely on something a bit more neutral instead:
- https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_contentviews.py#L620
- https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_contentviews.py#L644
- https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_contentviews.py#L670
- https://github.com/elyezer/robottelo/blob/fix-2055/tests/foreman/ui/test_settings.py#L546
- https://github.com/elyezer/robottelo/blob/fix-2055/tests/foreman/ui/test_template.py#L120
- https://github.com/elyezer/robottelo/blob/fix-2055/tests/foreman/ui/test_template.py#L145

**Comment by rplevka** [comment]
Are you sure?
From what I can see in the examples you've provided, I would say the asserts refer to the messages originating in **our** robottelo code, not the UI itself:

```python
        if element:
            element.click()
            self.wait_for_ajax()
            if self.wait_until_element(
                    tab_locators["contentviews.tab_puppet_modules"]):
                self.wait_until_element(
                    tab_locators["contentviews.tab_puppet_modules"]).click()
            else:
                raise UIError(
                    'Could not find tab to add puppet_modules'
                )

```
https://github.com/SatelliteQE/robottelo/blob/master/robottelo/ui/contentviews.py#L392

Checking the methods raising the mentioned exceptions, they don't seem to rely on any specific web-page string, so from my point of view they're fine. :v:

..unless ...I completely missed your point

**Comment by elyezer** [comment]
@rplevka you are right. But we need to ensure that the exceptions are raised based on a non-localized string locator.

**Comment by ntkathole** [comment]
We moved to new UI framework. Please feel free to re-open, if this still needs fixing.
