### ISSUE TITLE
Drop duplicate code by making common functions

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#2072]
I can see a lot of tests now required synced product/repo and along with published/promoted CV in specific env. We already have some functions but currently those functions are module specific. 

So where we can keep those common functions ? 
- helpers.py ?
- create new file with some name under common ?

Any suggestions/thoughts ?

**Comment by elyezer** [comment]
If I understand this you need a kind of factory that will give, a synced product/repo included in a published/promoted CV, right? If the answer is yes, then I think we can create an API helper in order to do all that actions in one go, but where to put this code I still thinking on it.

**Comment by sghai** [comment]
Yeah.. we already have functions to create product/repo/sync etc and all operations we are doing via api.. The only thing is where can I place them..?

**Comment by rochacbruno** [comment]
@sghai is this something we still need issue to track? or can we close and this thing is just a good practice of refactoring we must do in every iteration.

**Comment by sghai** [comment]
@rochacbruno : Yeah we can close this issue now as we are already using helper functions at module level and if needed, we can file a specific issue.
