### ISSUE TITLE
Automate `test_cv_clone_within_same_env`

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#2076]
This test is around cv clone functionality...

**Comment by sghai** [comment]
Test steps are: 
- Create a content-view with some repos
- publish it
- Now copy it with `copy-view` button
- Validate whether the cloned CV has same repos and version as the original one..

**Comment by jyejare** [comment]
@sghai  - Automated this test in PR #2079.
Validated by comparing the repo's in both the CV's as of now, because the version(s) are not copying in cloned CV. Raised an RFE for same BZ:1212425.
