### ISSUE TITLE
Method is_logged doesn't necessarily reflect the actual session state

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#2089]
the method `is_logged(self)` inside [login.py](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/ui/login.py) is based on checking for the UI element `gravatar`.

I don't think it's an ultimate approach for deciding whether the user is logged in or not.
What's more, `gravatar` can be disabled via Administer->Settings. In such case, no `gravatar` element exists which tricks the method to return 'False' every time.

I think the best solution to check whether the session is valid would be checking for the HTTP response code after sending out a GET request for some default resource (e.g. like <hostname>/dashboard).
if __200 (OK)__ - session is valid
if __302 (Found)__ - session is not valid and a redirect is happening (or check 'Location' header to make sure server is redirecting us to the login page)

This might be achievable using Sockets or some python HTTP library or using bash|curl|awk|sed:

__Nasty (yet working) example:__
```bash
# Obtaining a cookie
# First, extract the CSRF Token
AUTH=`curl -Lksc "c" https://${HOST}/users/login | grep csrf-token | awk -F \" '{print $2}' | sed 's/+/%2B/g'`
# Send the login request with obtained csrf token and save the session cookie to "c"
curl -Lkb "c" -c "c" -d "utf-8=✓&authenticity_token=${AUTH}&login[login]=admin&login[password]=changeme&commit=Login" "https://${HOST}/users/login"
# The actual check:
[ $(curl -sIkb "cookie" https://ibm-x3650m4-03-vm09.lab.eng.brq.redhat.com/dashboard | grep HTTP | awk '{print $2}') == 200 ] && echo True || echo False
```

**Comment by elyezer** [comment]
#2114 is merged, closing this.
