### ISSUE TITLE
Incorrect search entity mechanism

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2091]
At that moment search entity functionality assumes that we have at least one entity in the list and return exception "Search box not found" in case corresponding search box is absent, but in case we try to search in empty list we get mentioned exception by mistake as that field should not be present on the page in most ("but not in all") cases.

**Comment by elyezer** [comment]
:+1:

**Comment by oshtaier** [comment]
First of all, it is very time consuming and will give us a lot of code duplication in case we try to automate search functionality for all entities separately and independently. In the same time, it is impossible to create universal approach as different foreman entities have different UI for empty and full lists. For example:
Config groups:
![config_groups_empty](https://cloud.githubusercontent.com/assets/10895065/7273894/b67d4e08-e900-11e4-9b06-61c671de60f1.png)
Environments:
![environments_empty](https://cloud.githubusercontent.com/assets/10895065/7274044/246390fc-e902-11e4-9048-3ceb539b4d2f.png)
....
Provided approach should be best shot between value and code quality. From one point of view, it can make debbug procedure more complicated as we can miss situation when field missed when it should be present, however we can see problem in logs.

Upload in few hours

**Comment by sghai** [comment]
Yeah..I saw issues around in search_entity function.. @kbidarkar has also fixed so many issues around search_entity... 

@oshtaier thanks for catching this..
