### ISSUE TITLE
Please fix the jenkins automation failure : list of tests given in the description

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2093]
the failure says:

tests.foreman.cli.test_contentviews.TestContentView.test_associate_view_rh
robottelo.common.ssh: DEBUG: <<< [ERROR 2015-04-21 02:33:51 Exception] Error: product not found
Could not enable repository:
  Error: product not found

list of test names facing the above issue:
Test Names:
tests.foreman.cli.test_contentviews.TestContentView.test_associate_view_rh 
tests.foreman.cli.test_contentviews.TestContentView.test_associate_view_rh_custom_spin
tests.foreman.cli.test_subscription.TestSubscription.test_enable_manifest_repository_set
tests.foreman.cli.test_contentviews.TestContentView.test_cv_publish_rh
tests.foreman.cli.test_contentviews.TestContentView.test_cv_promote_rh

please, change the redhat repository product which can be recognized
thanks

**Comment by elyezer** [comment]
None of these tests was found in last result failure list, closing this.
