### ISSUE TITLE
Add CLI test for compute-resource-ids parameter in factory.make_org (multiple values scenario)

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#2098]
Add CLI test to cover creation of organization (```factory.make_org()```) 
with multiple compute resources, using ```compute-resource-ids``` parameter.
Amount of compute-resource-ids should be a random number between 2 and 5.
```
--compute-resource-ids                      COMPUTE_RESOURCE_IDS Compute resource IDs
                                            Comma separated list
                                            of values.
```
Issue is related to #1716

**Comment by oshtaier** [comment]
Blocked by BZ1226828
