### ISSUE TITLE
Add CLI test for config-template-ids parameter in factory.make_org (multiple values scenario)

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#2099]
Add CLI test to cover creation of organization (```factory.make_org()```) 
with multiple config templates, using ```config-template-ids``` parameter.
Amount of config-template-ids should be a random number between 2 and 5.
```
--config-template-ids CONFIG_TEMPLATE_IDS   Provisioning template IDs
                                            Comma separated list
                                            of values.
```
Issue is related to #1716

**Comment by oshtaier** [comment]
Blocked by BZ1226828
