### ISSUE TITLE
Automation failure : test_cv_associate_composite_dupe_modules_negative

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2100]
TestName:
tests.foreman.cli.test_contentviews.TestContentView.test_cv_associate_composite_dupe_modules_negative

the test is failing due to a bz:
- https://bugzilla.redhat.com/show_bug.cgi?id=1214212

please use the decorator  @skip_if_bug_open('bugzilla', 1214212)
the test would be waived for the upcoming runs untill the bz is fixed

please fix it
thanks

**Comment by elyezer** [comment]
The listed test was not found in the latest result failures, closing this.

**Comment by tkolhar** [comment]
this issue is found in snap4 compose 2
Error Message
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv content-view puppet-module add --content-view-id="322" --name="ntp"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x4273ad0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x4273ad0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x4273ad0
robottelo.common.ssh: DEBUG: <<< [ERROR 2015-05-14 04:08:03 Exception] Couldn't find Puppet Module 'ntp'.
Could not add the puppet module:
  Couldn't find Puppet Module 'ntp'.
[ERROR 2015-05-14 04:08:03 Exception] 

RestClient::ResourceNotFound (404 Resource Not Found):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.10/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.10/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.10/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.10/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.10/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.10/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.10/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

**Comment by elyezer** [comment]
I have done the following change on the test:

```diff
diff --git a/tests/foreman/cli/test_contentviews.py b/tests/foreman/cli/test_contentviews.py
index be648f0..564eaaa 100644
--- a/tests/foreman/cli/test_contentviews.py
+++ b/tests/foreman/cli/test_contentviews.py
@@ -971,29 +971,29 @@ class TestContentView(CLITestCase):
             'List of puppet modules was not generated')
         self.assertEqual(
             len(puppet_result.stderr), 0)
-        puppet_module = random.choice(puppet_result.stdout)
-
-        # Associate puppet module to CV
-        result = ContentView.puppet_module_add({
-            u'content-view-id': content_view['id'],
-            u'name': puppet_module['name']
-        })
-        self.assertEqual(
-            result.return_code, 0,
-            'Puppet module was not associated'
-        )
-        self.assertEqual(len(result.stderr), 0)
-
-        # Re-associate same puppet module to CV
-        result = ContentView.puppet_module_add({
-            u'content-view-id': content_view['id'],
-            u'name': puppet_module['name'],
-        })
-        self.assertNotEqual(
-            result.return_code, 0,
-            'Same puppet module should not be associated twice'
-        )
-        self.assertGreater(len(result.stderr), 0)
+        # puppet_module = random.choice(puppet_result.stdout)
+        for puppet_module in puppet_result.stdout:
+            # Associate puppet module to CV
+            result = ContentView.puppet_module_add({
+                u'content-view-id': content_view['id'],
+                u'name': puppet_module['name']
+            })
+            self.assertEqual(
+                result.return_code, 0,
+                'Puppet module was not associated'
+            )
+            self.assertEqual(len(result.stderr), 0)
+
+            # Re-associate same puppet module to CV
+            result = ContentView.puppet_module_add({
+                u'content-view-id': content_view['id'],
+                u'name': puppet_module['name'],
+            })
+            self.assertNotEqual(
+                result.return_code, 0,
+                'Same puppet module should not be associated twice'
+            )
+            self.assertGreater(len(result.stderr), 0)
 
     # Content View: promotions
     # katello content view promote --label=MyView --env=Dev --org=ACME
```

The above change is to remove the random choice of the puppet module, with the added code it will run for every puppet module available.

Also I have run three time and got no failure:

```
$ py.test tests/foreman/cli/test_contentviews.py -ktest_cv_associate_composite_dupe_modules_negative
================================================= test session starts =================================================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 57 items

tests/foreman/cli/test_contentviews.py .

==================== 56 tests deselected by '-ktest_cv_associate_composite_dupe_modules_negative' =====================
====================================== 1 passed, 56 deselected in 76.63 seconds =======================================

$ py.test tests/foreman/cli/test_contentviews.py -ktest_cv_associate_composite_dupe_modules_negative
================================================= test session starts =================================================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 57 items

tests/foreman/cli/test_contentviews.py .

==================== 56 tests deselected by '-ktest_cv_associate_composite_dupe_modules_negative' =====================
====================================== 1 passed, 56 deselected in 79.78 seconds =======================================

$ py.test tests/foreman/cli/test_contentviews.py -ktest_cv_associate_composite_dupe_modules_negative
================================================= test session starts =================================================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 57 items

tests/foreman/cli/test_contentviews.py .

==================== 56 tests deselected by '-ktest_cv_associate_composite_dupe_modules_negative' =====================
====================================== 1 passed, 56 deselected in 82.71 seconds =======================================
```

As I was not able to catch the failure I will close this and will monitor the failures if it happen again.

**Comment by elyezer** [comment]
Was able to reproduce the issue, reopening this.
