### ISSUE TITLE
Please fix the jenkins automation failure : tests.foreman.cli.test_model.TestModel.test_create_model_2

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2101]
TestName : 
tests.foreman.cli.test_model.TestModel.test_create_model_2

u"(u'\\U0002ab20\\u6783\\u9f33\\uc5f5\\U0002016e\\U0002021e\\U00020a1f\\U0002a280\\U0002a902\\U000251c9',)" != (u'\U0002ab20\u6783\u9f33\uc5f5\U0002016e\U0002021e\U00020a1f\U0002a280\U0002a902\U000251c9',)
there is difference of escape character ('\') which results into failure
please fix it
thanks

**Comment by jyejare** [comment]
The issue has been taken care into PR #2111
