### ISSUE TITLE
Automation failure : RepositoryTestCase.test_sync

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2102]
Test Name:
tests.foreman.api.test_repository.RepositoryTestCase.test_sync

the  failure is due to : 
"errors":["One of parameters [ organization_id ] required but not specified."]
please specify organization_id  

please fix this
thanks

**Comment by elyezer** [comment]
The `tests.foreman.api.test_repository.RepositoryTestCase.test_sync` in latest compose results. Seems that this have already been fixed, closing this.
