### ISSUE TITLE
Automation failure : list of test names given in description

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2104]
Test Names : 
tests.foreman.api.test_repository.RepositoryTestCase.test_sync
tests.foreman.api.test_repository.RepositoryTestCase.test_update_contents
tests.foreman.api.test_repository.RepositoryTestCase.test_update_gpgkey 
<nose.suite.ContextSuite context=RepositoryUpdateTestCase>:setup

('Connection aborted.', error(111, 'Connection refused'))
i guess there is infrastructure issue and it can be fixed
please fix it
thanks

**Comment by elyezer** [comment]
This failure was caused probably by the server being reprovisioned. I have checked the latest results and none of the listed tests is in the failure list. Closing this.
