### ISSUE TITLE
Add CLI test for location-ids parameter in factory.make_compute_resource (multiple values scenario)

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#2109]
Add CLI test to cover creation of compute resource 
(```factory.make_compute_resource()```) with multiple locations, using 
```location-ids``` parameter.
Amount of location-ids should be a random number between 2 and 5.
```
--location-ids LOCATION_IDS   REPLACE locations with given ids
```
Issue is related to #1715

**Comment by oshtaier** [comment]
Blocked by
https://satellite-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Compose/job/satellite6-automation-downstream-rhel71-cli/lastCompletedBuild/testReport/tests.foreman.cli.test_computeresource/TestComputeResource/test_create_compute_resource_with_location/

**Comment by oshtaier** [comment]
Not blocked anymore
