### ISSUE TITLE
Automation failure smoke test : test names listed below

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2119]
Test result for Sat6 GA snap1
TestNames:
tests.foreman.smoke.test_cli_smoke.TestSmoke.test_end_to_end
tests.foreman.smoke.test_cli_smoke.TestSmoke.test_smoke 

The above tests are failing due the bz:
- https://bugzilla.redhat.com/show_bug.cgi?id=1215027

if the decorator is  @skip_if_bug_open('bugzilla', 1215027) the tests will be skipped untill
the bz is fixed

please fix it thanks

**Comment by elyezer** [comment]
Smoke tests are green again, closing this.
