### ISSUE TITLE
Automation failure smoke test : TestSmoke.test_end_to_end

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2121]
Test results for GA snap1
Testnames:
tests.foreman.smoke.test_ui_smoke.TestSmoke.test_end_to_end 

test is failing becoz a manifest not containing that product is imported 
Could not find the repo: Red Hat Enterprise Virtualization Agents for RHEL 6 Server (RPMs)
 raise UIError('Could not find the repo: {0}'.format(repo))
'Could not find the repo: Red Hat Enterprise Virtualization Agents for RHEL 6 Server (RPMs)\n--------------------

please fix it thanks

**Comment by elyezer** [comment]
Smoke is green again, closing this.
