### ISSUE TITLE
Automation failure : testnames listed below

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2123]
This test fails for sat6 GA snap1
Testnames:
please refer https://satellite-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Compose/job/satellite6-automation-downstream-rhel66-cli/27/#showFailuresLink for tests

there are many testcases failing for same reasons
the tests are failing due to below bz:
- https://bugzilla.redhat.com/show_bug.cgi?id=1215027
please add the appropriate decorator for the tests to fix it

please fix it thanks

**Comment by elyezer** [comment]
The bug is now fixed in the latest build. With that said, there is no need to skip the tests, closing this.
