### ISSUE TITLE
Automation failure : test_negative_create_user

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2124]
the test results are for sat6 GA snap1
Testnames:
tests.foreman.cli.test_user.User.test_negative_create_user_4_1_email_brazil_b 

hammer -v -u admin -p changeme --output=csv user create --firstname="ZvZhVdolpr" --lastname="EVECtIUniV" --mail="email@brazil.b" --login="yhCPzELOJp"
Message,Id
User created,90

since its a negative test scenario it should not accept the email id
please fix it
thanks

**Comment by elyezer** [comment]
According to the latest failures result this is fixed, closing this.
