### ISSUE TITLE
Automation failure : .TestHostCollection.test_positive_delete

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2132]
this test is failing in nightly
Testnames:
tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_delete

hammer -v -u admin -p changeme  host-collection delete --id="18" --organization-id="213"
ERROR 2015-04-26 21:55:16 Exception] Error: Unrecognised option '--organization-id'

See: 'hammer host-collection delete --help'
Could not delete the host collection:
  Error: Unrecognised option '--organization-id'
  
  See: 'hammer host-collection delete --help'
[ERROR 2015-04-26 21:55:16 Exception] 

please remove the organization-id to fix this issue
thanks

**Comment by omaciel** [comment]
The problem here is that **nightly** has removed ``--organization, --organization-id`` as a valid argument. We will need to investigate and check with DEV whether this change was intentional or not.

**Comment by tkolhar** [comment]
The requirement of options for command is different both in GA compose and nightly 
Satellite 6.1 GA compose
-----------------------------

# hammer -v -u admin -p changeme host-collection delete -h
Usage:
    hammer host-collection delete [OPTIONS]

Options:
 --id ID                                 Id of the host collection
 --name NAME                             Host collection name to search by
 --organization ORGANIZATION_NAME        Organization name to search by
 --organization-id ORGANIZATION_ID       organization ID
 --organization-label ORGANIZATION_LABEL Organization label to search by
 -h, --help                              print help

Nightly build
--------------

# hammer -v -u admin -p changeme host-collection delete -h
Usage:
    hammer host-collection delete [OPTIONS]

Options:
 --id ID                       Id of the host collection
 --name NAME                   Host collection name to search by
 -h, --help                    print help

Need to wait until developers confirm that it is intentionally done
Thanks

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all upstream failures
