### ISSUE TITLE
Automation failure : testnames is mentioned below

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2149]
these tests are failing in snap2 GA
TestNames:
tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_1
tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_2

this test is failing due bz:
- https://bugzilla.redhat.com/show_bug.cgi?id=1217334

sample command to see th failure: 
$ LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv lifecycle-environment update --id="281" --organization-id="240" --description="ÝÝÒÕÔÐÌûîÃÁíÂÄÒ"
[ERROR 2015-04-30 03:30:38 Exception] Error: At least one of options --prior, --prior-id is required

See: 'hammer lifecycle-environment update --help'
Could not update environment:
  Error: At least one of options --prior, --prior-id is required
  
  See: 'hammer lifecycle-environment update --help'
[ERROR 2015-04-30 03:30:38 Exception] 

Clamp::UsageError (At least one of options --prior, --prior-id is required):
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.9/lib/hammer_cli/./apipie/../abstract.rb:37:in `parse'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:66:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.9/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.9/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.9/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.9/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

please add appropriate decorator and fix the test
thanks

**Comment by elyezer** [comment]
This duplicates #2092.
