### ISSUE TITLE
Increased the timeout value for test `test_sync_rh_repos`

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#2156]
Stacktrace
```
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-ui/tests/foreman/ui/test_sync.py", line 83, in test_sync_rh_repos
    self.sync.enable_rh_repos(repos)
  File "robottelo/ui/sync.py", line 162, in enable_rh_repos
    "Could not select the product: '{0}'".format(PRDS[prd]))
'Could not select the product: \'Red Hat Enterprise Linux Server\'\n-------------------- >>
```

**Comment by sghai** [comment]
Fixed in PR #2154

**Comment by sghai** [comment]
Closing issue as PR is already merged.

**Comment by elyezer** [comment]
Updated milestone and assignee.

**Comment by sghai** [comment]
Re-opening ...still failing

**Comment by sghai** [comment]
This test is working fine locally but failing in jenkins via test automation.
```
@Test: Create Content RedHat Sync with two repos. ... ok

----------------------------------------------------------------------
Ran 1 test in 230.838s

OK
```

We may need to increase the timeout value again here from 100 to 120.

**Comment by sghai** [comment]
PR raised: https://github.com/SatelliteQE/robottelo/pull/2203

**Comment by sghai** [comment]
PR is merged with increased timeout to 120 but still would like to keep this open until next automation run. I'll close it, If fix is working fine in next compose,

**Comment by elyezer** [comment]
As per conversation on IRC with @sghai "#2156 is already covered by jyejare, so it can be close now".
