### ISSUE TITLE
Automate stubbed test : ui/test_activationkey/test_associate_host 

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#2170]
Please automate the UI test test_associate_host.

@Feature: Activation key - Host

@Steps:
1. Create Activation key
2. Create different hosts
3. Associate the hosts to Activation key

@Assert: Hosts are successfully associated to Activation key

**Comment by elyezer** [comment]
@jyejare seems that you are planning to work on this issue during this sprint, adding related milestone to it.
