### ISSUE TITLE
Automation failure : test_search_permissions

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2173]
TestNames : 
tests.foreman.api.test_permission.PermissionsTestCase.test_search_permissions

the test says  : 
Items in the second set but not the first:
u'Docker/ImageSearch'
u'Container'
u'DockerRegistry'
more details : 
- https://jenkins.example.com/view/Nightly/job/satellite6-automation-upstream-rhel71-api/56/testReport/junit/tests.foreman.api.test_permission/PermissionsTestCase/test_search_permissions/

the search function is failing
please fix it 
thanks

**Comment by oshtaier** [comment]
'API'
u'Docker/ImageSearch'
u'Container'
u'DockerRegistry'

refer to
'UI'
'Docker/ImageSearch'
'Docker/Container'
'Docker/DockerRegistry'

'UI' implementation sounds much better and probably should be used as a standard.
Should we fix automation as is? Or wait for better naming?

**Comment by elyezer** [comment]
@oshtaier good point. I think worth opening a bug.

**Comment by Ichimonji10** [comment]
@oshtaier FYI, upstream and downstream systems expose different permissions. Keep that in mind when testing any permissions-related tests.

**Comment by elyezer** [comment]
And now we have `get_server_software` helper which helps us differentiate from upstream and downstream.

**Comment by Ichimonji10** [comment]
Thank you for that @elyezer. :smile:

**Comment by oshtaier** [comment]
Created:
https://bugzilla.redhat.com/show_bug.cgi?id=1222523
