### ISSUE TITLE
Automation failure : list of tests given below

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2175]
TestNames:
please refer this link for testnames as there are many 
- https://satellite-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Nightly/job/satellite6-automation-upstream-rhel71-ui/49/#showFailuresLink

the failure says ; 
<selenium.webdriver.remote.webelement.WebElement object at 0x31c0810> is not None

please fix it 
thanks

**Comment by sghai** [comment]
The given link contains 74 failures.. Please file seperate issues and don't share the links here.. thanks.

**Comment by elyezer** [comment]
I have edited the URL
