### ISSUE TITLE
Automation failure : lifecycle-environment update

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2181]
TestNames: 
tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_1
tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_2

$ hammer -v -u admin -p changeme --output=csv lifecycle-environment update --new-name="qTDG1eDJtbgGhkR" --id="326" --organization-id="289"
Error: At least one of options --prior, --prior-id is required

See: 'hammer lifecycle-environment update --help'
Could not update environment:
  Error: At least one of options --prior, --prior-id is required
  
  See: 'hammer lifecycle-environment update --help'
[ERROR 2015-05-06 17:30:33 Exception] 

Clamp::UsageError (At least one of options --prior, --prior-id is required):
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:37:in `rescue in parse'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:31:in `parse'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:66:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

**Comment by elyezer** [comment]
This duplicates #2092.
