### ISSUE TITLE
Get rid from all static delays in the code or move them into one place

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2198]
At that moment we have some static delays (e.g. ```sleep(5)```) in the code that definitely is bad practice for any test automation approach. It is necessary to spend some time on investigation and try to find generic approach how we treat situation like that in future. Ideally, we should remove all of them and implement specific solution per each occurrence in the code

**Comment by oshtaier** [comment]
Refer to #2185

**Comment by elyezer** [comment]
All sleeps found by `git grep sleep` are being used for some workaround that is protected by a BZ checking and for some pooling. Not found any sleep on UI other than `tests/foreman/ui/test_discoveredhosts.py`:

```
$ git grep sleep robottelo/ui/ tests/foreman/ui/
tests/foreman/ui/test_discoveredhosts.py:from time import sleep
tests/foreman/ui/test_discoveredhosts.py:        sleep(30)
```

The above sleep is intended for waiting a machine to boot which is a reasonable value. Closing this.
