### ISSUE TITLE
Automation failure : test_associate_host 

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2230]
TestNames
tests.foreman.ui.test_activationkey.ActivationKey.test_associate_host

Error Message
'NoneType' object has no attribute 'click'
-------------------- >> begin captured logging << --------------------
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.password" by id: "login_password"
robottelo.ui.locators: DEBUG: Accessing locator "submit" by name: "commit"
robottelo.ui.locators: DEBUG: Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"
robottelo.ui.base: DEBUG: NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
robottelo.ui.locators: DEBUG: Accessing locator "menu.current_text" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "menu.fetch_org" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'org-menu')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "menu.fetch_loc" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'loc-menu')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "menu.any_context" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "org.nav_current_org" by xpath: "(//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]//li/a[@data-toggle='dropdown'])[1]"
robottelo.ui.locators: DEBUG: Accessing locator "org.select_org" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@href='/organizations/clear']/../../li/a[contains(.,'%s')]"
robottelo.ui.locators: DEBUG: Accessing locator "menu.current_text" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "menu.fetch_org" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'org-menu')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "menu.content" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='content_menu']"
robottelo.ui.locators: DEBUG: Accessing locator "menu.activation_keys" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_activation_keys']"
robottelo.ui.locators: DEBUG: Accessing locator "ak.new" by xpath: "//button[@ui-sref='activation-keys.new']"
robottelo.ui.base: DEBUG: TimeoutException: Timed out waiting for element '//button[@ui-sref='activation-keys.new']' to display.

**Comment by tkolhar** [comment]
when tried locally using nosetests:
$ nosetests -c robottelo.properties -m test_associate_host /home/tkolhar/git/robottelo/tests/foreman/ui/test_activationkey.py
ERROR
ERROR
ERROR: @Test: Test that hosts can be associated to Activation Keys
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_activationkey.py", line 1109, in test_associate_host
    session, org=self.org_name, name=key_name, env=ENVIRONMENT)
  File "/home/tkolhar/git/robottelo/robottelo/ui/factory.py", line 183, in make_activationkey
    ActivationKey(session.browser).create(**create_args)
  File "/home/tkolhar/git/robottelo/robottelo/ui/activationkey.py", line 31, in create
    self.wait_until_element(locators["ak.new"]).click()
AttributeError: 'NoneType' object has no attribute 'click'
ERROR: @Test: Test that hosts can be associated to Activation Keys
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 256, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 244, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
XML: foreman-results.xml
Ran 1 test in 61.824s
FAILED (errors=2)

instead of getting locators["ak.new"]) object we are getting NoneType object 
please fix it
thanks
I

**Comment by jyejare** [comment]
Ran locally on my system, works Fine. Also passing in the latest Jenkins run on both RHEL6 and RHEL7.

Results:
```
[root@jyejare robottelo]# nosetests -m test_associate_host -s ./tests/foreman/ui/test_activationkey.py
.
----------------------------------------------------------------------
Ran 1 test in 172.253s

OK
```
So closing the issue.
