### ISSUE TITLE
Automation failure : tests.foreman.cli.test_import.TestImport

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2231]
TestNames:
tests.foreman.cli.test_import.TestImport.test_import_orgs_default
tests.foreman.cli.test_import.TestImport.test_import_users_default 

Error Message
'transitions.export_tar.url'
-------------------- >> begin captured logging << --------------------
robottelo: DEBUG: Running test TestImport/test_import_orgs_default
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] mktemp -d
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x3c94ad0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x3c94ad0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x3c94ad0
robottelo.common.ssh: DEBUG: <<<
/tmp/tmp.HwthlzPSVT

Stack trace
File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_import.py", line 42, in test_import_orgs_default
    files = prepare_import_data()[1]
  File "robottelo/common/helpers.py", line 326, in prepare_import_data
    tar_remote_path = conf.properties['transitions.export_tar.url']

**Comment by tkolhar** [comment]
when executed locally using nosetests the results are

$ nosetests -c robottelo.properties -m test_import_orgs_default /home/tkolhar/git/robottelo/tests/foreman/cli/test_import.py
ERROR
ERROR: @test: Import all organizations from the default data set
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_import.py", line 42, in test_import_orgs_default
    files = prepare_import_data()[1]
  File "/home/tkolhar/git/robottelo/robottelo/common/helpers.py", line 326, in prepare_import_data
    tar_remote_path = conf.properties['transitions.export_tar.url']
KeyError: 'transitions.export_tar.url'
XML: foreman-results.xml
Ran 1 test in 4.280s

The key 'transitions.export_tar.url' seems to be invalid please provide the correct key
thanks

**Comment by rplevka** [comment]
`transitions.export_tar.url` is a correct key grabbed from `robottelo.properties` file but there's no url by default in `robottelo.properties.sample` file.
The jenkins job needs to be reconfigured to set up this option before running the tests.

**Comment by elyezer** [comment]
https://github.com/SatelliteQE/robottelo-ci/pull/30 fixes that issue. The automation jobs will now provide a configuration for this.
