### ISSUE TITLE
UI testing with multiple locales remotely

### ISSUE THREAD

**Issue by blrm** [SatelliteQE/robottelo#224]
Testing with other locales remotely on Sauce Labs is an important future feature for robottelo. One issue that makes this challenging is that there is no browser agnostic method of selecting a locale with selenium, so there will need to be different approaches for each browser.

**Comment by rplevka** [comment]
This is the feature we don't plan to implement any time soon and it has no meaning to keep it opened. We can always reopen this when it becomes actual.
