### ISSUE TITLE
Add test for /repositories/:repo_id/puppet_modules

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2246]
Our automation has shown that the API call to `GET /repositories/:repo_id/puppet_modules` is returning results containing more puppet modules than should be returned. In other words, if you create a repository that contains 4 puppet modules and then create a second repository with a random number of modules, calling `/repositories/:repo_id/puppet_modules` for the first repository is returning more than 4 results.

At a first glance it looks like this API will return all available puppet modules, regardless of which organizations and/or repositories they're associated to.

A Bugzilla will be filed shortly.

**Comment by omaciel** [comment]
Here's the [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1222118) issue with steps to reproduce it.

**Comment by sghai** [comment]
Bz is closed so this can be automated in next sprint.
