### ISSUE TITLE
Add test for /content_views/:content_view_id/content_view_puppet_modules

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#2248]
The API call response is not including the UUID value for the available puppet modules. Create a test to ensure that the UUID value is being returned.

For more information check https://bugzilla.redhat.com/show_bug.cgi?id=1222125.

**Comment by sghai** [comment]
BZ is closed and its as per design. 

@eleyezer: can we close this issue ? please confirm.

**Comment by sghai** [comment]
I think we can cover a test scenario here:
- Create a product & add puppet repo, sync it
- create a CV and add puppet repo and select the specific version of puppet module. Please don't select  latest version' of the puppet module.
- list the puppet-modules in CV and response should show the UUID of module.

**Comment by JacobCallahan** [comment]
This has been previously automated. Additionally, this functionality is likely to be removed in future versions of Satellite.
