### ISSUE TITLE
Automation failure : test_update_os_template

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2252]
TestNames:
tests.foreman.ui.test_operatingsys.OperatingSys.test_update_os_template

Error Message
'NoneType' object has no attribute 'tag_name'
-------------------- >> begin captured logging << --------------------
nailgun.client: DEBUG: Making HTTP POST request to https://qe-sat6-rhel66.usersys.redhat.com/api/v2/operatingsystems with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"operatingsystem": {"major": "46", "name": "Oaei"}}.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":59,"name":"Oaei","title":"Oaei 46","description":null,"major":"46","minor":"","family":null,"release_name":null,"password_hash":"MD5","created_at":"2015-05-15T19:00:09Z","updated_at":"2015-05-15T19:00:09Z","parameters":[],"media":[],"architectures":[],"ptables":[],"config_templates":[],"os_default_templates":[],"images":[]}
nailgun.client: DEBUG: Making HTTP POST request to https://qe-sat6-rhel66.usersys.redhat.com/api/v2/config_templates with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"config_template": {"name": "JYyW", "snippet": true, "operatingsystem_ids": [59], "organization_ids": [347], "template": "\ud86c\udc95\u0135\ud851\udd6b\ud847\ude71\ud861\udfc2\u59cb\ud851\ude86\ud80c\uddb5"}}.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":74,"name":"JYyW","template_kind_id":null,"template_kind_name":null,"snippet":true,"audit_comment":null,"created_at":"2015-05-15T19:00:09Z","updated_at":"2015-05-15T19:00:09Z","template":"10𫂕ĵ10𫂕𤕫10𫂕𤕫𡹱10𫂕𤕫𡹱𨟂始10𫂕𤕫𡹱𨟂𤚆10𫂕𤕫𡹱𨟂𤚆𓆵","locked":false,"locations":[],"organizations":[{"id":347,"name":"㐽뵢㜂10𫂕𤕫𡹱𨟂𤚆𓆵𧆸姻将ﱵ10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇蘭10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢愉10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊膕10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔","title":"㐽뵢㜂10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸姻将ﱵ10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄𦯝10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄𦯝𡾣10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄𦯝𡾣𣶻10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄𦯝𡾣𣶻𫀥10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄𦯝𡾣𣶻𫀥𤻇蘭10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢愉10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊膕10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊10𫂕𤕫𡹱𨟂𤚆𓆵𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔𧆸𡂄𦯝𡾣𣶻𫀥𤻇𥚢𩸊𣤽𐤊𣙔"}],"template_combinations":[],"operatingsystems":[],"os_default_templates":[]}
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.password" by id: "login_password"
robottelo.ui.locators: DEBUG: Accessing locator "submit" by name: "commit"
robottelo.ui.locators: DEBUG: Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"
robottelo.ui.base: DEBUG: NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
robottelo.ui.locators: DEBUG: Accessing locator "menu.any_context" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "org.nav_current_org" by xpath: "(//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]//li/a[@data-toggle='dropdown'])[1]"
robottelo.ui.locators: DEBUG: Accessing locator "org.select_org" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@href='/organizations/clear']/../../li/a[contains(.,'%s')]"
robottelo.ui.locators: DEBUG: Accessing locator "menu.current_text" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "menu.fetch_org" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'org-menu')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "menu.hosts" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@id='hosts_menu']"
robottelo.ui.locators: DEBUG: Accessing locator "menu.operating_systems" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@id='menu_item_operatingsystems']"
robottelo.ui.locators: DEBUG: Accessing locator "operatingsys.operatingsys_name" by xpath: "//a[contains(., '%s')]"
robottelo.ui.locators: DEBUG: Accessing locator "search" by id: "search"
robottelo.ui.locators: DEBUG: Accessing locator "search_button" by xpath: "//button[contains(@type,'submit')]"
robottelo.ui.locators: DEBUG: Accessing locator "tab_primary" by xpath: "//a[@href='#primary']"
robottelo.ui.locators: DEBUG: Accessing locator "operatingsys.tab_ptable" by xpath: "//a[@href='#ptable']"
robottelo.ui.locators: DEBUG: Accessing locator "operatingsys.tab_medium" by xpath: "//a[@href='#media']"
robottelo.ui.locators: DEBUG: Accessing locator "operatingsys.tab_templates" by xpath: "//a[@href='#templates']"
robottelo.ui.locators: DEBUG: Accessing locator "operatingsys.template" by id: "operatingsystem_os_default_templates_attributes_0_config_template_id"
robottelo.ui.base: DEBUG: NoSuchElementException: Could not locate element operatingsystem_os_default_templates_attributes_0_config_template_id.

**Comment by tkolhar** [comment]
when executed locally nosetests:
$  nosetests -c robottelo.properties -m test_update_os_template /home/tkolhar/git/robottelo/tests/foreman/ui/test_operatingsys.py
ERROR
ERROR: @Test: Update provisioning template

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_operatingsys.py", line 405, in test_update_os_template
    self.operatingsys.update(os_name, template=template_name)
  File "/home/tkolhar/git/robottelo/robottelo/ui/operatingsys.py", line 152, in update
    medium_list=new_mediums
  File "/home/tkolhar/git/robottelo/robottelo/ui/operatingsys.py", line 63, in _configure_os
    self.find_element(locators["operatingsys.template"])
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/support/select.py", line 34, in __init__
    if webelement.tag_name.lower() != "select":
AttributeError: 'NoneType' object has no attribute 'tag_name'

ERROR: @Test: Update provisioning template
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 256, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 244, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
XML: foreman-results.xml
Ran 1 test in 67.852s
FAILED (errors=2)

it seems webelement does not contains any object and hence cannot find 'tag_name'

**Comment by jyejare** [comment]
The Tests locally passing on my machine, but failing when I run it on jenkins machine.

Passing Result:
```
[root@jyejare robottelo]# nosetests -m test_update_os_template ./tests/foreman/ui/test_operatingsys.py
.
----------------------------------------------------------------------
Ran 1 test in 62.888s

```
It has an issue with associating Template with OS on Jenkins systems only. It internally uses Nailgun for this. Needs to figure out the issue from Nailgun end.
