### ISSUE TITLE
Automate create compute resource with invalid username

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2257]
hi
please automate https://bugzilla.redhat.com/show_bug.cgi?id=1222848

create a rackspace compute resource with username $$$$
error should be thrown for invalid username

**Comment by sghai** [comment]
BZ is not fixed yet. Its in New state.

**Comment by pgagne** [comment]
@sghai @rochacbruno the BZ on this was set to NOT FIX, does that mean we can close this one?

**Comment by rochacbruno** [comment]
Yeah I think we can close what do you think @JacobCallahan ?
