### ISSUE TITLE
Test international email support

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#2275]
The question about international email support was raised in the product list and it is something to consider. This issue is to not lose track about it and help ask for update if no clear implementation step still.

**Comment by Ichimonji10** [comment]
See #2265 for further information about this bug.

**Comment by pgagne** [comment]
@elyezer @Ichimonji10 @rochacbruno I was looking to work on this, but have some questions first.

1. When you talk about "international email support" what areas of the product are you referring too?  Creating new users?

**Comment by rochacbruno** [comment]
@oshtaier @elyezer I see that this issue is very old, and @elyezer code in #2265 is replaced with a newer approach.

Is this still valid or our new approach is already covering this issue?

**Comment by elyezer** [comment]
International email is basically testing if the system supports the international email format. International email is email that contains international characters (characters which do not exist in the ASCII character set), 

Refer to [1] in order to find more information.

[1] https://en.wikipedia.org/wiki/International_email

**Comment by rochacbruno** [comment]
@elyezer @pgagne @oshtaier I am guessing that our current test factory already tests that kind of emails. (although using one_data_point it may use one email at once)

**Comment by pgagne** [comment]
@elyezer @rochacbruno 

So when we talk about "international" email my understanding is we are talking about 3 separate, but somewhat related things:

1. international characters in email addresses. This we can test by generating email addresses with international characters in accordance with the relevant RFCs.

2. international characters in email headers. This might require more investigation to see what information Satellite includes in the headers of email it sends, for example if one of the headers may have a value that include something like the Organization name, creating a email for that organization.

3. International characters in email bodies. Similar to headers, but I am not sure if there is much in the way of RFC guidance here, or even if there is anything to test. 

@elyezer @rochacbruno Does this make sense, did I leave something out? Which of these do you think we could focus on here? 1 makes the most sense and maybe 2, but that requires more research.

**Comment by elyezer** [comment]
I think you covered it all.

In order to receive emails you will need to have a server running, it would be great to have a tool that can collect the emails or check the mailing on the satellite system to fetch messages sent by satellite.

I think starting with 1 as the first steps is reasonable.

**Comment by pgagne** [comment]
So I was doing some research on this and came across this bug:

http://projects.theforeman.org/issues/14641

Until this issue is fixed, I don't think there is anything we can really do here. Satellite does not seems to support international email addresses. I am all for removing the validation and just checking to make sure the ``@`` symbol is present.

**Comment by elyezer** [comment]
I see, thanks for following this up @pgagne

**Comment by JacobCallahan** [comment]
Closing this due to its low priority and higher complexity.
