### ISSUE TITLE
Automation failure : test_create_compute_resource_with_location

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2320]
TestNames:
tests.foreman.cli.test_computeresource.TestComputeResource.test_create_compute_resource_with_location

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv compute-resource create --location-ids="220" --name="HjDBW9Dj" --url="qemu+tcp://localhost:16509/system" --provider="Libvirt"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x3b8f3d0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x3b8f3d0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x3b8f3d0
robottelo.common.ssh: DEBUG: <<< [?[31mERROR?[0m ?[34m2015-05-28 00:55:02?[0m ?[36mException?[0m] undefined method `uniq' for "220":String
Could not create the compute resource:
  undefined method `uniq' for "220":String
[?[31mERROR?[0m ?[34m2015-05-28 00:55:02?[0m ?[36mException?[0m] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.12/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

filed a bz : https://bugzilla.redhat.com/show_bug.cgi?id=1225861
please fix it thanks

**Comment by tkolhar** [comment]
This issue occured again on dated 06/04/2015
Error Message

Failed to create ComputeResource with {u'description': None, u'location-ids': u'223', u'user': None, u'password': None, u'tenant': None, u'uuid': None, u'name': u'gJGSm5bV', u'url': 'qemu+tcp://localhost:16509/system', u'region': None, u'server': None, u'organization-ids': None, u'set-console-password': None, u'provider': 'Libvirt'} data due to:
  [ERROR 2015-06-03 17:02:53 Exception] undefined method `uniq' for "223":String
  Could not create the compute resource:
    undefined method `uniq' for "223":String
  [ERROR 2015-06-03 17:02:53 Exception] 
  
  RestClient::InternalServerError (500 Internal Server Error):
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
      /usr/lib/ruby/1.8/net/http.rb:543:in `start'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.13/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
      /usr/bin/hammer:19:in `load'
      /usr/bin/hammer:19
  
filed a bz : https://bugzilla.redhat.com/show_bug.cgi?id=1228178

**Comment by oshtaier** [comment]
Not reproducible anymore neither on ```satellite6-automation-downstream-rhel66-cli``` nor on ```satellite6-automation-downstream-rhel71-cli```
Of course, functionality works properly locally too:
```
nosetests tests/foreman/cli/test_computeresource.py -m test_create_compute_resource_with_location
.
----------------------------------------------------------------------
Ran 1 test in 27.999s

OK
```
