### ISSUE TITLE
Automation failure : tests.foreman.cli.test_hostgroup.TestHostGroup

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2330]
TestNames:
tests.foreman.cli.test_hostgroup.TestHostGroup.test_create_hostgroup_with_organization
tests.foreman.cli.test_hostgroup.TestHostGroup.test_create_hostgroup_with_location

Error Message
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv hostgroup create --location-ids="250" --name="LN332G"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x311e550
robottelo.common.ssh: INFO: Destroying Paramiko client 0x311e550
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x311e550
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-05-28 19:00:28 Exception] undefined method `uniq' for "250":String
Could not create the hostgroup:
  undefined method `uniq' for "250":String
[ERROR 2015-05-28 19:00:28 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.12/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

filed a bz for the same : 
https://bugzilla.redhat.com/show_bug.cgi?id=1226197
please fix it thanks

**Comment by tkolhar** [comment]
this issue occured again dated 06/04/2015
Error Message

Failed to create HostGroup with {u'medium-id': None, u'domain': None, u'location-ids': None, u'operatingsystem': None, u'operatingsystem-id': None, u'subnet': None, u'realm': None, u'parent-id': None, u'organization-ids': u'254', u'environment': None, u'domain-id': None, u'ptable-id': None, u'medium': None, u'puppet-ca-proxy-id': None, u'ptable': None, u'subnet-id': None, u'architecture-id': None, u'environment-id': None, u'puppet-proxy-id': None, u'realm-id': None, u'name': u'09bbCS', u'puppetclass-ids': None, u'puppet-proxy': None, u'architecture': None, u'puppet-ca-proxy': None} data due to:
  [ERROR 2015-06-03 18:24:54 Exception] undefined method `uniq' for "254":String
  Could not create the hostgroup:
    undefined method `uniq' for "254":String
  [ERROR 2015-06-03 18:24:54 Exception] 
  
  RestClient::InternalServerError (500 Internal Server Error):
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
      /usr/lib/ruby/1.8/net/http.rb:543:in `start'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.13/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
      /usr/bin/hammer:19:in `load'
      /usr/bin/hammer:19
  filed a bz for the same :
https://bugzilla.redhat.com/show_bug.cgi?id=1226197
please fix it thanks

**Comment by oshtaier** [comment]
Not reproducible anymore neither on ```satellite6-automation-downstream-rhel66-cli``` nor on ```satellite6-automation-downstream-rhel71-cli```
Of course, functionality works properly on local environment too:
```
nosetests tests/foreman/cli/test_hostgroup.py -m test_create_hostgroup_with_organization
.
----------------------------------------------------------------------
Ran 1 test in 28.439s

OK
```
```
nosetests tests/foreman/cli/test_hostgroup.py -m test_create_hostgroup_with_location
.
----------------------------------------------------------------------
Ran 1 test in 27.390s

OK
```
