### ISSUE TITLE
Automation failure : tests.foreman.cli.test_subscription.TestSubscription

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2333]
TestNames:
tests.foreman.cli.test_subscription.TestSubscription.test_manifest_refresh
tests.foreman.cli.test_subscription.TestSubscription.test_enable_manifest_repository_set
tests.foreman.cli.test_subscription.TestSubscription.test_manifest_history
tests.foreman.cli.test_subscription.TestSubscription.test_manifest_upload

Error Message
1657 != 0
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x3455e50
robottelo.common.ssh: INFO: Destroying Paramiko client 0x3455e50
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x3455e50
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  subscription upload --organization-id="306" --file="/tmp/tmpmZmN_M"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x344f310
robottelo.common.ssh: INFO: Destroying Paramiko client 0x344f310
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x344f310
robottelo.common.ssh: DEBUG: <<< stderr
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, elapsed: 00:00:00
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:02
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:04
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:06
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:08
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:10
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:12
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:14
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:17
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:19
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:21
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:23
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:25
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:27
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:29
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:32
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:34
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:36
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad success: 1.0/1, 100%, 0.1/s, elapsed: 00:00:39
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad success: 1.0/1, 100%, 0.1/s, elapsed: 00:00:39

Failed

tests.foreman.cli.test_subscription.TestSubscription.test_manifest_upload (from nosetests)
Failing for the past 2 builds (Since Unstable#40 )
Took 51 sec.
Error Message

1657 != 0
-------------------- >> begin captured logging << --------------------
robottelo: DEBUG: Running test TestSubscription/test_manifest_upload
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv organization create --name="1GTjGU"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x34666d0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x34666d0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x34666d0
robottelo.common.ssh: DEBUG: <<< stdout
Message,Id,Name
Organization created,306,1GTjGU

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  organization info --id="306"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x3466810
robottelo.common.ssh: INFO: Destroying Paramiko client 0x3466810
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x3466810
robottelo.common.ssh: DEBUG: <<< stdout
Id:                     306
Name:                   1GTjGU
Users:                  

Smart proxies:          
    qe-sat6-rhel66.usersys.redhat.com
Subnets:                

Compute resources:      

Installation media:     

Templates:              
    Boot disk iPXE - generic host (Bootdisk)
    Boot disk iPXE - host (Bootdisk)
    idm_register ()
    Kickstart default iPXE (iPXE)
    Kickstart default PXELinux (PXELinux)
    kickstart_networking_setup ()
    puppet.conf ()
    PXELinux default local boot (PXELinux)
    PXELinux global default (PXELinux)
    Satellite Kickstart Default (provision)
    Satellite Kickstart Default Finish (finish)
    Satellite Kickstart Default User Data (user_data)
    subscription_manager_registration ()
Domains:                

Environments:           

Hostgroups:             

Parameters:             

Created at:             2015/05/28 23:35:14
Updated at:             2015/05/28 23:35:14
Label:                  1GTjGU
Description:            
Red Hat Repository URL: https://cdn.redhat.com

robottelo.common.ssh: INFO: Instantiated Paramiko client 0x3455e50
robottelo.common.ssh: INFO: Destroying Paramiko client 0x3455e50
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x3455e50
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  subscription upload --organization-id="306" --file="/tmp/tmpmZmN_M"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x344f310
robottelo.common.ssh: INFO: Destroying Paramiko client 0x344f310
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x344f310
robottelo.common.ssh: DEBUG: <<< stderr
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, elapsed: 00:00:00
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:02
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:04
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:06
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:08
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:10
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:12
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:14
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:17
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:19
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:21
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:23
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:25
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:27
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:29
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:32
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:34
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:36
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad success: 1.0/1, 100%, 0.1/s, elapsed: 00:00:39
Task 5acaeb35-97cd-4f9b-8311-dfe44440e1ad success: 1.0/1, 100%, 0.1/s, elapsed: 00:00:39

--------------------- >> end captured logging << ---------------------

Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-cli/tests/foreman/cli/test_subscription.py", line 41, in test_manifest_upload
    self._upload_manifest(self.manifest, self.org['id'])
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-cli/tests/foreman/cli/test_subscription.py", line 31, in _upload_manifest
    self.assertEqual(len(result.stderr), 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)

**Comment by tkolhar** [comment]
when executed locally using nosetests:

$ nosetests -c robottelo.properties -m test_manifest_refresh /home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py
015-05-29 15:15:04 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2015-05-29 15:15:08 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x2e7e850
2015-05-29 15:15:37 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x2e7e850
2015-05-29 15:15:37 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x2e7e850
2015-05-29 15:15:37 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  subscription upload --organization-id="417" --file="/tmp/tmpe6yqmc"
2015-05-29 15:15:40 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x2e7e1d0
2015-05-29 15:16:30 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x2e7e1d0
2015-05-29 15:16:30 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x2e7e1d0
2015-05-29 15:16:30 - robottelo.common.ssh - DEBUG - <<< stderr
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, elapsed: 00:00:00
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:02
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:04
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:06
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:08
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:10
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:13
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:15
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:17
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:19
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:22
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:24
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:26
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:28
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:30
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:33
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:35
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:37
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:39
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:41
Task 138a4107-8dfd-4c35-822b-3e43747f587e running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:43
Task 138a4107-8dfd-4c35-822b-3e43747f587e success: 1.0/1, 100%, 0.1/s, elapsed: 00:00:45
Task 138a4107-8dfd-4c35-822b-3e43747f587e success: 1.0/1, 100%, 0.1/s, elapsed: 00:00:45

FAIL
FAIL: @Test: upload manifest (positive) and refresh
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/common/decorators.py", line 362, in wrapper_func
    return func(*args, **kwargs)
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py", line 160, in test_manifest_refresh
    self._upload_manifest(self.manifest, self.org['id'])
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py", line 31, in _upload_manifest
    self.assertEqual(len(result.stderr), 0)
AssertionError: 1918 != 0


XML: foreman-results.xml
Ran 1 test in 113.284s
FAILED (failures=1)

**Comment by tkolhar** [comment]
this issue occured dated on 06/04/2015
Error Message

74 != 0

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "robottelo/common/decorators.py", line 375, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-cli/tests/foreman/cli/test_subscription.py", line 172, in test_manifest_refresh
    self.assertEqual(len(result.stderr), 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'74 != 0\n--------------------

**Comment by tkolhar** [comment]
this issue occurred again dated on 06/05/2015
Error Message
74 != 0

2015-06-05 12:51:21 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  subscription refresh-manifest --organization-id="412"
2015-06-05 12:51:23 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1f25290
2015-06-05 12:51:28 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1f25290
2015-06-05 12:51:28 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1f25290
2015-06-05 12:51:28 - robottelo.common.ssh - DEBUG - <<< stderr
Task 664ae82c-4b38-44a6-9164-e50f88d796f2 running: 0.0/1, 0%, elapsed: 00:00:00
Task 664ae82c-4b38-44a6-9164-e50f88d796f2 warning: 1.0/1, 100%, 0.5/s, elapsed: 00:00:02
Task 664ae82c-4b38-44a6-9164-e50f88d796f2 warning: 1.0/1, 100%, 0.5/s, elapsed: 00:00:02
Unit 2f20e47c-8f94-4fcc-a180-243a380b0e76 has been deleted

FAIL


FAIL: @Test: upload manifest (positive) and refresh
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/common/decorators.py", line 375, in wrapper_func
    return func(*args, **kwargs)
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py", line 172, in test_manifest_refresh
    self.assertEqual(len(result.stderr), 0)
AssertionError: 59 != 0
XML: foreman-results.xml
Ran 1 test in 113.348s
FAILED (failures=1)

manually when executed on sat6 server we get:
$LANG=en_US.UTF-8 hammer -v -u admin -p changeme  subscription refresh-manifest --organization-id="412"

[......................................................................] [100%]
Unit 2f20e47c-8f94-4fcc-a180-243a380b0e76 has been deleted

it seems that manifest we are trying to refresh is deleted
please fix it
thanks

**Comment by elyezer** [comment]
@tkolhar manifest refresh will not work with the manifests robottelo generates.

**Comment by elyezer** [comment]
This have been fixed and the remaining failure (`test_manifest_refresh`) will be fixed by #2352.
