### ISSUE TITLE
Automation failure : tests.foreman.cli.test_template.TestTemplate

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2334]
TestNames:
tests.foreman.cli.test_template.TestTemplate.test_create_template_with_location
tests.foreman.cli.test_template.TestTemplate.test_create_template_with_organization

LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv template create --name="wENBwBJtYm" --file="/tmp/KVM09M7jRj" --type="script" --organization-ids="308"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x34667d0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x34667d0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x34667d0
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-05-28 19:37:49 Exception] undefined method `uniq' for "308":String
Could not create the config template:
  undefined method `uniq' for "308":String
[ERROR 2015-05-28 19:37:49 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.12/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

filed a bz : https://bugzilla.redhat.com/show_bug.cgi?id=1226247

**Comment by tkolhar** [comment]
this issue occurred again dated on 06/04/2015
Error Message

Failed to create Template with {u'audit-comment': None, u'name': u'fZnoZFcYlI', u'file': '/tmp/zQQLn5zSQ8', u'type': 'user_data', u'organization-ids': None, u'locked': None, u'operatingsystem-ids': None, u'location-ids': u'311'} data due to:
  [ERROR 2015-06-03 19:03:30 Exception] undefined method `uniq' for "311":String
  Could not create the config template:
    undefined method `uniq' for "311":String
  [ERROR 2015-06-03 19:03:30 Exception] 
  
  RestClient::InternalServerError (500 Internal Server Error):
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
      /usr/lib/ruby/1.8/net/http.rb:543:in `start'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.13/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
      /usr/bin/hammer:19:in `load'
      /usr/bin/hammer:19

filed a bz : filed a bz : https://bugzilla.redhat.com/show_bug.cgi?id=1226247

**Comment by oshtaier** [comment]
Not reproducible anymore neither on ```satellite6-automation-downstream-rhel66-cli``` nor on ```satellite6-automation-downstream-rhel71-cli```
Of course, functionality works properly on local environment too:
```
nosetests tests/foreman/cli/test_template.py -m test_create_template_with_location
.
----------------------------------------------------------------------
Ran 1 test in 35.705s

OK
```
```
nosetests tests/foreman/cli/test_template.py -m test_create_template_with_organization
.
----------------------------------------------------------------------
Ran 1 test in 37.767s

OK
```
