### ISSUE TITLE
Automation failure : tests.foreman.cli.test_user.User

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2336]
TestNames:
tests.foreman.cli.test_user.User.test_create_user_with_default_location
tests.foreman.cli.test_user.User.test_create_user_with_defaut_org (

 LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv user create --firstname="qC7Y77loPR" --lastname="kTkgjhEEOD" --password="JhscVjF8CK" --auth-source-id="1" --organization-ids="310" --default-organization-id="310" --mail="vXXA9K@example.com" --login="vXXA9K"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x34a8c50
robottelo.common.ssh: INFO: Destroying Paramiko client 0x34a8c50
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x34a8c50
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-05-28 19:40:08 Exception] undefined method `uniq' for "310":String
Could not create the user:
  undefined method `uniq' for "310":String
[ERROR 2015-05-28 19:40:08 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.12/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

filed a bz : https://bugzilla.redhat.com/show_bug.cgi?id=1226252
please fix it 
thanks

**Comment by tkolhar** [comment]
this issue occurred again dated on 06/04/2015
Error Message

Failed to create User with {u'firstname': u'O3Tkn6PrDY', u'lastname': u'zjJq1p7gcJ', u'location-ids': None, u'password': u'voVN5Z0krY', u'auth-source-id': 1, u'default-location-id': None, u'organization-ids': u'314', u'default-organization-id': u'314', u'admin': None, u'mail': 'ohRTan@example.com', u'login': u'ohRTan'} data due to:
  [ERROR 2015-06-03 19:05:48 Exception] undefined method `uniq' for "314":String
  Could not create the user:
    undefined method `uniq' for "314":String
  [ERROR 2015-06-03 19:05:48 Exception] 
  
  RestClient::InternalServerError (500 Internal Server Error):
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
      /usr/lib/ruby/1.8/net/http.rb:543:in `start'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
      /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
      /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.13/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
      /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
      /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
      /usr/bin/hammer:19:in `load'
      /usr/bin/hammer:19
  
filed a bz : https://bugzilla.redhat.com/show_bug.cgi?id=1226252

**Comment by oshtaier** [comment]
Not reproducible anymore neither on ```satellite6-automation-downstream-rhel66-cli``` nor on ```satellite6-automation-downstream-rhel71-cli```
Of course, functionality works properly on local environment too:
```
nosetests tests/foreman/cli/test_user.py -m test_create_user_with_default_location
.
----------------------------------------------------------------------
Ran 1 test in 30.776s

OK
```
```
nosetests tests/foreman/cli/test_user.py -m test_create_user_with_defaut_org
.
----------------------------------------------------------------------
Ran 1 test in 31.056s

OK
```
