### ISSUE TITLE
Please review failure for tests.foreman.api.test_hostgroup.HostGroupTestCase.test_bz_1107708

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2370]
The test **tests.foreman.api.test_hostgroup.HostGroupTestCase.test_bz_1107708** failed today with the following error:  ``0 != 1``

The stacktrace shows:

```python
File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-api/tests/foreman/api/test_hostgroup.py", line 71, in test_bz_1107708
    self.assertEqual(len(cv_attrs['puppet_modules']), 1)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
```

Going through the entire log for this test (please check Jenkins job ``satellite6-automation-downstream-rhel66-api/46/testReport/tests.foreman.api.test_hostgroup/HostGroupTestCase/test_bz_1107708`` for details) I noticed that the following [code block](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_hostgroup.py#L49-L58) may not have run (at least I do not see any calls being made):

```python
        results = content_view.available_puppet_modules()['results']
        # Working with 'ntp' module as we know for sure that it contains at
        # least few puppet classes
        for result in results:
            if result['name'] == 'ntp':
                content_view.add_puppet_module(
                    result['author'],
                    result['name']
                )
                break
```

I went through the process of running the same code manually and it worked fine as shown below:

```python
In [2]: from nailgun.config import ServerConfig

In [3]: server_config = ServerConfig('https://qe-sat6-rhel66.usersys.redhat.com', auth=('admin', 'changeme'), verify=False)

In [4]: from nailgun.entities import *

In [5]: content_view = ContentView(server_config, id=174).read()

In [6]: content_view.name
Out[6]: u'BJlMSnhVQz'

In [7]: results = content_view.available_puppet_modules()['results']

In [8]: len(results)
Out[8]: 5

In [9]: for result in results:
   ...:     print result['name']
   ...:
ntp
pureftpd
samba
httpd
cron

In [10]: for result in results:
   ....:     if result['name'] == 'ntp':
   ....:         content_view.add_puppet_module(result['author'], result['name'])
   ....:         break
```

I then manually ran the rest of the code and everything looked ok, so I wonder if there's a race condition here where the ``ntp`` module is not being associated to the content view? Perhaps add some kind of assertion that, if ``ntp`` is not present, it should fail?

**Comment by omaciel** [comment]
@sthirugn here's the issue we talked about today. I have assigned it to @oshtaier as discussed.

**Comment by sthirugn** [comment]
:+1:

**Comment by oshtaier** [comment]
If we still have issues on Jenkins - we can try to add skip_if_bug_open for https://bugzilla.redhat.com/show_bug.cgi?id=1222118 as suggested by @elyezer. That BZ can be root cause for the initial problem

**Comment by elyezer** [comment]
I agree on skipping this with the bug or doing a workaround if the bug is open. We can't do much since the server is returning inconsistent results.

**Comment by oshtaier** [comment]
Confirmed on latest compose build
