### ISSUE TITLE
Automate Satellite upgrade process

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#2392]
Please automate the upgrade process.

Consider Upgrading:
-> Satellite 6.0 to Satellite 6.1
-> Capsule 6.0 to Capsule 6.1
-> Client Upgrade(Katello Agent Upgrade)

Thanks.

**Comment by elyezer** [comment]
This seems to be an issue more related to automation-tools than robottelo itself. As the requirements for the upgrade test are provisioning machines, installing different versions of the system...

**Comment by jyejare** [comment]
Elyezer, as per the dicussions on IRC, we have decided to use the Openstack images to automate the upgrade process.

**Comment by jyejare** [comment]
Adding this issue as a part of automation-tools.
