### ISSUE TITLE
Automation failure : tests.foreman.cli.test_contenthost.TestCHKatelloAgent

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2418]
TestNames:
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_apply_errata
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_get_errata_info

Error Message
Failed to enable repository set

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Server" --basearch="x86_64" --releasever="7Server" --name="Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)" --organization-id="228"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x25b95d0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x25b95d0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x25b95d0
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-06-10 15:03:07 Exception] Forbidden - server refused to process the request
Could not enable repository:
  Forbidden - server refused to process the request
[ERROR 2015-06-10 15:03:07 Exception] 

RestClient::Forbidden (403 Forbidden):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:76:in `put'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 360, in run
    self.setUp()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_contenthost.py", line 597, in setUp
    u'activationkey-id': TestCHKatelloAgent.activation_key['id'],
  File "robottelo/common/decorators.py", line 76, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 1793, in setup_org_for_a_rh_repo
    raise CLIFactoryError('Failed to enable repository set')
'Failed to enable repository set\n--------------------

**Comment by sthirugn** [comment]
Failed in Snap 12

**Comment by tkolhar** [comment]
tested this using nosetests locally and it fails with below error
$ nosetests -c robottelo.properties -m test_contenthost_apply_errata /home/tkolhar/git/robottelo/tests/foreman/cli/test_contenthost.py
2015-07-29 13:24:05 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Server" --basearch="x86_64" --releasever="7Server" --name="Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)" --organization-id="324"
2015-07-29 13:24:08 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x7fce305299d0
2015-07-29 13:24:11 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x7fce305299d0
2015-07-29 13:24:11 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x7fce305299d0
2015-07-29 13:24:11 - robottelo.common.ssh - DEBUG - <<< stderr
[ERROR 2015-07-29 03:54:10 Exception] Error: repository_set not found
Could not enable repository:
  Error: repository_set not found
[ERROR 2015-07-29 03:54:10 Exception] 

HammerCLIForeman::ResolverError (repository_set not found):
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:191:in `pick_result'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:156:in `find_resource'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:139:in `get_id'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:129:in `repository_set_id'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:149:in `send'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:149:in `get_resource_id'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:138:in `get_identifier'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:230:in `customized_options'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:235:in `request_params'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19



ERROR

ERROR: @Test: Apply errata to content host
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_contenthost.py", line 597, in setUp
    u'activationkey-id': TestCHKatelloAgent.activation_key['id'],
  File "/home/tkolhar/git/robottelo/robottelo/common/decorators.py", line 73, in cacheable_function
    new_object = func(options)
  File "/home/tkolhar/git/robottelo/robottelo/cli/factory.py", line 1830, in setup_org_for_a_rh_repo
    raise CLIFactoryError('Failed to enable repository set')
CLIFactoryError: Failed to enable repository set

XML: foreman-results.xml
Ran 1 test in 149.702s

FAILED (errors=1)

**Comment by tkolhar** [comment]
this issue occurred again dated 07/27/2015
TestNames:
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_apply_errata
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_get_errata_info

Error Message
Failed to enable repository set

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Server" --basearch="x86_64" --releasever="7Server" --name="Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)" --organization-id="380"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x45ecb90
robottelo.common.ssh: INFO: Destroying Paramiko client 0x45ecb90
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x45ecb90
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-07-29 19:47:17 Exception] ["releasever"] cannot be specified for Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs) as that information is not substituable in /content/beta/rhel/server/7/$basearch/sat-tools/6/os 
Could not enable repository:
  ["releasever"] cannot be specified for Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs) as that information is not substituable in /content/beta/rhel/server/7/$basearch/sat-tools/6/os 
[ERROR 2015-07-29 19:47:17 Exception] 

RestClient::UnprocessableEntity (422 Unprocessable Entity):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:80:in `put'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 360, in run
    self.setUp()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-cli/tests/foreman/cli/test_contenthost.py", line 597, in setUp
    u'activationkey-id': TestCHKatelloAgent.activation_key['id'],
  File "robottelo/common/decorators.py", line 73, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 1830, in setup_org_for_a_rh_repo
    raise CLIFactoryError('Failed to enable repository set')
'Failed to enable repository set\n-------------------

**Comment by tkolhar** [comment]
this issue occurred again dated 07/31/2015
TestNames:
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_get_errata_info
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_apply_errata

Error Message
Failed to enable repository set

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Server" --basearch="x86_64" --releasever="7Server" --name="Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)" --organization-id="297"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x3530dd0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x3530dd0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x3530dd0
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-07-31 03:35:05 Exception] ["releasever"] cannot be specified for Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs) as that information is not substituable in /content/beta/rhel/server/7/$basearch/sat-tools/6/os 
Could not enable repository:
  ["releasever"] cannot be specified for Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs) as that information is not substituable in /content/beta/rhel/server/7/$basearch/sat-tools/6/os 
[ERROR 2015-07-31 03:35:05 Exception] 

RestClient::UnprocessableEntity (422 Unprocessable Entity):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:76:in `put'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 360, in run
    self.setUp()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_contenthost.py", line 597, in setUp
    u'activationkey-id': TestCHKatelloAgent.activation_key['id'],
  File "robottelo/common/decorators.py", line 73, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 1830, in setup_org_for_a_rh_repo
    raise CLIFactoryError('Failed to enable repository set')
'Failed to enable repository set\n--------------------

**Comment by tkolhar** [comment]
this issue occurred again dated 08/03/2015
TestNames:
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_get_errata_info
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_apply_errata

Error Message
Failed to enable repository set

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel67.usersys.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Server" --basearch="x86_64" --releasever="7Server" --name="Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)" --organization-id="297"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x43a9cd0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x43a9cd0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x43a9cd0
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-08-03 17:18:04 Exception] ["releasever"] cannot be specified for Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs) as that information is not substituable in /content/beta/rhel/server/7/$basearch/sat-tools/6/os 
Could not enable repository:
  ["releasever"] cannot be specified for Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs) as that information is not substituable in /content/beta/rhel/server/7/$basearch/sat-tools/6/os 
[ERROR 2015-08-03 17:18:04 Exception] 

RestClient::UnprocessableEntity (422 Unprocessable Entity):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:80:in `put'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 360, in run
    self.setUp()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-cli/tests/foreman/cli/test_contenthost.py", line 597, in setUp
    u'activationkey-id': TestCHKatelloAgent.activation_key['id'],
  File "robottelo/common/decorators.py", line 73, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 1830, in setup_org_for_a_rh_repo
    raise CLIFactoryError('Failed to enable repository set')
'Failed to enable repository set\n--------------------

**Comment by abalakh** [comment]
Fix is already pending in #2633 and #2649

**Comment by tkolhar** [comment]
this issue occurred again dated 08/05/2015
TestNames:
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_apply_errata
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_get_errata_info

Error Message

Failed to enable repository set

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel67.usersys.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Server" --basearch="x86_64" --releasever="7Server" --name="Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)" --organization-id="294"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x40bfcd0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x40bfcd0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x40bfcd0
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-08-05 17:51:57 Exception] ["releasever"] cannot be specified for Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs) as that information is not substituable in /content/beta/rhel/server/7/$basearch/sat-tools/6/os 
Could not enable repository:
  ["releasever"] cannot be specified for Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs) as that information is not substituable in /content/beta/rhel/server/7/$basearch/sat-tools/6/os 
[ERROR 2015-08-05 17:51:57 Exception] 

RestClient::UnprocessableEntity (422 Unprocessable Entity):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:80:in `put'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 360, in run
    self.setUp()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-cli/tests/foreman/cli/test_contenthost.py", line 597, in setUp
    u'activationkey-id': TestCHKatelloAgent.activation_key['id'],
  File "robottelo/common/decorators.py", line 73, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 1830, in setup_org_for_a_rh_repo
    raise CLIFactoryError('Failed to enable repository set')
'Failed to enable repository set\n-------------------
