### ISSUE TITLE
Automation failure : test_associate_view_rh

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2419]
TestNames:
tests.foreman.cli.test_contentviews.TestContentView.test_associate_view_rh

Error Message
Couldn't synchronize repo

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository synchronize --product="Red Hat Enterprise Linux Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation RPMs x86_64 6Workstation" --organization-id="231"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x25b9250
robottelo.common.ssh: INFO: Destroying Paramiko client 0x25b9250
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x25b9250
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-06-10 15:06:36 Exception] Error: repository not found
Could not synchronize the repository:
  Error: repository not found
[ERROR 2015-06-10 15:06:36 Exception] 

HammerCLIForeman::ResolverError (repository not found):
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:191:in `pick_result'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:156:in `find_resource'
    /usr/share/gems/gems/hammer_cli_katello-0.0.7.15/lib/hammer_cli_katello/id_resolver.rb:58:in `repository_id'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:149:in `get_resource_id'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:138:in `get_identifier'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:230:in `customized_options'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:235:in `request_params'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman_tasks-0.0.3.4/lib/hammer_cli_foreman_tasks/async_command.rb:14:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_contentviews.py", line 585, in test_associate_view_rh
    self.create_rhel_content()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_contentviews.py", line 126, in create_rhel_content
    self.fail("Couldn't synchronize repo")
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'Couldn\'t synchronize repo\n-------------------

**Comment by tkolhar** [comment]
this issue occurred again dated 7/8/2015
TestNames:
tests.foreman.cli.test_contentviews.TestContentView.test_associate_view_rh

Error Message
Couldn't synchronize repo

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository synchronize --product="Red Hat Enterprise Linux Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation RPMs x86_64 6Workstation" --organization-id="256"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x36d6f50
robottelo.common.ssh: INFO: Destroying Paramiko client 0x36d6f50
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x36d6f50
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-07-08 19:44:08 Exception] Error: repository not found
Could not synchronize the repository:
  Error: repository not found
[ERROR 2015-07-08 19:44:08 Exception] 

HammerCLIForeman::ResolverError (repository not found):
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:191:in `pick_result'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:156:in `find_resource'
    /usr/share/gems/gems/hammer_cli_katello-0.0.7.17/lib/hammer_cli_katello/id_resolver.rb:58:in `repository_id'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:149:in `get_resource_id'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:138:in `get_identifier'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:230:in `customized_options'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:235:in `request_params'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman_tasks-0.0.3.4/lib/hammer_cli_foreman_tasks/async_command.rb:14:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_contentviews.py", line 658, in test_associate_view_rh
    self.create_rhel_content()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_contentviews.py", line 126, in create_rhel_content
    self.fail("Couldn't synchronize repo")
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'Couldn\'t synchronize repo\n--------------------

**Comment by sthirugn** [comment]
Failed in Snap 12

**Comment by tkolhar** [comment]
tested locally using nosetests:
the test is failing due to below error
2015-07-29 13:17:15 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv repository synchronize --product="Red Hat Enterprise Linux Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation RPMs x86_64 6Workstation" --organization-id="323"
2015-07-29 13:17:18 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x3e05410
2015-07-29 13:17:21 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x3e05410
2015-07-29 13:17:21 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x3e05410
2015-07-29 13:17:21 - robottelo.common.ssh - DEBUG - <<< stderr
[ERROR 2015-07-29 03:47:21 Exception] Error: repository not found
Could not synchronize the repository:
  Error: repository not found
[ERROR 2015-07-29 03:47:21 Exception] 

HammerCLIForeman::ResolverError (repository not found):
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:191:in `pick_result'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:156:in `find_resource'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_katello-0.0.7.17/lib/hammer_cli_katello/id_resolver.rb:58:in `repository_id'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:149:in `send'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:149:in `get_resource_id'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:138:in `get_identifier'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:230:in `customized_options'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:235:in `request_params'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman_tasks-0.0.3.5/lib/hammer_cli_foreman_tasks/async_command.rb:14:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19



FAIL

FAIL: @test: associate Red Hat content in a view
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_contentviews.py", line 658, in test_associate_view_rh
    self.create_rhel_content()
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_contentviews.py", line 126, in create_rhel_content
    self.fail("Couldn't synchronize repo")
AssertionError: Couldn't synchronize repo

FAIL: @test: associate Red Hat content in a view

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_contentviews.py", line 700, in test_associate_view_rh_custom_spin
    self.create_rhel_content()
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_contentviews.py", line 126, in create_rhel_content
    self.fail("Couldn't synchronize repo")
AssertionError: Couldn't synchronize repo

XML: foreman-results.xml
Ran 2 tests in 304.601s

FAILED (failures=2)

**Comment by tkolhar** [comment]
this issue occurred again dated 07/27/2015
TestNames:
tests.foreman.cli.test_contentviews.TestContentView.test_associate_view_rh

Error Message
Couldn't synchronize repo

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv repository synchronize --product="Red Hat Enterprise Linux Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation RPMs x86_64 6Workstation" --organization-id="384"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x46d6c50
robottelo.common.ssh: INFO: Destroying Paramiko client 0x46d6c50
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x46d6c50
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-07-29 20:01:59 Exception] Error: repository not found
Could not synchronize the repository:
  Error: repository not found
[ERROR 2015-07-29 20:01:59 Exception] 

HammerCLIForeman::ResolverError (repository not found):
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:191:in `pick_result'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/id_resolver.rb:156:in `find_resource'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_katello-0.0.7.17/lib/hammer_cli_katello/id_resolver.rb:58:in `repository_id'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:149:in `send'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:149:in `get_resource_id'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:138:in `get_identifier'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:230:in `customized_options'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:235:in `request_params'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman_tasks-0.0.3.5/lib/hammer_cli_foreman_tasks/async_command.rb:14:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-cli/tests/foreman/cli/test_contentviews.py", line 658, in test_associate_view_rh
    self.create_rhel_content()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-cli/tests/foreman/cli/test_contentviews.py", line 126, in create_rhel_content
    self.fail("Couldn't synchronize repo")
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'Couldn\'t synchronize repo\n--------------------
