### ISSUE TITLE
Automate location list in api

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2424]
Please automate:

GET /api/locations
List all locations
Params
Param name  Description
search
optional    

filter results

Value: String
order
optional    

sort results

Value: String
page
optional    

paginate results

Value: String
per_page
optional    

number of entries per request

Value: String

**Comment by rplevka** [comment]
when it comes to GET /lcoations  i think we got this pretty much covered in locations t1 tests (and almost all test which call make_location()).
for the rest - these are generic options common to all endpoints and i don't think we should create the tests for each endpoint
