### ISSUE TITLE
CLI Automation failure : test_enable_manifest_repository_set 

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2444]
TestNames:
tests.foreman.cli.test_subscription.TestSubscription.test_enable_manifest_repository_set 

Error Message
77 != 0

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Workstation" --basearch="x86_64" --releasever="6Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation (RPMs)" --organization-id="311"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x34dd310
robottelo.common.ssh: INFO: Destroying Paramiko client 0x34dd310
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x34dd310
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-06-13 14:51:20 Exception] Forbidden - server refused to process the request
Could not enable repository:
  Forbidden - server refused to process the request
[ERROR 2015-06-13 14:51:20 Exception] 

RestClient::Forbidden (403 Forbidden):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:76:in `put'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_subscription.py", line 107, in test_enable_manifest_repository_set
    self.assertEqual(result.return_code, 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'77 != 0\n--------------------

**Comment by tkolhar** [comment]
when executed locally using nosetest:
$ nosetests -c robottelo.properties -m test_enable_manifest_repository_set /home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py
2015-06-15 16:38:24 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv subscription list --organization-id="427"
2015-06-15 16:38:27 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x2afa210
2015-06-15 16:38:29 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x2afa210
2015-06-15 16:38:29 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x2afa210
2015-06-15 16:38:29 - robottelo.common.ssh - DEBUG - <<< stdout
Name,Contract,Account,Support,Quantity,Consumed,End Date,ID,Product,Quantity,Attached
CloudForms Employee Subscription,10041814,477931,Self-Support,10,0,2022-01-01,ff8080814dedb08b014df6e7c3b73ab9,CloudForms Employee Subscription,10,0
Red Hat Employee Subscription,10169793,477931,SELF-SUPPORT,10,0,2022-01-01,ff8080814dedb08b014df6e7c1b939c5,Red Hat Employee Subscription,10,0

2015-06-15 16:38:29 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Workstation" --basearch="x86_64" --releasever="6Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation (RPMs)" --organization-id="427"
2015-06-15 16:38:32 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x3002690
2015-06-15 16:38:38 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x3002690
2015-06-15 16:38:38 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x3002690
2015-06-15 16:38:38 - robottelo.common.ssh - DEBUG - <<< stderr
[ERROR 2015-06-15 07:08:38 Exception] Forbidden - server refused to process the request
Could not enable repository:
  Forbidden - server refused to process the request
[ERROR 2015-06-15 07:08:38 Exception] 

RestClient::Forbidden (403 Forbidden):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:76:in `put'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'
FAIL
FAIL: @Test: enable repository set (positive)
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py", line 107, in test_enable_manifest_repository_set
    self.assertEqual(result.return_code, 0)
AssertionError: 77 != 0
XML: foreman-results.xml
Ran 1 test in 101.957s

FAILED (failures=1)

**Comment by oshtaier** [comment]
Passing successfully for a long time
