### ISSUE TITLE
CLI Automation failure : test_enable_manifest_repository_set

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2448]
TestNames:
tests.foreman.cli.test_subscription.TestSubscription.test_enable_manifest_repository_set

Error Message
77 != 0

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv subscription list --organization-id="311"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x37d9190
robottelo.common.ssh: INFO: Destroying Paramiko client 0x37d9190
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x37d9190
robottelo.common.ssh: DEBUG: <<< stdout
Name,Contract,Account,Support,Quantity,Consumed,End Date,ID,Product,Quantity,Attached
Employee SKU,10169793,477931,Self-Support,10,0,2022-01-01,ff8080814dfaced6014dfb60cd6438d7,Employee SKU,10,0
Red Hat Satellite Employee Subscription,10461238,477931,Self-Support,1,0,2022-01-01,ff8080814dfaced6014dfb60cf6839fb,Red Hat Satellite Employee Subscription,1,0

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Workstation" --basearch="x86_64" --releasever="6Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation (RPMs)" --organization-id="311"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x37d91d0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x37d91d0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x37d91d0
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-06-16 03:59:16 Exception] Forbidden - server refused to process the request
Could not enable repository:
  Forbidden - server refused to process the request
[ERROR 2015-06-16 03:59:16 Exception] 

RestClient::Forbidden (403 Forbidden):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:76:in `put'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_subscription.py", line 107, in test_enable_manifest_repository_set
    self.assertEqual(result.return_code, 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'77 != 0\n-------------------

**Comment by tkolhar** [comment]
when executed locally using nosetests:
$ nosetests -c robottelo.properties -m test_enable_manifest_repository_set /home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py
2015-06-16 16:54:34 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Workstation" --basearch="x86_64" --releasever="6Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation (RPMs)" --organization-id="425"
2015-06-16 16:54:47 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x2544a10
2015-06-16 16:54:54 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x2544a10
2015-06-16 16:54:54 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x2544a10
2015-06-16 16:54:54 - robottelo.common.ssh - DEBUG - <<< stdout
Message,Id
Repository enabled,953eb0e9-6b2e-4fbd-a949-60f7d2258e79

2015-06-16 16:54:54 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository synchronize --product="Red Hat Enterprise Linux Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation RPMs x86_64 6Workstation" --organization-id="425"
2015-06-16 16:54:57 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1ae4650
2015-06-16 16:55:12 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1ae4650
2015-06-16 16:55:12 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1ae4650
2015-06-16 16:55:12 - robottelo.common.ssh - DEBUG - <<< stdout
No new packages.

2015-06-16 16:55:12 - robottelo.common.ssh - DEBUG - <<< stderr
Task cc40ac7b-f16b-4622-b810-435bd57daa60 running: 0.005/1, 0%, elapsed: 00:00:00
Task cc40ac7b-f16b-4622-b810-435bd57daa60 running: 0.005/1, 0%, elapsed: 00:00:02
Task cc40ac7b-f16b-4622-b810-435bd57daa60 running: 0.005/1, 0%, elapsed: 00:00:04
Task cc40ac7b-f16b-4622-b810-435bd57daa60 running: 0.005/1, 0%, elapsed: 00:00:06
Task cc40ac7b-f16b-4622-b810-435bd57daa60 running: 0.675/1, 67%, elapsed: 00:00:09
Task cc40ac7b-f16b-4622-b810-435bd57daa60 success: 1.0/1, 100%, elapsed: 00:00:11
Task cc40ac7b-f16b-4622-b810-435bd57daa60 success: 1.0/1, 100%, elapsed: 00:00:11


ok
XML: foreman-results.xml
Ran 1 test in 153.137s

OK

It seems the test works fine when executed locally

**Comment by tkolhar** [comment]
this issue occurred again dated 06/17/2015

tests.foreman.cli.test_subscription.TestSubscription.test_enable_manifest_repository_set
Error Message
77 != 0

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Workstation" --basearch="x86_64" --releasever="6Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation (RPMs)" --organization-id="313"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x3992990
robottelo.common.ssh: INFO: Destroying Paramiko client 0x3992990
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x3992990
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-06-17 06:09:08 Exception] Forbidden - server refused to process the request
Could not enable repository:
  Forbidden - server refused to process the request
[ERROR 2015-06-17 06:09:08 Exception] 

RestClient::Forbidden (403 Forbidden):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:76:in `put'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_subscription.py", line 107, in test_enable_manifest_repository_set
    self.assertEqual(result.return_code, 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'77 != 0\n--------------------

**Comment by sthirugn** [comment]
Passed in Snap 12
