### ISSUE TITLE
CLI Automation failure : test_update_positive_1__u_description

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2450]
TestNames:
tests.foreman.cli.test_computeresource.TestComputeResource.test_update_positive_1__u_description___u_L6XdAAcSu4_

Error Message

Failed to create ComputeResource with data:
{
  "description": null, 
  "location-ids": null, 
  "locations": null, 
  "name": "KKgycD5E", 
  "organization-ids": null, 
  "organizations": null, 
  "password": null, 
  "provider": "Libvirt", 
  "region": null, 
  "server": null, 
  "set-console-password": null, 
  "tenant": null, 
  "url": "qemu+tcp://localhost:16509/system", 
  "user": null, 
  "uuid": null

robottelo: DEBUG: Running test TestComputeResource/test_update_positive_1__u_description___u_L6XdAAcSu4__
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv compute-resource create --name="KKgycD5E" --url="qemu+tcp://localhost:16509/system" --provider="Libvirt"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x3448490
robottelo.common.ssh: INFO: Destroying Paramiko client 0x3448490
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x3448490
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-06-15 12:55:20 Exception] Error: Request Timeout
Could not create the compute resource:
  Error: Request Timeout
[ERROR 2015-06-15 12:55:20 Exception] 

RestClient::RequestTimeout (Request Timeout):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:184:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/9514c559/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-cli/tests/foreman/cli/test_computeresource.py", line 303, in test_update_positive
    comp_res = make_compute_resource()
  File "robottelo/common/decorators.py", line 76, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 1129, in make_compute_resource
    return create_object(ComputeResource, args, options)
  File "robottelo/cli/factory.py", line 94, in create_object
    json.dumps(options, indent=2, sort_keys=True)
'Failed to create ComputeResource with data:\n{\n  "description": null, \n  "location-ids": null, \n  "locations": null, \n  "name": "KKgycD5E", \n  "organization-ids": null, \n  "organizations": null, \n  "password": null, \n  "provider": "Libvirt", \n  "region": null, \n  "server": null, \n  "set-console-password": null, \n  "tenant": null, \n  "url": "qemu+tcp://localhost:16509/system", \n  "user": null, \n  "uuid": null\n}\n-------------------- >> begin captured logging << --------------------

**Comment by tkolhar** [comment]
when executed locally using nosetests:
$ nosetests -c robottelo.properties -m test_update_positive_1 /home/tkolhar/git/robottelo/tests/foreman/cli/test_computeresource.py
2015-06-16 17:02:57 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  compute-resource info --id="60"
2015-06-16 17:03:00 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1b90cd0
2015-06-16 17:03:03 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1b90cd0
2015-06-16 17:03:03 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1b90cd0
2015-06-16 17:03:03 - robottelo.common.ssh - DEBUG - <<< stdout
Id:          60
Name:        񂡍超󴼅𳤐񩹦𸥒򀛞񖮰񷉰轘󥒛񳿭񗱥򡲅򾭻񷃉򿽩󀧷񞛬򐦝򑼇򑥬򦈉񼾭񐭨򖿻󦕡񃌩򙉿񽵢𑙦򙻲񵨫򻎄򀤚򫩠񕚊󮱟𘐄􎑘񷫊򇑷𠣾瘳򏐹󇽽󵘙򵍩轑􍣻󵰔򞅰󏷭𰩁󇟦򌼑󹱯Ⱐ􏙓񢶲񻹭񺗫𯱮񫋨򗱅򨿏񲤰𦨹󰌪𘦙󢻮򸂥򊷳𭀱󓞓󲗞𸚩𨕵󮨤󺣟􄗱񉡼񈀀󥹵󓆿𡳇󯉙󂘈屒񟛸񶱰򡈀񙺻񧯔򋰓󸲑񽕡Ӡ󠤤򗻨򘜙񉁮񲱛󌪳񊏅󚆢򄋬񔅟񧂘񄘐򾎸幠󔌤𱆢􄚉􊦴𸂓􈘐򸢮󅼱񐔀𐮻󉣏򓣛ﾈ􂧧񋧪𲀗ợ􌨪񮿅񸌱󿵠𳕵򎓧򙲷󞚹珄梿򘘺򖸓󿹤򀌠𷉩򽽫񋪤򦂊󏑙񘀷󶰩源𨆥㑓󯘀𸃂󀳊󘾅򉃰󬌬󶴼𶲻򨆹󁕉򼢮񝞑𑏡򦀥񦻐󀘗񅾩󣄱𙘍򑮘𨯜򝤑񚴩񫓣򄍶󼯡󊮲𯐳𬑩򉡌򈍺𕞫󪛟񍞐򪛈୙򓢣񧩜􍮶񀀅𵉉񖊐򕖺񤩆󀞶컻󋷽󖰋𵺞𐃺򄁐򀨸򍈴򐅿񷴴𫘗񼚆򤡄򲫖񯊡𿡝򔀺񢊇򻙾񉰆򁗸󆜟󐮽𧗛𳣽򘀅󶅰񛐟􊻳󶛌󉍊𔉑󷨹𠈬񆦱􍟚􍚖򃙬𩄐󱵶􌄫ꗜ񔔋𢕴򏘉򪻰󱁐󬃂󩠧񼼸𩦛󁓟𙺌􍱑󠧲𵓭
Provider:    Libvirt
Url:         qemu+tcp://localhost:16509/system
Description: 
User:        
Created at:  2015/06/16 11:32:40
Updated at:  2015/06/16 11:32:56


ok

XML: foreman-results.xml
Ran 1 test in 27.316s

OK

the test works fine when executed locally

**Comment by sthirugn** [comment]
Passed in Snap 12
