### ISSUE TITLE
Automate : manifest refresh in ui

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2455]
Please automate:
Import manifest
update manifests
refresh manifest
in UI

**Comment by sghai** [comment]
I think valid test would be 
- improt manifest
- update manifest from portal by adding/removing subscriptions
- refresh manifest

Assert: newly added/removed subscriptions should be updated on UI.

However, not sure how can we deal with manifest update ?

**Comment by sghai** [comment]
@rplevka : hey, do you have any idea how can we update the manifest via api's to handle the scenario mentioned in this issue.

**Comment by rplevka** [comment]
@sghai `katello/api/v2/subscriptions/refresh_manifest ` ?
or did I get you wrong?

**Comment by abalakh** [comment]
@rplevka not refresh, but update. See step 2) from @sghai 's previous comment. And i guess Saching meant not satellite but portal's api.

**Comment by rplevka** [comment]
@abalakh yeah, i read it, but i don't know what he meant by that. Isn't that just another manifest upload?

**Comment by sghai** [comment]
@rplevka @abalakh : So test is like:

- User imported a manifest today w/ some set of subscriptions. Later, user requested more subscriptions and updated them  via portal, e.g. added atomic host subscriptions
- on refresh, manifest should be updated and user should be able to see the newly added subscriptions.

However, I'm not sure how can we update the manifest as that part looks tricky.

@SatelliteQE/quality-engineers : Anyone any idea about this scenario as how can we achieve this?

May be we should ping candlepin folks ?

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
