### ISSUE TITLE
Add verification for certificates per each test that has interactions with manifests

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2465]
We have bunch of tests that are working with manifests (importing, cloning, applying). It doesn't make sense to run such tests if we have incorrect security certificates installed (or not installed at all) on a server as these tests will fail due obvious reason. We need to add mechanism that will skip (not fail) each and every test that work with functionality mentioned above.

**Comment by elyezer** [comment]
:+1:

**Comment by oshtaier** [comment]
Not actual after `@skip_if_not_set('fake_manifest')` functionality is implemented
