### ISSUE TITLE
Automation failure : test_cv_composite_create

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2468]
TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_composite_create

Error Message
403 Client Error: Forbidden

 Back to Project
 Status
 Changes
 Console Output
 View as plain text
 View Build Information
 History
 Parameters
 Environment Variables
 Git Build Data
 Test Result
 Previous Build
Regression

tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_composite_create (from nosetests)
Failing for the past 1 build (Since Unstable#49 )
Took 47 sec.
Error Message

403 Client Error: Forbidden
-------------------- >> begin captured logging << --------------------
nailgun.client: DEBUG: Making HTTP POST request to https://qe-sat6-rhel66.usersys.redhat.com/katello/api/v2/organizations with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"name": "\u8953\ud864\uddff\u8fdf"}.
nailgun.client: DEBUG: Received HTTP 201 response: {"ancestry":null,"apply_info_task_id":null,"created_at":"2015-06-17T12:11:07Z","default_info":{"system":[],"distributor":[]},"description":null,"id":335,"ignore_types":[],"katello_default":true,"label":"26737e78-7553-4085-9965-51b1a5baeba9","name":"襓10𩇿迟","title":"襓10𩇿𩇿迟","updated_at":"2015-06-17T12:11:07Z","service_levels":[],"service_level":null}
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.password" by id: "login_password"
robottelo.ui.locators: DEBUG: Accessing locator "submit" by name: "commit"
robottelo.ui.locators: DEBUG: Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"
robottelo.ui.base: DEBUG: NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
nailgun.client: DEBUG: Making HTTP POST request to https://qe-sat6-rhel66.usersys.redhat.com/katello/api/v2/organizations/335/subscriptions/upload with options {'files': {'content': <open file '/tmp/tmpFPDKEm', mode 'rb' at 0x32d5150>}, 'verify': False, 'auth': ('admin', 'changeme')} and no data.
nailgun.client: DEBUG: Received HTTP 202 response: {"id":"18ae81a2-9f1e-4138-9395-adf4cb0167ed","label":"Actions::Katello::Provider::ManifestImport","pending":true,"username":"admin","started_at":"2015-06-17T12:11:10Z","ended_at":null,"state":"running","result":"pending","progress":0.0,"input":{"provider":{"id":620,"name":"Red Hat"},"organization":{"id":335,"name":"襓10𩇿迟","label":"26737e78-7553-4085-9965-51b1a5baeba9"},"path":"/usr/share/foreman/tmp/import_305405d1c82be58b75d0.zip","force":null,"remote_user":"admin-d6e4918f","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization '襓10𩇿𩇿迟'","link":"/organizations/335/edit"}]],"output":"","errors":[]},"cli_example":null}

nailgun.client: DEBUG: Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/foreman_tasks/api/tasks/18ae81a2-9f1e-4138-9395-adf4cb0167ed with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":"18ae81a2-9f1e-4138-9395-adf4cb0167ed","label":"Actions::Katello::Provider::ManifestImport","pending":true,"username":"admin","started_at":"2015-06-17T12:11:10Z","ended_at":null,"state":"running","result":"pending","progress":0.0,"input":{"provider":{"id":620,"name":"Red Hat"},"organization":{"id":335,"name":"襓10𩇿迟","label":"26737e78-7553-4085-9965-51b1a5baeba9"},"path":"/usr/share/foreman/tmp/import_305405d1c82be58b75d0.zip","force":null,"remote_user":"admin-d6e4918f","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization '襓10𩇿𩇿迟'","link":"/organizations/335/edit"}]],"output":"","errors":[]},"cli_example":null}
nailgun.client: DEBUG: Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/foreman_tasks/api/tasks/18ae81a2-9f1e-4138-9395-adf4cb0167ed with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":"18ae81a2-9f1e-4138-9395-adf4cb0167ed","label":"Actions::Katello::Provider::ManifestImport","pending":true,"username":"admin","started_at":"2015-06-17T12:11:10Z","ended_at":null,"state":"running","result":"pending","progress":0.0,"input":{"provider":{"id":620,"name":"Red Hat"},"organization":{"id":335,"name":"襓10𩇿迟","label":"26737e78-7553-4085-9965-51b1a5baeba9"},"path":"/usr/share/foreman/tmp/import_305405d1c82be58b75d0.zip","force":null,"remote_user":"admin-d6e4918f","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization '襓10𩇿𩇿迟'","link":"/organizations/335/edit"}]],"output":"","errors":[]},"cli_example":null}
nailgun.client: DEBUG: Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/foreman_tasks/api/tasks/18ae81a2-9f1e-4138-9395-adf4cb0167ed with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":"18ae81a2-9f1e-4138-9395-adf4cb0167ed","label":"Actions::Katello::Provider::ManifestImport","pending":true,"username":"admin","started_at":"2015-06-17T12:11:10Z","ended_at":null,"state":"running","result":"pending","progress":0.0,"input":{"provider":{"id":620,"name":"Red Hat"},"organization":{"id":335,"name":"襓10𩇿迟","label":"26737e78-7553-4085-9965-51b1a5baeba9"},"path":"/usr/share/foreman/tmp/import_305405d1c82be58b75d0.zip","force":null,"remote_user":"admin-d6e4918f","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization '襓10𩇿𩇿迟'","link":"/organizations/335/edit"}]],"output":"","errors":[]},"cli_example":null}
nailgun.client: DEBUG: Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/foreman_tasks/api/tasks/18ae81a2-9f1e-4138-9395-adf4cb0167ed with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":"18ae81a2-9f1e-4138-9395-adf4cb0167ed","label":"Actions::Katello::Provider::ManifestImport","pending":true,"username":"admin","started_at":"2015-06-17T12:11:10Z","ended_at":null,"state":"running","result":"pending","progress":0.0,"input":{"provider":{"id":620,"name":"Red Hat"},"organization":{"id":335,"name":"襓10𩇿迟","label":"26737e78-7553-4085-9965-51b1a5baeba9"},"path":"/usr/share/foreman/tmp/import_305405d1c82be58b75d0.zip","force":null,"remote_user":"admin-d6e4918f","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization '襓10𩇿𩇿迟'","link":"/organizations/335/edit"}]],"output":"","errors":[]},"cli_example":null}
nailgun.client: DEBUG: Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/foreman_tasks/api/tasks/18ae81a2-9f1e-4138-9395-adf4cb0167ed with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":"18ae81a2-9f1e-4138-9395-adf4cb0167ed","label":"Actions::Katello::Provider::ManifestImport","pending":true,"username":"admin","started_at":"2015-06-17T12:11:10Z","ended_at":null,"state":"running","result":"pending","progress":0.0,"input":{"provider":{"id":620,"name":"Red Hat"},"organization":{"id":335,"name":"襓10𩇿迟","label":"26737e78-7553-4085-9965-51b1a5baeba9"},"path":"/usr/share/foreman/tmp/import_305405d1c82be58b75d0.zip","force":null,"remote_user":"admin-d6e4918f","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization '襓10𩇿𩇿迟'","link":"/organizations/335/edit"}]],"output":"","errors":[]},"cli_example":null}
nailgun.client: DEBUG: Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/foreman_tasks/api/tasks/18ae81a2-9f1e-4138-9395-adf4cb0167ed with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":"18ae81a2-9f1e-4138-9395-adf4cb0167ed","label":"Actions::Katello::Provider::ManifestImport","pending":true,"username":"admin","started_at":"2015-06-17T12:11:10Z","ended_at":null,"state":"running","result":"pending","progress":0.0,"input":{"provider":{"id":620,"name":"Red Hat"},"organization":{"id":335,"name":"襓10𩇿迟","label":"26737e78-7553-4085-9965-51b1a5baeba9"},"path":"/usr/share/foreman/tmp/import_305405d1c82be58b75d0.zip","force":null,"remote_user":"admin-d6e4918f","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization '襓10𩇿𩇿迟'","link":"/organizations/335/edit"}]],"output":"","errors":[]},"cli_example":null}
nailgun.client: DEBUG: Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/foreman_tasks/api/tasks/18ae81a2-9f1e-4138-9395-adf4cb0167ed with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":"18ae81a2-9f1e-4138-9395-adf4cb0167ed","label":"Actions::Katello::Provider::ManifestImport","pending":true,"username":"admin","started_at":"2015-06-17T12:11:10Z","ended_at":null,"state":"running","result":"pending","progress":0.0,"input":{"provider":{"id":620,"name":"Red Hat"},"organization":{"id":335,"name":"襓10𩇿迟","label":"26737e78-7553-4085-9965-51b1a5baeba9"},"path":"/usr/share/foreman/tmp/import_305405d1c82be58b75d0.zip","force":null,"remote_user":"admin-d6e4918f","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization '襓10𩇿𩇿迟'","link":"/organizations/335/edit"}]],"output":"","errors":[]},"cli_example":null}
nailgun.client: DEBUG: Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/foreman_tasks/api/tasks/18ae81a2-9f1e-4138-9395-adf4cb0167ed with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":"18ae81a2-9f1e-4138-9395-adf4cb0167ed","label":"Actions::Katello::Provider::ManifestImport","pending":false,"username":"admin","started_at":"2015-06-17T12:11:10Z","ended_at":"2015-06-17T12:11:45Z","state":"stopped","result":"success","progress":1.0,"input":{"provider":{"id":620,"name":"Red Hat"},"organization":{"id":335,"name":"襓10𩇿迟","label":"26737e78-7553-4085-9965-51b1a5baeba9"},"path":"/usr/share/foreman/tmp/import_305405d1c82be58b75d0.zip","force":null,"remote_user":"admin-d6e4918f","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization '襓10𩇿𩇿迟'","link":"/organizations/335/edit"}]],"output":"","errors":[]},"cli_example":null}
nailgun.client: DEBUG: Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/katello/api/v2/products with options {'verify': False, 'data': '{"organization_id": "335", "name": "Red Hat Enterprise Linux Server"}', 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"total":1,"subtotal":1,"page":1,"per_page":20,"search":null,"sort":{"by":null,"order":null},"results":[{"sync_state":"not_synced","last_sync":null,"last_sync_words":null,"organization":{"name":"襓10𩇿迟","label":"26737e78-7553-4085-9965-51b1a5baeba9","id":335},"id":3300,"cp_id":"69","name":"Red Hat Enterprise Linux Server","label":"Red_Hat_Enterprise_Linux_Server","description":null,"provider_id":620,"sync_plan_id":null,"sync_status":{"created_at":null,"finish_time":null,"id":null,"organization_id":null,"parameters":{},"progress":{"items_left":0,"total_count":0,"size_left":0,"total_size":0},"result":null,"start_time":null,"state":"not_synced","task_owner_id":null,"task_owner_type":null,"task_type":null,"updated_at":null,"user_id":0,"uuid":null,"pending?":false},"sync_summary":{},"gpg_key_id":null,"redhat":true,"repository_count":0,"":null}]}

nailgun.client: DEBUG: Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/katello/api/v2/products/3300/repository_sets with options {'verify': False, 'data': '{"name": "Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)"}', 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"total":1,"subtotal":1,"page":null,"per_page":null,"search":null,"sort":{"by":null,"order":null},"results":[{"repositories":[],"id":"4380","name":"Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)","label":"rhel-7-server-satellite-tools-6-beta-rpms","type":"yum","vendor":"Red Hat","gpgUrl":"file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta,file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release","contentUrl":"/content/beta/rhel/server/7/$basearch/sat-tools/6/os"}]}

nailgun.client: DEBUG: Making HTTP PUT request to https://qe-sat6-rhel66.usersys.redhat.com/katello/api/v2/products/3300/repository_sets/4380/enable with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"basearch": "x86_64", "releasever": "7Server"}.
nailgun.client: WARNING: Received HTTP 403 response: {"displayMessage":"CDN loading error: access forbidden to https://cdn.redhat.com:443/content/beta/rhel/server/7/x86_64/sat-tools/6/os/repodata/repomd.xml","errors":["CDN loading error: access forbidden to https://cdn.redhat.com:443/content/beta/rhel/server/7/x86_64/sat-tools/6/os/repodata/repomd.xml"]}
--------------------- >> end captured logging << ---------------------

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_contentviews.py", line 494, in test_cv_composite_create
    self.setup_to_create_cv(rh_repo=rh_repo, org_id=org_id)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_contentviews.py", line 85, in setup_to_create_cv
    rh_repo['releasever'])
  File "robottelo/api/utils.py", line 122, in enable_rhrepo_and_fetchid
    reposet_id=reposet_id,
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 2652, in enable_rhrepo
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 102, in _handle_response
    response.raise_for_status()
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
'403 Client Error: Forbidden\n--------------------

**Comment by tkolhar** [comment]
when executed locally using nosetests:
2015-06-18 16:36:29 - nailgun.client - DEBUG - Received HTTP 200 response: {"id":"7922667c-b4a8-484d-bf07-69024bf2ea02","label":"Actions::Katello::Provider::ManifestImport","pending":false,"username":"admin","started_at":"2015-06-18T11:06:06Z","ended_at":"2015-06-18T11:06:27Z","state":"stopped","result":"success","progress":1.0,"input":{"provider":{"id":1230,"name":"Red Hat"},"organization":{"id":701,"name":"𢍀%􄲿󂖔𚿭𗫧񥂰𐼼󴲋绁􊍦󌠿𷡄󵲈򁁊󠟹񧶬뎬񪱨򹕁򄸆򏗪񑀵𥄫","label":"b538bbd6-6c0f-4154-af9e-5a449d37fc38"},"path":"/usr/share/foreman/tmp/import_0b8aacd2171f95436a7d.zip","force":null,"remote_user":"admin-d6e4918f","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization '𢍀%􄲿󂖔𚿭𗫧񥂰𐼼󴲋绁􊍦󌠿𷡄󵲈򁁊󠟹񧶬뎬񪱨򹕁򄸆򏗪񑀵𥄫'","link":"/organizations/701/edit"}]],"output":"","errors":[]},"cli_example":null}
2015-06-18 16:36:29 - nailgun.client - DEBUG - Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/katello/api/v2/products with options {'verify': False, 'data': '{"organization_id": "701", "name": "Red Hat Enterprise Linux Server"}', 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
2015-06-18 16:36:30 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2015-06-18 16:36:32 - nailgun.client - DEBUG - Received HTTP 200 response: {"total":1,"subtotal":1,"page":1,"per_page":77105,"search":null,"sort":{"by":null,"order":null},"results":[{"sync_state":"not_synced","last_sync":null,"last_sync_words":null,"organization":{"name":"𢍀%􄲿󂖔𚿭𗫧񥂰𐼼󴲋绁􊍦󌠿𷡄󵲈򁁊󠟹񧶬뎬񪱨򹕁򄸆򏗪񑀵𥄫","label":"b538bbd6-6c0f-4154-af9e-5a449d37fc38","id":701},"id":4441,"cp_id":"69","name":"Red Hat Enterprise Linux Server","label":"Red_Hat_Enterprise_Linux_Server","description":null,"provider_id":1230,"sync_plan_id":null,"sync_status":{"created_at":null,"finish_time":null,"id":null,"organization_id":null,"parameters":{},"progress":{"items_left":0,"total_count":0,"size_left":0,"total_size":0},"result":null,"start_time":null,"state":"not_synced","task_owner_id":null,"task_owner_type":null,"task_type":null,"updated_at":null,"user_id":0,"uuid":null,"pending?":false},"sync_summary":{},"gpg_key_id":null,"redhat":true,"repository_count":0,"":null}]}

2015-06-18 16:36:32 - nailgun.client - DEBUG - Making HTTP GET request to https://qe-sat6-rhel66.usersys.redhat.com/katello/api/v2/products/4441/repository_sets with options {'verify': False, 'data': '{"name": "Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)"}', 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
2015-06-18 16:36:32 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2015-06-18 16:36:35 - nailgun.client - DEBUG - Received HTTP 200 response: {"total":0,"subtotal":0,"page":null,"per_page":null,"search":null,"sort":{"by":null,"order":null},"results":[]}

ERROR
ERROR

ERROR: @test: create a composite content views

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py", line 494, in test_cv_composite_create
    self.setup_to_create_cv(rh_repo=rh_repo, org_id=org_id)
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py", line 85, in setup_to_create_cv
    rh_repo['releasever'])
  File "/home/tkolhar/git/robottelo/robottelo/api/utils.py", line 118, in enable_rhrepo_and_fetchid
    reposet_id = entities.Product(id=prd_id).fetch_reposet_id(name=reposet)
  File "/usr/lib/python2.7/site-packages/nailgun/entities.py", line 2460, in fetch_reposet_id
    "The length of the results is:", len(results))
APIResponseError: ('The length of the results is:', 0)

ERROR: @test: create a composite content views

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 260, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 248, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
XML: foreman-results.xml
Ran 1 test in 69.267s
FAILED (errors=2)

**Comment by sthirugn** [comment]
Passed in Snap 12
