### ISSUE TITLE
Automate hostgroup clone feature in ui/cli/api

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2476]
https://bugzilla.redhat.com/show_bug.cgi?id=1233391

**Comment by Ichimonji10** [comment]
:+1:

**Comment by pondrejk** [comment]
Currently supported in UI and API only, filed [BZ#1376376](https://bugzilla.redhat.com/show_bug.cgi?id=1376376) to include the CLI

**Comment by sghai** [comment]
@pondrejk @rochacbruno : Thanks for implementing this from UI/API. Lets keep it open for CLI.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
