### ISSUE TITLE
UI Revamp

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#2490]
This issue will contain all suggestions for the improved UI tools. Feel free to comment anything that you think that will bring more value and/or speed to our UI tests.

This can also list good practices, after grouping all good practices, a document can be created to list them.

**Comment by elyezer** [comment]
Trying to understand more about selecting/locating elements on a page I have discovered the following:

```
In [9]: %timeit driver.find_element_by_id('lst-ib')
100 loops, best of 3: 6.1 ms per loop

In [10]: %timeit WebDriverWait(driver, 12, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, 'lst-ib')))
100 loops, best of 3: 16 ms per loop
```

Then I checked Robottelo codebase and found that wait_for_element is called more than find_element:

```
$ git grep "self.wait_until_element(" | wc -l
    396

$ git grep "self.find_element(" | wc -l
    222
```

With that said, I think we can adopt as a good practice to use find_element and only use wait_until_element if it is really necessary.

**Comment by oshtaier** [comment]
Definitely we should remove wait_for_ajax from all places except base class and generic methods. Make sure that functionality works properly after that.

**Comment by elyezer** [comment]
We definitely have many wait_for_ajax calls:

```
$ git grep wait_for_ajax | wc -l
     281
```

This is other function that we need to make sure to use when really necessary.

**Comment by sghai** [comment]
Yeah, we are extensively using  `wait_for_ajax` but our tests are relying on that. Without it, a log of tests may fail. We need solution here.. How can we replace it ?

**Comment by oshtaier** [comment]
We need to make them called implicitly in more generic methods

**Comment by oshtaier** [comment]
Adding connection to "Get rid from all static delays in the code or move them into one place" #2198 as it is from the same scope

**Comment by elyezer** [comment]
Also, all negative tests have a timeout of 12 when making sure that the element is not present. This increases the test time a lot.

**Comment by oshtaier** [comment]
wait_for_element should not downgrade peromance at all as it exits after it find the element immediately. But it makes test runs more stable (MUCH stable)... maybe we can decrease 'poll_frequency' parameter value

**Comment by elyezer** [comment]
@oshtaier and @sghai, do you think that we can close this?

**Comment by sghai** [comment]
I think we can close this issue now. If needed, we can re-open later and file a new issue.
