### ISSUE TITLE
CLI - test_import - optimize tests

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#2513]
Every test is making use of `prepare_import_data` function which download TAR from a predefined source, extract it and returns a Dictionary object with the paths to individual CSV files.

Since we recently implemented a method for modifying the dataset (`update_csv_values`) which does not edit the original dataset but instead make an updated copy of the updated files,
I believe we could optimize the test run times by calling `prepare_import_data` only once on a startup and do the cleanup after all `import` tests are finished.

**Comment by elyezer** [comment]
#2527 is merged, should we close this?

**Comment by rplevka** [comment]
@elyezer:
yes, i'm closing it, sorry, been OOO.
