### ISSUE TITLE
Improve coverage for product update procedure (customer found issue)

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2515]
Basically, it doesn't matter whether that issue is reproducible in application at that moment as scenario makes sense from user stand point at any given moment.

Steps:

1. Rename a product from NAME1 to NAME2
2. Rename the same product back from NAME2 to NAME1

Possible behavior:
An error occurred saving the Product: Product with name 'xxx' already exists in this organization.

It is possible to apply such scenario for **all** entities in the application (at least for new coverage in future)

**Comment by jyejare** [comment]
Yeah, It good to automate this stuff. Thanks for adding this in Automation.

**Comment by elyezer** [comment]
:+1:

**Comment by jyejare** [comment]
Closing this issue as PR #2535 has been merged.
