### ISSUE TITLE
Provide meaningful test data to debug the failures.  

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2521]
It is a nightmare trying to actually debug failures in tests.  I propose to use standard english names for most of the tests and use special characters for probably a subset of tests.

![screenshot](https://cloud.githubusercontent.com/assets/3309189/8460115/d5074038-1fef-11e5-8ea1-0fc81518ac49.png)

**Comment by oshtaier** [comment]
Huh. That was a thing that I rose on a meeting 26 Jun. It is a common thing for any environment

**Comment by Ichimonji10** [comment]
We could do something like default to generating [Cyrillic](http://www.fileformat.info/info/unicode/block/cyrillic/utf8test.htm) characters no more than 30 characters long. Doing so would still send multi-byte characters to Satellite, yet make it *much* easier to use the web interface and read through log files.

**Comment by sthirugn** [comment]
This is biting us again with crazy org names.  @elyezer mentioned in irc that we may fix this by using standard/clean names for default entity names.

Field validation will still be done by other entity tests which will not be affected by this proposed change.

**Comment by oshtaier** [comment]
Addressed in https://github.com/SatelliteQE/nailgun/pull/291
