### ISSUE TITLE
Automation failure : tests.foreman.cli.test_contenthost.TestCHKatelloAgent

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2533]
TestNames:
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_apply_errata
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_get_errata_info

Error Message
Failed to enable repository set

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Server" --basearch="x86_64" --releasever="7Server" --name="Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)" --organization-id="245"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x398c3d0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x398c3d0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x398c3d0
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-07-02 16:43:30 Exception] There was an issue with the backend service pulp: Pulp message bus connection issue.
Could not enable repository:
  There was an issue with the backend service pulp: Pulp message bus connection issue.
[ERROR 2015-07-02 16:43:30 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:76:in `put'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 360, in run
    self.setUp()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_contenthost.py", line 597, in setUp
    u'activationkey-id': TestCHKatelloAgent.activation_key['id'],
  File "robottelo/common/decorators.py", line 76, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 1830, in setup_org_for_a_rh_repo
    raise CLIFactoryError('Failed to enable repository set')
'Failed to enable repository set\n--------------------

filed a bz:
- https://bugzilla.redhat.com/show_bug.cgi?id=1240255

**Comment by sthirugn** [comment]
Addressed in Snap 12
