### ISSUE TITLE
Automation failure : tests.foreman.cli.test_contenthost.TestContentHost

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2534]
TestNames:
tests.foreman.cli.test_contenthost.TestContentHost.test_positive_create_2_1
tests.foreman.cli.test_contenthost.TestContentHost.test_positive_create_1
tests.foreman.cli.test_contenthost.TestContentHost.test_positive_create_4
tests.foreman.cli.test_contenthost.TestContentHost.test_positive_create_3
tests.foreman.cli.test_contenthost.TestContentHost.test_positive_update_1
tests.foreman.cli.test_contenthost.TestContentHost.test_positive_delete_1

Error Message

Failed to create ContentHost with data:
{
  "content-view": null, 
  "content-view-id": "271", 
  "description": null, 
  "guest-ids": null, 
  "host-collection-ids": null, 
  "last-checkin": null, 
  "lifecycle-environment": null, 
  "lifecycle-environment-id": "246", 
  "location": null, 
  "name": "\u00d0\u00c0\u00f0\u00d3\u00e0\u00d1\u00d4\u00fd\u00da\u00dd\u00d9\u00e7\u00e7\u00c3\u00ef", 
  "organization": null, 
  "organization-id": "237", 
  "organization-label": null, 
  "release-ver": null, 
  "service-level": null
}

robottelo: DEBUG: Running test TestContentHost/test_positive_delete_1_1__u_name___u__xd0_xc0_xf0_xd3_xe0_xd1_xd4_xfd_xda_xdd_xd9_xe7_xe7_xc3_xef__
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv content-host create --content-view-id="271" --organization-id="237" --name="ÐÀðÓàÑÔýÚÝÙççÃï" --lifecycle-environment-id="246"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x3924b50
robottelo.common.ssh: INFO: Destroying Paramiko client 0x3924b50
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x3924b50
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-07-02 16:44:25 Exception] There was an issue with the backend service pulp: Pulp message bus connection issue.
Could not create content host:
  There was an issue with the backend service pulp: Pulp message bus connection issue.
[ERROR 2015-07-02 16:44:25 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:67:in `post'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/107b379a/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_contenthost.py", line 493, in test_positive_delete_1
    u'lifecycle-environment-id': self.LIBRARY['id']})
  File "robottelo/common/decorators.py", line 76, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 852, in make_content_host
    return create_object(ContentHost, args, options)
  File "robottelo/cli/factory.py", line 94, in create_object
    json.dumps(options, indent=2, sort_keys=True)
'Failed to create ContentHost with data:\n{\n  "content-view": null, \n  "content-view-id": "271", \n  "description": null, \n  "guest-ids": null, \n  "host-collection-ids": null, \n  "last-checkin": null, \n  "lifecycle-environment": null, \n  "lifecycle-environment-id": "246", \n  "location": null, \n  "name": "\\u00d0\\u00c0\\u00f0\\u00d3\\u00e0\\u00d1\\u00d4\\u00fd\\u00da\\u00dd\\u00d9\\u00e7\\u00e7\\u00c3\\u00ef", \n  "organization": null, \n  "organization-id": "237", \n  "organization-label": null, \n  "release-ver": null, \n  "service-level": null\n}

filed a bz:
- https://bugzilla.redhat.com/show_bug.cgi?id=1240257

**Comment by sthirugn** [comment]
Addressed in Snap 12
