### ISSUE TITLE
Automation failure : tests.foreman.cli.test_location.TestLocation

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2546]
TestNames:
tests.foreman.cli.test_location.TestLocation.test_create_location_with_user_by_id
tests.foreman.cli.test_location.TestLocation.test_create_location_with_user_by_name
tests.foreman.cli.test_location.TestLocation.test_update_location_with_user_by_id

Error Message
Failed to create User with data:
{
  "admin": null, 
  "auth-source-id": 1, 
  "default-location-id": null, 
  "default-organization-id": null, 
  "firstname": "dB3YEKzjOR", 
  "lastname": "MhYFqksmve", 
  "location-ids": null, 
  "login": "f9zKCP", 
  "mail": "f9zKCP@example.com", 
  "organization-ids": null, 
  "password": "2OWUeZu0eR"
}
robottelo.cli.factory: DEBUG: User "f9zKCP" password not provided 2OWUeZu0eR was generated
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv user create --firstname="dB3YEKzjOR" --lastname="MhYFqksmve" --password="2OWUeZu0eR" --auth-source-id="1" --mail="f9zKCP@example.com" --login="f9zKCP"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x4593390
robottelo.common.ssh: INFO: Destroying Paramiko client 0x4593390
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x4593390
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-07-02 17:13:34 Exception] There was an issue with the backend service pulp: Pulp message bus connection issue.
Could not create the user:
  There was an issue with the backend service pulp: Pulp message bus connection issue.
[ERROR 2015-07-02 17:13:34 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:67:in `post'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_location.py", line 73, in test_create_location_with_user_by_id
    user = make_user()
  File "robottelo/common/decorators.py", line 76, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 1105, in make_user
    return create_object(User, args, options)
  File "robottelo/cli/factory.py", line 94, in create_object
    json.dumps(options, indent=2, sort_keys=True)
'Failed to create User with data:\n{\n  "admin": null, \n  "auth-source-id": 1, \n  "default-location-id": null, \n  "default-organization-id": null, \n  "firstname": "dB3YEKzjOR", \n  "lastname": "MhYFqksmve", \n  "location-ids": null, \n  "login": "f9zKCP", \n  "mail": "f9zKCP@example.com", \n  "organization-ids": null, \n  "password": "2OWUeZu0eR"\n}\n--------------------

filed a bz:
- https://bugzilla.redhat.com/show_bug.cgi?id=1241065

**Comment by sthirugn** [comment]
Passed in Snap 12
