### ISSUE TITLE
Automation failure : tests.foreman.cli.test_product.TestProduct.test_positive_update

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2550]
TestNames:
tests.foreman.cli.test_product.TestProduct.test_positive_update_1
tests.foreman.cli.test_product.TestProduct.test_positive_update_2 

Error Message

u'FtjwuIWznkFUkdJGQqDR' != u'\U00020be2\U00025875\u37a0\ucfa0\u154c\U00021f05\U00021064\u9b95\U00022c8a\u79 [truncated]...
- FtjwuIWznkFUkdJGQqDR
+ 10𠯢10𠯢𥡵㞠쾠ᕌ10𠯢𥡵𡼅10𠯢𥡵𡼅𡁤鮕10𠯢𥡵𡼅𡁤𢲊禔10𠯢𥡵𡼅𡁤𢲊𩶑鬧10𠯢𥡵𡼅𡁤𢲊𩶑𓋙郇10𠯢𥡵𡼅𡁤𢲊𩶑𓋙𣩓

LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv product update --id="2944" --description="10𠯢10𠯢𥡵㞠쾠ᕌ10𠯢𥡵𡼅10𠯢𥡵𡼅𡁤鮕10𠯢𥡵𡼅𡁤𢲊禔10𠯢𥡵𡼅𡁤𢲊𩶑鬧10𠯢𥡵𡼅𡁤𢲊𩶑𓋙郇10𠯢𥡵𡼅𡁤𢲊𩶑𓋙𣩓"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x4628dd0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x4628dd0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x4628dd0
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-07-02 17:26:06 Exception] There was an issue with the backend service pulp: Pulp message bus connection issue.
Could not update the product:
  There was an issue with the backend service pulp: Pulp message bus connection issue.
[ERROR 2015-07-02 17:26:06 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:76:in `put'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/107b379a/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_product.py", line 268, in test_positive_update_1
    result.stdout['description'], test_data['description'])
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 964, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'u\'FtjwuIWznkFUkdJGQqDR\' != u\'\\U00020be2\\U00025875\\u37a0\\ucfa0\\u154c\\U00021f05\\U00021064\\u9b95\\U00022c8a\\u79 [truncated]...\n- FtjwuIWznkFUkdJGQqDR\n+ \xf0\xa0\xaf\xa2\xf0\xa5\xa1\xb5\xe3\x9e\xa0\xec\xbe\xa0\xe1\x95\x8c\xf0\xa1\xbc\x85\xf0\xa1\x81\xa4\xe9\xae\x95\xf0\xa2\xb2\x8a\xe7\xa6\x94\xf0\xa9\xb6\x91\xe9\xac\xa7\xf0\x93\x8b\x99\xe9\x83\x87\xf0\xa3\xa9\x93\n\n--------------------

filed a bz:
- https://bugzilla.redhat.com/show_bug.cgi?id=1241081

**Comment by sthirugn** [comment]
Addressed in Snap 12
