### ISSUE TITLE
Automation failure : tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_create

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2551]
TestNames:
tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_create

Error Message
'max-content-hosts'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/107b379a/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_host_collection.py", line 139, in test_positive_create_3
    self.assertEqual(new_host_col['max-content-hosts'], str(test_data))
'\'max-content-hosts\'\n-------------------- >> begin captured logging << --------------------\nrobottelo: DEBUG: Running test TestHostCollection/test_positive_create_3_1_5\nrobottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv host-collection create --organization-id="243" --max-content-hosts="5" --name="WkntbbpxDoQLHRl"\nrobottelo.common.ssh: INFO: Instantiated Paramiko client 0x3679e50\nrobottelo.common.ssh: INFO: Destroying Paramiko client 0x3679e50\nrobottelo.common.ssh: INFO: Destroyed Paramiko client 0x3679e50\nrobottelo.common.ssh: DEBUG: <<< stdout\nMessage,Id,Name\nHost collection created,18,WkntbbpxDoQLHRl\n\nrobottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  host-collection info --id="18"\nrobottelo.common.ssh: INFO: Instantiated Paramiko client 0x3d93190\nrobottelo.common.ssh: INFO: Destroying Paramiko client 0x3d93190\nrobottelo.common.ssh: INFO: Destroyed Paramiko client 0x3d93190\nrobottelo.common.ssh: DEBUG: <<< stdout\nID:                  18\nName:                WkntbbpxDoQLHRl\nLimit:               5\nDescription:         \nTotal Content Hosts: 0\n\n\n---------------------

**Comment by sthirugn** [comment]
Failed in Snap 12

**Comment by tkolhar** [comment]
tested locally using nosetests:
$ nosetests -c robottelo.properties -m test_positive_create /home/tkolhar/git/robottelo/tests/foreman/cli/test_host_collection.py
ERROR: @Test: Check if host collection can be created with random names
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_host_collection.py", line 69, in setUp
    self.assertEqual(result.return_code, 0)
AssertionError: 70 != 0

XML: foreman-results.xml
Ran 17 tests in 285.590s
FAILED (errors=1)
