### ISSUE TITLE
Look into improving our Unicode generator algorithms

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2554]
At that moment, any Unicode characters (even these that almost impossible to display) can be generated for our test. It will be really nice to investigate possibility to generate only valid and supported symbols

**Comment by Ichimonji10** [comment]
Related to #2521.

**Comment by renzon** [comment]
The related issue above has some PRs merged. Maybe this is already solved and this issue can be closed.

**Comment by rochacbruno** [comment]
Yeah @sthirugn  fixed it im May, we can close it.
