### ISSUE TITLE
Improve 'Navigator' object

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2607]
We should improve mentioned object that it contains all necessary waiters (e.g. ```wait_for_ajax```) inside
After that it is needed to update all modules that refer to that object and remove redundant code

**Comment by elyezer** [comment]
:+1:

**Comment by oshtaier** [comment]
Covered in https://github.com/SatelliteQE/robottelo/pull/2809, https://github.com/SatelliteQE/robottelo/pull/3017 and in some other PRs
