### ISSUE TITLE
Rename tests/foreman to tests/satellite

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#2618]
As we test Satellite and not Foreman, I think that renaming the package will give more meaning because we have tools to actually interact with a Satellite instance and not Foreman. This specially that we are now testing plugins that is only available on the former.

**Comment by renzon** [comment]
is this still valid? AFAIK we have a upstream job running as well. @rplevka have also warned me when implementing specific Sat stuff like #3709

**Comment by rplevka** [comment]
yeah, i would stick to foreman. If renaming should take place, then it should be named `katello` perhaps.

**Comment by elyezer** [comment]
On Pulp Smash we organized the project a little bit different, all tests that are supposed to run against Pulp Server are inside the pulp_smash package. And the tests for the framework itself are on the tests directory which is sibling of the pulp_smash (common Python package organization).

If we would adopt this for Robottelo then tests.foreman will be moved to robottelo.tests.foreman... and tests.robottelo will become just tests.

Not sure if this issue stills valid, feel free to close it if that is the case.

**Comment by omaciel** [comment]
This is definitely not a high priority item for us now, but let me ask you @elyezer this: would renaming our tests affect our naming convention in Polarion?

**Comment by sghai** [comment]
Yes, we already have so much backlog.  Not on priority for now.

**Comment by elyezer** [comment]
@omaciel since now we are using IDs for each test moving them should not break anything. But I think renaming and moving will not bring any real benefit which makes me think we should close this issue.

**Comment by rplevka** [comment]
I'm ok with closing this issue

**Comment by sghai** [comment]
Lets close this now. If needed, we can reopen later or file a new one.
