### ISSUE TITLE
Please review tests that sync Puppet-based repositories

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2637]
While playing with synchronization of Puppet-based repos (we have a few of them being used in our automation [here](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/common/constants.py#L229-L234)) I noticed that we may have an issue with repositories that don't have a `modules.json` file, which in our case are:
- [FAKE_1_PUPPET_REPO](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/common/constants.py#L230)
- [FAKE_2_PUPPET_REPO](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/common/constants.py#L231)
- [FAKE_3_PUPPET_REPO](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/common/constants.py#L232)
- [FAKE_4_PUPPET_REPO](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/common/constants.py#L233)
- [FAKE_5_PUPPET_REPO](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/common/constants.py#L234)

[FAKE_0_PUPPET_REPO](https://davidd.fedorapeople.org/repos/random_puppet/) however, should be ok to use, so I would like to ask for the following to be performed:
- Synchronize **FAKE_0_PUPPET_REPO** (api/cli/ui) and check:
  - No errors from **pulp** or **foreman** in api/cli/ui **and** logs (`/var/log/messages` and `/var/log/foreman/*.log`)
- Synchronize **FAKE_1_PUPPET_REPO** (api/cli/ui) and check:
  - No errors from **pulp** or **foreman** in api/cli/ui **and** logs (`/var/log/messages` and `/var/log/foreman/*.log`)
- Puppet modules can be seen via api/cli/ui and are associated to corresponding repositories

If issues are found (errors or modules cannot be seen/found via api/cli/ui), then:
- Check that the presence of a `modules.json` is a requirement for Puppet-based repo syncs:
  - If the answer is `yes` then update our tests and remove `FAKE_1_PUPPET_REPO` through `FAKE_5_PUPPET_REPO` and set all existing tests to use `FAKE_1_PUPPET_REPO` instead
- Make the judgement call to figure out if new Bugzilla issues are required as well to handle errors that are not being reported to the UI.

**Comment by kbidarkar** [comment]
We can sync content, from the existing repos above if
a) we add modules.json 
b) and follow the below directory structure to place the content in
system/releases/<author first letter>/<author name>/
Example:  For saz-motd module 
system/releases/s/saz/
c) coutesy: http://www.pulpproject.org/2012/08/29/mirroring-puppet-forge-with-pulp/
d) Tested and it is working, for me.

As this is a one time effort, may be we can try fixing the puppet repos itself.

**Comment by kbidarkar** [comment]
Ah!, there are many puppet-modules in those repos, I just tried creating modules.json and the required directory structure for one puppet-module. So I doubt if this approach would be feasible, anyways will use my newly created puppet-repo of saz-motd for puppet_end_to_end testcase.

**Comment by rplevka** [comment]
@omaciel, bump. Would you mind converting your repos to compliant puppet repos?
Otherwise they're not valid and we should remove them from our constants. I believe, more feasible approach would be you fixing them on fedorapeople.org.

**Comment by omaciel** [comment]
@rplevka wow, this is old!!! hehehe anyhow, just last week @svtkachenko created a brand new puppet module which I uploaded to https://omaciel.fedorapeople.org/bagoftricks/  As you can see, this repo has all the expected files in place, so... @svtkachenko how about you give me the content and I can update those repos? :)

**Comment by svtkachenko** [comment]
@omaciel Sure :)

**Comment by rplevka** [comment]
@omaciel yeah, that PR is actually what brought me here ;)
thank you, gentlemen

**Comment by svtkachenko** [comment]
@omaciel Updated repos.
[fakepuppet01.tar.gz](https://github.com/SatelliteQE/robottelo/files/570007/fakepuppet01.tar.gz)
[fakepuppet02.tar.gz](https://github.com/SatelliteQE/robottelo/files/570010/fakepuppet02.tar.gz)
[fakepuppet03.tar.gz](https://github.com/SatelliteQE/robottelo/files/570011/fakepuppet03.tar.gz)
[fakepuppet04.tar.gz](https://github.com/SatelliteQE/robottelo/files/570008/fakepuppet04.tar.gz)
[fakepuppet05.tar.gz](https://github.com/SatelliteQE/robottelo/files/570009/fakepuppet05.tar.gz)

**Comment by omaciel** [comment]
Thank you @svtkachenko all directories have been updated with the content you provided :)

**Comment by sghai** [comment]
@svtkachenko : Could you please handle this issue if something still needs to be done here ? Adding it to next sprint.

**Comment by svtkachenko** [comment]
Everything is done. Closing.
