### ISSUE TITLE
Implement Docker API stubs

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2642]
We have list of stubs that need to be implemented for that task:

* [x] `test_add_multiple_docker_repos_to_content_view`
* [x] `test_publish_multiple_docker_repo_content_view`
* [x] `test_publish_multiple_docker_repo_composite_content_view`
* [x] `test_promote_docker_repo_content_view`
* [x] `test_promote_multiple_docker_repo_content_view`
* [x] `test_promote_docker_repo_composite_content_view`
* [x] `test_promote_multiple_docker_repo_composite_content_view`
* [x] `test_add_docker_repo_to_activation_key`
* [x] `test_remove_docker_repo_to_activation_key`
* [x] `test_add_docker_repo_composite_view_to_activation_key`
* [x] `test_remove_docker_repo_composite_view_to_activation_key`
* [ ] `test_docker_client_pull_image`
* [ ] `test_docker_client_upload_image`
* [x] `test_update_internal_docker_compute_resource`
* [x] `test_list_containers_internal_docker_compute_resource`
* [x] `test_update_external_docker_compute_resource`
* [x] `test_list_containers_external_docker_compute_resource`
* [x] `test_create_container_local_compute_resource`
* [x] `test_create_container_external_compute_resource`
* [x] `test_create_container_local_compute_resource_power`
* [x] `test_create_container_external_compute_resource_power`
* [x] `test_create_container_local_compute_resource_read_log`
* [x] `test_create_container_external_compute_resource_read_log`
* [ ] `test_create_container_external_registry`
* [x] `test_delete_container_local_compute_resource`
* [x] `test_delete_container_external_compute_resource`
* [x] `test_create_registry`
* [x] `test_update_registry_name`
* [x] `test_update_registry_url`
* [x] `test_update_registry_description`
* [x] `test_update_registry_username`
* [x] `test_delete_registry`

**Comment by oshtaier** [comment]
Going to look on first 10 methods from the list

**Comment by jyejare** [comment]
![done](https://cloud.githubusercontent.com/assets/11752425/9059390/28d09b96-3ac7-11e5-87eb-f15ecbf60893.png)

**Comment by elyezer** [comment]
:+1:

**Comment by omaciel** [comment]
![leonard-dicaprio-dancing](https://cloud.githubusercontent.com/assets/53362/9856908/7a344094-5ae5-11e5-91e5-c7dc031bee38.gif)

Time to write up more test cases :)
