### ISSUE TITLE
Create tests for big numbers as search queries parameters (targeting BZ #1252046)

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2670]
It is necessary to add few generic tests for different entries (e.g. `gpgkey`, `environments`, ...) to address scenarios where we use big numbers (more than usual integer boundaries: 2147483648+
) as queries parameters (e.g. `search` or `per_page`) in search procedures (entities list GETers, e.g. 'GET /katello/api/gpg_keys' or 'GET /api/environments'). Basically, we need to make sure that queries like this will not crash server flows and do not expose any sql data in the returned errors

For our current Nailgun/Robottelo implementation - we can use next statement as an example of things that we need to verify in this task:

```
entities.Environment(name='test').search({'name'}, query={'per_page': 50, 'order': 'name DESC', 'search': '2147483648'})
```

**Comment by JacobCallahan** [comment]
Closing since the bug linked has been closed downstream and upstream.
