### ISSUE TITLE
Add input helper method in UI

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2675]
Create new .input() method similar to .click() method implemented in #2556 which will include all necessary waiters. Get rid of send_keys() direct usage from the code.

**Comment by elyezer** [comment]
my vote is to call this fill which should be able to identify the type of the element and fill it properly. Also we can have fill_form which may receive a dictionary and fill all fields listed as keys with the corresponding values.

**Comment by elyezer** [comment]
@oshtaier any update on this?

**Comment by oshtaier** [comment]
I am really want to work on that, but as usually we have a lot of other priorities (especially working on coverage which has much higher priority than any improvement), but I can put that task in the list.

**Comment by elyezer** [comment]
@oshtaier this can be worked on a proper time. Just wanted to know the status.
