### ISSUE TITLE
Refactor repetitive nailgun helper method usages

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/robottelo#2683]
Some modules call the same NailGun helper method with an identical set of arguments over and over. For example, module `test_contentview.py` calls `ContentViewVersion.promote` fifteen times! Each call looks something like this:

```python
content_view.version[0].promote(data={u'environment_id': lc_env.id})
```

It'd be nice if we didn't have to write out `{u'environment_id': ...}` in every single one of those calls. We should review the usages of the various helper methods and see if we can refactor them down into more compact forms.

**Comment by Ichimonji10** [comment]
There's a couple ways to do this. One way is to add functions to `robottelo.api.utils`. This should be done with caution, though. Why? Consider the `promote` method again. The server accepts three arguments via that method:

* `id`
* `force`
* `environment_id`

`id` is included in the path for the request. As a result, you may end up with the following three functions:

```python
def promote_1(cv_ver, force):
    return cv_ver.promote(data={'force': force})

def promote_2(cv_ver, environment_id):
    return cv_ver.promote(data={'environment_id': environment_id})

def promote_3(cv_ver, force, environment_id):
    return cv_ver.promote(data={
        'force': force,
        'environment_id': environment_id,
    })
```

This is problematic, because it produces a proliferation of methods, and we may end up adding and dropping methods all the time as the test suite changes.

A second approach is to add private functions on a per-module basis. For example, in `tests.foreman.api.test_contentview`:

```python
def _promote(cv_ver, environment_id):
    return cv_ver.promote(data={'environment_id': environment_id})

# [...]

_promote(content_view.version[0], lc_env.id)
```

As you might imagine, I advocate for the second approach.

**Comment by Ichimonji10** [comment]
Depends on SatelliteQE/robottelo#2677.

**Comment by elyezer** [comment]
These methods can be located under the robottelo/api namespace. Also we can add some entities requirements creation there like getting an activation key ready for using for other tests that requires one activation key.

Currently in the api.utils there is just enable_rhrepo_and_fetchid. But I think we can think a little and organize the helpers in modules. Like a module for simple helpers and other for more complex one that creates many entities in one go.
