### ISSUE TITLE
CLI - Import - extend the object by the related transition data

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#2685]
Every test is currently responsible for reaching out to server for parsing the `${HOME}/.transition_data/*.csv`.
The idea is to move this dance to the object instance itself so the data might be accessible via `import_obj.transition_data`

**Comment by Ichimonji10** [comment]
Thanks for making an issue to track this, @rplevka. If I remember correctly, this issue impacts module [`tests.foreman.cli.test_import`](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_import.py) especially heavily.

**Comment by rplevka** [comment]
@Ichimonji10 - correct, thanks for mentioning.

**Comment by elyezer** [comment]
I have started a conversation about the design decision of this. Even though I agree that is handy to have that patched on the SSHCommandResult that will break the entire design of the CLI framework. For more info https://github.com/SatelliteQE/robottelo/pull/2686#discussion_r37152677

**Comment by rplevka** [comment]
https://github.com/SatelliteQE/robottelo/pull/2686
Closes this issue
