### ISSUE TITLE
Drop common package

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#2693]
And move all modules to robottelo main package. Import from robottelo.helpers does not hurt the meaning and is shorter than robottelo.common.helpers.

**Comment by sthirugn** [comment]
:+1:

**Comment by Ichimonji10** [comment]
Agreed.

We have common code placed in both the `robottelo` and `robottelo.common` packages. I think common code should be in just one of the two. We might as well choose the former option, as it'll lead to shorter package names.
