### ISSUE TITLE
Automation failure :  test_hammer_options

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2696]
TestNames:
tests.foreman.cli.test_hammer.HammerCommandsTestCase.test_hammer_options 

Error Message

{
 "hammer docker container create": {
  "added_command": false, 
  "added_options": [
   "registry"
  ]
 }, 
 "hammer docker registry create": {
  "added_command": false, 
  "added_options": [
   "username", 
   "url", 
   "password", 
   "name", 
   "description"
  ]
 }, 
 "hammer docker registry delete": {
  "added_command": false, 
  "added_options": [
   "id", 
   "name"
  ]
 }, 
 "hammer docker registry info": {
  "added_command": false, 
  "added_options": [
   "id", 
   "name"
  ]
 }, 
 "hammer docker registry list": {
  "added_command": false, 
  "added_options": [
   "search", 
   "page", 
   "order", 
   "per-page"
  ]
 }, 
 "hammer docker registry update": {
  "added_command": false, 
  "added_options": [
   "username", 
   "description", 
   "url", 
   "password", 
   "id", 
   "new-name", 
   "name"
  ]
 }
}

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-cli/tests/foreman/cli/test_hammer.py", line 110, in test_hammer_options
    json.dumps(self.differences, indent=True, sort_keys=True)
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'{\n "hammer docker container create": {\n  "added_command": false, \n  "added_options": [\n   "registry"\n  ]\n }, \n "hammer docker registry create": {\n  "added_command": false, \n  "added_options": [\n   "username", \n   "url", \n   "password", \n   "name", \n   "description"\n  ]\n }, \n "hammer docker registry delete": {\n  "added_command": false, \n  "added_options": [\n   "id", \n   "name"\n  ]\n }, \n "hammer docker registry info": {\n  "added_command": false, \n  "added_options": [\n   "id", \n   "name"\n  ]\n }, \n "hammer docker registry list": {\n  "added_command": false, \n  "added_options": [\n   "search", \n   "page", \n   "order", \n   "per-page"\n  ]\n }, \n "hammer docker registry update": {\n  "added_command": false, \n  "added_options": [\n   "username", \n   "description", \n   "url", \n   "password", \n   "id", \n   "new-name", \n   "name"\n  ]\n }\n}\n--------------------

**Comment by elyezer** [comment]
Closing this as #2727 is merged.

**Comment by tkolhar** [comment]
this issue occurred again dated 09/03/2015
TestNames:
tests.foreman.cli.test_hammer.HammerCommandsTestCase.test_hammer_options

Error Message

{
 "hammer docker container create": {
  "added_command": false, 
  "added_options": [
   "cpu-set"
  ], 
  "removed_options": [
   "cpu-sets"
  ]
 }
}

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-cli/tests/foreman/cli/test_hammer.py", line 110, in test_hammer_options
    json.dumps(self.differences, indent=True, sort_keys=True)
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'{\n "hammer docker container create": {\n  "added_command": false, \n  "added_options": [\n   "cpu-set"\n  ], \n  "removed_options": [\n   "cpu-sets"\n  ]\n }\n}\n-------------------

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all downstream failures
