### ISSUE TITLE
Implement Docker CLI stubs

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#2705]
Following 55 CLI docker stubs should be implemented:

DockerRepositoryTestCase:
* [x] `test_create_one_docker_repo`
* [x] `test_create_multiple_docker_repo`
* [x] `test_create_multiple_docker_repo_multiple_products`
* [x] `test_sync_docker_repo`
* [x] `test_update_docker_repo_name`
* [x] `test_update_docker_repo_upstream_name`
* [x] `test_update_docker_repo_url`
* [x] `test_delete_docker_repo`
* [x] `test_delete_random_docker_repo`

DockerContentViewTestCase:
* [x] `test_add_docker_repo_to_content_view`
* [x] `test_add_multiple_docker_repos_to_content_view`
* [x] `test_add_synced_docker_repo_to_content_view`
* [x] `test_add_docker_repo_to_composite_content_view`
* [x] `test_add_multiple_docker_repos_to_composite_content_view`
* [x] `test_publish_once_docker_repo_content_view`
* [x] `test_publish_once_docker_repo_composite_content_view`
* [x] `test_publish_multiple_docker_repo_content_view`
* [x] `test_publish_multiple_docker_repo_composite_content_view`
* [x] `test_promote_docker_repo_content_view`
* [x] `test_promote_multiple_docker_repo_content_view`
* [x] `test_promote_docker_repo_composite_content_view`
* [x] `test_promote_multiple_docker_repo_composite_content_view`

DockerActivationKeyTestCase:
* [x] `test_add_docker_repo_to_activation_key`
* [x] `test_remove_docker_repo_to_activation_key`
* [x] `test_add_docker_repo_composite_view_to_activation_key`
* [x] `test_remove_docker_repo_composite_view_to_activation_key`

DockerClientTestCase:
* [x] `test_docker_client_pull_image`
* [x] `test_docker_client_upload_image`

DockerComputeResourceTestCase:
* [x] `test_create_internal_docker_compute_resource`
* [x] `test_update_internal_docker_compute_resource`
* [x] `test_list_containers_internal_docker_compute_resource`
* [x] `test_create_external_docker_compute_resource`
* [x] `test_update_external_docker_compute_resource`
* [x] `test_list_containers_external_docker_compute_resource`
* [x] `test_delete_docker_compute_resource`

DockerContainersTestCase:
* [x] `test_create_container_local_compute_resource`
* [x] `test_create_container_external_compute_resource`
* [x] `test_create_container_local_compute_resource_power`
* [x] `test_create_container_external_compute_resource_power`
* [x] `test_create_container_local_compute_resource_read_log`
* [x] `test_create_container_external_compute_resource_read_log`
* [x] `test_create_container_external_registry`
* [x] `test_delete_container_local_compute_resource`
* [x] `test_delete_container_external_compute_resource`

DockerRegistriesTestCase:
* [x] `test_create_registry`
* [x] `test_update_registry_name_by_id`
* [x] `test_update_registry_name_by_name`
* [x] `test_update_registry_url_by_id`
* [x] `test_update_registry_url_by_name`
* [x] `test_update_registry_description_by_id`
* [x] `test_update_registry_description_by_name`
* [x] `test_update_registry_username_by_id`
* [x] `test_update_registry_username_by_name`
* [x] `test_delete_registry_by_id`
* [x] `test_delete_registry_by_name`

**Comment by abalakh** [comment]
Will start from `DockerRepositoryTestCase`'s group.

**Comment by abalakh** [comment]
`DockerContainersTestCase` and `DockerRegistriesTestCase` are blocked by [BZ1230915](https://bugzilla.redhat.com/show_bug.cgi?id=1230915) and [BZ1259498](https://bugzilla.redhat.com/show_bug.cgi?id=1259498) accordingly

**Comment by elyezer** [comment]
#3562 is merged, closing this.
