### ISSUE TITLE
Improve code for WebUI to have single approach for delete() methods (where applicable)

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2750]
At that moment we have different approaches to delete entity from UI. We can do that using `delete_entity()` method or use whole flow for particular entity deletion procedure. It will be nice to get to common solution and use it in all situations

**Comment by elyezer** [comment]
:+1:

**Comment by oshtaier** [comment]
Basically, we have two possible generic scenarios for delete procedure:
1) List-based (when 'delete' button or dropdown with 'delete' button is located on the same page where entities list present). For that scenario, we pretty don't care about entity type as we can use same locators for them, because table appearance are the same for all entities

![image](https://cloud.githubusercontent.com/assets/10895065/10877745/8a85f996-8151-11e5-9fa5-85d8cb074a93.png)
or
![image](https://cloud.githubusercontent.com/assets/10895065/10877778/c4ecc8bc-8151-11e5-8390-f5628c44dfd3.png)
or
![image](https://cloud.githubusercontent.com/assets/10895065/10877792/ed739d74-8151-11e5-8c9f-b77f2017ff7b.png)

2) Entity-based (when we need to open entity instance to access necessary 'delete' elements).

![image](https://cloud.githubusercontent.com/assets/10895065/10877919/1748dd02-8153-11e5-9353-055982f67466.png)
or
![image](https://cloud.githubusercontent.com/assets/10895065/10877932/382bd6fa-8153-11e5-92fb-d3a69596e7e7.png)

**Comment by oshtaier** [comment]
It was decided to move on with single method approach. Going to look in that direction. Thanks

**Comment by oshtaier** [comment]
Do not forget to check every 'delete', 'remove' and 'disassociate' instance and get to one single naming standard.

**Comment by elyezer** [comment]
:+1:
