### ISSUE TITLE
Add build_env variables for sattools and capsule for non-cdn jobs

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#2752]
Realized one issue if we are planning to use the "sate6tools" from cdn directly.
This is an issue for 
a) capsule, 
b) oscap, 
c) incremental updates, 
d) katello_agents

Issue:
a) I believe using cdn content of sat6tools will only be helpful for the jenkins "cdn job" but not for 
i) qe-sat6-downstream 
ii) iso 
iii) zstream
as the latest content would never be available on cdn till GA.

Reasons:
a) oscap and puppet needs to be tested with it's corresponding build from SNAP-sat6tools and not cdn.
b) I think errata depends upon the packages being brought in by sat6tools, so we won't have latest build to be used if we plan to sync content from cdn.
c) Also capsule packages needs SNAP-sat6tools and not content from cdn.
d) Otherwise we can't run these tests till the GA or zstream available via CDN.

Solution:
a) Seems that we need a configuration here. If a custom sat6 tools repo is defined use that instead of using CDN one.
b) What we need is Build environment variables to be specified in jenkins and thus use the latest build from SNAP-sat6tools as custom repo for sat6tools.

Edit: Cleaned up for more clarity on this issue and what all jobs needs to be updated on jenkins.

**Comment by Ichimonji10** [comment]
:+1:

**Comment by Ichimonji10** [comment]
Related to #2730.

**Comment by sthirugn** [comment]
:+1:

**Comment by elyezer** [comment]
:+1:

**Comment by kbidarkar** [comment]
The fixes required here were mostly in 
a) robottelo-ci and
b) In updating the `SATELLITE6 REPO URLS` in the jenkins managed config files to also include the `CAPSULE URL` and `SATTOOLS_URL`

Will be updating the robottelo-ci PR's which addresses this issue.

**Comment by kbidarkar** [comment]
Below are the PR's related to it:
a) https://github.com/SatelliteQE/robottelo-ci/pull/56
b) https://github.com/SatelliteQE/robottelo-ci/pull/59
c) https://github.com/SatelliteQE/robottelo-ci/pull/71
d) some fixes went in along with this PR,  https://github.com/SatelliteQE/robottelo-ci/pull/74 and 
 https://github.com/SatelliteQE/robottelo-ci/pull/75
