### ISSUE TITLE
Update reference to entities in tests/foreman/longrun/test_inc_updates.py 

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2760]
Created from https://github.com/SatelliteQE/robottelo/pull/2730

elyezer:
The common usage for entities are like:

``` py
from nailgun import entities

entities.Something().create()
```

This is not a blocker but it should be better to stick with the common usage. I know that it require more typing but when I see entities.Organization on the code I know that is being provided by API and not a CLI or UI Organization.

sthirugn:
The majority of usage in this module is entities (I use 13+ entities) so calling them entities.\* in each call will make the code redundant and boring.

elyezer:
This is more a personal thing. I would use the same style as other parts in robottelo. This is also not a blocker.

**Comment by sghai** [comment]
@sthirugn @elyezer: long run incremental tests been updated recently by @oshtaier and I think they way its written looks good.  So do you guys want to still keep this issue open ?

**Comment by sthirugn** [comment]
I am ok to close this - we have more high priority stuff to work on.

**Comment by sghai** [comment]
Closing this now and have checked with @elyezer too.
<elyezer> sghai: looking
<elyezer> sghai: feel free to close it
