### ISSUE TITLE
Use cls.assertequal instead of assert

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2761]
Created from this PR https://github.com/SatelliteQE/robottelo/pull/2730

**Comment by Ichimonji10** [comment]
Even better:

```python
self.assertGreater(len(subs), 0)
````

**Comment by sthirugn** [comment]
I am getting error calling assertequal or assertgreater in setUpClass().  These need instance to run.

TypeError: unbound method assertEqual() must be called with TestIncrementalUpdate instance as first argument (got list instance instead)

**Comment by sthirugn** [comment]
Closing as per my comment.

**Comment by elyezer** [comment]
An alternative would be creating a method that will fill that information in the first call to setUp, but I think that does not worth the work needed. Agreed on leave the assert statement there.
