### ISSUE TITLE
Improve robottelo configuration parsing

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#2770]
Let's bring robottelo configuration parsing to a next level. Need to make the config object smart enough to tell if some feature can be tested or not. For example, suppose the user have not configured vm provisioning tests that depends on that feature should be skipped.

Also if user indicates that wants to use that feature, let's say by having the config header in place, then robottelo should properly validate the configuration and raise exception if something is missing. With that said, we can have a minimal set of required configuration and other optional (basically the ones that depends on extra infrastructure). Robottelo should be smart enough to identify that and act accordingly.

Based on the current state, will be described some of the changes needed to accomplish the proposed solution:

Currently configuration are accessed by reading values from the properties dictionary. This leave room for some issues like when accessing a key that is not set during import time, making the entire module import fail. In order to improve this all config parsing should happen when robottelo is imported and if some required configuration is missing a ImproperlyConfigured exception should be raised with all detailed information about what is missing. For example we can't run any test with at least the Satellite server URL and admin user and password, instead of failing for the first missing configuration we should provide the complete information to the user and being clear about what are the required configuration.

For the optional configuration, or configuration that requires extra infrastructure other than a installed Satellite server, the config should provide methods to check if that is available. Then tests can be skipped by checking if the the extra infrastructure information is in place or not. For example, vm provisioning to allow clients creation, if that configuration is not in place then is better to just skip the tests that requires it than block the entire test execution.

The goal of this is make robottelo easier to be used by everyone and require as less as possible configuration for a quick start.

**Comment by Ichimonji10** [comment]
:+1:

**Comment by elyezer** [comment]
One of the goals of this improvement is that robottelo have the capability of skipping tests that depends on additional infrastructure. What will tell robottelo if the infrastructure is in place or not is the configuration filled for that. My proposal here is to use the following approach: separate optional configuration in sections (since we are using ini file format), if that section is present then robottelo must validate the contents and ensure all configuration is in place. With that said robottelo will skip things if the section is not present and will raise ImproperlyConfigurationError when a section is present and not all required values are filled.

With that said, the properties file will need some work on better organizing the configuration and also drop some values like the saucelabs section as we are not using it.

Other than that, I'm in favor of creating a server config object that will tell important information about the server, like how to access it via ssh (using a ssh key or a password, for example), if the server have an upstream or downstream build (this could be fetched https://github.com/SatelliteQE/robottelo/blob/master/robottelo/helpers.py#L46), etc.. For now we have just one server configuration, but would be great if we can specify a list of servers. Choosing what should be used can be done by setting an environment variable or use another method.

**Comment by sthirugn** [comment]
There are two tasks in this:
* Refactor robottelo configuration
* Adding metadata for each test with its requirements.  Using nose's attr() is one of the ways of populating such metadata for tests.

**Comment by elyezer** [comment]
@sthirugn actually the idea is not choose a runner and use its feature like `@attr` from nose. Once we have config.has_client_provisioning returning either True or False we can use standard unittest `@skipIf(not config.has_client_provisining)`. This way the test will be automatically skipped without the need to select an attr to run against.

**Comment by elyezer** [comment]
Implemented by #2869
