### ISSUE TITLE
CLI: Move SSHCommandResult processing from tests to Base class

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#2776]
Currently after executing CLI commands, we're sending `SSHCommandResult` directly to tests without any changes or processing. This makes tests responsible for validating the command execution result. As a result, after each executed command, we're "manually" checking `return_code`, `stderr` and processing `stdout` every single time inside the test instead of doing this automatically inside the framework. 
So the simplified flow is following:
* Test asks framework to execute some CLI command
* Framework executes command and sends `SSHCommandResult` to the test
* Test checks if `return_code` is `0`
* Test checks if `stderr` is empty
*  If everything is ok, test starts working with `stdout`.

Just compare this example of API vs CLI command:
```python
# API
content_view = entities.ContentView(id=123).read()

# CLI
result = ContentView.info({'id': 123})
self.assertEqual(result.return_code, 0, "Failed to fetch object")
self.assertEqual(len(result.stderr), 0,
    "There should not be an exception here")
content_view = result.stdout
```
So, for each executed command we have about 2-4 lines of redundant code. And tests usually have not just 1 command executed, but probably 3-5 of them in average, increasing the number of redundant lines of code to 6-20 per "average" test.

The solution here is to stop sending `SSHCommandResult` directly to the tests and make framework to be responsible for `SSHCommandResult` processing. Simplified flow is following:
* Test asks framework to execute some CLI command
* Framework executes command and receives `SSHCommandResult`
* Framework checks if `return_code` is `0`
* Framework checks if `stderr` is empty
* If everything is ok, framework sends `stdout` to test, if not - raises an exception.
* Test recieves `stdout` and starts working with it

This will greatly reduce amount of code per each executed command:
```python
# Before
result = ContentView.info({'id': 123})
self.assertEqual(result.return_code, 0, "Failed to fetch object")
self.assertEqual(len(result.stderr), 0,
    "There should not be an exception here")
content_view = result.stdout

# After
content_view = ContentView.info({'id': 123})
```

That will work for about 95% cases, as we usually don't need `return_code` or `stderr`, we just need to be sure command was executed ok. 
In case we expect and error (for negative tests), we can catch an exception like this:
```python
# Before
result = ContentView.info({'id': 123})
self.assertNotEqual(result.return_code, 0, "Expected an error here")

# After
with self.assertRaises(CLICommandExecutionError):
    result = ContentView.info({'id': 123})
```
And even if we need the `return_code` (pretty rare case), we can still fetch it from the exception:
```python
# Before
result = ContentView.info({'id': 123})
self.assertEqual(result.return_code, 1, "Expected return_code 1 here")

# After
with self.assertRaises(CLICommandExecutionError) as e:
    ContentView.info({'id': 123})
self.assertEqual(e.exception.return_code, 1)
```
IMO, this change will reduce amount of code in CLI tests for ~30-50%

**Comment by abalakh** [comment]
The drawback is that this approach will definitely be backwards incompatible, so all the CLI tests should be refactored together with this change.
I'll list all the modules we have for tracking purposes:
* [ ] activationkey
* [ ] architecture
* [ ] 
* [ ] 
* [ ]

**Comment by elyezer** [comment]
:+1:

**Comment by sthirugn** [comment]
:+1:
