### ISSUE TITLE
Update mock tests in test_decorators.py

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2780]
This is from https://github.com/SatelliteQE/robottelo/pull/2775:

@Ichimonji10 wrote: 
> In tests/robottelo/test_decorators.py:
>
> ```diff
>          """Back up objects and generate common values."""
>          self.backup = decorators._get_bugzilla_bug
>          self.bug_id = gen_integer()
> -
> -    def tearDown(self):  # noqa pylint:disable=C0103
> +        self.upstream_backup = conf.properties.get('main.upstream')
> ```
>
> This may (actually, I'm almost certain it will) modify conf.properties like so:
>
> ```python
> conf.properties['main.upstream'] = None
> ```
>
> Can we properly mock out conf.properties in the tests? I did the backup/restore thing for quite a while, but now realize that it's a very fragile approach.

**Comment by sthirugn** [comment]
If possible try avoiding updating class attributes MockBug.status, MockBug.whiteboard in the loop

**Comment by elyezer** [comment]
I have updated all robottelo tests on the newconfig branch, they are using mock module in order to mock settings.

**Comment by elyezer** [comment]
Test decorators is now with 100% coverage and already using mock to properly mock settings. Closing this.

**Comment by Ichimonji10** [comment]
:+1:
