### ISSUE TITLE
Replace %s and %d usage in string formatting with .format()

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2853]

**Comment by helgie** [comment]
taking this one

**Comment by elyezer** [comment]
Is this issue relevant? We should take advantage of using string interpolation for logging messages, but in other cases using format can be better.

**Comment by rochacbruno** [comment]
ui.locators also uses %s by default
 (but we can implement format there if needed)

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
