### ISSUE TITLE
test_hammer_options needs to be updated to contain latest hammer options

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2864]
Our automation shows that the test_hammer_options test is failing with:

```bash
Error Message

{
 "hammer filter available-permissions": {
  "added_command": false, 
  "added_options": [
   "search", 
   "order"
  ]
 }
}
```

I believe we need to re-generate the file that contains the expected hammer command options.

**Comment by omaciel** [comment]
@elyezer could you fix this for me? I would like to get as close to a green build as possible.

**Comment by elyezer** [comment]
Definitely.
