### ISSUE TITLE
TestAvailableURLs.test_get_links fails due to new API entries

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2867]
Our automation shows that there are 3 new API entries that we need to be aware of:

```bash
Error Message

Items in the first set but not the second:
u'arf_reports'
u'scaptimony_policies'
u'registries'
```

**Comment by omaciel** [comment]
@oshtaier hey, could you fix this for me? Should be pretty trivial and would get us closer to a gree smoke test suite :)

**Comment by oshtaier** [comment]
@omaciel Done. And that is not for you, but for all of us :)
