### ISSUE TITLE
Several CLI automated tests are failing with 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2876]
I wonder if this is related to the CLI changes we've recently merged?

Example of existing error (check Jenkins for latest CLI errors for latest compose build):

```bash
Stacktrace

  File "/home/jenkins/shiningpanda/jobs/107b379a/virtualenvs/d41d8cd9/lib/python2.7/site-packages/unittest2/case.py", line 67, in testPartExecutor
    yield
  File "/home/jenkins/shiningpanda/jobs/107b379a/virtualenvs/d41d8cd9/lib/python2.7/site-packages/unittest2/case.py", line 625, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_contentviews.py", line 1447, in test_cv_subscribe_rh2
    u'repository-id': TestContentView.rhel_repo['id'],
```

**Comment by omaciel** [comment]
@abalakh please look into this as your top priority?

**Comment by abalakh** [comment]
@omaciel sure, looking...

**Comment by omaciel** [comment]
@abalakh preferably when you're at work hehehe :)

**Comment by abalakh** [comment]
:smile:

**Comment by abalakh** [comment]
Locally this test (and a lot of other content view tests) is failing with the following error:
```
CLIReturnCodeError: Command 'repository-set enable' finished with return_code 77
stderr contains following message:
[ERROR 2015-10-07 08:54:32 Exception] Forbidden - server refused to process the request
Could not enable repository:
  Forbidden - server refused to process the request
```
The command it's trying to execute is following:
```
hammer -v repository-set enable --product="Red Hat Enterprise Linux Workstation" --basearch="x86_64" --releasever="6Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation (RPMs)" --organization-id="58"
```
I've tried to reproduce it multiple times - each time enabling this specific repo is unsuccessful. Another repos are being enabled ok.
I'm not sure if it's problem with repo itself or maybe something happend to our manifest.

**Comment by omaciel** [comment]
@abalakh  we could choose a simpler, more common repo-set then.

**Comment by abalakh** [comment]
Hm, this issue needs further investigation. All the mentioned content view tests aren't failing anymore, at least for 5 last jenkins runs. No PRs fixing the issue were risen, so i guess there was something wrong with repo/manifest, not robottelo.
However, now content-host tests are failing with exactly the same error - `Command 'repository-set enable' finished with return_code 77` and message `Forbidden - server refused to process the request`.

**Comment by omaciel** [comment]
@abalakh together with @elyezer we got a newer manifest file and tried to enable the repository that we had tried earlier today, and it worked fine. So we believe that the problem was the manifest file.
