### ISSUE TITLE
Please automate BZ 1259248

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2910]
The following bugzilla needs to be automated:  https://bugzilla.redhat.com/show_bug.cgi?id=1259248

I believe that the easiest thing would be to automate this using the UI.

**Comment by omaciel** [comment]
Assigned it to @oshtaier

**Comment by oshtaier** [comment]
1) Area is pretty unknown for me
2) Task is not so easy to implement from technical side (proper file management should be investigated and implemented)
But definitely I will look on that

**Comment by omaciel** [comment]
1) I can walk you through it 
2) We can think of something together. I have no doubt you can automate this 😊

**Comment by oshtaier** [comment]
Thanks. Let me look on that first :)

**Comment by oshtaier** [comment]
The first obstacle that I faced for that task is necessity to handle 'Save As...' dialog which can require changes to the fundamental part of our framework.
Per my own experience or some answers here:
http://stackoverflow.com/questions/1176348/access-to-file-download-dialog-in-firefox
or
http://stackoverflow.com/questions/27042302/unable-to-interact-with-dialog-box-using-selenium-in-python
or
https://blog.codecentric.de/en/2010/07/file-downloads-with-selenium-mission-impossible/

we can try to investigate more and implement any of that solutions:
1) Firefox Profiles
2) Window handling frameworks like pywinauto (or its alternatives)
3) Direct API calls to the server

I am not sure that I like any of these ideas, so we need decide whether we like to spend efforts on that. Anyway, my vote goes for third idea

**Comment by omaciel** [comment]
@oshtaier so I'm going to make two suggestions here:

1. Modify the base class that creates the webdriver instance to create a new profile if the browser is Firefox, and modify it so that downloads can be automatically done as per this [article](https://stackoverflow.com/questions/1176348/access-to-file-download-dialog-in-firefox). I honestly don't see any downsides to doing this.
2. The second option would be to let **wget** do the file download for us as described [here](https://blog.codecentric.de/en/2010/07/file-downloads-with-selenium-mission-impossible/). Inline:

```
You can pass wget the session ID with cookies and header parameters, so that wget can then access all the same files as the browser in the current Selenium session. Implemented as a keyword, it’s just two lines:

$ wget --cookies=on --header "Cookie: ${COOKIE}=${COOKIE_VALUE}" -O ${OUTPUT_DIR}${/}${FILENAME} ${URL}
```

If the second option works well, then we can use it instead of creating a profile, which would limit our tests to Firefox only. Thoughts?

**Comment by omaciel** [comment]
@elyezer @JacobCallahan @sghai @sthirugn @kbidarkar @jyejare @rplevka @lpramuk please chime in?

**Comment by oshtaier** [comment]
It seems we can achieve same result using our powerful Nailgun tool :) I will look on that further

**Comment by rplevka** [comment]
@omaciel 
> 1. Modify the base class that creates the webdriver instance to create a new profile if the browser is Firefox, and modify it so that downloads can be automatically done as per this article. I honestly don't see any downsides to doing this.

I vote for this option as we don't need the download dialog
I would even set this to the default profile to handle all downloads automatically.

**Comment by sthirugn** [comment]
I second @rplevka - the solution given in the link looks easier to implement as well.

**Comment by oshtaier** [comment]
Created separate issue to resolve mentioned scenario for generic case as we do not need to handle mentioned dialog anymore as alternative solution was found (using Nailgun)
