### ISSUE TITLE
Please automate BZ https://bugzilla.redhat.com/show_bug.cgi?id=1272448

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2912]
Please automate BZ https://bugzilla.redhat.com/show_bug.cgi?id=1272448

**Comment by abalakh** [comment]
Is that actually a valid defect? The issue described there is that `host set-parameter` command can't handle two parameters within the single call, like this:
```
hammer> host set-parameter --name ignore_automic --value true --name ignore_itm --value true --host vm76.xxx.com
```
But it doesn't sound like a valid case for me, as we have `name` and `value` arguments duplicated.
In other words, this command will look like this:
```python
Host.set_parameter({
    'name': 'ignore_automic',
    'value': 'true',
    'name': 'ignore_itm',
    'value': 'true',
    'host-id': result['id'],
})
```
We're overriding `name` and `value` here, inside the same dict so it's not surprising that command will work incorrectly (with only 1 actual name and value).

**Comment by omaciel** [comment]
@abalakh the issue is a bit different. The user is not trying to update the same `name` but different ones in one single call. From the BZ:

```bash
[1] Set a single value as "false" :  which is updated successfully ;

hammer> host set-parameter --name ignore_automic --value false --host vm76.xxx.com
New host parameter created
hammer> host info --name vm76.xxx.com

Parameters:         
    ignore_automic => false
    ignore_itm => true

[2] Set "ignore_automic --value true" with "ignore_itm --value true"; only "ignore_itm" value is changed  nothing has been changed in "ignore_automic".

hammer> host set-parameter --name ignore_automic --value true --name ignore_itm --value true --host vm76.xxx.com
Host parameter updated
hammer> host info --name vm76.xxx.com

Parameters:         
    ignore_automic => false
    ignore_itm => true
```

As you can see, the second command tries to update both ``--name ignore_automic`` and ``--name ignore_itm``

**Comment by abalakh** [comment]
And it will never succeed as we're _not_ updating parameters like this:
```
Host.set_parameter({
    'ignore_automic': 'true',
    'ignore_itm': 'true',
    'host-id': result['id'],
})
```
but like this:
```
Host.set_parameter({
    'name': 'ignore_automic',
    'value': 'true',
    'name': 'ignore_itm',
    'value': 'true',
    'host-id': result['id'],
})
````
as we're using `--name ignore_automic --value true` but not `--ignore_atomatic true`. That's why only 1 parameter gets actually updated - as only one pair of name-value remains, another one gets overriden.

**Comment by omaciel** [comment]
Got it now. So what you're really saying is that you'll look into a way to override this method so that it can take perhaps a list of names and values and generate the correct command, right? 😉

**Comment by abalakh** [comment]
Haha, yea. Actually I was wondering if that's a valid defect - I wouldn't be surprised if hammer has the same limitation and can't work with 2 arguments with the same name in single command (at least I can't remember any example of such command).
But if that defect is valid, then you're absolutely right - I'll look into a way to automate it :)

**Comment by omaciel** [comment]
Spoke to @abalakh and we now need to wait for DEV to tell us if this is a real bug or not

**Comment by omaciel** [comment]
@abalakh good news! The issue has been closed as **NOTABUG** :)
