### ISSUE TITLE
Upstream Failures: List of all upstream failures

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2929]
Combining all the upstream failures into one:
- [ ]  tests.foreman.cli.test_contenthost.TestContentHost.test_positive_create_1
- [ ]  tests.foreman.cli.test_activationkey.TestActivationKey.test_positive_content_override_1
- [ ]  tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_create_3
- [ ]  tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_delete_1
- [ ]  tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_update
- [ ]  tests.foreman.cli.test_contenthost.TestContentHost.test_positive_update_1_1
- [ ]  tests.foreman.cli.test_computeresource.TestComputeResource.test_update_negative_1
- [ ]  tests.foreman.cli.test_repository_set.TestRepositorySet
- [ ]  test_partitiontable.TestPartitionTableDelete.test_removeoperatingsystem_ptable
- [ ]  test_os.TestOperatingSystem.test_add_configtemplate
- [ ]  tests.foreman.cli.test_contentviews.TestContentView.test_remove_cv_version
- [ ]  test_contentviews.TestContentView.test_cv_subscribe_system_custom
- [ ]  test_contentviews.TestContentView.test_cv_subscribe_system_composite
- [ ]  test_contentviews.TestContentView.test_cv_subscribe_system 
- [ ]  tests.foreman.cli.test_repository.TestRepository
- [ ]  tests.foreman.cli.test_product.TestProduct
- [ ]  test_activationkey.TestActivationKey.test_positive_content_override_1
- [ ]  tests.foreman.api.test_subscription.SubscriptionsTestCase
- [ ]  test_permission.PermissionsTestCase.test_search_by_resource_type
- [ ]  test_permission.PermissionsTestCase.test_search_by_name
- [ ]  tests.foreman.cli.test_host_collection.TestHostCollection
- [ ]  tests.foreman.cli.test_contenthost.TestCHKatelloAgent
- [ ]  tests.foreman.cli.test_contentviews.TestContentView.test_cv_publish_rh
- [ ]  test_repository_set.TestRepositorySet.test_repositoryset_available_repositories
- [ ]  tests.foreman.cli.test_subscription.TestSubscription
- [ ]  tests.foreman.cli.test_host.HostTestCase.test_positive_create_1
- [ ]  tests.foreman.cli.test_product.TestProduct
- [ ]  tests.foreman.cli.test_host_collection.TestHostCollection
- [ ]  test_contentviews.TestContentView.test_associate_view_rh_custom_spin
- [ ]  test_contentviews.TestContentView.test_associate_view_rh 
- [ ]  tests.foreman.cli.test_activationkey.TestActivationKey
- [ ]  test_hammer_options
- [ ]  tests.foreman.api.test_contentviewfilter 
- [ ]  test_repository.RepositorySyncTestCase.test_redhat_sync_1
- [ ]  tests.foreman.api.test_docker.DockerContentViewTestCase
- [ ]  tests.foreman.api.test_contentview.ContentViewTestCase
- [ ]  test_add_docker_repo_to_composite_content_view_5
- [ ]  test_contentviews.TestContentView.test_remove_cv_version
- [ ]  test_contentviews.TestContentView.test_remove_cv_environment
- [ ]  test_subscription.TestSubscription.test_enable_manifest_repository_set 
- [ ]  tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_delete_1
- [ ]  tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_1
- [ ]  tests.foreman.cli.test_contenthost.TestContentHost.test_positive_create_8
- [ ]  tests.foreman.cli.test_contentviews.TestContentView.test_delete_cv_version
- [ ]  tests.foreman.cli.test_host.HostTestCase.test_positive_create_1
- [ ]  tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment
- [ ]  tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_delete_1
- [ ]  test_activationkey.TestActivationKey.test_remove_host_collection_by_name_1
- [ ]  tests.foreman.ui.test_gpgkey.GPGKey.test_negative_create_5
- [ ]  test_gpgkey.GPGKey.test_negative_create_4_1
- [ ]  test_gpgkey.GPGKey.test_negative_create_4_1
- [ ]  test_domain.Domain.test_set_domain_parameter_negative_2
- [ ]  test_computeresource.ComputeResource.test_create_resource_negative_2_1
- [ ]  test_activationkey.ActivationKey.test_usage_limit 
- [ ]  test_delete_positive_1_1__fieldset_jdrxvAVp__fieldset_ 
- [ ]  test_repository.DockerRepositoryTestCase.test_sync_docker_repo
- [ ]  test_host.HostsTestCase.test_bz_1120800
- [ ]  tests.foreman.cli.test_host_collection.TestHostCollection
- [ ]  test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_1
- [ ]  test_host_collection.TestHostCollection.test_positive_delete
- [ ]  test_activationkey.TestActivationKey.test_remove_host
- [ ]  test_activationkey.TestActivationKey.test_remove_host_1

**Comment by rplevka** [comment]
Can we close this? the list is quite obsolete.
If needed, we can put together a new (up-to date) list.

**Comment by sghai** [comment]
Yes Please @rplevka
