### ISSUE TITLE
Standardize search functionality

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2930]
The most essential part of current search approach is navigation to necessary page (which is actually performed to get system to some known state). For example:
```
    def search(self, name):
        """Searches existing Organization from UI."""
        Navigator(self.browser).go_to_org()
        return self.search_entity(name, locators['org.org_name'])
```
or
```
    def search(self, name):
        """Searches existing architecture from UI"""
        Navigator(self.browser).go_to_architectures()
        return self.search_entity(name, locators['arch.arch_name'])
```

In case, we want to get rid of search methods from all modules and move to exclusive `search_entity` usage, we should move mentioned navigation to some other level which is obviously not so easy task.
There are few options:
1) Move to test level
Example:
```
with Session(self.browser) as session:
    make_arch(session, name=test_data['name'], os_names=[test_data['os_name']])
    self.assertIsNotNone(self.architecture.search(test_data['name']))
```
changed on:
```
with Session(self.browser) as session:
    make_arch(session, name=test_data['name'], os_names=[test_data['os_name']])
    session.nav.go_to_architectures()
    self.assertIsNotNone(self.search_entity(test_data['name']), locators['arch.arch_name'])
```
pros:
- That is definitely most friendly approach from architecture point of view as navigation logic is separated from search logic.
- Flexible
- Easy to implement
- Reliable and error-tolerant approach

cons:
- A lot of redundant code will be introduced into the system
- Huge amount of testing and re-testing will be needed as we will touch every piece of code in webui

2) Move to base framework level
a) Some kind of correspondance table
```
'Organization' => go_to_org()
'Architecture' => go_to_architectures()
```
```
def search_entity(...):
    Navigator(self.browser).(check our table for required method)
...
```
```
with Session(self.browser) as session:
    self.assertIsNotNone(self.search_entity('Architecture', test_data['name']), locators['arch.arch_name'])
```
pros:
- One phase of re-test will be enough as we do not change tests logic
- Amount of code will be even decreased, so redundancy will not be introduced

cons:
- Mentioned table will look pretty ugly
- Not so flexible solution and not so easy to understand from user perspective

b) Pass entity class name as a part of navigation method name:
```
architecture => go_to_(class_name)()
org => go_to_(class_name)()
```
pros are the same
cons:
- Even less flexible solution as a) as we have more navigation methods than entities in application

3) Don't remove at all, but get search() to one format/look
Let's say that:
```
    def search(self, name):
        """Searches existing Organization from UI."""
        Navigator(self.browser).go_to_org()
        return self.search_entity(name, locators['org.org_name'])
```
is a standard that we should follow, so things like:
```
    def search(self, element_name):
        """Uses the search box to locate an element from a list of elements"""
        element = None
        strategy, value = locators['contentviews.key_name']
        searchbox = self.wait_until_element(common_locators['kt_search'])
        if searchbox:
            searchbox.clear()
            searchbox.send_keys(escape_search(element_name))
            self.click(common_locators['kt_search_button'])
            element = self.wait_until_element((strategy, value % element_name))
        return element
```
should be re-factored to have similar look
pros:
- Changes impact very small area of the code, so no extra efforts for testing required
- Easy to implement

cons:
- We are only improving things, but not solving initial problem.

**Comment by oshtaier** [comment]
Part of #2930

**Comment by abalakh** [comment]
Theoretically, we should choose option 1) or 2) to solve the issue, but proposed approaches have too many cons and are pretty time-consuming to implement, imo they don't worth it. I don't have better ideas though. For now, voting for 3), as it's nice improvement to have and there's really no point in reinventing the wheel in each search function when we have standard `search_entity` func.

**Comment by omaciel** [comment]
@oshtaier if I understood you correctly, I am going to vote for option (3), but to be clear, here's what I want:

*There should be a `search` method in the `base` class for UI "entities" which should be robust and work for the majority of entity searches. This means renaming `search_entity` to `search`.
* All UI entities should call the inherited `search` method
* For the corner/special cases cases where some logic is required, such as passing a different locator depending on the length of the name you're searching for, then the entity should override the `search` method from the `base` class and call its `super`

@elyezer @sghai @kbidarkar @jyejare @sthirugn @JacobCallahan @rplevka @lpramuk  Thoughts?

**Comment by sghai** [comment]
+1 to @omaciel suggestion. I would vote for option (3).

**Comment by sthirugn** [comment]
+1 to Option 3.  Option 3 is the best way and that is why it is used widely now.

I see the following items as part of omaciel's request:

Todo 1:
Rename base-> search_entity() to search()

Todo 2:
Make sure that the overriden search() methods:
* call corresponding Navigator function
* call base -> search() with right options. 

Todo 3: 
Make the base -> search() smart enough to address as many patches which are used in some of the overriden search() methods.  
* There may be some corner cases which still need to be addressed in overriden methods only - which is okay.
* Ofcourse I know that there is a separate issue https://github.com/SatelliteQE/robottelo/issues/2913 to address the character length problem.

Also NACK on Approach 1 and 2 suggested here as the base is not expected to work for all entities.  I agree it should be smart enough but logic to navigate to a specific entity page should be still in the overriden search() methods.

**Comment by oshtaier** [comment]
@abalakh @lpramuk @kbidarkar 
Decided to move with third option. Here is a template that should be used for **all** entities:
```
def search(self, name)
    Navigator(self.browser).go_to_your_entity()
    return super(Your_Entity_Class, self).search(name, locators['your_locator_name'])
```

List of entities to cover:
* [ ] `Activation Key`
* [ ] `Architecture`
* [ ] `Compute Resource`
* [ ] `Config Groups`
* [ ] `Content View`
* [ ] `Discovered Hosts`
* [ ] `Discovered Rules`
* [ ] `Docker Container`
* [ ] `Domains`
* [ ] `Environment`
* [ ] `GPGKey`
* [ ] `HardwareModel`
* [ ] `Host Group`
* [ ] `Hosts`
* [ ] `LdapAuthSource`
* [ ] `Life-cycle environments`
* [ ] `Location`
* [ ] `Medium`
* [ ] `Operating System`
* [ ] `Organization`
* [ ] `OpenScapContent`
* [ ] `OpenScapPolicy`
* [ ] `OpenScapReports`
* [ ] `PartitionTable`
* [ ] `Products`
* [ ] `Puppet Classes`
* [ ] `Registry`
* [ ] `Repositories`
* [ ] `Role`
* [ ] `Subnet`
* [ ] `Subscriptions`
* [ ] `Syncplan`
* [ ] `Template`
* [ ] `Trend`
* [ ] `User`
* [ ] `User Group`

**Comment by abalakh** [comment]
I've created separate branch `ui_search` for this task, as our change will be backwards incompatible and needs to be merged to master only when it's fully complete. Please post your PR's to `ui_search`, not `master`.

**Comment by oshtaier** [comment]
As it is temporary branch, I think one ACK should suffice any pull request in that direction(except merge into master, of course) to not stop development and provide code for re-use to other team members

**Comment by kbidarkar** [comment]
I will work on the below:
a) will first pick up "Activation Keys"
b) Also fix the search locators for length variance issues ( related to issue #2913 )

**Comment by oshtaier** [comment]
@kbidarkar please, look on 'content view' first

**Comment by kbidarkar** [comment]
@oshtaier , ok 'content view' it is. :)

**Comment by oshtaier** [comment]
@kbidarkar Please, look on these entities:
```
Content View
Discovered Hosts
Discovered Rules
Docker Container
Domains
Environment
HardwareModel
Host Group
Hosts
```
@lpramuk Please, look on these entities:
```
LdapAuthSource
Life-cycle environments
Location
Medium
Operating System
Organization
OpenScapContent
OpenScapPolicy
OpenScapReports
```

**Comment by oshtaier** [comment]
Changed branch from `ui_search` on `ui_search_v2`. Please, do rebase from it

**Comment by oshtaier** [comment]
Changed branch from ui_search_v2 on ui_search_v3. Please, do rebase from it
Removed ui_search and ui_search_v2

**Comment by oshtaier** [comment]
@abalakh Will take `subnet` from you, if you don't mind

**Comment by oshtaier** [comment]
@kbidarkar Unchecked `Discovered Rules` as every class should implement  `def navigate_to_entity(self):` and `def _search_locator(self):` methods. Correspondingly, all calls like `Navigator(self.browser).go_to_discovery_rules()` should be substituted by new method
