### ISSUE TITLE
Downstream Failures: List of all downstream failures

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2931]
Combining all the downstream failures into one:
- [ ] tests.foreman.smoke.test_smoke.SELinuxTestCase.test_installer_check_services
- [ ] tests.foreman.smoke.test_api_smoke.TestAvailableURLs.test_get_links
- [ ] tests.foreman.smoke.test_api_smoke.TestSmoke.test_end_to_end
- [ ] tests.foreman.smoke.test_ui_smoke.TestSmoke.test_puppet_install
- [ ] tests.foreman.rhai.test_rhai.RHAITestCase.test_unregister_system_from_rhai
- [ ] tests.foreman.ui.test_adusergroups.ADUserGroups
- [ ] test_syncplan.SyncPlanProductTestCase.test_remove_product
- [ ] test_permission.PermissionsTestCase.test_search_permissions
- [ ] test_contentviewversion.CVVersionTestCase.test_incremental_update_puppet 
- [ ] test_contentviews.TestContentView.test_cv_associate_composite_dupe_modules_negative
- [ ] test_contentviews.TestContentView.test_cv_subscribe_system_puppet
- [ ] test_contentviewfilter.TestContentViewFilter.test_create_cvf_with_description
- [ ] test_contentviewfilter.TestContentViewFilter.test_create_cvf_with_repo_by_name
- [ ] test_contenthost.TestContentHost.test_bugzilla_1154611
- [ ] test_puppetmodule.TestPuppetModule.test_puppet_module_list
- [ ] test_contentviews.TestContentView.test_cv_promote_badenvironment_negative
- [ ]  TestComputeResource.test_create_comp_res_with_console_password_1
- [ ] test_activationkey.TestActivationKey.test_associate_host_1_AbVIlIUAXZ
- [ ] test_operatingsys.OperatingSys.test_negative_create_os_with_same_name_and_version
- [ ] test_template.Template .test_negative_create_template_without_upload
- [ ] tests.foreman.ui.test_adusergroups.ADUserGroups.test_create_external_adusergroup_3 
- [ ] tests.foreman.ui.test_adusergroups.ADUserGroups.test_adusergroup_admin_role 
- [ ] tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_package_remove
- [ ] test_settings.Settings.test_positive_update_general_param
- [ ] tests.foreman.ui.test_adusergroups.ADUserGroups.test_create_external_adusergroup_2
- [ ] tests.foreman.ui.test_adusergroups.ADUserGroups.test_external_adusergroup_roles_delete
- [ ] tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_package_upgrade 
- [ ] tests.foreman.ui.test_settings.Settings.test_positive_update_general_param
- [ ] tests.foreman.ui.test_products.Products.test_remove_prd_1
- [ ] test_hammer.HammerCommandsTestCase.test_hammer_options 
- [ ] test_repository.TestRepository.test_positive_create_6
- [ ] test_activationkey.TestActivationKey.test_remove_host_collection_by_id 
- [ ] test_adusergroups.ADUserGroups.test_external_adUserGroup_additional_user_roles
- [ ] test_contenthost.TestCHKatelloAgent.test_contenthost_package_upgrade 
- [ ] tests.foreman.ui.test_syncplan.Syncplan.test_positive_update_2
- [ ] test_operatingsys.OperatingSys.test_negative_set_os_parameter_1
- [ ] tests.foreman.ui.test_gpgkey.GPGKey.test_positive_delete_2
- [ ] test_adusergroups.ADUserGroups.test_adusergroup_foreman_role
- [ ] test_org.Org.test_remove_hostgroup_1_584
- [ ] tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_promote_rh_1
- [ ] tests.foreman.ui.test_ldapauthsource.LDAPAuthSource.test_create_ldap_authsource_withad_1
- [ ] test_contentviews.TestContentViewsUI.test_delete_version_with_ak
- [ ] test_adusergroups.ADUserGroups.test_create_ldap_auth_withad
- [ ] test_usergroup.UserGroup.test_negative_create_usergroup_3
- [ ] test_positive_update_activation_key_with_rh_product_1_50212913
- [ ] test_activationkey.ActivationKey.test_associate_product_3
- [ ] tests.foreman.api.test_permission.PermissionsTestCase.test_search_permissions
- [ ] tests.foreman.ui.test_products.Products.test_remove_prd_1
- [ ] tests.foreman.cli.test_subscription.TestSubscription.test_manifest_refresh
- [ ] test_contentviews.TestContentViewsUI.test_delete_version_non_default 
- [ ] test_operatingsys.OperatingSys.test_positive_set_os_parameter_1

**Comment by sthirugn** [comment]
Latest run report:
Combining all the downstream failures into one:
*Smoke:*
- [ ] None

*API:*
- [ ] <nose.suite.ContextSuite context=CVPublishPromoteTestCase>:setup
- [ ] test_contentview.ContentViewTestCase.test_cv_associate_composite_dupe_modules_negative
- [ ] tests.foreman.api.test_contentview.ContentViewTestCase.test_cv_clone_within_diff_env
- [ ] tests.foreman.api.test_contentview.ContentViewTestCase.test_cv_clone_within_same_env
- [ ] tests.foreman.api.test_contentviewversion.CVVersionTestCase.test_incremental_update_puppet
- [ ] tests.foreman.api.test_discoveredhost.Discovery.test_upload_facts
- [ ] test_docker.DockerContainersTestCase.test_create_container_compute_resource_power
- [ ] test_docker.DockerContainersTestCase.test_create_container_compute_resource_read_log
- [ ] tests.foreman.api.test_foremantask.ForemanTasksIdTestCase.test_summary
- [ ] tests.foreman.api.test_product.RepositorySetsTestCase.test_repositoryset_disable
- [ ] tests.foreman.api.test_product.RepositorySetsTestCase.test_repositoryset_enable
- [ ] <nose.suite.ContextSuite context=CVVSearchTestCase>:setup
- [ ] tests.foreman.api.test_repository.RepositoryTestCase.test_update_contents

*CLI:*

*UI:*

**Comment by sthirugn** [comment]
This is not relevant anymore. Closing.

**Comment by elyezer** [comment]
:+1:
