### ISSUE TITLE
Refactor UI module for Docker container

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2946]
I feel that there are two areas that should be re-visited and refactored for the UI module that handles Docker containers:
1. We have methods `_configure_orgs` and `_configure_locations` which are very similar with only 1 value being different. In my opinion these 2 should be merged into a more generic method;
2. The `create` method for `class Container` uses a logic that is repeated a few times in order to 'walk' through a Dokcer container 'wizard'. I don't have a suggestion as to how make it better and simpler yet, but I feel that we need to work on it soon-ish.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
