### ISSUE TITLE
Remove redundant ui tests

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2954]
Item 1: https://github.com/SatelliteQE/robottelo/pull/2953#issuecomment-151911699 - There are UI tests which tests for positive name values and also max length values.

**Comment by sghai** [comment]
All tests have been renamed with a correct naming format and name clearly state what exactly a test case does so now tests named like:
`test_positive_create_with_name`
`test_positive_create_with_long_name`

And both tests are valid. I'm closing this issue for now. If you come across any specific redundant tests then please raise a new issue.
