### ISSUE TITLE
Add proper 'Save As...' dialog handler

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2960]
In case you try to save any file using browser window flow, you will need to handle 'Save As...' dialog which is not JavaScript alert, Browser pop-up or Browser message, but operation system call which cannot be processed by Selenium WebDriver due obvious architecture reasons.

Find ideas or approaches to resolve mentioned issue in https://github.com/SatelliteQE/robottelo/issues/2910

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
