### ISSUE TITLE
Either eliminate ddt from MetaCLITest or migrate from MetaCLITest to CLITestCase

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2968]
Affected modules:
* [x] `tests/foreman/cli/test_architecture.py` @elyezer
* [x] `tests/foreman/cli/test_domain.py` @elyezer
* [x] `tests/foreman/cli/test_environment.py` @elyezer
* [ ] `tests/foreman/cli/test_hostgroup.py` @elyezer
* [ ] `tests/foreman/cli/test_model.py` @elyezer

**Comment by omaciel** [comment]
Huge :+1: from me!

**Comment by elyezer** [comment]
I'm tracking my changes here https://github.com/SatelliteQE/robottelo/compare/SatelliteQE:master...elyezer:fix-2968
