### ISSUE TITLE
Update docstring for robottelo.helpers.generate_strings_list

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#2970]
The docstring for `robottelo.helpers.generate_strings_list` is outdated and does not contain information for the all arguments that it accepts. Currently, only parameter `len1` is documented but `remove_str` and `bug_id` are not.

I further recommend that `len1` be changed to `size` as it is in my humble opinion a better name to describe the true meaning for the argument. Note that you'll have to make sure that every call to `generate_strings_list` will have to be checked to make sure that all occurrences of `len1` are changed to `size`.

**Comment by sthirugn** [comment]
Closed in https://github.com/SatelliteQE/robottelo/pull/3002
