### ISSUE TITLE
Improve ui org tests

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2971]
Improvements are suggested in https://github.com/SatelliteQE/robottelo/pull/2967

**Comment by renzon** [comment]
Comparing test time to check how much will we gain on time execution. Multiple orgs creation on docker, sat 6.3:

Multiple Orgs creation for domain remove (199.98 s):
```console
/home/renzo/PycharmProjects/venvs/robottelo/bin/python /home/renzo/bin/pycharm-2016.3/helpers/pycharm/pytestrunner.py -p pytest_teamcity /home/renzo/PycharmProjects/robottelo/tests/foreman/ui/test_organization.py "-k OrganizationTestCase and test_positive_remove_domain"
================== 1 passed, 32 deselected in 199.98 seconds ===================
```

Single Orgs creation for domain remove (143.56:

```console
================== 1 passed, 32 deselected in 143.56 seconds ===================
```
And with only one org is created for all remove test, time spent will be even less overall.
