### ISSUE TITLE
Check documentation build on Travis

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#2973]
By dropping MetaCLITestCase (depends on #2968), we will be able to build the documentation on travis since the warnings caused by the usage of MetaCLITestCase will not be raised anymore.

With this new checking, we can ensure that no one will break documentation generation on every single pull request sent.

@Ichimonji10 will definitely like this :smile:

**Comment by Ichimonji10** [comment]
Yes, I do like this. :smile:
