### ISSUE TITLE
End_to_end test improvements

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2979]
- [ ] Remove Test redundancy
- [ ] Improve docstring
- [ ] Perform UI smoke test with newly created user

**Comment by JacobCallahan** [comment]
I propose that we consolidate all, but the API link tests into one main smoke test. Most of the tests perform the same steps, but will add one or two things. We can add each unique piece to the main test and remove the others. The name is still up for debate (e.g. test_smoke vs test_end_to_end).

**Comment by JacobCallahan** [comment]
The newly proposed steps for API and UI are:
        1. Create a new organization
        2. Clone and upload manifest
        3. Create two new lifecycle environments
        4. Create a custom product
        5. Create a custom YUM repository
        6. Create a custom PUPPET repository
        7. Synchronize both custom repositories
        8. Sync a RedHat repository
        9. Create a new content view
        10. Associate all repositories to new content view
        11. Publish content view
        12. Promote content view to both lifecycles
        13. Create an activation-key
        14. Add Red Hat product to activation-key
        15. Create a new libvirt compute resource
        16. Create a new subnet
        17. Create a new domain
        18. Create a new hostgroup and associate previous entities to it
        19. Create new virtualmachine
        20. Pull rpm from Foreman server and install on client
        21. Register client with foreman server using activation-key
        22. Install rpm on client

UI will also include the puppet-specific pieces.

**Comment by sthirugn** [comment]
Update: @JacobCallahan is done with api code and he will try testing soon and submit a PR

**Comment by sghai** [comment]
Smoke tests are now  renamed to end_to_end tests so updated the description. However now we can extend end_to_end tests with host provisioning etc.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
