### ISSUE TITLE
[In Progress] Create different test tiers in robottelo

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#3048]
Proposed Approaches:
* Approach 1 [sthirugn]:  Create unittest test suite for different tiers:
  * Pilot project: https://github.com/sthirugn/tiertest
  * Advantages: https://github.com/sthirugn/tiertest#advantages
  * Use testimony tags to populate the test runner: https://github.com/SatelliteQE/testimony/blob/master/README.rst
* Approach 2 [omaciel]: Using pytest mark:
* Approach 3 [unassigned]: Using nosetest attr:

More info to come.

**Comment by JacobCallahan** [comment]
I currently am in favor of Approach 2. It is the most flexible, and easier to switch to of the three options.

**Comment by sthirugn** [comment]
ping @SatelliteQE/quality-engineers @SatelliteQE/robottelo-automation

**Comment by oshtaier** [comment]
I am fine with both solutions (1 or 2) and cannot find serious advantages of one against another.
First approach is better in terms of readability and usability, second is more flexible. Fine to work with any of them

**Comment by abalakh** [comment]
* Approach 4 : Using custom decorator, which will decorate with both pytest mark: and nosetest attr:

Voting for 4) if it's acceptable, if not - option 2).

**Comment by elyezer** [comment]
@abalakh how to differentiate between them?

**Comment by abalakh** [comment]
@elyezer i was hoping both attributes and marks can co-exist, as they're tagging in a different ways. If they didn't conflict, we would be able to tag with both (if pytest can be imported - mark the test, if nose is present - add attribute) and simply use any runner. I've just tried to test that and it seems that they're incompatible. That breaks the idea and yes, in this case we need to differentiate between them somehow. If there's no easy way to determine what runner is executing the test, then it's probably a bad option.

**Comment by elyezer** [comment]
@abalakh the edge case is also when both are installed... because I may have a venv that I use for my day to day python and have both runners installed due to different project requirements. With all this said, I think we should adopt py.test only and avoid additional work needed to support both.

**Comment by omaciel** [comment]
Closing it as we have decided to use `Approach 2`, aka py.test marks.
