### ISSUE TITLE
Create new test or correct existing one to cover BZ 1283941

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3060]
BZ issue: https://bugzilla.redhat.com/show_bug.cgi?id=1283941

We have couple of tests for OS description functionality, but they have been written in a way that omit most obvious scenario. Needs to revise them or create one more test specific for that approach

**Comment by omaciel** [comment]
Redmine issue is http://projects.theforeman.org/issues/12554

**Comment by oshtaier** [comment]
After deep investigation, we get to the fact that mentioned behavior is expected one. All details can be reviewed in https://github.com/theforeman/foreman/pull/2925.

**Comment by oshtaier** [comment]
And our test automation scripts work as they should
