### ISSUE TITLE
Changes required to fix discovery tests as per new infra.

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#3063]
I was trying to fix setup related to host provisioning and host discovery. But looks like now decent changes are required as per new infra. Also, earlier we were creating host on Satellite itself by enabling nested virt. It means we were using Satellite server as hypervisor. But now plan is to use some other external compute-resource. 

I'm planning to use external libvirt. 

what all changes are required ?

1. Like provisioning server, we may need to define the libvirt_server setting along with image_dir in robottelo properties file as well as in jenkins.

2. Since external libvirt host is accessible via ssh. So we need to configure ssh key-pairs between Satellite server and hypervisor.

3. For host_discovery, the first variable we need is 'bridge_interface' . This is based on the different vlan configurations. Currently we have four bridges based on different distros.
I'm not sure best place to fetch/configure this but as per discussion with @kbidarkar, I think we can fetch this with hostname. Please let us know if anyone has any other way to get that ?

4. we may also required to fetch Gateway/Subnet etc depending on selected bridge interface.

Note: I tested manually host discovery by configuring external libvirt server along with our Satellite automation rhel67 server.

**Comment by kbidarkar** [comment]
@sghai  will be working on 1) and 2) 

I will be working on 3) and 4)

**Comment by sghai** [comment]
Thank you @kbidarkar for picking 3) and 4).

**Comment by sghai** [comment]
1) and 2) are covered in  #3064 and https://github.com/SatelliteQE/automation-tools/issues/264

**Comment by sghai** [comment]
This issue is well covered and implemented. Thank you @kbidarkar for helping out to populate Vlan networking stuff. It was a great help.

Closing this issue.
