### ISSUE TITLE
Improve system unregistration check for RHAI test

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#3065]
A hard sleep of 30 seconds is being added to `test_unregister_system_from_rhai` by #3057. But as we all know using that is not a good thing, with that said, let's try to find out a better way to check if the system was really unregistered.

**Comment by elyezer** [comment]
@anarang are Robottelo's RHAI tests valid still?

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
