### ISSUE TITLE
Base().search method should support search queries

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#3066]
in current design, `Base.search()` method only accepts the 'value' to be searched and the search query is hardcoded to `{0} = {1}` where {0} is a search key attached to the entity object.
With the `scoped search` feature, we start to support more complex [queries](https://github.com/wvanbergen/scoped_search#query-language), with a number of different operators.

I could create a standalone method to submit the raw queries, but that would make code quite redundant. Therefore I think we might want to extend the current `search()` method.

One of the ways would be to move whole logic (navigating to the page, locating the search form, sending the keys to the search field) to the generic `search_raw` method.
and call it from inside the `search` method, which is just a specific case of the query.

**Comment by abalakh** [comment]
It will result in something like this:
```python
    self.search_key = 'name'

    def search_raw(query):
        # navigate to entity
        # type 'query' into search field
        # perform search
        # return result

    def search(element_name):
        query = '{} = {}'.format(self.search_key, element_name)
        return search_raw(query)
```
As a result, our `search()` will work as it was before, so nothing to fix/update, plus we'll receive the ability to use custom search queries:
```python
repo.search('test_repo')
repo.search_raw('name = test_repo OR label = another_repo')
```
So I'm voting for this approach :)
Of course, there're a lot of ways to do that, for example with separate `search_query()` method, or optional `query=` argument, so feel free to share your thoughts.

**Comment by elyezer** [comment]
I suggest a different naming like:

```python
def search(query):
    """Base search functionality accepting all queries."""

def search_by_name(name):
    """Search using the query "name = {}".format(name)."""

def search_by_...(...):
    """So on and so forth."""
```

**Comment by omaciel** [comment]
I like @elyezer suggestion as it also matches some existing designs 'out there' :)

**Comment by rplevka** [comment]
ok, What would you suggest should be the returning value of the `search()` method?
Since we're not asking for locating any single particular element, I guess we should simply return a reference to the results table. The question is, whether returning a `WebElement` object is enough. We could also parse it and return a dictionary representation of the table - however, this approach (although I think is correct) would be inconsistent with the return values of other similar methods (such as `search_by_name` which returns a reference to a `WebElement` object).

**Comment by elyezer** [comment]
@rplevka excellent observation! I see two options 1) is to return a reference to an object that maps the table result and can also handle pagination or 2) to return a list with the results (a list of WebElements). Why return a list on all methods is because even though I'm searching by name I can search for things like `My Amazing Entity 1` and `My Amazing Entity 2` if I use `search_by_name('My Amazing')` it should return both elements or a mapping to the results.

On tests that expect just one result when searching for the complete name, then an assertion can be added to make sure the length of the results is always 1. Also returning a list on search is a common pattern on different pieces of software and also APIs.

**Comment by elyezer** [comment]
If we are expecting to have methods that will return a single object, then we should thing on different nomenclature like `get_...`.

**Comment by rplevka** [comment]
@elyezer,
- ++ on `get_*` nomenclature rule
- a list of `WebElement` instances is much easier to be accomplished as `WebDriver` directly support such methods (`find_elements_by_*` instead of `find_element_by_*`). Anyway, I believe we mostly rely on `wait_until_element` methods, which uses the singular form. I believe this method should return a list of elements instead of a single element. Trying to refactoring this might be quite challenging as there are many methods and tests that use it.

**Comment by sthirugn** [comment]
+1 to returning list of webelement objects.

**Comment by renzon** [comment]
After discussing with @rplevka and @elyezer I am going to make this:
1. Implement helper _search(property, value) to be used by subclasses on all their search_by* methods
2. Refactoring current search to get_by* which return single webelement or raises exception with more then one result is available
3. removing search_key class attr from base

**Comment by renzon** [comment]
Closing this in favor of #3906
