### ISSUE TITLE
Move several helper functions from CLI/import to a separate module

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#3081]
created from https://github.com/SatelliteQE/robottelo-ci/issues/79

**Comment by omaciel** [comment]
@rplevka @lpramuk ping?

**Comment by lpramuk** [comment]
What is the reasoning behind this? We want that testcase contains only  test_*() methods and data generation funcs? Right?

**Comment by rplevka** [comment]
after checking all the methods in our `test_import.py` module,
I came to conclusion, that only method applicable to the query would be `build_csv_file()`.
All the others are transitions or data specific and I don't see why they should go anywhere else.

The only possible place for them might be the `Import` class (as static methods) but we would like to keep the class as an object representation of the actual hammer command.

**Comment by omaciel** [comment]
I would like to keep logic separate from test cases, as much as possible

**Comment by rplevka** [comment]
this has been deprecated for a really long time (import module is gone)
