### ISSUE TITLE
Update test-cases which use sattools repo from CDN to point to custom repo for non-cdn job

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#3093]
All the robottelo tests which sync sattools repo from CDN, needs to be updated to point to latest custom sattools repos, automatically depending upon the jobs.

This effort required updating stuff for all the below jobs:
a) API
b) CLI 
c) UI
d) rhai
e) longrun
f) smoke.

**Comment by kbidarkar** [comment]
I think we can get started with smoke jobs.

**Comment by elyezer** [comment]
@kbidarkar when you have a chance, please make sure that this issue still valid.

**Comment by sghai** [comment]
@kbidarkar : is this still a valid issue ?

**Comment by kbidarkar** [comment]
@sghai , yes, this issue is very much valid, we need a way , so that non-CDN jobs can pick up the latest sat-tools repos.

**Comment by kbidarkar** [comment]
We can decide to close this issue in favour of issue #4429

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
