### ISSUE TITLE
Get to single delete() method usage across the code

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3101]
Remove delete_entity() method and get to similar approach that was used for search() procedure in #2930

**Comment by lpramuk** [comment]
+1 
tests.foreman.ui.test_org:Org.test_positive_delete_bz1225588 is failing in delete_entity as it check for result within itself - ugly. We better check the result in tests.

**Comment by oshtaier** [comment]
Needs to apply similar approach for name length verification (like to use another locator for names longer than 32 symbols)

**Comment by oshtaier** [comment]
And consequently get rid of all `generate_strings_list(length=8)` statements for all update and delete operations

**Comment by elyezer** [comment]
@oshtaier please update the status when you have a chance. Thanks in advance.

**Comment by oshtaier** [comment]
@elyezer I have the vision on approach that we can use here, but as usually we need time on that. Currently we have too strict requirements for coverage and I cannot switch. Basically that task has lower priority with other improvements as impact of current issue is minimal and mentioned approach can be changed significantly with any upcoming changes to WebUI.

**Comment by elyezer** [comment]
@oshtaier thanks. I thought the reference PR that is merged could have in some way fixed this. Yes adding coverage is high priority now.

**Comment by oshtaier** [comment]
@elyezer Yes, that was first part of the fix, but still we don't have such nice single point for delete() method as we have for search() method
