### ISSUE TITLE
Naming convention for test modules and test case class names

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#3102]
Since we are coming up with a naming convention for tests on #3083, we should do the same for test modules and test case class names.

Initial proposal is:

For test modules, they should start with `test_`, followed by the entity name on singular and entity name words separated by `_`. It also should not abbreviate the entity name. Examples:

* test_architecture
* test_content_view
* test_content_view_version
* test_organization

For test case class names, they should end with the suffix `TestCase` and for classes named after the entity they should have the entity name on singular CamelCases. Entities names should not be abbreviated. Example:

* OrganizationTestCase
* ContentViewTestCase
* ContentViewVersionTestCase
* NonEntityRelatedTestCase

PS.: All test cases classes must inherit from `robottelo.test.TestCase` or one of its subclasses like `APITestCase`, `CLITestCase` and `UITestCase`.

**Comment by sthirugn** [comment]
I agree with the suggestion except the following:
* Do not hyphenate the entity name because it can change the  meaning of the module.  Example I like: `test_contentview.py` instead of `test_content_view.py`.
  - Similarly I like `test_activationkey.py` instead of `test_activation_key.py`
* hyphenate after the entity name, if needed. Example: `test_host_system_unification` (here `host` is the entity)

**Comment by omaciel** [comment]
I'd also like to standardize the actual names of modules across the interfaces. For example:

* api/test_organization.py
* cli/test_org.py

so my proposal is to always write out the full name for the entity.

**Comment by elyezer** [comment]
:+1: for @sthirugn and @omaciel suggestions.

**Comment by oshtaier** [comment]
Maybe we can put more context for names like `rhci`, `rhai`, `rhsm` and etc

**Comment by sthirugn** [comment]
more context where?

**Comment by oshtaier** [comment]
I understand that names like `red_hat_access_insight` is too long, but maybe we can use something similar

**Comment by sthirugn** [comment]
do you mean for test modules or test cases or anything else?

**Comment by oshtaier** [comment]
ohh, I am sorry. I mean test folders names

**Comment by oshtaier** [comment]
and also we have module with name `test_rhsm.py`
