### ISSUE TITLE
Include ability to run tests for specific features

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#3103]
For example, I need to 
- quickly test _manifest_ related tests
- quickly test _provisioning_ related tests

Note: that in the given examples above, the `manifest` related tests or the `provisioning` related tests may live in different modules in robottelo, but I need a quick way to test it.  May be we can use py.test mark for this.  But this needs more research.

**Comment by omaciel** [comment]
I believe that py.test -m manifest would help

**Comment by rochacbruno** [comment]
@omaciel @sthirugn can we close this?
