### ISSUE TITLE
Update test names according to new naming convention (#3083)

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#3127]
We need to update existing API, CLI and UI test names according to new naming convention, described in #3083.
Approximate tests amount per interface is:
1) API - 460
2) CLI - 859
3) UI - 659

Let's split the task like that:
@abalakh (~534 tests)
* API tests (all)
* Part I of UI tests:
```
test_activationkey.py
...
test_contentsearch.py
```

@oshtaier (~581 tests)
* Part II of UI tests:
```
test_contentview.py
...
test_usergroup.py
```

@sthirugn (~440 tests)
* Part I of CLI tests:
```
test_abrt.py
...
test_import.py
```

@omaciel (~419 tests)
* Part II of CLI tests:
```
test_installer.py
...
test_user.py
```

**Comment by omaciel** [comment]
Rock on!

**Comment by oshtaier** [comment]
@omaciel Could you please, leave `test_user.py` for me? I am planning (or actually already started) to work on stubbs for that module and it is more convenient for me to work with names right away. That means that task will be closed a little bit later, but this week for sure

**Comment by omaciel** [comment]
Sure thing.


Sent on the new Sprint Network from my Samsung Galaxy S®4

-------- Original message --------

**Comment by abalakh** [comment]
@sthirugn if you don't mind, i'll take `cli/test_gpgkey.py` from you. I was checking stubs there, saw 20+ invalid onces so i'd probably remove them + maybe add some coverage. That means i could easily rename remaining tests as I'm already working with that module :)

**Comment by sthirugn** [comment]
sthirugn:
tests/foreman/cli
- [x] test_abrt.py
- [x] test_activationkey.py
- [ ] test_architecture.py
- [x] test_capsule_installer.py
- [x] test_capsule.py
- [x] test_computeresource.py
- [ ] test_contenthost.py
- [ ] test_contentviewfilter.py
- [ ] test_contentviews.py
- [ ] test_discovery.py
- [ ] test_docker.py
- [ ] test_domain.py
- [ ] test_environment.py
- [ ] test_errata.py
- [ ] test_fact.py
- [ ] test_globalparam.py
- [x] test_gpgkey.py - @abalakh 
- [ ] test_hammer.py
- [ ] test_host_collection.py
- [ ] test_host_system_unification.py
- [ ] test_host.py
- [ ] test_hostgroup.py
- [ ] test_import.py

**Comment by sthirugn** [comment]
Looks like this is all addressed now. Closing the issue.
