### ISSUE TITLE
Move API repository set tests to separate module

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#3148]
`class RepositorySetTestCase` is stored inside `test_product.py` right now. For UI/CLI we have separate module `test_repository_set.py` for that purpose. Need to make API consistent with other interfaces.

**Comment by elyezer** [comment]
@abalakh can you please update the status?

**Comment by abalakh** [comment]
@elyezer sure, i'm taking this issue, will try to close it this week.

**Comment by elyezer** [comment]
@abalakh thanks.
