### ISSUE TITLE
Improve test data processing for User entity

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3178]
We have a lot of entries in code like:

```
include_list = [gen_string("alphanumeric", 100)]
    for login in valid_usernames_list() + include_list:
```

or

```
include_list = [gen_string("alphanumeric", 50)]
    for firstname in valid_usernames_list() + include_list:
```

It will be good to simplify that to one method and apply it for all necessary test cases

Also, it will be nice to get rid of `email.replace('"', r'\"').replace('`', r'`')` and escape such exceptions on a data level, especially taking in account that we have only one occurrence of that specific situation

**Comment by abalakh** [comment]
:+1: 
Yep, basically datafactory is generating usernames with default length of 10 characters. We need to investigate and add boundary values and then we can drop workarounds like 
```python
include_list = [gen_string("alphanumeric", 100)]
    for login in valid_usernames_list() + include_list:
```

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
