### ISSUE TITLE
Update existing automation to support pxe-less discovery

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#3202]
To support pxe-less discovery, we have to boot the unknown host via modified discovery ISO instead of PXE.  ISO needs to be rebuilt with some extra kernel options. These options includes
- server name
- gw
- dns
- custom facts

These options helps to perform discovery in an unattended manner. Use won't need to pass these options interactively.
Since our infrastructure is based on different vlans. So `gw`and `server` name will vary based on the vlan configuration. We have two ways to handle this:

1. Build the ISOs and place them on libvirt server  ( one time task, but we may need to rebuild again on new release). we will just pass the ISO name as exported parameter.

2. Build the ISO on every automation run based on different vlan configurations.

I would prefer to go with `option 1` now. Later, we can move to `option 2`.

Any suggestions/feedback ?

**Comment by sghai** [comment]
Raised PR https://github.com/SatelliteQE/robottelo/pull/3204 that implements `option 1`.

**Comment by sthirugn** [comment]
ACK for option 1.

**Comment by sghai** [comment]
Support for pxe-less discovery is added with option1. Thank you @sthirugn for Voting option1. I'm closing this issue for now.
