### ISSUE TITLE
Update jenkins for new pxe-less discovery tests.

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#3206]
From  https://github.com/SatelliteQE/robottelo/pull/3204 :

Please note that robottelo-ci and robottelo.properties.sample still needs to be updated with discovery_iso parameter. Idea here is to share the approach. 
I'll update robottelo-ci and sample-properties file, If all changes defined in this PR looks good to reviewers.

**Comment by sghai** [comment]
Perfect.. thanks for filing the issue.

**Comment by sghai** [comment]
Raised PR  https://github.com/SatelliteQE/robottelo-ci/pull/108 for robottelo-ci changes. Exported the ISO name via Provisioning variables and updated the robottelo properties with same parameters in Jenkins.

robottelo.properties.sample file is also updated with PR https://github.com/SatelliteQE/robottelo/pull/3210

**Comment by sghai** [comment]
Most of the changes around PXELess feature has already been done in Jenkins in referenced PRs and in https://github.com/SatelliteQE/robottelo-ci/pull/114. Closing this issue.
