### ISSUE TITLE
Refactor VirtualMachine class to accomodate libvirt changes required for discovery from LibvirtGuest class

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#3209]
PR https://github.com/SatelliteQE/robottelo/issues/3206 handles the support of pxe and pxe-less discovery via LibvirtGuest class. Idea is to handle the same via VirtualMachine class to avoid code duplication.

Here is the suggestion from @elyezer 

`This code is very similar to the virtual machine one. We may consider to create a base virtual machine class that is able to handle Libvirt and snap-guest virtual machines.

We can have a base VirtualMachine class that offers the basic API (e.g. create and destroy and the context manager implementation). Also the init should have common arguments and new ones can be added after them. `

**Comment by elyezer** [comment]
:+1:

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
