### ISSUE TITLE
Implement test to add a puppet-module to content-view

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#3219]
- Make sure pyuppet-module should be added via repo URL.
- Repo URL should be unique ( it means the module provided by URL should never been used by any other test)

**Comment by elyezer** [comment]
@sghai #3217 is merged, can this be closed? Or what is still missing?

**Comment by sghai** [comment]
This test needs to be implemented with a unique puppet repo which is not being used by our robottelo code base. I'll implement this as soon as I get a puppet repo with a new module.

**Comment by elyezer** [comment]
@sghai thank you.

**Comment by rplevka** [comment]
@sghai, if needed, I can create a unique repo at my fedorapeople public space. I already use it for some other fake repositories

**Comment by sghai** [comment]
Lets prioritize this for next sprint.
