### ISSUE TITLE
Remove / move smoke tests to tier tests

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#3226]
Since we changed to tier testing, smoke test suite is unusable now.  We need to review the smoke test cases and remove the unwanted ones and move the required ones to specific tiers.

**Comment by elyezer** [comment]
#2979 should be done before doing this.

**Comment by sghai** [comment]
All smoke tests have been renamed to end_to_end tests and the referenced issue #2979 is around end_to_end test improvements. We will try to cover this in next automation sprint.

**Comment by sghai** [comment]
closing this issue for now.
