### ISSUE TITLE
Skip UI host tests if required settings is not available

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#3236]
On file tests/foreman/ui/test_host.py line 71 `settings.rhel6_repo` is being accessed and if that information is not available that value will be `None`. With that said the test will fail to sync since null url will be provided.

Should be checked all places that this setting is being used and also for the rhel7 setting.

**Comment by sghai** [comment]
Lets fix this in next sprint.

**Comment by svtkachenko** [comment]
Looks like this issue is not relevant anymore as `settings.rhel6_repo` is not used anymore in `tests/foreman/ui/test_host.py`.
> all places that this setting is being used 

can be checked in scope of #3006 that seems more general.
