### ISSUE TITLE
Implement Stubs for Smart Class Parameter

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#3240]

**Comment by jyejare** [comment]
Initial Draft of Test Stubs in PR #3239 .

**Comment by elyezer** [comment]
@jyejare #3239 is merged, what next? This issue can be closed?

**Comment by jyejare** [comment]
Yes, We can close this as Test Stubs for API, CLI and UI for SC-Param are added.

Closing this.
