### ISSUE TITLE
Run supported Tier TestCases on Upgraded System.

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#3257]

**Comment by elyezer** [comment]
@jyejare this sounds more a robottelo-ci or automation-tools issue. We should probably move to some of those repos.

**Comment by sghai** [comment]
Agreed what @elyezer said.

**Comment by sghai** [comment]
Closing this here and filed new issue here https://github.com/SatelliteQE/robottelo-ci/issues/425
