### ISSUE TITLE
Add CRUDs for missing fields for API Hosts entity

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#3270]
#3253 introduced CRUDs for most fields for API Hosts. However, following fields were skipped:
- [ ] compute_attributes
- [ ] capabilities
- [ ] progress_report_id
- [x] provision_method
- [x] image_id
- [x] host_parameters_attributes
- [ ] realm_id
- [x] puppet_class_ids
- [x] owner_type
- [x] content_facet_attributes

Need to add tests for these fields too.

**Comment by elyezer** [comment]
@abalakh please check on the list what #3253 have covered from this issue. Thank you in advance.

**Comment by abalakh** [comment]
@elyezer #3253 haven't covereded anything from this list. #3253 covered 16 of 25 hosts fields, remaining 9 are tracked here.

**Comment by elyezer** [comment]
@abalakh thanks for the clarification.

**Comment by svtkachenko** [comment]
Most of the fields were covered in #4118, however `compute_attributes` and `realm_id` real environment setup. `compute_attributes`  requires access to compute resource and virtual machine that is created on on this resource. `realm_id` requires capsule with configured realm feature.

Unfortunately, I'm not sure what is `capabilities` and `progress_report_id` as documentation is very limited.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
