### ISSUE TITLE
Improve validation for negative scenarios for API tests

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3273]
At that moment, we only verify that expected error is raised in case we try to create entity with invalid parameters. For example:

```
with self.assertRaises(HTTPError):
    entities.Organization(name=name).create()
```

or

```
with self.assertRaises(HTTPError):
    entities.ContentView(name=name).create()
```

It will be nice if we also verify that entity was not actually created despite any exceptions that we get

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
