### ISSUE TITLE
Augment test coverage for sync plan functionality

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3276]
It is really nice idea to create sync plans for future period of time (like in 5 minutes from current time) and try to assign that plan to the product. After that it is necessary to verify that product repositories are actually synchronized.

Also, it is necessary to verify that sync plans interval functionality (at least, 'hourly') is really working. That means that we need to check that product is re-synchronized in one hour after first sync is happened

**Comment by rplevka** [comment]
Could we possibly use a docker container as isolated ecosystem and simply mess with the system date&time?
