### ISSUE TITLE
Set up 'katello_upstream' branch to reflect the differencies between upstream and downstream

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#3283]
With 6.2 behind the door, we might want to start to test katello_upstream more intensively to reflect all the changes and updates that will land downstream.
There are already some visual/functional differences causing the automation to fail on katello_upstream.
For the sake of modifying the code for upstream while keeping the original code for downstream I propose creating a standalone branch which will hold all the differences, which could be merged with master when 6.2 lands downstream.

I've already set up such branch on my fork:
https://github.com/rplevka/robottelo/tree/katello_upstream

Could we pull it upstream so we can use it with jenkins job?

**Comment by sthirugn** [comment]
+1 for the upstream branch creation.  Once we branch or tag 6.1 from master, we can merge this new upstream branch to robottelo master.

**Comment by oshtaier** [comment]
Please, let me know if you need any help with tests failures analysis

**Comment by elyezer** [comment]
The branch can be created right now and be rebased against master to make sure that the start point is gonna be when we stop the 6.1 cycle.

**Comment by rplevka** [comment]
Not sure, whether this is still planned as we already have multiple branches to take care of.

**Comment by rplevka** [comment]
closing this as fixed since we consider `master` as our upstream branch
