### ISSUE TITLE
Fix all discovery related tests

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#3288]
Following tests have been failing and I believe just because of timing issue. I may need to increase the time..
- tests.foreman.ui.test_discoveredhost.DiscoveryTestCase.test_positive_refresh_facts_pxe
- tests.foreman.ui.test_discoveredhost.DiscoveryTestCase.test_positive_add_fact_column
- tests.foreman.ui.test_discoveredhost.DiscoveryTestCase.test_positive_pxe_based_discovery
- tests.foreman.ui.test_discoveredhost.DiscoveryTestCase.test_positive_delete
- tests.foreman.ui.test_discoveredhost.DiscoveryTestCase.test_positive_delete_from_facts
- tests.foreman.ui.test_discoveredhost.DiscoveryTestCase.test_positive_delete_multiple

```
tests/foreman/ui/test_discoveredhost.py:124: in test_positive_pxe_based_discovery     self.assertIsNotNone(self.discoveredhosts.search(hostname)) 
E   AssertionError: unexpectedly None
```

**Comment by sghai** [comment]
Locally tests are working fine..

```
[sghai@dhcp193-30 robottelo]$ nosetests -c robottelo.properties  -m test_positive_refresh_facts_pxe /home/sghai/QE/robottelo/tests/foreman/ui/test_discoveredhost.py
.S
----------------------------------------------------------------------
Ran 2 tests in 193.452s

OK (SKIP=1)
```

**Comment by sghai** [comment]
Raised PR: https://github.com/SatelliteQE/robottelo/pull/3289

**Comment by sghai** [comment]
```
[sghai robottelo]$ nosetests -c robottelo.properties  -m test_positive_add_fact_column /home/sghai/QE/robottelo/tests/foreman/ui/test_discoveredhost.py
.
----------------------------------------------------------------------
Ran 1 test in 221.175s

OK
```

**Comment by elyezer** [comment]
@sghai since #3289 is merged, can this be closed?

**Comment by sghai** [comment]
Tests works fine locally but failed in jenkins while searching the discovered host. So I would like to keep this open until next run.

**Comment by elyezer** [comment]
@sghai sounds like a plan.

**Comment by omaciel** [comment]
@sghai says that we can close this.

**Comment by sghai** [comment]
Closing this as I recently tested all UI discovery tests w/ PR #4090
