### ISSUE TITLE
CLI Import - automation run in concurrent threads breaks asserts

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#3291]
For asserts we cannot rely on testing environment isolation as other thread can change testing environment in the meantime.

Example: test negative import organizations
- list orgs
- try to import org (negative: No action taken.)
- list orgs
- assert org lists are identical [FAIL]

**Comment by rplevka** [comment]
we decided with @elyezer to implement a standalone job for transitions job:

https://github.com/SatelliteQE/robottelo-ci/issues/230

- will remove the `@tier` decorators after jenkins job is prepared

**Comment by elyezer** [comment]
It is not gonna be a standalone job, but an additional step on tier1 job which will run transitioning tests in serial and then Jenkin will join both results tier1 and transitioning when doing the report.

**Comment by rplevka** [comment]
@elyezer :+1:

**Comment by elyezer** [comment]
https://github.com/SatelliteQE/robottelo-ci/pull/231 and #3366 are merged. We are safe to close this now.
