### ISSUE TITLE
automation - testing scoped search for each entity would be too costy

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#3315]
I wanted to start a discussion on how to approach the `scoped search` feature automation.
The problem is that we need to pre-create multiple instances (~2-4) per each entity in order to test the filtering functionality. But creating instances just to test the filtering functionality is quite time-consuming.

Shall we loosen the coverage and test the `feature` only for some of the features? some sort of `smoke` test?

just for a record, `scoped search` is applicable in UI, CLI and API (one of the ways of making this more effective would be to perform the search on all 'platform' inside a single unit test so we can create the instances only once + we can directly compare the results)

Opinions are welcome :)

**Comment by oshtaier** [comment]
Just to clarify
>But creating instances just to test the filtering functionality is quite time-consuming.`

I think that we can agree to use API for any instance create procedure, no matter whether we work with UI or API. It doesn't seem so time consuming to perform that operation (about 20-25 seconds per 4 instances). Or even 25 seconds is too much?

**Comment by rplevka** [comment]
@oshtaier, ok, now take some more complex entity that needs another kind of entities in order to be created.
Or, let's say we want to apply a `Repository` filter based on `synced` field. We would need to create and synchronize some...
Similarly with `Hosts` or `Content Hosts` -> create org, create product, create repo, create content view, create cv_version, publish the version (or even promote it), ...

**Comment by oshtaier** [comment]
@rplevka I took not the simplest case, but I got your point. Of course, we cannot have 100% of coverage here as it doesn't make sense. I propose to start from basic things, to have best coverage for minimum time and efforts (like take the most important entities and do only fundamental actions)

**Comment by rplevka** [comment]
@oshtaier yes, and that's what I wanted to discuss :) - which ones to cover and which strategy to choose.
