### ISSUE TITLE
All package/package-group/errata sub-commands moved to host entity from content-hosts

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#3326]
As per of 6.2 host unification changes, all commands related to errata/package and package group are now moved from content-hosts to hosts entity. 
So all existing tests that points to content-host object should point to hosts object now.

```
 ~]# hammer -u admin -p changeme host | grep -ie errata -ie package -ie package-group
 errata                        Manage errata on your hosts
 package                       Manage packages on your hosts
 package-group                 Manage package-groups on your hosts
```

**Comment by abalakh** [comment]
Sigh... At first i faced [BZ1313976](https://bugzilla.redhat.com/show_bug.cgi?id=1313976) and [BZ1314775](https://bugzilla.redhat.com/show_bug.cgi?id=1314775), wrote simple workarounds for them... And now got stuck on another [BZ1311821](https://bugzilla.redhat.com/show_bug.cgi?id=1311821) - can't sync sat6-tools repo, as a result can't install katello-agent on hosts later.
So i can't verify tests are working after the changes, sat6.2 is a bit too buggy atm :disappointed:

**Comment by sghai** [comment]
@abalakh : hey [BZ1311821](https://bugzilla.redhat.com/show_bug.cgi?id=1311821) is for manifest import. You can simply set the custom tools repo from the snap2 links if you'r able to get pass other two bz's.

**Comment by abalakh** [comment]
@sghai thanks, that worked :+1:
