### ISSUE TITLE
Revise coverage for partition table

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3332]
We have changes for ptable entity, so need revise our code for it

**Comment by sghai** [comment]
@oshtaier : I see that #3555 PR is already merged. Anything still needs to be covered here with this issue ? or Can we close this ?

**Comment by oshtaier** [comment]
Still like to look on the 'History' tab of the partition table entity

**Comment by elyezer** [comment]
Would be interesting to add more details on the issue. This will ensure good information if we decide to hold this and work in one month from now for example.

**Comment by oshtaier** [comment]
Here is an example of the tab to be covered:
![image](https://cloud.githubusercontent.com/assets/10895065/17173505/eb49e4b0-5403-11e6-982d-adf01b8768fe.png)

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
