### ISSUE TITLE
Update tests/foreman/api/test_user module

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#3361]
As per #3359 discussion - need to drop `_user_attrs()` in favor of datafactory's `valid_data_list()` or `generate_strings_list()` and divide the "universal" `test_positive_create` test into separate `test_positive_create_with_firstname`, `test_positive_create_with_lastname` etc.

**Comment by rochacbruno** [comment]
@abalakh implemented on #3359 please check if it is ok

**Comment by rochacbruno** [comment]
@abalakh can we close this?

**Comment by abalakh** [comment]
@rochacbruno sure. Next time please just put a line like 'Closes #3361' in your pull request message and the issue will be closes automatically as soon as PR gets merged.

**Comment by abalakh** [comment]
Closing #3361 via #3359.
