### ISSUE TITLE
Work on skip bug decorators according to resolved issues

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3395]
Refer to:
https://docs.google.com/spreadsheets/d/1AprD2_XuDOscZHYqDdCErgAzO30WdAVi5ylWTcprUsg/edit#gid=0

**Comment by oshtaier** [comment]
Resolved in https://github.com/SatelliteQE/robottelo/pull/3397

**Comment by elyezer** [comment]
Assigning to @rochacbruno since he have done the job.
