### ISSUE TITLE
Move docker external registry info to robottelo.properties.sample

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#3403]
DOCKER_0_EXTERNAL_REGISTRY = u'https://registry.access.redhat.com'
DOCKER_1_EXTERNAL_REGISTRY = ***

**Comment by abalakh** [comment]
Picking up this one.
So, if i'm not wrong, the task consists of 3 parts:
1) robottelo PR, with adding 2 new properties and updating the tests to use them
2) setting 2 new environment variables on jenkins with external registries urls
2) automation-tools PR which will update properties file with environment variables contents.

**Comment by abalakh** [comment]
Or, if we have Jenkins Config File Provider Plugin or something similar installed (i suspect we have), then instead of steps 2) and 3) we can simply set that property value on jenkins and that's it.
