### ISSUE TITLE
Automate Bugzilla #1330239  - WebUI: Unable to save changes to an Organization

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#3410]
Satellite is not working when editing an Organization and immediately clicking on `submit` button without change anything.

I tried to automate like the following:

``` python
    @tier1
    def test_positive_create_with_premature_save(self):
        """Create an organization and then edit it and immediatelly save.

        @feature: Organizations

        @assert: Organization can be saved without any change after its
        creation.
        """
        org_name = gen_string('alpha')
        with Session(self.browser) as session:
            make_org(session, org_name=org_name)
            org = self.org.search(org_name)
            self.assertIsNotNone(org)
            org.click()
            self.org.wait_for_ajax()
            self.org.click(common_locators['submit'])
```

But doing that it does not fail. I tried to creating an org and editing it manually and it worked, but when I clicked on a previous created one I was able to reproduce the bug.

When implementing this more investigation will be required in order to identify what is making the failure happen.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1330239

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
