### ISSUE TITLE
Organization cleanup after tests

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#3459]
Most of the tests requires that an Organization is created in order to assign entities to the created Organization. Because this after running a complete set of tests (tier1, tier2, ...) against a Satellite machine it will leave hundreds of Organizations created.

A clean up approach should be put in place to make sure that not that many Organizations is left on the system after running automation.

A possible solution would be create a list of Organizations to remove and whenever a new object is created its ID can be appended to that list, after running the tests (possibly on the tearDownClass) the list can be checked and any Organizations ID stored on it should be removed.

**Comment by rplevka** [comment]
@elyezer not a bad approach but quite possibly more logic would be needed here as there are scenarios, where you can't simply delete an Organization (assigned hosts, ...)

**Comment by rochacbruno** [comment]
@rplevka are right! Last week I tried that and opened the [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1336004) about it. 

This is the expected behavior so we would need to implement the delete cascade in our side by overriding EntityDeleteMixin and clean up all related entities before removing the org.

**Comment by sthirugn** [comment]
A rough solution is implemented here: https://github.com/SatelliteQE/robottelo/pull/3460

@elyezer suggested an improvement as per: https://github.com/SatelliteQE/robottelo/pull/3460#discussion_r63603817

We need to revisit this when we have time.  PR #3460 will be merged soon to prevent capsules test affecting other tests.

**Comment by rochacbruno** [comment]
I have some results for an isolated test (executed locally)

## A test that creates only 1 organization 

```bash
$ py.test -s tests/foreman/api/test_organization.py -k with_name_and_label

Current robottelo code, nailgun 0.26.0 without signals
=== 1 passed, 20 deselected in 6.04 seconds ===

Currently robottelo code, nailgun 0.27.0 with signals but no handler connected
=== 1 passed, 20 deselected in 6.06 seconds ===

Cleanup handler connected to post_create signal (deleting org async)
=== 1 passed, 20 deselected in 8.16 seconds ===
```

Then in tearDownClass that queue is iterated and **.delete(synchronous=False)** called.

## Now a test creating 7 random organizations
```bash
$ py.test tests/foreman/api/test_organization.py -k with_name_and_description

Current robottelo code, nailgun 0.26.0 without signals
=== 1 passed, 20 deselected in 38.52 seconds ===

Currently robottelo code, nailgun 0.27.0 with signals but no handler connected
=== 1 passed, 20 deselected in 38.59seconds ===

Cleanup handler connected to post_create signal (deleting 7 orgs async)
=== 1 passed, 20 deselected in 54.03 seconds ===
```

Conclusion:
1. Adding signals to **nailgun** has no considerable overhead if we do not connect handlers
2. Signal handlers will introduce a very little overhead depending on what is implemented
3. The iteration of queue and call to **.delete** consumes 2 seconds for each deleted entity

NOTE: This results does not take assigned host deletion yet

**Comment by rochacbruno** [comment]
BTW: This is the robottelo code I used for testing, if any of you have any suggestion will be welcome.

```python
class TestCase(unittest2.TestCase):
    """Robottelo test case"""

    cleanup_queue = []

    @classmethod
    def tearDownClass(cls):
        for item in cls.cleanup_queue:
            item.delete(synchronous=False)

    @classmethod
    def register_entities_for_cleanup(cls, sender, entity):
        if isinstance(entity, entities.Organization):
            cls.cleanup_queue.append(entity)


signals.post_create.connect(TestCase.register_entities_for_cleanup)
```

**Comment by rochacbruno** [comment]
PR #3492 sent for API cleanup, I'll paste results there

**Comment by rochacbruno** [comment]
Closing as we are using snapshots approach.
