### ISSUE TITLE
Fix oscap tests since default rhel contents are not created anymore

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#3467]
test: tests.foreman.ui.test_oscapcontent.OpenScapContentTestCase.test_positive_default 
bug: https://bugzilla.redhat.com/show_bug.cgi?id=1336374

This test will be skipped until a decision is made for a permanent fix for this test.

**Comment by sghai** [comment]
@kbidarkar : is this still valid ?

**Comment by kbidarkar** [comment]
This is fixed in automation-tools and hence can be closed, we now run a command which will create default rhel oscap contents.

**Comment by kbidarkar** [comment]
https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L629
