### ISSUE TITLE
Custom admin users taking long time to login

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#3502]
@oshtaier discovered that since we introduced #3455 the custom users is taking more time to login in to the system than default admin user.

Usually default admin takes max of 2 seconds, while custom admin user can take 2 minutes.

**Comment by rochacbruno** [comment]
Some things I observed:

- if I create a new **custom admin** user via api and then login in a **clean box** it takes less than 1 second to load dashboard page. 
- So I ran **api/test_host** and got some hosts and orgs created. 
- Then if I login with default admin credentials it is quick
- But If I use that custom user it takes more time, in that case more than 40 seconds. 
- I suspect that default "admin" bypasses any permission check in dashboard 
- While custom admin user has still to have its roles checked or something like this. 
- That can explain why default admin have roles disabled in UI while custom admins still have the field to select its roles

**Comment by rochacbruno** [comment]
More information to help to figure out this

UI login process

```python
# submit button pressed
2016-05-26 04:24:00 - robottelo.ui.locators - DEBUG - Accessing locator "submit" by name: "commit" 

# 1 minute and 49 seconds passed....

# next locator
2016-05-26 04:25:49 - robottelo.ui.locators - DEBUG - Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"

```

User has been created with a call like this:

```python
2016-05-26 04:23:44 - nailgun.client - DEBUG - Making HTTP POST request to 
/api/v2/users 
with options 
{'verify': False, 
'auth': ('admin', '******'), 
'headers': {'content-type': 'application/json'}} 
and data 
{"user": {
     "firstname": "Foreman User", 
     "admin": true, 
      "mail": "mWHiXBQx@test.com", 
      "login": "hCvaFHhQNl", 
       "password": "********", 
       "auth_source_id": 1
    }
}.

2016-05-26 04:23:44 - nailgun.client - DEBUG - Received HTTP 201 response: 
{
"firstname":"Foreman User",
"lastname":null,
"mail":"mWHiXBQx@test.com",
"admin":true,
"auth_source_id":1,
"auth_source_name":"Internal",
"timezone":null,
"locale":null,
"last_login_on":null,
"created_at":"2016-05-26 08:23:44 UTC",
"updated_at":"2016-05-26 08:23:44 UTC",
"id":366,
"login":"hCvaFHhQNl",
"default_location":null,
"locations":[],
"default_organization":null,
"organizations":[],
"auth_source_internal": {
    "id":1,
    "type":"AuthSourceInternal",
     "name":"Internal"
   },
   "mail_notifications":[],
    "roles":[{"name":"Anonymous","id":14}],
    "usergroups":[]
}
```

**Comment by sthirugn** [comment]
@rochacbruno I think I found a solution for this issue.  I created a new user in auto rhel 7 box and it took a long time to login.  But when I assigned the default Organization id (UI - Default on login, hammer - default-organization-id), the login was instant.

I think when the user does not have any context, it tries to query each available org and tries to produce the dashboard summary.

**Comment by rochacbruno** [comment]
default "admin" takes 319ms to load dashboard index. 
custom admin user  takes 8201.5ms to load dashboard index.
But since we assign default_organization to custom admin users it takes 317.7ms

So @sthirugn solved the problem 

Accessing dashboard with "any context" is a no go if we have a lot of organizations.

we need to check if there is another UI tests failing or taking long time and using "any context"

**Comment by rochacbruno** [comment]
Lets close this only after next automation results...

**Comment by rochacbruno** [comment]
Closing this as now we are using session_user with "default_on_login" to session_org and login is much faster with this.
