### ISSUE TITLE
Docker tests failing because of external docker url

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#3508]
Following tests are failing because we use our `sesame` machine as external docker url:
```
tests.foreman.api.test_docker.DockerContainerTestCase.test_positive_read_container_log
tests.foreman.api.test_docker.DockerContainerTestCase.test_positive_create_using_cv
tests.foreman.cli.test_docker.DockerContainersTestCase.test_positive_create_using_cv
tests.foreman.ui.test_docker.DockerContainerTestCase.test_positive_create_with_compresource
tests.foreman.ui.test_docker.DockerContainerTestCase.test_positive_power_on_off
tests.foreman.ui.test_docker.DockerContainerTestCase.test_positive_delete
```
After changing external compute resource to e.g. `http://localhost:2375` tests are passing.
Few @elyezer's thoughts from IRC on this:
```
<elyezer> it is probably failing because in order to create a container it is needed to install the certificate
<elyezer> otherwise docker will consider the registry (satellite docker repo) being untrusted
<elyezer> abalakht: as I said that is not possible to do on sesame because we can't install a certificate for each machine we are testing and also it is a fedora machine
<elyezer> you should use localhost instead
<elyezer> you can even access by http or unix socket
<elyezer> abalakht: the point here is, if the external compute resource needs to have the certificate installed, then we should update the tests and just use internal one. Because we can't install the certificate on sesame (to not mess with the machine).
```
We could try to use `http://localhost:2375` instead of sesame, but the thing is our CI is running the tests on sesame, and for sesame `localhost == sesame` so we can't use it.
One of possible options is to remove external compute resource from tests, as suggested by @elyezer .
Any ideas/suggestions are welcome

**Comment by elyezer** [comment]
@abalakh using localhost for external compute resource will actually be the satellite machine. Since the satellite will try to access localhost from itself and there localhost is satellite machine.

**Comment by abalakh** [comment]
@elyezer right, my bad. I've provided test results in #3509 with `external_url=http://localhost:2375`, all the tests are passing. Should we update our CI `robottelo.properties` file or you have other ideas?

**Comment by elyezer** [comment]
I did the following on a testing machine:

1. Create a Docker Compute resource using sesame as the URL
2. Went to the new container wizard and deployed a container on it from Docker Hub.

To do that it is not needed to install the certificate.

Tried to create a container using a custom repository and when doing so I got the failure caught by automation, I am checking with devs to see if that is because the certificate is not available or some bug.

**Comment by elyezer** [comment]
Instead of using localhost I would use the machines hostname to be more close to the external access.

**Comment by oshtaier** [comment]
@abalakh Can we close that?

**Comment by abalakh** [comment]
@oshtaier yeah, wanted to leave the issue open till we get the results, and according to 2 latest test runs failures are gone, so we can close it.
