### ISSUE TITLE
No package 'libffi' found - while installing from requirements.txt

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#3530]
```
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
```
I hit this on my fedora 23 system. I had to manually install  `libffi-devel` package in order to get the `pip install -r requirements.txt` finished successfully.

**Comment by rochacbruno** [comment]
It is mentioned on documentation http://robottelo.readthedocs.io/en/latest/index.html#quickstart @elyezer added when introduced cryptograph in place of pycrypto

**Comment by rplevka** [comment]
@rochacbruno :+1:
