### ISSUE TITLE
Improve multi threading logging sequence

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#3536]
@oshtaier raised the problem that:

Currently running with 4 threads in py.test gives us unsorted log messages

```bash
[gw0] DEBUG: "Message from worker 0"
[gw4] DEBUG: "Message from worker 4"
[gw3] DEBUG: "Message from worker 3"
[gw2] DEBUG: "Message from worker 2"
```

We cannot control the thread logging order but we can try to write separate log files for each thread or even separate log files for each test_case.

In the end we can join and output to jenkins in the propor order

Any other ideas?

**Comment by oshtaier** [comment]
Yeah, if we have time of execution for each command, so it will be nice just to append all files in one to have something similar that we have at that moment, but in the right order

**Comment by elyezer** [comment]
Having separates files looks a good option to me.
