### ISSUE TITLE
Add test to check the proper Timezone value after changing it back to "Browser timezone"

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3574]
When saving a user as "Browser Timezone" after changing the timezone to something other than "Browser Timezone" that the value is saved as an empty string instead of nil.

For more information see https://bugzilla.redhat.com/show_bug.cgi?id=1342603

**Comment by elyezer** [comment]
I have edited the issue title and description to add more information here on github.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
