### ISSUE TITLE
Add json parser for CLI or substitute current csv parser by json parser

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3575]
It seems that current csv parser cannot handle all our needs and process pretty basic entities in a wrong way. For example:
```
Override values: 
    Merge overrides:     yes
    Merge default value: no
    Avoid duplicates:    yes
    Order:               fqdn, hostgroup, os, domain
    Values:              
     1) Id:    20
        Match: domain=test.com
        Value: ["test", "test2"]
     2) Id:    21
        Match: domain=test11.com
        Value: ["test", "test2"]
```
is parsed in:
```
[
    {u'value': ["test", "test2"], u'id': u'10', u'match': u'domain=test.com'},
    {u'value': ["test", "test2"], u'id': u'10', u'match': u'domain=test11.com'},
]
```
entire section:
```
    Merge overrides:     yes
    Merge default value: no
    Avoid duplicates:    yes
    Order:               fqdn, hostgroup, os, domain
```
is completely omitted.

That means we can process only one level of sub-parameters.

Of course, we can workaround that problem and make our csv parser even more complex and uglier, but it is definitely better to move to json as hammer finally supports it.

**Comment by omaciel** [comment]
@rochacbruno assigned this issue to you. You can talk to @oshtaier to figure out the details :)

**Comment by renzon** [comment]
Could you guys take a look: https://github.com/renzon/robottelo/commit/cba9c8c2a7caf9a0dfc10da0b4ae1e2971dfaf38.

I've changed the format of ContentView.list I run https://github.com/renzon/robottelo/blob/master/tests/foreman/cli/test_contentview.py#L1065 with success. But not sure if the sub-dicts must be also normalized. Once you guys confirm I can change all ContentView methods to use json instead of csv. Dont know if I need do that with all classes extending from base or not.

**Comment by oshtaier** [comment]
@renzon 
Here we are talking about parser, not about the way we pass parameters to the server. Basically, we need to re-implement https://github.com/SatelliteQE/robottelo/blob/master/robottelo/cli/hammer.py or create an alternative json parser to it.
Currently, we are send all commands like this:
```hammer -v -u admin -p changeme --output=csv sc-param add-override-value --smart-class-parameter-id='48' --value='jAyhqynXVV' --match='is_virtual=true'```
But need to have:
```hammer -v -u admin -p changeme --output=json sc-param add-override-value --smart-class-parameter-id='48' --value='jAyhqynXVV' --match='is_virtual=true'```

I think @rochacbruno can provide more details about that

Things that you proposed in renzon@cba9c8c is really nice to have, but currently we need to add support for other things as approach that we have with csv cannot parse essential things
