### ISSUE TITLE
Add a KANBAN to organize issues and PRs

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#3583]
I am suggesting using waffle.io or Zenhub or Huboard to give a nice overview of issues and PRs in a "kanban" board.

1. https://github.com/integrations/zenhub
    example: https://waffle.io/SatelliteQE/robottelo

2. https://github.com/integrations/zenhub
    example: http://awesomescreenshot.com/081608gh82

3. https://github.com/integrations/huboard
    example: https://huboard.com/SatelliteQE/robottelo/

If we choose waffle, someone with admin rights should add github hooks (when logged in there is a button to add in the bottom of page) Also the waffle.io badges is useful to add on robottelo readme

For zenhub there is a browser extension to be installed, it is not intrusive so no hooks or labels needs to be added. Everyone using the extension can see the boards and pipelines.

Huboard works like waffle but it is very simple.

**Comment by elyezer** [comment]
@rochacbruno what is your personal recommendation here? I can add the hooks if needed, just let me know.

**Comment by rochacbruno** [comment]
I like waffle

[![Stories in Ready](https://badge.waffle.io/SatelliteQE/robottelo.svg?label=backlog&title=Backlog)](http://waffle.io/SatelliteQE/robottelo)

[![Stories in Ready](https://badge.waffle.io/SatelliteQE/robottelo.svg?label=ready&title=Ready)](http://waffle.io/SatelliteQE/robottelo)

[![Stories in Ready](https://badge.waffle.io/SatelliteQE/robottelo.svg?label=in progress&title=In Progress)](http://waffle.io/SatelliteQE/robottelo)

[![Stories in Ready](https://badge.waffle.io/SatelliteQE/robottelo.svg?label=review&title=Review)](http://waffle.io/SatelliteQE/robottelo)

[![Stories in Ready](https://badge.waffle.io/SatelliteQE/robottelo.svg?label=done&title=Done)](http://waffle.io/SatelliteQE/robottelo)


```
[![Stories in Ready](https://badge.waffle.io/SatelliteQE/robottelo.svg?label=ready&title=Ready)](http://waffle.io/SatelliteQE/robottelo)
```

**Comment by rochacbruno** [comment]
@elyezer so can you go to https://waffle.io/SatelliteQE/robottelo and activate the github hooks?

**Comment by sthirugn** [comment]
This is cool.
