### ISSUE TITLE
Implement UI content view stubs

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#3586]
List of stubbed tests:
- [x] test_positive_edit_rh_custom_spin
- [x] test_positive_add_rh_custom_spin
- [x] test_negative_add_dupe_modules
- [x] test_positive_promote_with_rh_custom_spin
- [x] test_positive_promote_composite_with_custom_content
- [x] test_negative_promote_default
- [x] test_positive_publish_with_rh_custom_spin
- [x] test_positive_publish_composite_with_custom_content
- [x] test_positive_publish_version_changes_in_target_env
- [x] test_positive_publish_version_changes_in_source_env
- [x] test_positive_clone_within_diff_env
- [x] test_positive_refresh_errata_to_new_view_in_same_env
- [x] test_positive_subscribe_system
- [ ] test_positive_restart_promote_via_dynflow
- [ ] test_positive_restart_publish_via_dynflow
- [x] test_positive_admin_user_actions
- [x] test_positive_readonly_user_actions
- [x] test_negative_non_admin_user_actions
- [x] test_negative_non_readonly_user_actions
- [x] test_positive_add_custom_ostree
- [x] test_positive_add_rh_ostree
- [x] test_positive_remove_custom_ostree
- [x] test_positive_remove_rh_ostree
- [x] test_positive_create_with_custom_ostree_other_contents
- [x] test_positive_create_with_rh_ostree_other_contents
- [x] test_positive_publish_with_custom_ostree
- [x] test_positive_remove_published_custom_ostree_version
- [x] test_positive_promote_with_custom_ostree
- [x] test_positive_remove_promoted_custom_ostree_contents
- [x] test_positive_publish_promote_with_custom_ostree_and_other
- [x] test_positive_remove_published_version_of_mixed_contents
- [x] test_positive_publish_with_rh_ostree
- [x] test_positive_remove_published_rh_ostree_version
- [x] test_positive_promote_with_rh_ostree
- [x] test_positive_remove_promoted_rh_ostree_contents
- [x] test_positive_publish_promote_with_rh_ostree_and_other

**Comment by elyezer** [comment]
What a big task, the plan is to do all at once?

**Comment by ldjebran** [comment]
test_positive_subscribe_system, blocked by BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1406315

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
