### ISSUE TITLE
Make external_registry settings a list property

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#3589]
PR #3582 has added the external registry robottelo setting but it have not taken advantage of the List properties.

Instead of having multiple entries for the external registry like:

```
external_registry_1=
external_registry_2=
```

It is better to have:

```
external_registries=registry1,registry2,...
```

This way any number of external registry urls can be added and robottelo can randomly fetch one of them when needed.

Check https://github.com/SatelliteQE/robottelo/blob/master/robottelo/config/settings.py#L435-L436 as an example on how to declare a list property.

**Comment by rochacbruno** [comment]
A note for this issue, we can easily move from `.ini` format to `toml` which has better support for lists and dicts and is lightweight (better than YAML for config files)  https://github.com/toml-lang/toml

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
