### ISSUE TITLE
Hammer: Add more testcases around location taxonomy

### ISSUE THREAD

**Issue by cswiii** [SatelliteQE/robottelo#3594]
Need to assure we have test coverage here as well as automate any existing cases.

**Comment by helgie** [comment]
Will do my best :-)

**Comment by omaciel** [comment]
@helgie bump?

**Comment by omaciel** [comment]
@pondrejk this is more of a research issue. Please look into this and file additional issues for automation as needed.

**Comment by pondrejk** [comment]
https://github.com/SatelliteQE/robottelo/pull/4378 also location related

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
