### ISSUE TITLE
Change Hammer parser to json instead of csv

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#3602]
Once json parser is added and csv can cause some [issues](https://github.com/SatelliteQE/robottelo/issues/3575)) , [Base](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/cli/base.py#L342) and its subclasses can use json as default.

Nowadays json parse do some [transformations](https://github.com/SatelliteQE/robottelo/blob/master/tests/robottelo/test_hammer.py#L115), like transforming id in str instead of int, to conform to csv parser.

**Comment by renzon** [comment]
Once json parser is added and csv can cause some [issues](https://github.com/SatelliteQE/robottelo/issues/3575)) , [Base](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/cli/base.py#L342) and its subclasses can use json as default.

Nowadays json parse do some [transformations](https://github.com/SatelliteQE/robottelo/blob/master/tests/robottelo/test_hammer.py#L115), like transforming id in str instead of int, to conform to csv parser.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
