### ISSUE TITLE
Add possibility to run specific test or test class on specified platform

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3605]
Decide best way (probably decorators) and implement that idea to be able to run specific test or class for RHEL6 or RHEL7 platforms. That will require getting information about server (not the machine where tests are executed) operating system. Approach should work both locally and on CI

For example:
```
@run_only_on('RHEL6')
@tier1
def test_positive_create_with_name(self):
```
or
```
@run_only_on('RHEL6')
class PartitionTableTestCase(UITestCase):
```

**Comment by renzon** [comment]
@oshtaier Could you provide more detail about intended uses? "@run_only_on" could make a test be skipped  on future OS releases and maybe it is harmful. Maybe some other decorators could be more useful: "@run_only_on_previous" "@run_only_on_next".

**Comment by oshtaier** [comment]
Hmm, you are right, maybe we can go in opposite direction and say "@skip_on(RHEL6)", just provide the list of unsupported platforms. Anyway, we have not so many of them at that moment and it doesn't seem that we will have serious increase in next decade =)

About the details, nothing special here. I just want to mark tests that cannot be executed on both platforms, but work only for one

**Comment by rochacbruno** [comment]
It would be nice if there is an API endpoint in Katello/Foreman to retrieve system information: example: `curl -XGET http://satbox/api/v2/system_info` so with this we can avoid the need to SSHin to the machine just to get OS version.

**Comment by renzon** [comment]
@rochacbruno I have started with the ssh. Do we have such API now?

**Comment by sghai** [comment]
AFAIK, there is no such foreman/katello api. 

Please make a note that why we need this feature to run specific tests on platform because of a new feature called `ostree` which is used to manage Atomic hosts. Since ostree is supported only on rhel7, so tests should not be executed on rhel6 platform.

**Comment by renzon** [comment]
@rochacbruno @sghai @oshtaier  [decorator](https://github.com/renzon/robottelo/blob/3605/robottelo/decorators.py) file has lot of responsibilities. Thought about refactoring to module, but this would change all modules using it. What should I do? I prefer refactoring but I am too newbie to evaluate if the impact on code could bother the entire team with possible conflicts.

**Comment by renzon** [comment]
Just thought in a middle solution: creating decorators module and moving current file to its __init__, so it would have no impact on project, but still been able to create the new decorator in a segregated module. But still I prefer refactoring properly ;)

**Comment by rochacbruno** [comment]
@renzon +1 to refactor to get better organization and namespaces, BTW you can do that without breaking compatibility, just do a **bare import** of all existing decorators in to **decorators/__init__.py** adding **# noqa** comment and you can keep things working and also have better namespace.

**Comment by rochacbruno** [comment]
e.g:

`decorators/__init__.py`
```python
from .tiers import tier1, tier2, tier3, tier4  # noqa
from .skipping import skip_if_bz_open, ...   # noqa
```

**Comment by renzon** [comment]
@rochacbruno what this "# noqa" does?

**Comment by rochacbruno** [comment]
@renzon if you do not put **# noqa** pep8/flake8 will fail saying  **unused import**

**Comment by renzon** [comment]
@rochacbruno got it, ty

**Comment by sghai** [comment]
Guys: This may be not the right time for re-factoring, we are close to release. So please make sure to test all changes thoroughly.

**Comment by renzon** [comment]
@sghai ok. Have done some tests last night and refactoring everything would take a lot of time. Just moved decorators.py to decorators/__init__.py and everything worked. I am going to finish like this and create an issue for later refactoring

**Comment by rochacbruno** [comment]
reopened due to comments in #3610
