### ISSUE TITLE
Smart Class Parameters implementation (phase 2)

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3620]
- Improve `valid_sc_parameters_data` dataset with new verification datapoints:
  -  Add all possible string data types for 'string' type ('alpha', 'utf8' and etc)
  -  Check whether we can use any existing 'real' type data generator or create our own
  -  Think about adding test files as an input for yaml and json types
  -  Add dynamic data for 'array' type
- Track https://bugzilla.redhat.com/show_bug.cgi?id=1352491 and add corresponding coverage (remove stubbs that are left)

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
