### ISSUE TITLE
Solve timetout issues when manipulating manifest

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#3628]
Tests which manipulates manifest take too long when satellite is full of data used on prior tests

See #3618 conversation for reference about the issue.
#3617 is also affected by this

**Comment by renzon** [comment]
@rochacbruno give an idea of running this tests before all the others. Maybe tear down can also solve this.

**Comment by renzon** [comment]
@omaciel @sghai I closed the related issues in favor of this one. Waiting for your ideas.

**Comment by sghai** [comment]
commented here: https://github.com/SatelliteQE/robottelo/issues/3618#issuecomment-233839221

**Comment by rplevka** [comment]
@omaciel I'd liek to propose closing this issue in favor of: https://github.com/SatelliteQE/robottelo/issues/4028
