### ISSUE TITLE
Create single data file to create entities in images of upgrade also to validate post upgrade tests

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#3637]
Connected to #1622 
Connected to #1986

Currently:
1. We have aYAML pre-upgrade data files(for rhel6 and rhel7 separately) containing details of each entity  which we are passing to validate the entity's existance and its associates after upgrade.

What we want now:https://github.com/SatelliteQE/robottelo/issues/3637
1. Create single YAML(or anything) data file which will be used to create entities on pre-upgrade images and validate the existance of those entites after upgrade on both rhel6 and rhel7.
1. We need to write functions to create entities from data file and validate the enties using data file.

Thanks,
Jitendra Yejare

**Comment by sghai** [comment]
This can be closed once #4004 is done.

**Comment by rochacbruno** [comment]
Tool is released in satellite-populate repo, this issue can now be solved using the populate datafile.

**Comment by ntkathole** [comment]
This is part of satellite6-upgrade project. We have existence tests. Please feel free to re-open, if this still needs fixing.
