### ISSUE TITLE
RHEL6 os_tree tests not been skipped 

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#3638]
Test: https://satellite-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/satellite6-automation-downstream-rhel6-tier1/104/testReport/tests.foreman.ui.test_repository/RepositoryTestCase/test_positive_create_custom_ostree_repo/

Decorator: https://github.com/SatelliteQE/robottelo/pull/3629/files#diff-4ac5ea985efa38f0c89842de24c052e6R525

**Comment by renzon** [comment]
SSH on the server and the problem is the version there: 

cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.8 (Santiago)
so RHEL 6 will not skip

@sghai what minor versions do we test against? Only this 6.8? I have [included this version](https://github.com/renzon/robottelo/commit/f7dedb1014156218bee53427ebbdfdb8d2a2b8d6#diff-4ac5ea985efa38f0c89842de24c052e6R526) but with test against other I can include them as well:

**Comment by rochacbruno** [comment]
@renzon I think **RHEL6** stands for all **RHEL6.x** and **RHEL7** for all **RHEL7.x** so I guess we dont need to add "RHEL6.8" token

**Comment by renzon** [comment]
@rochacbruno I thing this is what we want know, but don't know if it is a general case. I thinking on defensive program where we skip only precise versions. Otherwise we can skiping an import test on future versions of os without wanting it. What you think?

**Comment by renzon** [comment]
@rochacbruno maybe been explicity and creating another decorator @skip_if_prior_os()...

**Comment by rochacbruno** [comment]
@renzon I think we can make it simple.. if the token is "RHEL6" all **6.x** is skipped... if token is specific "RHEL6.8" only the **6.8** is skipped

**Comment by rochacbruno** [comment]
@sghai ^ what do you think?

**Comment by renzon** [comment]
So as far as a asked, we are supposed to test the last versions. Whe are on 6.8 but when 6.9 got out we change targert os to this new version. In that case ostree could be backported and if we get this simple now we coul have less coverage. But I agree it's annoyng defining the versions again and again.

**Comment by renzon** [comment]
@rochacbruno I made a [branch ](https://github.com/renzon/robottelo/commit/6b762af8850bdd1fa2d15db094cb3106d791e8d2)with ignoring entire major version. So I have both done and wll create PR accordingly to @sghai vote ;)

**Comment by renzon** [comment]
@omaciel @elyezer I think your input would be nice too ;)

**Comment by renzon** [comment]
I spoke with @omaciel and he has the same feeling as @rochacbruno. In fact I think it was the same for @sghai once he considered tests were failing when they shouldn't. So I going to send second branch PR.

**Comment by sghai** [comment]
@renzon : Sorry for delay. As per our official docs, user should be on latest released version of OS and product. So in any case, we don't need to worry about different minor versions of same OS like `rhel6.7 ` and `rhel6.8`. Otherwise, we may need to update the decorator everytime when a new os version released.

So I vote for `rhel6` and `rhel7` should work with `skip_if_os`
