### ISSUE TITLE
Fix add_puppet_module helper for content_view tests

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3639]
Fix next downstream tests:
tests.foreman.ui.test_contentview.ContentViewTestCase.test_positive_add_puppet_module
tests.foreman.ui.test_contentview.ContentViewTestCase.test_positive_create_composite
tests.foreman.ui.test_contentview.ContentViewTestCase.test_negative_add_puppet_repo_to_composite

**Comment by sghai** [comment]
:+1:
