### ISSUE TITLE
Fix tests.foreman.ui.test_host.HostTestCase.test_positive_create_libvirt

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3661]
IP address cannot be provided by DHCP server by unknown reason
![image](https://cloud.githubusercontent.com/assets/10895065/17204187/b2671894-54ac-11e6-9dc0-5fc0c931bee4.png)
Subnet has default capsule assigned:
![image](https://cloud.githubusercontent.com/assets/10895065/17204267/3aacb498-54ad-11e6-932f-f704dee576f9.png)
And default capsule has DHCP enabled:
![image](https://cloud.githubusercontent.com/assets/10895065/17204305/6d48bdca-54ad-11e6-9371-269ca9ee14b8.png)

**Comment by sghai** [comment]
@oshtaier : I think this issue can be close now ?

**Comment by oshtaier** [comment]
@sghai Is issue resolved?

**Comment by sghai** [comment]
Yeah.. I automated a atomic host provisioning test. There I see host is correctly getting IP from DHCP.. I didn't check this specific test.

**Comment by oshtaier** [comment]
Just curious whether Libvirt provisioning works in the same way

**Comment by sghai** [comment]
Yeah..atomic host provisioning works same way and on external libvirt. but I'll double check this test..

**Comment by oshtaier** [comment]
thanks... appreciate that

**Comment by rplevka** [comment]
bump.
I use this path every day and never experienced this error - unless one ommits to use 'IPAM' for the subnet (which the attached screenshots don't show) - i would say this was the issue.

I'm going to close it, however @oshtaier or @sghai , if you guys think there is still some sort of issue in this, feel free to reopen.

thanks for understanding.
