### ISSUE TITLE
Create helper to upload ssh key to remote server

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3665]
Create helper similar that we have for ssh module `upload_file`, but
1) Check that remote folder (.ssh) exists and create if not
2) Check whether file `authorized_keys` exists and create if not
3) Append content (from `~foreman-proxy/.ssh/id_rsa_foreman_proxy.pub` for example) to `authorized_keys` file (probably through `echo 'key' >> ~/.ssh/authorized_keys`)

**Comment by abalakh** [comment]
Right permissions for each created file should be set too as otherwise ssh connection won't succeed.

**Comment by oshtaier** [comment]
Yes, thanks @abalakh 
```
chmod 700 <%= ssh_path %>
chmod 600 <%= ssh_path %>/authorized_keys
```

**Comment by oshtaier** [comment]
Refer to `remote_execution_ssh_keys` provisioning template for more details
