### ISSUE TITLE
Document skip_if_os decorator

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#3674]

**Comment by renzon** [comment]
@omaciel I changed the docs to include the decorators in a subsection, once it was decorators has become a package instead of a module. But I am not sure this is the kind of documentation you is expecting. The doc will be inserted in this section: http://robottelo.readthedocs.io/en/latest/api/index.html. Can you confirm it?

**Comment by omaciel** [comment]
@renzon right, I am looking for a good write up on why we have this decorator, what it does, and how to use it? Something that teaches people how to use it.
