### ISSUE TITLE
Pagination control config not working for content host in host collection

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#3676]
See BZ [1343583](https://bugzilla.redhat.com/show_bug.cgi?id=1343583)

**Comment by renzon** [comment]
After playing around this issue, I found 3 approaches:

## Changing cli_config.yml

In fact I have already uploaded [a version](https://github.com/renzon/robottelo/commit/b4db1907d1740b16a09c9ff78b08cbaa95bedfa5) for it.

**Pro** 
* It test exactly what was described on BZ by the client
**Con** 
* cli_config.yml is used globally for all calls, so there is a chance that it can affect another tests when running in multi thread environment

## Passing another configuration file

Hammer cli accepts -c option to pass another configuration file when making calls.
Example:

``` bash
hammer -u admin -p changeme -c /tmp/cli_config.yml --output json host-collection hosts --organization-id 3 --id 8
```
Result
``` javascript
[
  {
    "ID": 3,
    "Name": "fdaxvztljrfehac"
  },
  {
    "ID": 4,
    "Name": "hwhnekpyeodpdeh"
  }
]
```
**Pro** 
* A random file could be generated for each test not so it would not  cause side effects when running in multi trhread
**Cons** 
* Doesn't test exactly what was described on BZ
* It would required some refactoring on [base](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/cli/hostcollection.py#L69) class to pass a -c option, once it current doesnt offer this paremetre. Another approache would be making a ssh comand directly to fethc data.

## Using per_page parameter

Hammer cli subcommand accepts --per_page option. Example:

``` bash
hammer -u admin -p changeme --output json host-collection hosts --organization-id 3 --id 8 --per_page 1
```
Result
``` javascript
[
  {
    "ID": 3,
    "Name": "fdaxvztljrfehac"
  }
]
```

**Pro** 
* Would not  cause side effects when running in multi trhread
* Dont have to refactor code once host_colletcion hosts accepts this kind of option as paremeter
**Cons** 
* Most far from BZ description

**Comment by rochacbruno** [comment]
I like the options 2 and 3 (passing -c or passing parameter directly and explicitly), we do not want to affect multi threading processes.

**Comment by renzon** [comment]
@rochacbruno: I am going with number 3 because it is easier. Besides that, I am including the manual test I done to check if both global and command configuration is working: 

``` bash
[root@foo ~]# grep per_page /etc/hammer/cli_config.yml 
  # :per_page: 20

[root@foo ~]# hammer -u admin -p changeme host-collection hosts --organization-id 3 --id 1 
---|----------------
ID | NAME           
---|----------------
2  | bizndtpogcpxiah
3  | wihfxmdfmpzxdjq
---|----------------

[root@foo ~]# hammer -u admin -p changeme host-collection hosts --organization-id 3 --id 1 --per-page 1
---|----------------
ID | NAME           
---|----------------
2  | bizndtpogcpxiah
---|----------------
Page 1 of 2 (use --page and --per-page for navigation)

[root@foo ~]# grep per_page /etc/hammer/cli_config.yml 
  :per_page: 1

[root@foo ~]# hammer -u admin -p changeme host-collection hosts --organization-id 3 --id 1 --per-page 2
---|----------------
ID | NAME           
---|----------------
2  | bizndtpogcpxiah
3  | wihfxmdfmpzxdjq
---|----------------

[root@foo ~]# hammer -u admin -p changeme host-collection hosts --organization-id 3 --id 1 
---|----------------
ID | NAME           
---|----------------
2  | bizndtpogcpxiah
---|----------------
Page 1 of 2 (use --page and --per-page for navigation)
```

**Comment by elyezer** [comment]
worth mentioning that robottelo set --per_page to 10000 if that option is not defined check https://github.com/SatelliteQE/robottelo/blob/master/robottelo/cli/base.py#L332-L333 for more information.
