### ISSUE TITLE
Write documentation for ssh module

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#3681]
robottelo.ssh needs documentation with usage examples

**Comment by elyezer** [comment]
Better to write on the code itself. That will help developers and users in one shot.

**Comment by rochacbruno** [comment]
@elyezer we should define standard way of doing that. @renzon done this https://github.com/SatelliteQE/robottelo/pull/3675/files as rst docs. should we move that to docstrings and auto_import?

**Comment by elyezer** [comment]
@rochacbruno my personal opinion is to have the docs within the source code. That helps maintain it updated since during the review process the docstrings can be analyzed. Having a separated RST file works too, but everyone reviewing should make sure that all docs are updated for every change otherwise the docs can say one thing and code other.

**Comment by renzon** [comment]
@rochacbruno @elyezer I've done that, only generating the doc from code first:

http://robottelo.readthedocs.io/en/latest/api/tests.robottelo.html#module-tests.robottelo.test_ssh

But as you can see, from a user point of view would be difficult to find out Robottelo main features reading/searching directly into source code documentation. I think that is the reason @omaciel wanted a more high level documentation. See the new section I created: http://robottelo.readthedocs.io/en/latest/features/index.html. Maybe we could provide a more organized documentation, more like a tutorial. But I totally agree that upgrading docs is going to be an issue.

**Comment by elyezer** [comment]
I think if documentation check is present and enforced on the review process than the documentation getting obsolete should not happen or be as minimal as possible
