### ISSUE TITLE
[RFE] Add interactive browsing command for UI

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#3702]
when #3701 is merged a new **manage ui** command group should be created

It should work in the following way:

```console
$ cd robottelo
$ manage ui features
This is the Robottelo UI browseable features
  - contentview (vc)
  - contenthost (ch)
  - host 
  - hostcollection (hc)
  - ...
  manage ui features help <feature_name> to see more information 
```

With a feature name in hand, the **QE** can do:

```console
$ manage ui browse contenthost --options=...
```

with the above command a new browser session is started using configured driver from properties file unless specified in options a different driver **e.g: --driver=saucelabs**  (if firefox or chrome a new browser window should open or new container started...), and then the **console** will be ready to interact with the page. (in the same way scrapy shell works).

In that shell the **QE** can execute UI commands such as click, find_element etc... and the session command history is saved in a tmp log file.

> NOTE: new runtime syntax sugar can be added to deal with UI elements and locators.

**Comment by rochacbruno** [comment]
@omaciel let me know if this is the feature you talked about in our last robottelo meeting.

**Comment by omaciel** [comment]
@rochacbruno I need to fully digest your proposal for handling UI interactions. At first I thought about doing everything from the shell command, and if I wanted to interact with the UI through a browser, then I'd implicitly get one started for me when I instantiated a UI element (eg ui.login would open the browser) and then I could continue interacting with it. From this point onward it would be like using webdriver from the console, but using our syntactic sugar to navigate to pages and create entities. I will try to spend a bit more time on this today while in training.

Thank you for the quick turnaround!
