### ISSUE TITLE
Refactor Exception attribute msg to message

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#3717]
CLIReturnCodeError is one of exceptions which defines msg on its __init__ method. The problem is Exception already has a message attribute which holds error message for same purpose. This make polymorphism broken.

As partial workaround I am going to keep both of them on CLIReturnCodeError to make test easier on #3716. But latter it must be changed and all possible impacts fixed.

**Comment by renzon** [comment]
Surprise: Python 3 has args attrubute instead of message:https://travis-ci.org/SatelliteQE/robottelo/jobs/153352582. So we need to think better about this.

**Comment by rochacbruno** [comment]
I guess `str(e)` should work for py2 and py3

**Comment by elyezer** [comment]
Yes str(exception_object) works for both Py2 and Py3.

**Comment by sghai** [comment]
@renzon : Could you please prepare a checklist for all the modules that needs to be updated, So that we can assign folks to work on ?

**Comment by renzon** [comment]
after #3789 there is no need to work on this
