### ISSUE TITLE
Make `tests/foreman/ui/test_errata.py` compatible with both Python 2 and 3

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#3726]
The `nested` from `contextlib` is not available anymore on Python 3. That is causing an error when running the tests using Python 3.

```console
$ python --version
Python 3.4.3
$ python -c 'from contextlib import nested'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'nested'
```

**Comment by renzon** [comment]
I Assume we are using Python greater then 2.6. In this case: http://stackoverflow.com/questions/3024925/python-create-a-with-block-on-several-context-managers. In fact I refactore some cli tests and they worked: https://github.com/SatelliteQE/robottelo/pull/3718/files#diff-bf0b497a0bffe7aa3fca0507f8ef3e99R546 very well.

**Comment by abalakh** [comment]
@renzon so far python 2.6 was supported too, that's why contextlib was used. 
regardless, this failure should be fixed, thanks for raising it

**Comment by rochacbruno** [comment]
Why do we support 2.6? 

I think we can support 2.7 and generally use 3.x (as far as I remember only fabric was not migrated, but now it is)

**Comment by sghai** [comment]
@abalakh : can we close this now ?

**Comment by abalakh** [comment]
@sghai let me fix it first. I'd like to implement another test for that module, so will probably fix this issue in scope of that task
