### ISSUE TITLE
Add CRUD tests for Repository `download_policy` via CLI

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#3728]
Please add automated test cases to cover basic functionality for the new `download_policy` attribute of repositories.

Assuming your checkout is up to date and that you updated all dependencies with `pip install -U -r requirements.txt -r requirements-optional.txt` to get latest changes for `NailGun` and the new Robottelo interactive **shell**:

```shell
$ manage shell
Python 2.7.12 (default, Jun 29 2016, 14:05:02)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

Welcome to Robottelo Interactive shell
	Auto imported: ['rt', 'nailgun', 'settings', 'robottelo', 'ng', 'entities', 'locators']

In [1]: from robottelo.cli.factory import make_org

In [2]: from robottelo.cli.factory import make_product_wait, make_repository

In [3]: org = make_org()

In [4]: product = make_product_wait({u'organization-id': org['id']})

In [5]: repository = make_repository({'name': 'foobar', 'product-id': product['id'], 'c
   ...: ontent-type': 'yum', 'download-policy': 'on_demand'})

In [6]: repository
Out[6]:
{u'content-counts': {u'errata': u'0',
  u'package-groups': u'0',
  u'packages': u'0'},
 u'content-type': u'yum',
 u'created': u'2016/08/19 09:29:18',
 u'download-policy': u'on_demand',
 u'gpg-key': {},
 u'id': u'156',
 u'label': u'foobar',
 u'name': u'foobar',
 u'organization': u'Uh5U7f',
 u'product': {u'id': u'20', u'name': u'lveoyIJjUc'},
 u'publish-via-http': u'yes',
 u'published-at': u'http://satellite.example.com/pulp/repos/Uh5U7f/Library/custom/eQsfHYQhEVUUnmrBkLaE/foobar/',
 u'red-hat-repository': u'no',
 u'relative-path': u'Uh5U7f/Library/custom/eQsfHYQhEVUUnmrBkLaE/foobar',
 u'sync': {u'status': u'Not Synced'},
 u'updated': u'2016/08/19 09:29:20',
 u'url': u'http://inecas.fedorapeople.org/fakerepos/zoo3/'}

In [7]: assert repository['download-policy'] == 'on_demand'
```

The following test cases can be automated for **YUM** repositories **ONLY**:

- [x] As a user I can create a new repository using the **immediate** download policy (default). Assert that download policy matches the expected value;
- [x] As a user I can create a new repository using the **on_demand** download policy. Assert that download policy matches the expected value;
- [x] As a user I can create a new repository using the **background** download policy. Assert that download policy matches the expected value;
- [x] As a user I cannot create a new repository using a random value for the download policy field. Assert that repository is not created;
- [x] As a user I can create a new repository using any of the allowed values for download policy but cannot update this field to a random value that does not match the allowed values. Assert that the download policy is **not** updated;
- [x] As a user I can create a new repository using the **immediate** download policy (default) and update it to use the **on_demand** download policy. Assert that the download policy is updated to the expected value;
- [x] As a user I can create a new repository using the **immediate** download policy (default) and update it to use the **background** download policy. Assert that the download policy is updated to the expected value;
- [x] As a user I can create a new repository using the **on_demand** download policy (default) and update it to use the **immediate** download policy. Assert that the download policy is updated to the expected value;
- [x] As a user I can create a new repository using the **on_demand** download policy (default) and update it to use the **background** download policy. Assert that the download policy is updated to the expected value;
- [x] As a user I can create a new repository using the **background** download policy (default) and update it to use the **immediate** download policy. Assert that the download policy is updated to the expected value;
- [x] As a user I can create a new repository using the **background** download policy (default) and update it to use the **on_demand** download policy. Assert that the download policy is updated to the expected value;
- [x] As a user I should get an exception if I try to set the download policy field for non-YUM repositories;

All of these tests should be part of our `Tier1` suite and could go into the existing `cli/test_repository.py` module.

**Comment by rochacbruno** [comment]
@pondrejk If you have any problem running the shell, I also recommend you to run `$ make pyc-clean` in robottelo directory to get rid of old pre-compiled modules since there was module naming changes.

**Comment by pondrejk** [comment]
I added  the cases required in the checklist, though it would be nice to check if the repos actually behave according to the specified policy during the sync. Probably a topic for a separate issue.

**Comment by omaciel** [comment]
@pondrejk agreed that this would be a different thread.
