### ISSUE TITLE
Implement stubs from cli.test_myaccount.py

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#3742]

**Comment by renzon** [comment]
While checking into this issue I found that https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_myaccount.py is very similar to https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_user.py. Should I merge tests?

**Comment by elyezer** [comment]
I thinking merging then seems reasonable

**Comment by sghai** [comment]
I think `My Account` is more relevant to webUI, to manage user's self account from `My Account` menu. In CLI, we don't have any separate sub-command for my account so we should merge this.

**Comment by renzon** [comment]
@oshtaier pointed out on #3847 how my_account is different from user:

```
hammer -u ADMIN_USER -p ADMIN_PASSWORD update user --name MY_ACCOUNT --newname MY_ACCOUNT2
```

and 

```
hammer -u MY_ACCOUNT -p MY_ACCOUNT_PASSWORD update user --name MY_ACCOUNT --newname MY_ACCOUNT2
```
