### ISSUE TITLE
CLI - content-host subcommand no longer exists upstream

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#3780]
There was an update somewhere in between  `nightly.201607122230gitba43845.el* ` and `nightly.201608302211gitd696e2e.el*` which removes the `hammer` `content-host` subcommand, leaving only `host` subcommand in place.

That being said, it renders our `CLI` code outdated and we need to update it.

**Comment by rplevka** [comment]
Confirmed by devs via e-mail:
> In 6.2 most everything had been moved to 'hammer host' commands (hammer host update, hammer host subscription, hammer host errata), we had just not gotten around to deleting the content host command.  It is now gone.

**Comment by sghai** [comment]
Yes, This needs to be handled on priority.

@abalakh @oshtaier @svtkachenko : Guys, can any of you please take this up once your done with on-going task ?

**Comment by rplevka** [comment]
Closing in favor of https://github.com/SatelliteQE/robottelo/issues/3939

**Comment by abalakh** [comment]
@sghai sorry, missed your request. anyway it's picked up as i've submitted another issue #3939 which is currently in progress. I'll post any updates there
