### ISSUE TITLE
Fix CLI negative tests to check error messages -- second half

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#3800]
Related to #3749 #3611 #3768 
Working on o-v on list from #3611

**Comment by sghai** [comment]
@pondrejk : I think we can close this issue for now. If needed, we can re-open it or open a new one later ? what do  you think ?

**Comment by pondrejk** [comment]
Well, if I remember correctly, at the meeting there was a decision that this is not a needed solution, so I'm ok with closing.
