### ISSUE TITLE
Update documentation about required RPM package

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#3808]
Please update our documentation to mention that the package redhat-rpm-config is required to install all of our requirements.

**Comment by elyezer** [comment]
I am wondering why that package is needed?

I usually install the group `Development Tools` and the package `python-devel` for being able to compile C libraries. Also depending on the library additional header files are needed, for example  Cryptography package requires headers provided by the packages `libffi-devel` and `openssl-devel`.

**Comment by elyezer** [comment]
I went ahead and checked that `redhat-rpm-config` is the package that provides `/usr/lib/rpm/redhat/redhat-hardened-cc1` required by cffi package. I am sending a pull request to update documentation.
