### ISSUE TITLE
Duplicate test UUID across the test suite

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#3834]
I spotted some duplicate UUIDs while doing my routine check. I guess we should fix them to keep Polarion gods happy ;):
```bash
$ grep "@id" */*.py | sort | uniq -d
api/test_repository.py:        @id: 6dff0c90-170f-40b9-9347-8ec97d89f2fd
api/test_variables.py:        @id: a90b5bcd-f76c-4663-bf41-2f96e7e15c0f
cli/test_hostgroup.py:        @id: 32be4630-0032-4f5f-89d4-44f8d05fe585
cli/test_hostgroup.py:        @id: c468fcac-9e42-4ee6-a431-abe29b6848ce
ui/test_contenthost.py:        @id: 13b9422d-4b7a-4068-9a57-a94602cd6410
ui/test_hostcollection.py:        @id: 5a6fff0a-686f-419b-a773-4d03713e47e9
ui/test_remoteexecution.py:        @id: 7f0cdd1a-c87c-4324-ae9c-dbc30abad217
ui/test_repository.py:        @id: 8037a68b-66b8-4b42-a80b-fb08495f948d
```

**Comment by pondrejk** [comment]
maybe Travis should check this

**Comment by rochacbruno** [comment]
I added #3735 to cover this, (I am waiting the #3721 to be merged, so I can use the same structure to add the needed command (I already checked betelgeuse tools needed to do that)

**Comment by rochacbruno** [comment]
@omaciel what would be the strategy for that found duplicates? keep the oldest and change the newest test?

**Comment by omaciel** [comment]
@rochacbruno yes, but is the plan to do this automatically or show the failure and let the contributor manually update the uuid?

**Comment by rochacbruno** [comment]
@omaciel the idea is to run the validation on travis CI, so it is going to fail. also **make test-robottelo** should run  @rplevka's `$ grep "@id" */*.py | sort | uniq -d` before test. So contributor can run locally

**Comment by rochacbruno** [comment]
@omaciel @rplevka 

We can 2 two things.

1. add `grep "@id" */*.py | sort | uniq -d` as a call before **make test-robottelo** and if any output returned it exists with error.

2. add a command in robottelo **manage genuuids --path=filename**

That command will find any occurence of empty  `@id: ` and generate a new ID and automatically fill it.

So when writing stubs we can just generate all ids in bulk for that file.

**Comment by omaciel** [comment]
@rochacbruno I wonder if we should use a pre-commit hook that calls the make task? So folks have no choice and have to fix things **before** they can commit?

**Comment by rochacbruno** [comment]
@omaciel the pre-commit hook will call **make test-robottelo** anyway, good idea, but everyone should add the hook locally
