### ISSUE TITLE
Automate uploading SRPM package via UI

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#3846]
Uploading a `srpm` package into a custom repository fails with the following error:

![screenshot from 2016-09-21 09-47-35](https://cloud.githubusercontent.com/assets/53362/18713485/763f5444-7fe0-11e6-906c-2be8ab3be948.png)

The following automated test cases should be added:
## Setup
- Create a new organization
- Create a new custom product
- Create a new custom repository **without** using a **feed**
## Positive Upload Test
- Upload a `srpm` package
- Assert that the package was successfully uploaded
- Assert that the package can be listed/displayed

Feel free to use the [abrt](http://archive.fedoraproject.org/pub/archive/fedora/linux/releases/14/Fedora/source/SRPMS/abrt-1.1.13-2.fc14.src.rpm) package but let's also discuss if we should keep this file somewhere else just to make sure that our packages are always around.

**Comment by omaciel** [comment]
@SatelliteQE/quality-engineers should we store a `srpm` somewhere?

**Comment by sghai** [comment]
@omaciel: how about in data ? https://github.com/SatelliteQE/robottelo/tree/master/tests/foreman/data

**Comment by elyezer** [comment]
Please consider using https://repos.fedorapeople.org/pulp/pulp/fixtures/, there you have RPMS, DRPMS, SRPMS that can be downloaded to the machine which is running Robottelo and then uploaded to the system.

**Comment by omaciel** [comment]
@elyezer yup, as soon as the fixture issue for signing those repos is finished we can start using these repos.

**Comment by Ichimonji10** [comment]
I'm working on https://github.com/PulpQE/pulp-fixtures/issues/32 right now.

**Comment by rplevka** [comment]
this has already been addressed for all: API, CLI and UI
