### ISSUE TITLE
Automate synchronizing SRPM package via API/CLI/UI

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#3854]
# Request

Since **pulp** allows one to synchronize `source rpms` (aka `srpms`), we need to make sure that we can perform the synchronization of repositories containing this type of content.

## Setup

* Create a new organization **ORG**
* Create a new lifecycle environment **LCE** with **LIBRARY** as its prior environment
* Create a new product **PROD**
* Create a new cusotm repository **REPO** with a feed pointed at ~~`https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/test_srpm_repo/`~~  `https://repos.fedorapeople.org/repos/pulp/pulp/fixtures/srpm/` (note the `srpm` part of the url)

## Tests

* Synchronize content and assert that it is fully synchronized and that `srpms` can be listed
* Synchronize content, add product to a content view, publish it and make sure that `srpms` can be listed under the proper content view
* Synchronize content, add product to a content view, publish it, promote it to  and make sure that `srpms` can be listed under the proper content view

## Validation

Since `srpms` are **not** displayed on Satellite interface, there are three possible ways to validate that this type of content has been successfully synchronized:

* Look under `/var/lib/pulp/published/yum/https/repos/ORG/Library/custom/PROD/REPO/` and make sure that you see files with names ending in `.src.rpm`
* Open a connection (GET) against `http://SATELLITE_FQDN/pulp/repos/ORG/Library/custom/PROD/REPO/drpms/` and check that the listing returned contains packages with names ending in `.src.rpm`
* Create a new host and associate it with a product containing `srpm` packages. Run `yum install` or `dnf install` and check that you can install a `srpms`

I recommend we use either the first or second method.

**Comment by abalakh** [comment]
May i take it? :)

**Comment by omaciel** [comment]
@abalakh please! :) Also, now you can use https://repos.fedorapeople.org/repos/pulp/pulp/fixtures/srpm/ for the repo and not the one mentioned in the issue :)
