### ISSUE TITLE
Question: HotBackup test pipeline

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#3905]
For Hot Backup feature we have test cases like this:

```
        @Setup:
        Populate the system with hosts/repos/contents
        @Steps:
        1. Run full backup (base)
        2. Make config change c1
        3. Run incremental backup ib1
        4. Restore base backup, verify c1 config doesnt not exist
        5. restore ib1, veirfy c1 config does exist
        6. Make config change c2
        7. run katello-backup <path_to_ib1> --incremental
        @Assert: Backup "ib1" is backed up.
```

Online backup can run along with the system (no need to shutdown or restart the system) but it is time consuming, also we can have race conditions if backup occurs along with other automation tests.

So I think we need a separated pipeline for sys/backup tests, reasons:
1. we do not want it to take longtime so we are not going to backup a heavily full system
2. we want to assert incremental backups so ensure parallel tests will not compromise the assertions
3. if something went wrong we want to have a clean debug and log

> NOTE: Backup tests are all `run_in_one_thread`  
## **Solutions**:

**Put at the end of existing pipeline.**
1. install pytest-order plugin
2. make backup tests to be the latest to run after some tier test ends
3. record separate artifacts on backup class teardown (system logs)

Pros: we have a system populated by previous tests. 
Cons: Backup errors will fail that tier, we can have more entities than needed taking a longtime to backup.

---

**Create a new pipeline only for sys/backup tests**
1. It can be triggered after tier4, we can have a `pytest.mark.sys`
2. Starts with clean system
3. Populate the system only with sufficient number of important entities
4. Artifacts will be separated anyway
5. It is a ONE THREAD pipeline

Pros: all the above
Cons: One more pipeline to maintain

---

Ideas?

**Comment by rochacbruno** [comment]
@kbidarkar @sghai @omaciel I am writing the tests but we need to discuss the pipeline in the next mtg, any ideas?

**Comment by ldjebran** [comment]
As a general idea we can create a service resource locker when a test case timeout waiting to lock some  resource the test runner will skip that test and send it to a a retry queue. and when all the tests pass, the test runner run the retry tests queue (until the retry number of all functions will be achieved).

example:
```python 
@lock_resource(resource='some_resource_id', timeout=60, retry=2)
def test_some_test _that_need_resource(self):
     pass
```
or in a function :
```python
def test_some_test _that_need_resource(self):
    ...
    with locking_resource(resource='some_resource_id', timeout=60)):
        pass
```
lock_resource and locking resource will try to acquire resource locking , if resource locking acquired, the service will return a uuid of the lock, before exiting the function will release the lock providing the uuid (only the holder of the locking uuid can unlock the resource) or the resource will be automatically released in a predefined max time (if not released in time).

Pros: We can be sure that only one thread/process is using the resource
Cons:
1. a service to maintain
3. the project already progress with well known to the team tiers procedure

**Comment by rochacbruno** [comment]
I figured out today that while `katello-backup` has `--online-backup` the `katello-restore` has not (which makes total sense as it is destructive action). But we may need to change the existing stubs.

And also, our ability to test `restore` demands stopping the system, which requires separated pipeline,

I am going to create a `backup` mark for those tests.

@kbidarkar is it possible to run those tests in a separate environment?

**Comment by kbidarkar** [comment]
I think as we have limited resources, we should be using the same existing pipeline, but create a separate job for it. Let this backup-job run after all the tier and rhai jobs run.  Example: Similar to upgrade jobs.

If anyone has any suggestions, we can take that too into consideration in a team meeting.

**Comment by rochacbruno** [comment]
This is now resolved as `@destructive`
