### ISSUE TITLE
repo download policy tests (api/cli/ui) need cherry pick to 6.2.z branch

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#3907]
Applies to commits:
https://github.com/SatelliteQE/robottelo/pull/3771/commits
https://github.com/SatelliteQE/robottelo/pull/3737/commits
https://github.com/SatelliteQE/robottelo/pull/3740/commits
https://github.com/SatelliteQE/robottelo/pull/3734/commits

**Comment by pondrejk** [comment]
I created a PR for cli and api tests https://github.com/SatelliteQE/robottelo/pull/3908
I'm not sure about the ui tests, since the commit (https://github.com/SatelliteQE/robottelo/pull/3771/commits/862b64523cac17fe85c22562c4e9bc007b294f1d) is mixed with other changes, @rochacbruno can you please check if this can be cherry-picked?

**Comment by rochacbruno** [comment]
@pondrejk the UI commit can't be cherry picked because `locators.py` have been promoted to a module `locators/*`

I think I can copy/paste the test cases if needed. @JacobCallahan is it needed to backport the UI tests to 6.2.z?

**Comment by JacobCallahan** [comment]
@rochacbruno yes. as of right now, this functionality is in the 6.2.z branch.

**Comment by rochacbruno** [comment]
covered in #3910

**Comment by sghai** [comment]
@rochacbruno : I think this issue can be closed now ?
