### ISSUE TITLE
Wish Alex a Happy Birthday!!!

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#3909]
# Test Case

Wish @oshtaier a very happy birthday and a wonderful day!

# Assertion

Make sure he knows how pleased we are to have him on-board and how valuable he is for this team!

![Happy Birthday](http://www.reactiongifs.com/wp-content/uploads/2013/06/birthday.gif)

**Comment by sghai** [comment]
@oshtaier : Happy B'day Alex :)

**Comment by sghai** [comment]
Oh forgot to ACK ;)

**Comment by rochacbruno** [comment]
```console
$./hap.py --birthday --to=alex --aka="sasha,oshtaier"
```

**Comment by pondrejk** [comment]
All the best @oshtaier !

**Comment by oshtaier** [comment]
Thank you guys!!! :) Appreciate that
