### ISSUE TITLE
Using API for performance or UI for isolation?

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#3928]
I see the discussion here: #3923 and @oshtaier pointed out using UI instead of API or CLI for isolations. The con in this approach is performance, once UI takes longer. In fact I have used API a lot to create user on #3924. So for this cases where we create a entity for every test (setUp/tearDown) should we use UI or API is fine?

**Comment by svtkachenko** [comment]
I think it was not `API` vs `UI` but rather `(API + CLI)` vs `only API` or `only CLI`.
That's becase we have some helpers implemented only in nailgun while other implemented only in hammer.

**Comment by rochacbruno** [comment]
I think API is preferable, but if functionality is missing then CLI preferable than UI factories. 
(in fact, should be better to have a single point of interaction with factory and internally it decides what to use)
