### ISSUE TITLE
System should be able to register with ak, even when Service Level is not set or raise some validation error

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#3929]
`Steps to Reproduce:`
1. Don't set any Service Level when creating Activation Key
2. subscription-manager register --org="RCH" --activationkey="<AK>" --force

`Actual results:`
It fails to register but one does not know why. 

`Expected results:`
System should be able to register, even when Service Level is not set. Otherwise, make Service Level Mandatory and fail if it's empty during creation

More info: https://bugzilla.redhat.com/show_bug.cgi?id=1385731

**Comment by sghai** [comment]
This needs to be automated on priority when referenced bz will be fixed.

**Comment by JacobCallahan** [comment]
This is likely the default testing behavior, so covered by all tests involving ak-based registration.

**Comment by swadeley** [comment]
> This is likely the default testing behavior, so covered by all tests involving ak-based registration.

I agree, AK registration test don't set a service level.
