### ISSUE TITLE
CLI: Merge content-host and host tests and drop content-host module

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#3939]
```
hammer content-host --help
Error: No such sub-command 'content-host'

See: 'hammer --help'
```

Content-hosts were completely dropped from hammer (in favor of hosts). This means we need to compare content-hosts and hosts tests, add whatever is missing to hosts module and completely drop cli content-hosts module for 6.3.

**Comment by abalakh** [comment]
Two more sub-tasks:
* drop all the content-host calls in any other tests (e.g. `make_content_host`) in favor of host.
* As set of required and acceptable options for content-host and host differs, we need to add new helper to create some 'fake' host which will pass all required arguments for host creation (something similar to `nailgun.entities.Host().create_missing()`)

**Comment by rplevka** [comment]
Closing https://github.com/SatelliteQE/robottelo/issues/3780 in favor of this one.

**Comment by abalakh** [comment]
@rplevka thanks, somehow i missed #3780 and basically submitted the same issue

**Comment by abalakh** [comment]
@sghai hey, i'm facing issue while porting [this test](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_contenthost.py#L348) - for hosts it just returns
```
E           [ERROR 2016-12-14 07:31:40 API] 422 Unprocessable Entity
E           [ERROR 2016-12-14 07:31:40 Exception] Name has already been taken
```
error. Is this test valid only for content-hosts (then we should drop it) or it's just a bug?

**Comment by sghai** [comment]
@abalakh : In 6.2 we can't have two hosts/content-hosts with same name afaik. I tried with this cmd:
```
# hammer -u admin -p changeme host subscription register --name test123 --lifecycle-environment-id=1 --content-view-id=1
Host successfully registered
```
If I register another host with same name, I don't see any error( could be abug) but host list doesn't show two different entries.

**Comment by abalakh** [comment]
@sghai tl;dr following scenario (2 hosts with the same name) definitely shouldn't be supported for 6.3 and i can drop that test for sure, right?
I'm curious why we have test for 2 content hosts with the same name in place if it wasn't supported for 6.2 though.

**Comment by sghai** [comment]
@abalakh : yes, you can drop the test for 6.3.

In6.2, we introduced a new feature called host-unification  but not completely as you still a few sub-commands there in 6.2 under content-host. My guess is that this test was added during 6.1 but I'm not 100% sure.
