### ISSUE TITLE
cli - naive proxy retrieval approach used causing errors

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#3942]
There's a naive approach used for getting the default (internal) capsule/smart proxy in the setUp() fixtures for `HostUpdateTestCase` and `HostDeleteTestCase`, causing test errors on irregular basis:

https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_host.py#L334
https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_host.py#L387
`edit`: API tests included:
https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_organization.py#L354

This approach does not count on possibility of another capsule being in place already, which might be printed as a first one (index 0). The sorting does not happen by id but by label (or a name?).

So from time to time, with no cleanup in place, test gets satellite with some capsule already in place considering it to be the internal one.

```
2016-10-25 14:50:25 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv proxy list --per-page="10000"
2016-10-25 14:50:28 - robottelo.ssh - DEBUG - <<< stdout
Id,Name,URL,Features
15,0eS0XZRGUE,https://sat6.com:9470,"Pulp, TFTP, DNS, DHCP, Puppet, Puppet CA, Dynflow, Discovery, Openscap, SSH"
1,sat6.com,https://sat6.com:9090,"Pulp, TFTP, DNS, DHCP, Puppet, Puppet CA, Dynflow, Discovery, Openscap, SSH"
...
2016-10-25 14:50:33 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv host create (...) --puppet-proxy-id="15"
```

another concurrent test, responsible for the fake capsule might in the meantime remove the capsule and, ta-daa:

```
ERROR 2016-10-25 14:50:36 Exception] ERROR:  insert or update on table "hosts" violates foreign key constraint "hosts_puppet_proxy_id_fk"
DETAIL:  Key (puppet_proxy_id)=(15) is not present in table "smart_proxies".
```

The test fails.

proposed fix:
use id=1 for the internal proxy (as it is always 1) or do the additional filtering.

**Comment by svtkachenko** [comment]
Still should be cherry-picked for 6.1 and 6.2

**Comment by svtkachenko** [comment]
Finally can be closed.
