### ISSUE TITLE
[bug] wrong logic in the TestCase logger setup causes duplicate messages

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#3979]
The current logic in the [_set_worker_logger](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/test.py#L106) fixture causes additional handlers being attached to the logger per each call of `setUpClass`, resulting in huge (hundreds of Megs to Gigabytes) robotello*.log files per tier per build!

- __root cause__: new handler is being created (with new hash) and attached to the logger without checking whether the logger already has such handler attached.

- __proposed fix__: use `handler.set_name()` in order to be able to identify the handler and wrap the attaching logic into a conditional (if such handler already attached => ignore)

- [x] master - https://github.com/SatelliteQE/robottelo/pull/3980
- [x] 6.2.z - https://github.com/SatelliteQE/robottelo/pull/3981

**Comment by rochacbruno** [comment]
@rplevka yeah good catch.
 we were using `--boxed` when that thing was implemented, and that caused the handlers to be isolated.

**Comment by rplevka** [comment]
@omaciel thanks for merging the master PR, but there's also a pending `6.2.z` cherry-pick attached to this issue.
