### ISSUE TITLE
Change Bugzilla decorator behavior

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#3997]
@omaciel wrote a internal document about using bugzilla flags to improve the behavior of decorator. So this issue aims to evolve our decorator according to it

**Comment by renzon** [comment]
The main idea is using flags (6.3, 6.2.x) to indicate which version the bug is fixed. So a value of + do 6.3 and ? to 6.2.z means we didn't decide if the fix must be cherry picked to z stream. If we decide so, the bug is cloned so its status can be ON_QA again so QE team can verify it on z strem. The original bug has its 6.2.z flag changed from ? to +.

@omaciel: on this scenario, lets say original is verified for 6.3 and cloned is still on ASSIGNED. Should the test run for 6.2.z or not? To me the answer is it should not run once it is not on z stream. But in this case, once we are not going to change the BZ number, implementation will more comples. We are going to check the + for minor version and check cloned BZ status.

Our document about process says it should run, and this would cause failures before the BZ get into ON_QA status.

**Comment by omaciel** [comment]
@renzon congratulations, I think you have found a flaw in my design :) I wanted to avoid having to update our code with new Bugzilla IDs, but what you said is correct. One thing that may be on our side is the fact that, by the time we run the automation, the fix associated to the cloned issue is already available in the proper branch, so even though the **original** issue shows as `VERIFIED` with `sat-6.3.0+, sat-6.2.z+` flags, the **cloned** issue would have a status of `ON_QA` and `sat-6.3.0+, sat-6.2.z+` flags too.

**Comment by rplevka** [comment]
any reason for creating a dupe of ?https://github.com/SatelliteQE/robottelo/issues/3868 ?

**Comment by rplevka** [comment]
@renzon @omaciel - a flaw? If I recall our recent conversation with @omaciel, the + should be set *after* devs fix the issue, not at the moment they decide to clone it.
That way we should not really need to look for the clone BZ id.

**Comment by renzon** [comment]
@rplevka I hope the process works. But letting them change original bz after it get on z stream seems "dangerous". Maybe we could do that onde we have verified the cloned bug on z stream.

Anyway, I opened this issue because I was not aware of #3868. So I am closing this in favor of it, once it has more details.

**Comment by omaciel** [comment]
@rplevka 'flaw' in the sense that it is assumed that flags are set at the right time, but what you said is correct.
