### ISSUE TITLE
GUI/CLI: Enter test stubs for GIT puppet repo mirroring.

### ISSUE THREAD

**Issue by cswiii** [SatelliteQE/robottelo#400]
Enter test stubs, as seen below, into an appropriate .py test suite within the automation.

PLEASE NOTE:  These may not be able to be automated yet, as functionality might not exist.  But at least we have test cases ready to go.

<pre>
# Notes for Puppet GIT puppet mirror content
# 
# This feature does not allow us to actually sync/update content in a GIT repo.
# Instead, we're essentially "snapshotting" what contains in a repo at any
# given time. The ability to update the GIT puppet mirror comes is/should be provided
# by pulp itself, via script.  However, we should be able to create a sync 
# schedule against the mirror to make sure it is periodically update to contain
# the latest and greatest.

def puppet_git_local_crud_create_gui(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - Local GIT puppet mirror - create link
@Setup: Assure local GIT puppet has been created and found by pulp
@Steps:  
1.  Create link to local puppet mirror
@Assert: Content source containing local GIT puppet mirror content is created
@Status: Manual
""" 

def puppet_git_local_crud_update_gui(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - Local GIT puppet mirror - update/modify link
@Setup: Assure local GIT puppet has been created and found by pulp
@Steps:  
1.  modify details for existing puppet repo (name, etc.)
@Assert: Content source containing local GIT puppet mirror content is modified
@Status: Manual
""" 

def puppet_git_local_crud_delete_gui(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - Local GIT puppet mirror - delete link
@Setup: Assure local GIT puppet has been created and found by pulp
@Steps:  
1.  Delete link to local puppet mirror
@Assert: Content source containing local GIT puppet mirror content no longer exists/is available.
@Status: Manual
""" 

def puppet_git_remote_crud_create_gui(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - remote GIT puppet mirror - create link
@Setup: Assure remote GIT puppet has been created and found by pulp
@Steps:  
1.  Create link to local puppet mirror
@Assert: Content source containing remote GIT puppet mirror content is created
@Status: Manual
""" 

def puppet_git_remote_crud_update_gui(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - remote GIT puppet mirror - update/modify link
@Setup: Assure remote  GIT puppet has been created and found by pulp
@Steps:  
1.  modify details for existing puppet repo (name, etc.)
@Assert: Content source containing remote GIT puppet mirror content is modified
@Status: Manual
""" 

def puppet_git_remote_crud_delete_gui(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - remote GIT puppet mirror - delete link
@Setup: Assure remote GIT puppet has been created and found by pulp
@Steps:  
1.  Delete link to remote puppet mirror
@Assert: Content source containing remote GIT puppet mirror content no longer exists/is available.
@Status: Manual
""" 

def puppet_git_sync_gui(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test:  Sync git mirror
@Setup: git mirror (local or remote) exists as a content source
@Steps:  
1.  Attempt to sync content from mirror
@Assert: Content is pulled down without error
@Assert: Confirmation that various resources actually exist in local content repo
@Status: Manual
""" 

def puppet_git_sync_schedule_gui(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test:  Scheduled Sync git mirror
@Setup: git mirror (local or remote) exists as a content source
@Steps:  
1.  Attempt to create a scheduled sync content from mirror
@Assert: Content is pulled down without error  on expected schedule
@Status: Manual
""" 

def puppet_git_view_content_gui(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test:  View content in synced git puppet mirror
@Setup: git mirror (local or remote) exists as a content source
@Steps:  
1.  Attempt to view contents of repo
@Assert: Spot-checked items (filenames, dates, perhaps checksums?) are correct.
@Status: Manual
""" 

def puppet_git_sync_with_content_change(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: If module changes in GIT mirror but the version in manifest does not change, content still pulled
@Setup: Assure remote GIT puppet has been created and found by pulp
@Steps:  
1.  Sync a git repo and observe the contents/checksum etc. of an existing puppet module
2.  Assure a puppet module in git repo has changed but the manifest version for this module does not change.
3.  Using pulp script, update repo mirror and re-sync within satellite
4.  View contents/details of same puppet module
@Assert: Puppet module has been updated in our content, even though the module's version number has not changed.
@Status: Manual
""" 

def puppet_git_local_crud_create_cli(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - Local GIT puppet mirror - create link
@Setup: Assure local GIT puppet has been created and found by pulp
@Steps:  
1.  Create link to local puppet mirror via cli
@Assert: Content source containing local GIT puppet mirror content is created
@Status: Manual
""" 

def puppet_git_local_crud_update_cli(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - Local GIT puppet mirror - update/modify link
@Setup: Assure local GIT puppet has been created and found by pulp
@Steps:  
1.  modify details for existing puppet repo (name, etc.) via cli
@Assert: Content source containing local GIT puppet mirror content is modified
@Status: Manual
""" 

def puppet_git_local_crud_delete_cli(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - Local GIT puppet mirror - delete link
@Setup: Assure local GIT puppet has been created and found by pulp
@Steps:  
1.  Delete link to local puppet mirror via cli
@Assert: Content source containing local GIT puppet mirror content no longer exists/is available.
@Status: Manual
""" 

def puppet_git_remote_crud_create_cli(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - remote GIT puppet mirror - create link
@Setup: Assure remote GIT puppet has been created and found by pulp
@Steps:  
1.  Create link to local puppet mirror via cli
@Assert: Content source containing remote GIT puppet mirror content is created
@Status: Manual
""" 

def puppet_git_remote_crud_update_cli(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - remote GIT puppet mirror - update/modify link
@Setup: Assure remote  GIT puppet has been created and found by pulp
@Steps:  
1.  modify details for existing puppet repo (name, etc.) via cli
@Assert: Content source containing remote GIT puppet mirror content is modified
@Status: Manual
""" 

def puppet_git_remote_crud_delete_cli(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test: CRUD - remote GIT puppet mirror - delete link
@Setup: Assure remote GIT puppet has been created and found by pulp
@Steps:  
1.  Delete link to remote puppet mirror via cli
@Assert: Content source containing remote GIT puppet mirror content no longer exists/is available.
@Status: Manual
""" 

def puppet_git_sync_cli(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test:  Sync git mirror
@Setup: git mirror (local or remote) exists as a content source
@Steps:  
1.  Attempt to sync content from mirror via cli
@Assert: Content is pulled down without error
@Assert: Confirmation that various resources actually exist in local content repo
@Status: Manual
""" 

def puppet_git_sync_schedule_cli(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test:  Scheduled Sync git mirror
@Setup: git mirror (local or remote) exists as a content source
@Steps:  
1.  Attempt to create a scheduled sync content from mirror, via cli
@Assert: Content is pulled down without error  on expected schedule
@Status: Manual
""" 

def puppet_git_view_content_cli(self):
"""
@Feature: Puppet - GIT puppet mirror
@Test:  View content in synced git puppet mirror
@Setup: git mirror (local or remote) exists as a content source
@Steps:  
1.  Attempt to list contents of repo via cli
@Assert: Spot-checked items (filenames, dates, perhaps checksums?) are correct.
@Status: Manual
""" 

</pre>

**Comment by sghai** [comment]
I think we should add all these test stubs in Robottelo and we can give a name like `test_gitpuppet_mirror.py` or something else. It was tested during 6.0 and close this out.

**Comment by omaciel** [comment]
@svtkachenko please file a separate issue to handle the actual automation of these, please?

**Comment by sghai** [comment]
@svtkachenko : hey as you were asking about some info around this feature as how we can use it. So pasting my comments here:

<sghai> stkachen, I need some time to find exact steps.. but in short  'pulp-puppet-module-builder' utility does all the magic.  pulp-puppet-tools rpm provides this utility
<sghai> stkachen, so this utility checkout all the modules from git repo and publish them so that those can be synced via sat server
<sghai> this utility publish the modules on local file system so repo type file:/// can be used for sync

**Comment by sghai** [comment]
@svtkachenko : shared an article with you that includes all info around this feature `3.4.3. Importing Puppet Modules from a GIT repo`. hope that helps.

**Comment by svtkachenko** [comment]
Both 6.2 and 6.3 stubs are merged.
