### ISSUE TITLE
invalid_names_list should no longer return long strings

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4005]
since `6.3` the most (if not all) string-length restrictions have been removed.
It means the negative tests expecting error to be raised on using such string no longer pass.

There is however a restriction in data payload which is sent to the server, so we can perhaps try to update the `gen_string(300)` by something much bigger, that would trigger this restriction.

https://github.com/SatelliteQE/robottelo/blob/master/robottelo/datafactory.py#L100

**Comment by rplevka** [comment]
Need to check whether the restriction has been removed also from other entities. Following is a list of test files utilizing the `invalid_names_list`:

 - [ ] tests/foreman/api/test_activationkey.py

 - [ ] tests/foreman/api/test_architecture.py

 - [ ] tests/foreman/api/test_contentview.py

 - [ ] tests/foreman/api/test_contentviewfilter.py

 - [ ] tests/foreman/api/test_environment.py

 - [ ] tests/foreman/api/test_repository.py

 - [ ] tests/foreman/api/test_template.py

 - [ ] tests/foreman/api/test_user.py

 - [ ] tests/foreman/cli/test_user.py

 - [ ] tests/foreman/ui/test_activationkey.py

 - [ ] tests/foreman/ui/test_computeresource.py

 - [ ] tests/foreman/ui/test_computeresource_rhev.py

 - [ ] tests/foreman/ui/test_contentview.py

 - [ ] tests/foreman/ui/test_gpgkey.py

 - [ ] tests/foreman/ui/test_hostcollection.py

 - [ ] tests/foreman/ui/test_organization.py

 - [ ] tests/foreman/ui/test_partitiontable.py

 - [ ] tests/foreman/ui/test_user.py

 - [ ] tests/foreman/ui/test_usergroup.py

 - [ ] tests/foreman/ui/test_variables.py

 - [ ] tests/robottelo/test_datafactory.py

**Comment by svtkachenko** [comment]
@rplevka By `There is however a restriction in data payload` you mean Satellite restriction or http server restriction? According to apache documentation [1] `LimitRequestBody` parameter is responsible for this but by default it is set to 0 that means unlimited.

[1] http://httpd.apache.org/docs/2.4/mod/core.html#limitrequestbody

**Comment by rplevka** [comment]
@svtkachenko I meant the data which is being put into the GET request => URL.
I've filed a BZ to cover this: https://bugzilla.redhat.com/show_bug.cgi?id=1401519

**Comment by svtkachenko** [comment]
Looks like only `Architecture` entity in `tests/foreman/api/test_architecture.py` is affected. Corresponding bug is opened. I think described in this issues changes are not needed.

**Comment by rplevka** [comment]
Looks like `UserGroup` entity is being affected as well, see results for:
```tests.foreman.cli.test_usergroup.UserGroupTestCase.test_negative_update_by_name```

**Comment by JacobCallahan** [comment]
Closing this issue since it has not been acted upon up until this point. Future component owners can reopen if they are going to address this.
