### ISSUE TITLE
automated 'hammer csv' testing

### ISSUE THREAD

**Issue by thomasmckay** [SatelliteQE/robottelo#4009]
The tests being written by devs for 'hammer csv' are meant to be run against a live server. We write them, record the output via VCR, and then use that for the github pull-request tests (non-live server). As devs, though, the tests/recording is most often against katello nightly. Since my goal for hammer csv is to be backwards compatible to Sat-6.2, there is a chance for gaps if not tested regularly against Sat-6.2, Sat-6.3, and katello. Perhaps the dev-written tests could be included in a QE suite somehow?

Here is an example test: https://github.com/Katello/hammer-cli-csv/blob/master/test/resources/activation_keys_test.rb

**Comment by elyezer** [comment]
@thomasmckay I think those tests can be added to the QE suite. I have some points that I need some clarification:

* Do you want to run the already written tests? Then we can add this a build step into the jobs
* Or do you want to the tests be ported to Python (Robottelo is written in Python) and QE start managing the tests.
* Do you want these tests to be run against a live or not live server? QE automation always runs against live servers.
* How do you want the test results be reported? By sending an email or providing a job URL so you or anyone interested on seeing the results can access and take a look?

Thank you for the issue, maintaining the compatibility is something that we should care about.

**Comment by thomasmckay** [comment]
>     Do you want to run the already written tests? Then we can add this a build step into the jobs
I would prefer the already written tests be run. The devs can continue to add new cases then as part of their normal workflow.

>     Or do you want to the tests be ported to Python (Robottelo is written in Python) and QE start managing the tests.
QE contribution to the test suite is welcome but no porting to python. QE could even, for example, open github issues (or redmine) against the test suite if they feel it is deficient in some way and do not wish to write ruby tests.

>     Do you want these tests to be run against a live or not live server? QE automation always runs against live servers.
Live servers are preferred.

>     How do you want the test results be reported? By sending an email or providing a job URL so you or anyone interested on seeing the results can access and take a look?
I am unfamiliar with my options, but an email with status and link is fine. If there is a way to email the github project managers, that would be fantastic.

Thanks!

**Comment by lpramuk** [comment]
We can have ```tests/foreman/cli/test_csv.py```(to be implemented) be part of our robottelo test suite. When we trigger automation then hammer csv sub-command will be tested. Results in Jenkins ofc.

**Comment by sghai** [comment]
We will take care of this in our next automation sprint.

**Comment by elyezer** [comment]
@lpramuk let's use the tests developers wrote. Better to reuse them.

@sghai thank you, we just need to add the already written tests to the automation pipeline.

**Comment by ntkathole** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1670090
