### ISSUE TITLE
test_computeresource: TimeoutException: Message: Timeout waiting for page to load

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4017]
A lot of [age:1] Timeout failures happened on 6.2.4 build

```
tests/foreman/ui/test_computeresource.py:83: in test_positive_create_libvirt_with_description
    ['Description', description, 'field']
robottelo/ui/factory.py:434: in make_resource
    ComputeResource(session.browser).create(**create_args)
robottelo/ui/computeresource.py:118: in create
    self.click(common_locators['submit'])
robottelo/ui/base.py:649: in click
    self.wait_for_ajax(ajax_timeout)
robottelo/ui/base.py:429: in wait_for_ajax
    self.ajax_complete, 'Timeout waiting for page to load'
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
```

**Comment by lpramuk** [comment]
- tests.foreman.ui.test_computeresource.ComputeResourceTestCase.test_positive_access_libvirt_via_profile
- tests.foreman.ui.test_computeresource.ComputeResourceTestCase.test_positive_create_libvirt_with_console_password
- tests.foreman.ui.test_computeresource.ComputeResourceTestCase.test_positive_create_libvirt_with_description
- tests.foreman.ui.test_computeresource.ComputeResourceTestCase.test_positive_create_libvirt_with_display_type
- tests.foreman.ui.test_computeresource.ComputeResourceTestCase.test_positive_create_libvirt_with_name
- tests.foreman.ui.test_computeresource.ComputeResourceTestCase.test_positive_delete
- tests.foreman.ui.test_computeresource.ComputeResourceTestCase.test_positive_update_libvirt_name
- tests.foreman.ui.test_computeresource.ComputeResourceTestCase.test_positive_update_libvirt_organization

**Comment by lpramuk** [comment]
Probably caused by libvirt1 outage. Lets see next build.

**Comment by san7ket** [comment]
> ### nosetests tests.foreman.ui.test_computeresource:ComputeResourceTestCase
> .........
> ----------------------------------------------------------------------
> Ran 9 tests in 591.542s
> 
> OK

Closing this.
