### ISSUE TITLE
OperatingSystemTestCase.test_negative_create_with_too_long_description

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4021]
negative test failing with ```AssertionError: HTTPError not raised```
```
tests/foreman/api/test_operatingsystem.py:322: in test_negative_create_with_too_long_description
    description=gen_string('alphanumeric', 256)).create()
E   AssertionError: HTTPError not raised
```

**Comment by lpramuk** [comment]
- [ ] OperatingSystemTestCase.test_negative_create_with_too_long_description

**Comment by lpramuk** [comment]
BZ was fixed for 6.3 and thus the test stopped to be skipped also in 6.2 branch and started to fail for 6.2.
We need to change bz decoration for 6.2

**Comment by svtkachenko** [comment]
Flags for corresponding BZ were updated, with new `skip_if_bug_open` logic test is skipped on `6.2.z`

**Comment by svtkachenko** [comment]
Nope, bot still resetting flags, re-open.

**Comment by lpramuk** [comment]
"Flag dance" in https://bugzilla.redhat.com/show_bug.cgi?id=1328935 prevents us to close this issue

**Comment by lpramuk** [comment]
Test is being skipped for 6.2.z as I removed sat-6.2.z? from BZ

(decorator evaluates that it's a 6.3 BZ what was fixed)
