### ISSUE TITLE
[RFE] Generate and Use a lightweight manifest for tier1&2 Subscription tests

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4028]
Since we're affected by https://github.com/SatelliteQE/robottelo/issues/3869, perhaps it could be a good call to split the subscription-related tests to:
- those which would test the tier1&2 functionality (basic upload, delete, refresh). These would use a really lightweight manifest (containing few subscriptions) in order to mitigate the timeout issues (as much as possible). In order to mitigate trouble with many orgs in place, we could possibly force these tests to be ran among the first.
- those testing the performance under heavy load (as a part of tier3&4/longrun tests)- the fully-blown manifest with dozens of organizations in place ([BZ#1339696](https://bugzilla.redhat.com/show_bug.cgi?id=1339696))

**Comment by lpramuk** [comment]
With every created organization a manifest upload time gets longer by ~ 1.5 sec
With every created organization that has our QE manifest uploaded a manifest upload time gets longer by ~ 15 sec. 

An organization with our QE manifest counts 10x more than an empty organization.
So we've come up with an idea of lightweight manifest for low tiers.

**Comment by kbidarkar** [comment]
We were using a light weight manifest from Oct 2015 to Oct 2016, but then to be able to also test and automate with virt-who feature, virt-who subscriptions were added to the existing manifest in August 2016.

So, if we want to,
1) Ignore virt-who automation in robottelo , 
2) Ignore atomic automation in robottelo,
we can use a light weight manifest like we used earlier.

May be something to discuss about, as currently AFAIK the manifest contain virt-who and atomics subs and we no longer use "Employee subscriptions"

**Comment by kbidarkar** [comment]
The current manifest is already the most light-weight manifest which supports virt-who and atomic automation.

The current robottelo-automation manifest which our automation uses has,

1) Red Hat Enterprise Linux for Virtual Datacenters, Premium    ( For the RHEV hosts )
2) Red Hat Enterprise Linux Server, Premium (Physical or Virtual Nodes) ( For the physical hosts )
3) Red Hat Enterprise Linux Server, Premium (8 sockets) (Unlimited guests) ( For guests )
4) Red Hat Enterprise Linux Atomic Host ( For Atomic )

So already we are not using, RHEL Employee subscription.

**Comment by sghai** [comment]
Guys, if we are planning to regenerate another manifest for automation then please add atomic subscriptions. There are already some tests in robottelo using this subscription.

**Comment by rplevka** [comment]
@kbidarka, @sghai. You must have misunderstood my point. That was, to use 2 manifests for 2 types of tests. The current manifest would stay untouched, since I'm aware we use the subscriptions to test various features.

The lightweight one could contain a random single product. We would use it for tests, which only exercise the upload, refresh & delete manifest functionality. So basically for the tier1 or 2 tests.

The current design is an overkill causing timeouts on very basic tests (due to a BZ stated above)

**Comment by san7ket** [comment]
There are lot's of test's failing in upgrade testing , due to this issue. This is due to upgrade boxes are already populated with various features and pulp data.

```
4-tests.foreman.api.test_subscription
2-tests.foreman.api.test_repository_set  
```
