### ISSUE TITLE
Cherry-pick cli.filter to [6.2.z] and possibly [6.1.z]

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4037]
The following PR: https://github.com/SatelliteQE/robottelo/pull/3704 is applicable to at least [6.2.z] and it would be appropriate to backport it.

Haven't checked [6.1.z] but it should be backported there as well, if applicable

**Comment by svtkachenko** [comment]
Not applicable for 6.1
```
E           Command "role info" finished with return_code 64
E           stderr contains following message:
E           [ERROR 2016-11-30 09:16:24 Exception] Error: No such sub-command 'info'
```
