### ISSUE TITLE
cli.test_filter.FilterTestCase.test_positive_create_with - organizations and locations parameters ignored

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4038]
This is a bug in satellite which needs to be filed and the test to be decorated.

root cause (after a brief look) is either:
- hammer filter create|update --locations|--organizations|--location-ids|--organization-ids are ignored

or
- hammer filter list does not list the locations|organizations

**Comment by ldjebran** [comment]
registred bug:  https://bugzilla.redhat.com/show_bug.cgi?id=1401469

**Comment by ldjebran** [comment]
1. The problem is persistent only for 6.3 
2. for 6.2 the tests pass
3. for 6.1 one manually recreated the procedure and the results are as expected, but there is an other problem is that in 6.1 command hammer role has no info sub command
under 6.1 the hammer command: 
```bash
hammer role info --id="19"
```
lead to exception
```bash 
[ERROR 2016-12-05 05:58:17 Exception] Error: No such sub-command 'info'

See: 'hammer role --help'
Error: No such sub-command 'info'

See: 'hammer role --help'
[ERROR 2016-12-05 05:58:17 Exception] 

Clamp::UsageError (No such sub-command 'info'):
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:28:in `find_subcommand_class'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:17:in `instatiate_subcommand'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:10:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.13/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.13/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.13/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'
```

**Comment by ldjebran** [comment]
@sghai , @rplevka suggest:
1. to remove the Labels 6.1, 6.2 from this issue
2. decorate the org and loc tests in module tests/foreman/cli/test_filter.py with decorator skip_if_bug_open('bugzilla', 1401469')

**Comment by sghai** [comment]
@ldjebran : Agreed, since issue is reproducible with 6.3 and bz is already there so please decorate the tests with appropriate BZ ID and for master branch only.

**Comment by rplevka** [comment]
@ldjebran remove the labels which are not applicable. thx
