### ISSUE TITLE
Add Buzilla credentials on configuration

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#4045]
After playing some time with the Bugzilla API, I discovered "flags" is only available on authenticated calls. I opened a bug for it: https://bugzilla.redhat.com/show_bug.cgi?id=1399755. So I am going to add bugzilla credentials on robottelo.properties accordingly.

related to #3868

**Comment by omaciel** [comment]
@renzon talk to @sthirugn about perhaps using our internal QE account for this :)

**Comment by renzon** [comment]
@omaciel you kind of read my mind! But I was able to make the call adding my own credentials on robottello.properties. But after this change I will need to jenkins robottelo.properties and send email to all the team.

**Comment by sthirugn** [comment]
@renzon look at https://github.com/SatelliteQE/robottelo-ci/blob/master/scripts/satellite6-closed-loop.sh#L7-L8 to see how you can use the already configured jenkins bugzilla user.
