### ISSUE TITLE
Support for Compute profile for all type's of compute resouces

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#4076]
Currently, the compute profile that are supported are for Libvirt and docker .
But futher , on adding CR's like RHEV, Openstack and Vmware the options differ and these new fields should be supported.
These functionality will help in creating hosts on CR's , attaching compute profile to desired compute resources and in-turn to hostgroups.

- [x] EC2  https://github.com/SatelliteQE/robottelo/pull/4710

- [x] RHEV  https://github.com/SatelliteQE/robottelo/pull/4710

- [x] VMware  https://github.com/SatelliteQE/robottelo/issues/4964

- [ ] Openstack

**Comment by ldjebran** [comment]
@san7ket , is there some simple stubbed tests that I can implement when resolving this issue?

**Comment by san7ket** [comment]
There are stubs for all CR's , like in ui/test_computeresource_rhev.py 
`def test_positive_access_rhev_with_custom_profile(self):`

**Comment by ldjebran** [comment]
@san7ket , thanks

**Comment by rochacbruno** [comment]
@san7ket EC@ and RHEV added by @ldjebran in https://github.com/SatelliteQE/robottelo/issues/4710 can we close this issue?

**Comment by san7ket** [comment]
Could this issue be a tracker Issue for remaining 2 CR's Openstack and VMware. 
I can always file another issue to cover remaining Cr's

**Comment by san7ket** [comment]
Not relevant anymore, airgun should have this
