### ISSUE TITLE
CLI Host setUp function needs refactoring

### ISSUE THREAD

**Issue by ldjebran** [SatelliteQE/robottelo#4105]
https://github.com/SatelliteQE/robottelo/blame/master/tests/foreman/cli/test_host.py#L1389

This setUp test function create a VM and in 6.3 latest compose there is a problem with installing katello-agent and the tests will fail because of this, and VMs are not deleted after setup crash
suggest  to make:
```python
try:
    ...
    # create VM
   ...
except Exception as exc:
    # delete VM
    raise exc

```

**Comment by abalakh** [comment]
Good catch, but it should be solved in a different way - by introducing cleanup functions here (`unittest.TestCase.addCleanup()`)
