### ISSUE TITLE
Replace all the tierDown and tierDownClass with cleanup functions

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#4113]
Inspired by #4105 and #4106 
tearDown has one serious drawback - it's executed only in case of failure inside the test and is not executed in case of exception inside setUp or setUpClass. 
Cleanup functions are being executed regardless of root place of failure, i.e. no matter if the failure happened in test or in setUp/setUpClass.
We should replace all the tearDown/tearDownClass calls with cleanup functions if we want to be sure all the post-conditions are being executed regardless of place where the failure happened.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
