### ISSUE TITLE
PEP8 and Robottelo style guide

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#4141]
[PEP8](https://www.python.org/dev/peps/pep-0008/#imports) and [Robottelo's official docs](http://robottelo.readthedocs.io/en/latest/code_standards.html#recommended) state the same about import:

>  Imports should be grouped in the following order:
> 
>     standard library imports
>     related third party imports
>     local application/library specific imports
> 
>     You should put a blank line between each group of imports. 

Besides that [on reviews](https://github.com/SatelliteQE/robottelo/pull/4118#discussion_r94018192) different style is required. In our unnoficial doc you can find style guide to import like this:

```python
    import a  
    import b  
    import c  
    from d.a import a  
    from d.c import z  
    from z import a  
``` 
But once it is not stating groups of import, it is ambiguous.

My personal concern here is that automated tool like Pycharm and vim plugin follow strictly PEP8 so it reorganize import like this:

```python
# PEP 8
import logging
from functools import wraps
from xml.parsers.expat import ExpatError, ErrorString

import bugzilla
import pytest
import re
import requests
import unittest2
from six.moves.xmlrpc_client import Fault

from robottelo.config import settings
from robottelo.constants import BZ_OPEN_STATUSES, NOT_IMPLEMENTED
from robottelo.host_info import get_host_sat_version
``` 
But once from imports are required to be together on reviews, one need to manually organize them:

```python

import logging

import bugzilla
import pytest
import re
import requests
import unittest2
from six.moves.xmlrpc_client import Fault

from functools import wraps
from robottelo.config import settings
from robottelo.constants import BZ_OPEN_STATUSES, NOT_IMPLEMENTED
from robottelo.host_info import get_host_sat_version
```
Currently flake is not reinforcing import styling 

So I see 2 options:

1) Follow PEP8, the upstream style guide so people,like me with Pycharm, can let automated tools take care of imports and turn on reinforcement on flake 8 if possible.

2) Keep import of kind "from" together, changing Robottelo docs accordingly and making people to organize import manually.

Obviously I vote on 1, but what you   @SatelliteQE/quality-engineers think?.

**Comment by rochacbruno** [comment]
My vote is to use PEP8 standard style, then we can run autopep8 in our codebase to fix current style. Also we can include flake8-import-order plugin on travis-ci.

**Comment by svtkachenko** [comment]
+1 for automating the process.

**Comment by ldjebran** [comment]
-1 for automating the process , can lead to serious hidden problem

**Comment by rochacbruno** [comment]
@ldjebran on "automate the process" we mean using `Ctrl + Alt + L` in PyCharm for example, which automatic adjusts pep8 and import order. Or of course use another plugin for doing that in a different editor, vim python, emacs-python-mode and others can do that. Also there is auto-pep8 command line tool which can do that.

So if we move to use pep8 import style, we need to run the fix once, or maybe we just do that on demand.

But I really think it is better to use pep8 ordering.

**Comment by ldjebran** [comment]
@rochacbruno , thanks 

+1 pep8 ordering (this is the best option) :) 
+1 also for an automated refactoring (that should touch only the import ordering) that goes in it's own PR, think we can do it once with the script you mentioned.
