### ISSUE TITLE
Decorate CLI test_positive_errata_list_of_sat_server with BZ #1351040

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4149]
- [ ] tests.foreman.cli.test_host.HostErrataTestCase.test_positive_errata_list_of_sat_server

6.2.7 automation results:
```
E           CLIReturnCodeError: Command "host errata list" finished with return_code 70
E           stderr contains following message:
E           [ERROR 2017-01-06 07:31:49 Exception] undefined method `installable_errata' for nil:NilClass
E           undefined method `installable_errata' for nil:NilClass
E           [ERROR 2017-01-06 07:31:49 Exception] 
```

**Comment by lpramuk** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1351040 is quite messy 
- reported for 6.2
- verified for 6.3 !!!
- failing for 6.2
- having pluses for both versions !!!

**Comment by rplevka** [comment]
I believe we can close this since this is getting EOL soon
