### ISSUE TITLE
assertion based on a hardcoded NIC list in discovery_host tests

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4156]
There are occurrences of the assertions based on a hardocded NIC list. This doesn't necessary match the actual NIC names of the Domain, since the IF names might come out unpredictable.
e.g. this would fail on fedora VM:

https://github.com/SatelliteQE/robottelo/blame/master/tests/foreman/ui/test_discoveredhost.py#L598

possibly we could get the actual list of the interfaces by ssh-ing to the domain and executing something like:
```bash
ip -o link | awk '{gsub(/:/,""); print $2}'
```

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
