### ISSUE TITLE
Add oscap capsule support to Hostgroup

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#4171]
Add support to add openscap capsule , while creating hostgroup.

**Comment by kbidarkar** [comment]
I think, this will be UI only for Sat6.2 and both CLI and UI for sat6.3 + nightly.

**Comment by san7ket** [comment]
Not currently as Bz is not fixed yet for 6.3 for the oscap cli hammer plugin, will make this UI currently and then later when bz is fixed fot CLI
