### ISSUE TITLE
UI - BookmarkTestCase: tests are failing randomly due to pagination

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4211]
- [ ] ui.test_bookmark.BookmarkTestCase .test_positive_update_bookmark_query
- [ ] ui.test_bookmark.BookmarkTestCase.test_positive_delete_bookmark
- [ ] ui.test_bookmark.BookmarkTestCase.test_positive_update_bookmark_name

Boomark tests are randomly failing due to existing pagination on Bookmarks page as 
they are unable to access items from the end of the alphabet

Checking results 113 bookmarks created, but only first 20 are visible. There are six pages
Bookmarks name starting with letter [E..Z] are not on the first page.

A lottery is going on here:
 If a test draws a name not from begging of the alphabet then such test fails.

**Comment by lpramuk** [comment]
Not to go paginate there had to be search field.
There were BZ for missing search field on Bookmarks page... And you can guess what happened to it.

**Comment by abalakh** [comment]
To deal with pagination in SetUp section there's a change for items_per_page set to some huge value, and tierDown returns items_per_page to its original value. The thing is, tests are executed in 8 threads, so as soon as 1 thread is done, it returns items_per_page to 20, causing other threads to randomly fail.

**Comment by abalakh** [comment]
Very easy but also ugly way to fix it is to use `@run_in_one_thread` decorator, but we'd better think of some clever solution instead. Too bad there's no searchbar, and most like it won't be there ever.

**Comment by rplevka** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1322012

**Comment by abalakh** [comment]
Fixed by #4243 #4252
