### ISSUE TITLE
Subscription tests fail for rhel6

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4212]
looks like there is  a subscription missing after uploading our fake manifest.
Oddly enough, it appears on `rhel7`.

a screenshot from another test reveals that the subscription was in place for another org even for rhel6:
![screenshot](http://storage9.static.itmages.com/i/17/0120/h_1484920812_7865991_5f298e3be8.png)

**Comment by abalakh** [comment]
I really hope it will be gone with #4207 #4208 SatelliteQE/nailgun#359 SatelliteQE/nailgun#360

**Comment by rplevka** [comment]
@abalakh just to make myself clear - i'm not talking about timeout issues.

**Comment by rplevka** [comment]
fixed
