### ISSUE TITLE
Workaround selenium's left parenthesis issue in Base class

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#4218]
Some of our UI helpers require typing left parenthesis into text field (e.g. compute resource name `test (Libvirt)`) to find and select correct value from drop down list, but as Selenium can't send left parenthesis (SeleniumHQ/selenium#674) such helpers contain workarounds to do so. There're at least 3 different places as for now (2 in `robottelo/ui/hosts.py` and 1 in `robottelo/ui/container.py`), and all are basically the same, so it would be nice to workaround this issue somewhere in Base class - inside `Base.select` or `Base.assign_value` not to have to copy-paste the same workaround to each place where the issue occurs.

Example of such workaround:
https://github.com/SatelliteQE/robottelo/blob/master/robottelo/ui/container.py#L74

**Comment by oshtaier** [comment]
`ActionChains(self.browser).key_down(Keys.SHIFT).send_keys('9').key_up(Keys.SHIFT).perform()` is overkill solution for that problem till we migrate to geckodriver
Approach should be implemented on base class `assign_value` level and all test affected fixed, so we can easily remove workaround in future

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
