### ISSUE TITLE
Bug 1262029 with new status CLOSED WONTFIX

### ISSUE THREAD

**Issue by ldjebran** [SatelliteQE/robottelo#4228]
Automation https://github.com/SatelliteQE/robottelo/pull/2762 
has been written for bug https://bugzilla.redhat.com/show_bug.cgi?id=1262029
but closed with status CLOSED WONTFIX

for the last build it has not failed but expected (locally already failing), as from now it will not be skipped any more.

**Comment by rochacbruno** [comment]
To be addressed in #4261

**Comment by rochacbruno** [comment]
Fixed in #4320
