### ISSUE TITLE
Fix package group install/remove on HostCollectionPackageManagementTest

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#4229]
On master the test for HostCollection is using FAKE_0_YUM_REPO (https://github.com/renzon/robottelo/blob/70304fd8faee092b283853a7978312dacc1e8d2c/tests/foreman/ui/test_hostcollection.py#L412-L412) while master is using FAKE_6_YUM_REPO. It turns out the former does not have package group called "birds", so this need to be fixed when sat 6.3 become our main target again.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
