### ISSUE TITLE
Replace nailgun.entites.ConfigTemplate calls with ProvisioningTemplate

### ISSUE THREAD

**Issue by svtkachenko** [SatelliteQE/robottelo#4232]
Replace `nailgun.entites.ConfigTemplate` calls with `nailgun.entites.ProvisioningTemplate`

`ConfigTemplate` now is deprecated, however new `ProvisioningTemplate` have at least 1 known problem [1]
`ProvisioningTemplate` added in SatelliteQE/nailgun#365

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1416040

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
