### ISSUE TITLE
incorrect provider type in custom job template UI test

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#4244]
Tier 3 test for running a custom job template errors out on provider type definition https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_remoteexecution.py#L439 
```
E UINoSuchElementError: JobTemplate: element ('xpath', u"//ul/li/div[normalize-space(.)='SSHExecutionProvider']") was not found while trying to click
```
According to experimentation in browser, "SSHExecutionProvider" should be chaneged just to "SSH". 

Note that this is limited to 6.3 as in Sat 6.2 the option is still called "SSHExecutionProvider"

**Comment by oshtaier** [comment]
Haven't mentioned that you assigned that to yourself and prepared PR too =)
Anyway, gonna merge yours as it is fixing the issue

**Comment by pondrejk** [comment]
@oshtaier thanks
