### ISSUE TITLE
Performance tests and numpy

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#4247]
There is a set of tests in https://github.com/SatelliteQE/robottelo/tree/master/tests/foreman/performance
which uses the `tests.ConcurrentTestCase` base class.

Checking our builds I can't find where those tests run, is that being used?

The problem is that it requires `numpy` and this library takes a long time to install in our CI and builds.
(in Travis it takes up to 9 minutes to install numpy)

We can save some minutes in builds if we remove numpy from our requirements, so I am proposing to remove numpy from requirements and then if there is any build running those tests do the `numpy` installation there in the build script.

**Comment by elyezer** [comment]
AFAIK these tests are not being run anymore, I think we can either drop them or move to a separated repository where robottelo is installed as a library.

**Comment by rochacbruno** [comment]
@omaciel this is low priority, but it is one more thing we can do to save time in builds.

**Comment by omaciel** [comment]
@rochacbruno first of all 💯  for looking into this! About 2 years ago we used to run these tests for the old performance team but they have been ignored for a while. How about we create a branch (or any other suggestion; I just don't want to completely delete the tests... yet) and then remove the tests (and most importantly, their dependencies) from master, 6.1.z and 6.2.z branches?

**Comment by rochacbruno** [comment]
@omaciel @elyezer we can keep the code there, only remove the dependency from requirements.

We just need to:
1) Do a conditional import `try: import numpy except: numpy=None` so it wont break framework with import error, then in the `ConcurrentTestCase` we check `if numpy is None: raise` so it fails only if one day we decide to run, so we know `numpy` needs to be included in CI script to be installed. 

2) Make linters, docstring checkers, and documentation to ignore that files.
