### ISSUE TITLE
locator update in host unification UI tests

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#4253]
A couple of tier 3 host unification UI tests (HostContentHostUnificationTestCase) error out with:

```
E  ValueError: Provided locator <|strategy=xpath|value=//div[@id='interfaceModal']//select[contains(@id, '_type')]|> is not supported by framework
```
Probably connected to setting the interface type for a host, occurs on 6.3 only.

**Comment by rochacbruno** [comment]
@pondrejk which is that a local test? which version of selenium was used? `pip freeze | grep selenium` and what are the configs in robottelo.properties regarding browser and driver?

I can see that menu locators has changed in 6.3, but I could not find where the locator `/div[@id='interfaceModal']//select[contains(@id, '_type')]` is being used?

**Comment by pondrejk** [comment]
@rochacbruno, no it is not local, it was automation-6.3-tier3-rhel, so I think the selenium version is given by automation-tools. Good point, I can't find where the locator (host.interface_type) is actually utilized, though I'm not a UI guru, however this suggests a quick fix -- removing the thing.

**Comment by odovzhenko** [comment]
@pondrejk and @rochacbruno 
According to latest test results this issue is no longer relevant.
Could you please close it if so?
