### ISSUE TITLE
Tests involving capsules should be run in a single thread until BZ#1393034 is resolved

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4258]
- __original issue__: if capsule is created, it is automatically assigned to the all existing organizations (it is not isolated since it leaks to other tests)
- __proposed solution__: explicitly specify the organization_ids during creating a proxy (e.g. in `make_proxy` factory methods)
  - __issue__: `organizations`, `organization_ids`, `locations`, `location_ids` parameters are being ignored due https://bugzilla.redhat.com/show_bug.cgi?id=1393034 :)
  - __proposed solution__: all tests involving capsule manipulation should be run in a single thread to prevent interference with other tests, until above BZ is being resolved

**Comment by abalakh** [comment]
I think we can link #4242 as a part of it (only for 6.2.z api tests)

**Comment by rplevka** [comment]
@abalakh thanks, yes, that PR is a subset of this.
We also need to include other tests using proxy.
e.g. `cli.test_location.test_remove_proxy`, etc.

**Comment by abalakh** [comment]
I think if we decide to decorate these tests it would be nice to implement some `@run_in_one_thread_if_bz_open()` decorator, as otherwise we'll need to manually remove the decorator when bz is closed.

**Comment by rplevka** [comment]
@abalakh yes, we came to the same conclusion with @lpramuk while we discussed this offline - we even came to the same name for the decorator :D

**Comment by ldjebran** [comment]
@rplevka @abalakh,  despite the run_in_one_thread one test (tests.foreman.api.test_smartproxy.CapsuleTestCase.test_positive_create_with_name)
failed in the last compose 4 on rhel7 but not massively as before

**Comment by rplevka** [comment]
@ldjebran it acutally failed for rhel6, not 7. However the root cause of that one is different.
https://github.com/SatelliteQE/robottelo/issues/4174

I'm looking into that one.

**Comment by sghai** [comment]
Guys, Can we fix this issue on priority ? its affecting so many tests post upgrade.. All post upgrade tier1 tests related to smart class parameters and smart variables are failing because of it. Please see issue #4575 for more info.

**Comment by ldjebran** [comment]
@sghai will try to make the same changes for CLI as for API in https://github.com/SatelliteQE/robottelo/pull/4242/files

**Comment by sghai** [comment]
@ldjebran Thank you.. that would be a big help.
