### ISSUE TITLE
Rename bz_bug_open to affected_by_bz and improve its logic

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#4262]
That function **NOT THE DECORATOR** will be renamed to `affected_by_bz` and the logic is:

- Return True if:
  - OPEN - Current used approach
  - CLOSED - WONTFIX
  - CLOSED - CANTFIX

- Return False if:
  - CLOSED (verified, onqa) - Current used approach

**Comment by renzon** [comment]
Logic was already improved on #4263, so now it's only a matter of renaming. Working on it

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
