### ISSUE TITLE
Improve exception handling for 'UnexpectedAlertPresentException' error

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#4270]
Usually, if you see that exception, it means that test code has flaws or mistakes and need to be fixed properly to handle all alerts that is expected from application side, but sometimes, there is a chance that something goes wrong and alert is displayed where it should not. In that case,  it will be very good to have at least information that contained inside of that alert. Probably, we can try to wrap our most basic operation with a method that will put that information into the logs.
Pseudo code example:
```
alert = driver.switchTo().alert();
text = alert.getText();
logger.debug(u'Alert is displayed with a text: %s', text)
```

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
