### ISSUE TITLE
Test BZ 1285669

### ISSUE THREAD

**Issue by JacobCallahan** [SatelliteQE/robottelo#4291]
From the bug description:
"Through the API, I issued a DELETE on https://10.0.50.1/api/v2/hosts/52/interfaces/188 and the entire host got deleted"
For this test, we will need to construct a host, with at least one interface, then attempt to delete that interface. The host itself should not be deleted as a result.

[1] - https://bugzilla.redhat.com/show_bug.cgi?id=1285669

**Comment by abalakh** [comment]
Covered in #4388 #4336
