### ISSUE TITLE
Fake capsule expects nmap to be installed

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4309]
All rhel7 capsule tests failed because it expects that nmap is installed. But it is not.
```
2017-02-08 12:53:31 - robottelo.ssh - DEBUG - >>> nmap --open -p 9090 qe-sat62-rhel7.example.com | grep 9090
2017-02-08 12:53:31 - robottelo.ssh - DEBUG - <<< stderr
bash: nmap: command not found
```

I propose much better command to use:

```
nc qe-sat62-rhel7.example.com 9090 <<< ''
```
returns 0 when open 

(nc is already installed, no need to install it by automation-tools as with nmap it would be)

**Comment by ldjebran** [comment]
@lpramuk , you have to test nc on rhel7 and rhel6 as when have done some investigations I had some problems with the options on of them

**Comment by lpramuk** [comment]
Decided for changes in automation-tools instead due to RHEL6 strange behavior.
