### ISSUE TITLE
Test BZ 1335014

### ISSUE THREAD

**Issue by JacobCallahan** [SatelliteQE/robottelo#4315]
This test will require an activation key and a content host.

Steps to Reproduce:
1. Register the rhel6.8 against Satellite

2. Auto attach without specifying service level:
[root@dhcp-128-71 ~]# subscription-manager attach
Installed Product Current Status:
Product Name: Red Hat Enterprise Linux Server
Status:       Subscribed

3. Remove all consumed subscriptions and auto attach without specifying service level:

[root@dhcp-128-71 ~]# subscription-manager remove --all
1 subscription removed at the server.
1 local certificate has been deleted.
[root@dhcp-128-71 ~]# subscription-manager attach --servicelevel=premium
undefined method `[]=' for nil:NilClass
[root@dhcp-128-71 ~]# subscription-manager attach --auto --servicelevel=premium
undefined method `[]=' for nil:NilClass

[1] - https://bugzilla.redhat.com/show_bug.cgi?id=1335014

**Comment by abalakh** [comment]
Could you please provide more meaningful expected result? Absence of error doesn't guarantee command was successful - it could fail silently.
For example, maybe some subscription should be successfully returned by `list` command after step 3), or package installation should be successful afterwards?

**Comment by JacobCallahan** [comment]
As an initial assertion, we shouldn't see the error specified. I believe there is some kind of verification message upon a successful registration, however I cannot test that right now (6.2.8 blocker).

**Comment by abalakh** [comment]
@JacobCallahan absence of error and presence of successful message should be checked for sure, but that's not enough to prove command is working - what if the command does nothing and just returns success message?
I was asking what's the outcome of that command, what is it supposed to do? For example if it adds a new entry to a list of subscriptions - then we can add a step 4) to run the subscriptions list and make sure a new subscription is there in output. Or if it subscribes system to some subscription - then in step 4 we could try to install some package and make sure installation was successful.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
