### ISSUE TITLE
Bug 1420439 - Satellite does not push updated SCAP content on a policy

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#4323]
Please automate the issue defined by https://bugzilla.redhat.com/show_bug.cgi?id=1420439

**Comment by san7ket** [comment]
This could be a long-run test for oscap, will take this up

**Comment by san7ket** [comment]
Found multiple issues with the product while trying to implement.

**Comment by san7ket** [comment]
Closing this , PR Merged
