### ISSUE TITLE
UI PuppetClassTestCase - fails to update PC that are listed mutiple times

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4332]
It seems that puppet class description cannot contain html tags chars.
It doesn't have to be necessarily a bug.  
```
tests/foreman/ui/test_puppetclass.py:54: in test_positive_update_description
    class_name, param_name)
E   AssertionError: u'<body>oRsGqPOCcAqYMGOkbCLwrMTgJyqHn</body>' != u''
E   - <body>oRsGqPOCcAqYMGOkbCLwrMTgJyqHn</body>
E   +
```
Last 7 test results shows that non-html decriptions are ok to pass. While 2 html tags decriptions are not.

**Comment by lpramuk** [comment]
RHEL6 has test failed for non-html tag description either. I've better checked the behavior and confirmed a bug:

- https://bugzilla.redhat.com/show_bug.cgi?id=1422171
Unable to update Puppet Class with Class name has already been taken

In 6.2.7 it is ok in 6.2.8 it is not => regression

**Comment by lpramuk** [comment]
The issue vented only on automation machine.
I wasn't able to reproduce it elsewhere.

fake capsules causing this?

**Comment by lpramuk** [comment]
The machine where it vented has the same puppet classes listed multiple times.
That's what prevents updating them. Once I deleted classes and left only one last class (access_insights_client) I was able to update the class.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
