### ISSUE TITLE
Turn RHEL image name constants into robottelo.properties' settings

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4360]
We need to have it because of Vault Requests and we dont want to change the code seamlessly with evry RHEL dot release.

Settings is the right way.
Related changes in robottelo-ci are covered by https://github.com/SatelliteQE/robottelo-ci/issues/497

**Comment by kbidarkar** [comment]
This was fixed by turning RHEL image name constants into robottelo.properties settings.
