### ISSUE TITLE
Post upgrade [6.1 -> 6.2] tier1 test failures due to org name

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#4374]
```console
2017-02-20 18:03:27 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme  organization info --name="Default Organization"
2017-02-20 18:03:31 - robottelo.ssh - DEBUG - <<< stderr
[ERROR 2017-02-20 18:03:28 Exception] Error: organization not found
Error: organization not found
[ERROR 2017-02-20 18:03:28 Exception] 
```
This issue is tricky as it appears only on upgrade instances. When we upgrade sat server from 6.0 to later releases, the default org name remain as it was in 6.0 release i.e `Default_Organization`.  However tests are using `Default Organization` (notice w/o underscore)

A bunch of tests are affected w/ this.

**Comment by ldjebran** [comment]
@sghai perhaps we have to consider Default Organization and Default_Organization as synonyms so if Default Organization does not exist we have to try Default_Organization and vice versa what do you think?

**Comment by sghai** [comment]
@ldjebran : I think we are good for now as we are renaming org post upgrade and before running tier1 tests. 

@san7ket : could you please confirm if that change fix the tier1 tests and close this ?

**Comment by san7ket** [comment]
Yes , the fix works , PR was raised in automation tools , added under post-upgrade tasks
