### ISSUE TITLE
UI: Container creation fails with Internal Server Error ("unable to open database file")

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4389]
RHEL6
these tests have it in setUpClass
- [ ] ui.test_adusergroup.ActiveDirectoryUserGroupTestCase.* (all 4 tests)
- [ ] ui.test_bookmark.BookmarkTestCase.* (all 11 tests)
- [ ] ui.test_docker.DockerRegistryTestCase.* (all 6 tests)
- [ ] ui.test_subscription.SubscriptionTestCase.* (all 1 test)

RHEL7
these tests have it in setUpClass
- [ ] ui.test_adusergroup.ActiveDirectoryUserGroupTestCase.* (all 4 tests)
- [ ] ui.test_bookmark.BookmarkTestCase.* (all 11 tests)
- [ ] ui.test_docker.DockerRegistryTestCase.* (all 6 tests)
- [ ] ui.test_subscription.SubscriptionTestCase.* (all 1 test)

others that failed on rhel7 have it in ```setUp``` and failed majority of tests (but not all)
- [ ] + over 100 ui tests

```
robottelo/test.py:256: in setUp
    self._docker_browser.start()
robottelo/ui/browser.py:92: in start
    self._create_container()
robottelo/ui/browser.py:183: in _create_container
    ports=[4444],
../../shiningpanda/jobs/9c131512/virtualenvs/d41d8cd9/lib/python2.7/site-packages/docker/api/container.py:135: in create_container
    return self.create_container_from_config(config, name)
../../shiningpanda/jobs/9c131512/virtualenvs/d41d8cd9/lib/python2.7/site-packages/docker/api/container.py:146: in create_container_from_config
    return self._result(res, True)
../../shiningpanda/jobs/9c131512/virtualenvs/d41d8cd9/lib/python2.7/site-packages/docker/client.py:178: in _result
    self._raise_for_status(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <docker.client.Client object at 0x7f31b9e2b290>
response = <Response [500]>, explanation = None

    def _raise_for_status(self, response, explanation=None):
        """Raises stored :class:`APIError`, if one occurred."""
        try:
            response.raise_for_status()
        except requests.exceptions.HTTPError as e:
            if e.response.status_code == 404:
                raise errors.NotFound(e, response, explanation=explanation)
>           raise errors.APIError(e, response, explanation=explanation)
E           APIError: 500 Server Error: Internal Server Error ("unable to open database file")

../../shiningpanda/jobs/9c131512/virtualenvs/d41d8cd9/lib/python2.7/site-packages/docker/client.py:174: APIError
```

**Comment by rplevka** [comment]
This turned out to be a read-only file system issue caused by dying HDD on our docker host.

**Comment by lpramuk** [comment]
also 
```APIError: 500 Server Error: Internal Server Error ("Driver devicemapper failed to remove root filesystem c431d1343fbbff2d2d33ba4c7871d540848d4745d320f418ad77dd59a372480c: Error saving transaction metadata: Error creating metadata file: open /opt/docker/devicemapper/metadata/.tmp186568039: input/output error")```

happens in ```robottelo/ui/browser.py:197: in _remove_container```

**Comment by lpramuk** [comment]
Caused by sesame's hdd breakdown
