### ISSUE TITLE
bz_bug_is_open is acting strange

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4396]
one starting example:
- ```/job/automation-6.2-tier1-rhel7/40/testReport/tests.foreman.cli.test_import/TestImport/test_positive_translate_macros/```
- ```/job/automation-6.2-tier1-rhel6/38/testReport/tests.foreman.cli.test_import/TestImport/test_positive_translate_macros/```

Skipped in automation on 2017-03-01 (before it was tested until today):
```
Skipping test due to open Bugzilla bug #1325880.

Standard Output

2017-03-01 13:36:57 - robottelo - DEBUG - Started Test: TestImport/test_positive_translate_macros
2017-03-01 13:36:57 - robottelo.decorators - DEBUG - Bugzilla bug 1325880 found in cache.
2017-03-01 13:36:57 - robottelo.decorators - DEBUG - Skipping test test_positive_translate_macros in module tests.foreman.cli.test_import due to Bugzilla bug #1325880
2017-03-01 13:36:57 - robottelo - DEBUG - Finished Test: TestImport/test_positive_translate_macros
```
However, https://bugzilla.redhat.com/show_bug.cgi?id=1325880 is ```VERIFIED``` since 2016-07-20
and ```CLOSED``` since 2016-07-27 !!!

**Comment by rochacbruno** [comment]
@renzon can you handle this one together with #4263 ?

**Comment by lpramuk** [comment]
on my machine (correct):
```
>>> bz_bug_is_open('1414821')
True
```
on paprika:
```
>>> bz_bug_is_open('1414821')
False
```
let get in the guts:
```
>>> import bugzilla
>>> bz_conn = bugzilla.RHBugzilla()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jenkins/shiningpanda/jobs/92c1a260/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bugzilla/base.py", line 256, in __init__
    raise TypeError("Specify a valid bugzilla url, or pass url=None")
TypeError: Specify a valid bugzilla url, or pass url=None
>>> bz_conn = bugzilla.RHBugzilla(url=None)
>>> bz_conn.connect('https://bugzilla.redhat.com/xmlrpc.cgi')
>>> bz_conn.getbugsimple('1414821')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'RHBugzilla' object has no attribute 'getbugsimple'
>>> bugzilla.__version__
'2.0.0'
```
my machine:
```
>>> bugzilla.__version__
'1.2.2'
```
1.2.2 VS. 2.0.0



```

**Comment by renzon** [comment]
@lpramuk @rochacbruno yeah, I am going to look into it. I hope bugzilla provides a way to fetch cloned tickets.

**Comment by rochacbruno** [comment]
Maybe this problem is authenticated X unauthenticated calls?

**Comment by renzon** [comment]
Yeah, I think automation job is not injecting global passwords while running the job.

**Comment by lpramuk** [comment]
As I said @renzo standalone is authenticated  vs. automation is un-authenticated

satellite6-standalone-automation:
```
+ sed -i 's/# bz_password=.*/bz_password=****/' robottelo.properties
+ sed -i 's/# bz_username=.*/bz_username=some6-account@redhat.com/' robottelo.properties
```
```/job/satellite6-standalone-automation/configure```
[v] Inject passwords to the build as environment variables
   Global passwords [v]

automation-6.2-tier*-rhel*:
```
+ sed -i 's/# bz_password=.*/bz_password=/' robottelo.properties
+ sed -i 's/# bz_username=.*/bz_username=some6-account@redhat.com/' robottelo.properties
```
```/job/automation-6.2-tier1-rhel6/configure```
[ ] Inject passwords to the build as environment variables

**Comment by renzon** [comment]
Just created SatelliteQE/robottelo-ci#525

**Comment by renzon** [comment]
After last updated I checked automation and it correctly ran tests/foreman/cli/test_import.py::TestImport::test_positive_translate_macros for Sat 6.2 RHEL 7. So I am closing this issue but feel free to reopen it if any other bug related missing BZ creds is found.
