### ISSUE TITLE
Cover "Remote Execution Features"

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#4399]
You can view and update rex features:
- in UI under **Administer  > Remote Execution Features**
- with hammer:
```
hammer remote-execution-feature -h
...
Subcommands:
 info                          Show remote execution feature
 list                          List remote execution features
 update                        Update a job template
```
- in API under **/api/remote_execution_features**

This is presently not covered in automation

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
