### ISSUE TITLE
remote_execution test case - fetch results from a host after assertion fails

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4402]
It is hard to find the root cause of a job invocation failure since we do not fetch the job invocation output for a host.
We should execute `hammer job-invocation output` just before doing any Assertions - this will give us much more control over what's going on on a host.

**Comment by pondrejk** [comment]
Completed for CLI and UI tests in 6.2 and 6.3. Currently there are no rex tests in for api, and no rex available in 6.1, therefore closing
