### ISSUE TITLE
HW models: avoid using names starting with numbers due to BZ1265150

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4407]
- [ ] ui.test_hw_model.HardwareModelTestCase.test_positive_delete

HW models webui has a bug that leads to accessing/editing incorrect HW model.

https://bugzilla.redhat.com/show_bug.cgi?id=1429545 
**UI: HW model names starting with number are wrongly treated as IDs**

When HW model name starts with number (name converts to decimal) and there happen to be HW model with that ID, then it is edited instead of the one you want.
```
E                   UIError: Delete functionality works improperly for "1DbhktzWtK" entity
```
In reality the test was trying to delete HW model with ```id = 1``` instead !!! and that obviously failed as it is bound to internal capsule host.

In automation we need to avoid using such names unless BZ 1429545 is fixed.

**Comment by lpramuk** [comment]
Although not completely identical in symptoms with https://bugzilla.redhat.com/show_bug.cgi?id=1265150 the fix for it will resolve also this one.

Lets just ```s/1429545/1265150/```

**Comment by rochacbruno** [comment]
We implemented similar solution in the PR #4194 I think maybe fauxfactory needs some kind of builtin support to validation.

**Comment by rochacbruno** [comment]
```python
from fauxfactory import gen_string

name = gen_string(
    'alpha', 
    validator=lambda x: not x.startswith(('1', '2', '3', '4', '5', '6', '7', '8', '9', '0')),
    default='foobar',
    tries=10
)
```

So fauxfactory should accept `validator` which should return True, otherwise the value is `None` or `default`. If `tries` is set, then it retries to generate 10 times, if `tries` = `0` it tries to generate until validator is met!

@omaciel @rplevka what do you think? so we can address this case and also the case on gen_mac

**Comment by lpramuk** [comment]
@rochacbruno this is valid bug in Satellite. Why to generate names without starting numbers when such names are valid ?

In test we can have logic that clips numbers in the name beginning out of it...

**Comment by omaciel** [comment]
@rochacbruno +1 for adding a validator argument. Maybe it would be a regex instead of a function?

**Comment by lpramuk** [comment]
ah, validator argument, ok then

**Comment by lpramuk** [comment]
@rochacbruno validator argument, is it optional?
will it still generate names with starting numbers or not? or do you mean changing the behavior of the factory?

**Comment by rochacbruno** [comment]
@lpramuk I suggested to add an optional validator argument to fauxfactory (i'll opening issue there and move conversation to there) so it can address the case I mentioned in #4194 and also this case if we really want to avoid those names.

**Comment by renzon** [comment]
I am going to implement validation on fauxfactory and change this test after it.

**Comment by renzon** [comment]
Once https://github.com/omaciel/fauxfactory/pull/87 get merged I am going to change this test.

**Comment by rochacbruno** [comment]
if https://bugzilla.redhat.com/show_bug.cgi?id=1265150 (for 6.2) use faux factory validator to generate only names starting with non-digits.

*check if BZ is going to be cloned or flagged for 6.2 ( @JacobCallahan  )

**Comment by JacobCallahan** [comment]
@rochacbruno If that bug is something you want in a future 6.2.z release, let me know and I can push for it. However, in cases like this. we shouldn't just change the 6.2 flag from nil to ?.

**Comment by rochacbruno** [comment]
ok @JacobCallahan I added `sat-6.2.z ?` to the bug and then we can proceed applying the workaround with fauxfactory validator.

**Comment by renzon** [comment]
I just merged the new version of fauxfactory. But in this specific case I tend to agree with @lpramuk [comment](https://github.com/SatelliteQE/robottelo/issues/4407#issuecomment-284740339). What you guys think @rochacbruno @JacobCallahan ?

**Comment by rochacbruno** [comment]
```python
if bz_bug_is_open(1265150):
     # generate names without numbers using validators
else:
    # generate without validator

```

**Comment by renzon** [comment]
I started to work on this but [BZ 1265150](https://bugzilla.redhat.com/show_bug.cgi?id=1265150) is verifed and has sat 6.2.z + flag. So bz_bug_is_open will not have any effect on this, once the bug for z stream should be cloned and not having this flag. 

Another thing is that [original bz](https://bugzilla.redhat.com/show_bug.cgi?id=1429545) would no be a duplicate IMO. I have tested it on 6.2.9 and it is still there. I am going to test on 6.3 to check if it is solved there. If not I will remove dup there and use this BZ on the code.

**Comment by renzon** [comment]
Just confirmed issue is solved on sat 6.3.

**Comment by renzon** [comment]
@JacobCallahan Check my 2 comments above. What should I do with 6.2.z flag? Change it?

**Comment by rplevka** [comment]
`6.2` is EOL and the bugzilla got fixed.
