### ISSUE TITLE
Replace @ to : (vice-versa) in fix_uuids script.

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#4427]
We should extend existing[1] or create a new script to

1) if on branch master, script will find any token in docstring in format `@id:` to `:id:`
1) if on other branch do the reverse.

[1] https://github.com/SatelliteQE/robottelo/blob/master/scripts/fix_uuids.sh

**Comment by elyezer** [comment]
I will work on this today and should have a PR for both master and 6.2 branch soon.

**Comment by elyezer** [comment]
Sent #4434 for 6.2.z branch and #4435 for master branch

**Comment by elyezer** [comment]
@rochacbruno the related PRs are now merged, where those scripts should be integrated? Or we will recommend folks to run it when cherry-picking?

**Comment by rochacbruno** [comment]
@elyezer I think a target like `uuid-fix` is a good place, but we can add a new target for this one
and then call in `can-i-push?` target.

https://github.com/SatelliteQE/robottelo/blob/master/Makefile#L150

**Comment by elyezer** [comment]
@rochacbruno I like the idea of having a separated target and adding it to the can-i-push target

**Comment by elyezer** [comment]
Sent #4444 and #4445 to add the new make targets, when those PRs are merged we can close this issue.
