### ISSUE TITLE
KatelloAgentTestCase (and generally all client testing) uses released bits

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4429]
In this test case we use packages out of CDN, thus we test already released packages. But we should test the packages that are going to be released (i.e. out of internal repositories).

Specifically I spotted it in KatelloAgentTestCase but generally all client testing is performed that way, i.e. out of CDN (we hit client issues together with CUs)

Lets use internal candidate repos instead.

**Comment by lpramuk** [comment]
Unfortunately it brought us unwanted fruits already:
- https://bugzilla.redhat.com/show_bug.cgi?id=1431747

**Comment by kbidarkar** [comment]
The infra required for this already exists in robottelo.properties file and the necessary stuff have been put in place, this requires only changes in the robottelo repos. I thought this was fixed.

I would suggest, this needs to be fixed as below,

```
If cdn == true;
   use repos from GA  ( the current existing method )
else:
   repo == settings.robottelo.sattools_repo ( use the dogfood link )
```
robottelo-ci already updates the right link in the robottelo.properties file.


https://gitlab.redhat.com/satelliteqe/jenkins-configs/blob/master/robottelo.properties#L82

**Comment by kbidarkar** [comment]
This was the issue which was raised in 2015, https://github.com/SatelliteQE/robottelo/issues/3093

**Comment by sghai** [comment]
Guys, we need to fix this on priority..

**Comment by kbidarkar** [comment]
Some more details, for folks, who would be working on this, https://github.com/SatelliteQE/robottelo-ci/blob/master/scripts/satellite6-automation.sh#L47

The above script mentions how things are populated in the robottelo.properties file.

**Comment by kbidarkar** [comment]
- [ ] api/test_errata.py:    setup_org_for_a_rh_repo
- [ ] cli/test_activationkey.py:    setup_org_for_a_rh_repo
- [ ] cli/test_host.py:    setup_org_for_a_rh_repo
- [ ] ui/test_contenthost.py:    setup_org_for_a_rh_repo
- [ ] ui/test_hostunification.py:        setup_org_for_a_rh_repo
- [ ] ui/test_activationkey.py:        setup_org_for_a_rh_repo
- [ ] ui/test_hostcollection.py:    setup_org_for_a_rh_repo
- [ ] ui/test_errata.py:    setup_org_for_a_rh_repo
