### ISSUE TITLE
Update UI codebase to support geckodriver and latest Firefox versions

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#4494]
Starting from Firefox 48, Selenium-Webdriver is not supported as native driver. All attempts to add such support seems as not reliable and it becomes must have approach to move to geckodriver in order running any UI scripts on Firefox browser:
https://github.com/SeleniumHQ/selenium/issues/2559
https://github.com/SeleniumHQ/selenium/issues/2942

To run tests using geckodriver next steps needs to be performed:
1) Download and put latest geckodriver version into $PATH
https://github.com/mozilla/geckodriver/releases
2) Install latest Firefox browser version
https://www.mozilla.org/en-US/firefox/new

Blocking issues at that moment:
1) Actions are not implemented, so it is not possible to work with ActionsChain class:
https://github.com/mozilla/geckodriver/issues/233
However there is issue that is closed and functionality has to work:
https://github.com/SeleniumHQ/selenium/issues/2285
but after some testing procedures and trying different alternatives, still stuck with that. Code is actually present in selenium, but doesn't seem to perform real mouse hover event

**Comment by oshtaier** [comment]
Update

Firefox 53 Beta 10
At least due to https://github.com/webcompat/web-bugs/issues/5601 all execution procedures are blocked

Firefox 52.0.2 + Selenium 3.3.3+Geckodriver 0.15
1) Issue with Actions Chains described above (https://bugzilla.mozilla.org/show_bug.cgi?id=1292178) seems partially fixed and integrated into Geckodriver/Marionette. We can select organization from context sub-menu, but further execution seems hung up (https://bugzilla.mozilla.org/show_bug.cgi?id=1345653). Needs to re-test on stable Firefox 53.
2) Increased amount of `StaleElementReferenceException` that require to make revision of `wait_for_ajax` method.
3) Fundamental interaction between browser and Selenium seems broken as execution procedure can go too fast skipping intermediate actions that consequently get us to failure. Probably some revisions of generic waiter approach can help us. Step-by-step debug execution seems much more stable than direct run
4) Unexpected interactions with menu dropdowns can be also a reason for skipping intermediate actions. Seems as Selenium like to emulate real user actions even more natural than needed

Risks:
- Geckodriver/Marionette is basically a black box, so present and future issues almost automatically becomes a serious blocker for any test cases development in UI area

Summary:
- Development processes for Firefox and Geckodriver are very intensive, so we have to move from one stable set of requirements to another and never put 'latest' versions
- Most basic issues are being fixed right at that moment, so it is good idea to wait few more weeks till core will be updated enough
- A lot of test cases can be passed successfully in debug mode  or with small hacks, but it is still unacceptable from stability point of view

**Comment by oshtaier** [comment]
Update:

Firefox 53.02 + Selenium 3.4.1 + geckodriver 0.16.1

Blocker:
- Randomly entire execution procedure hung up. There are some common patterns, but still not easy to narrow root cause
- Unexpected interactions with menu dropdowns can be a reason for skipping intermediate actions

Anyway, we can see great improvement in all directions to support newest Firefox browsers, so we able to run one basic module completely:
```
nosetests tests/foreman/ui/test_architecture.py
......
----------------------------------------------------------------------
Ran 6 tests in 470.450s

OK
```

Conclusion:
We can start investigation procedures and try to fix existing issues in case necessary priority will be provided for that task

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
