### ISSUE TITLE
Distro has to be standardized among robotello project

### ISSUE THREAD

**Issue by ldjebran** [SatelliteQE/robottelo#4506]
After PR https://github.com/SatelliteQE/robottelo/pull/4379 , we have distro information came from settings, we cannot be sure what rhel product is installed on the VM by default, as depending on this distro we have to choose the rhel produts to install on the VM, and that should done automatically depending on the distro information.

for this purpose propose:

1- introduce PRODUCT_KEY for each rh products that enter robotello
example:
```python
PRODUCT_KEY_RHEL = 'rhel'
PRODUCT_KEY_SATELLITE_CAPSULE = 'rhsc'
PRODUCT_KEY_SATELLITE_TOOLS = 'rhst'
```  
  
1- standardize distro information like (this will not invoke any changes simply to retrieve information)
```python
     distro =  rhel76beta
```
 - chars 0:3  ->  the rhel product key  (mandatory) must exist in PRDS constant
 - char 5   -> rhel major version (mandatory)
 - char 6   -> rhel minor version (mandatory)
 - from char 6 (exclusively) the special release info (alpha beta rc1 rc2 ...) (optional)

 **or we have to move to more general form 'rhel-major.minor-release'  like rhel-7.3-beta**
**so in the future we can handle major and minors number more than 9:  rhel-11.10-beta**
**or to support the two forms (look first if special chars exist "-" and "." )**

2 -  we need to investigate on arch should make always equal to 'x86_64', or this has to be part of distro info like **'rhel-arch-major.minor-release'**

3 - create a class that can handle this distro information
```python
class Distro:
     def __init__(distro):
         self.validate(distro)
         self._distro = distro
 
     @classmethod
     def validate(cls, distro):
          # do distro validation
          raise error if not valid

    @property
    def major_version(self):
         # return the major version
    @property
    def minor_version(self):
         # return the minor version

    @property
    def product_key:
        # return the product key eg rhel
        # the key must exist in PRDS contant

    @property
    def arch(self):
       # we have to investigate how to our standard to handle this or by default 
       return u'x86_64'

    @property
    def release:
        # return beta alpha rc1 .. or None if not indicated

   @property
    def release_version:
        # return 
        return '{0}.{1}'.format(self.major_version, self.minor_version)

    def get_distro_product_info(self):
        # return the product info dict eg: 
        return {'product': PRDS[self.product_key],
        'repository_set': REPOSET['{0}.{1}'.fomat(self.product_key, self.major_version)],
        'repository_name': 'Red Hat Enterprise Linux {0} Server RPMs x86_64 {1}.{2}'.format(self.major_version, self.release_version),
        'repository_id': u'{0}-{1}-server-rpms'.format(self.product_key, self.major_version),
        'arch': self.arch,
        'releasever': u'7.3',
        'major_version': self.major_version}

    def get_rh_product_info(product_key):
        # return a product info dict in a more genral form
        if product_key == self.product_key:
            return get_distro_product_info()
        product_version_key = '{0}{1}'.format(product_key, self.majorversion
        return {'product': PRDS[product_key],
        'repository-set': REPOSET[product_version_key],
        'repository_name': REPOS[product_version_key]['name'],
        'repository-id': REPOS[product_version_key]['id'],
        'arch': self.arch}
```

that way we can for any distro get the appropriate products information and the needed validations 
```python
distro = Distro(distro_text)
rhel_info = distro.get_distro_product_info()  # this the rhel dict info 
sat_tools_product_info = distro.get_rh_product_info(PRODUCT_KEY_SATELLITE_TOOLS)
sat_capsule_product_info = distro.get_rh_product_info(PRODUCT_KEY_SATELLITE_CAPSULE)
```

 - @omaciel this a step forward to resolve your question https://github.com/SatelliteQE/robottelo/pull/4381#pullrequestreview-23724596

**Comment by lpramuk** [comment]
@ldjebran You are a bit mixing things.

With every dot rhel release (rhel7.2 7.3...) other repos stays same. 
It's not like to different dot release you need another repo No!

rhel72 + tools6.2 
rhel73 + tools6.2 

You better consider rhel7 as a continuos stream. This distro is just to be able to use diffrent/newer image of OS to test. **But it it is still the same RHEL7**

**Comment by ldjebran** [comment]
@lpramuk, thanks, yes I understand that the major version is the principal, 

The main idea is from the distro string extract the product info that we want without using the major version each time so the tests remain valid all the time even when majorversion RHEL8 enter production.
and even we can check  DISTRO == RHEL7,
retreive get_product_info_for_distro(DISTRO, SAT_TOOLS)  or Distro(distro).get_rh_product_info(PRODUCT_KEY_SATELLITE_TOOLS) and should return all the info necessary to select that product from UI-CLI-API

for the moment I do not see the usage of minor version (from the above usage) it's only needed for a detailed information of what exactly distro is. 

To achieve this we have to fix a format of the distro string, that should rarely change in time, and for that it must contain the full range of information.

for the exression: 
Distro(distro).get_rh_product_info(PRODUCT_SATELLITE_TOOLS),
you can even not explicitely know what is the major version, 

one example usage : 
```python
distro = get_satellite_distro()  # get the distro of sat server
# prepare products repositories
sat_tools = Distro(distro).get_rh_product_info(PRODUCT_SATELLITE_TOOLS)
# create product content view
repo_id = sat_tools.repository_id
# and create a vm with the same
   with VirtualMachine(distro=distro) as vm:
      vm.create()
      # subscribe vm host to sat
      vm.enable_rh_repo(sat_tools)
```
