### ISSUE TITLE
Distro constants not valid

### ISSUE THREAD

**Issue by ldjebran** [SatelliteQE/robottelo#4507]
Note 6.3 master branch these constants are not valid distros and many tests that use explicitly these constants to create a VM will fail :
```python
DISTRO_RHEL7="rhel7"
DISTRO_RHEL6="rhel6" 
```

**Comment by lpramuk** [comment]
these constants are overridden by settings 
did @kbidarkar commited his work also to master?

**Comment by lpramuk** [comment]
@ldjebran you have to update your settings (robottelo.properties) as these constants are overridden by settings

Check robottelo.properties.sample for hints

**Comment by ldjebran** [comment]
@lpramuk have you run some tests on 6.3 that use VM distro with these constants?

**Comment by ldjebran** [comment]
@lpramuk please show the line of code that update distro constants as I cannot find it, has some troubles with this when wanted to port the capsule code to master

**Comment by ldjebran** [comment]
the tests use these constants to create the vm and the vm raise raise VirtualMachineError distro not supported

**Comment by ldjebran** [comment]
Thanks @lpramuk I found the problem, I am having the capsule code that check the vm distro and compare it to the constants  DISTRO_RH6 and DISTRO_RH7 and as there constants are different from the real vm distro I was not able to choose the needed software.
if you cherry-pick that PR to 6.2.z the capsule tests will broken.

**Comment by ldjebran** [comment]
closing the issue as related to non compatiblity od vm_capsule with the new vm strategy
@lpramuk @rochacbruno @kbidarkar  please notify me when you have to cherry-pick this PR to 6.2.z as vm_capsule has to be updated too
