### ISSUE TITLE
[UI]  Tests time out waiting for dashboard to load

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4524]
ActivationKeyTestCase.test_positive_remove_user
DashboardTestCase.test_positive_search_random

The above test has timed out almost every single time since it got introduced.
There's a custom user being created and webdriver tries to login using its credentials. The login goes smooth and webdriver ends up on a Dashboard, where it times out to wait till all the widgets are loaded.

It is a pain and it's not even robottelo's fault. However, there might be few strategies we could apply.

- increase timeout (i don't like this, it's just a temporary and not very effective solution)
- exclude optional elements from the waiter function (widgets in this case) and have them tested in separate tests.
- ... YOU decide :)

The way we test it right now is suboptimal, since it allows some elements to fail completely unrelated tests.

**Comment by oshtaier** [comment]
There are much more tests that end up with the same issue. It was a moment when we always get to Hosts page rather than Dashboard after login, so problem cannot exist in its beginning, but now we need think about proper solution

**Comment by svtkachenko** [comment]
Ok, this time I've looked more carefully ( :D ),  custom user has no associated organization by default and that's why it has `Any Context` after login. And `Any Context` leads to timeouts.

**Comment by sghai** [comment]
Guys, where this issue stands ? Can we please spend some time and figure out possible ways to handle these timeouts.

**Comment by san7ket** [comment]
This affecting 2 dashboard tests in upgrade, the test cases are failed consistently 
tests.foreman.ui.test_dashboard.DashboardTestCase.test_positive_search
tests.foreman.ui.test_dashboard.DashboardTestCase.test_positive_search_random

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
