### ISSUE TITLE
[ui] DashboardTestCase/test_positive_task_status - search bar data differs

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4527]
Looks like the test asserts on statement `state=stopped&result=error`, however, the widget actually put `state=paused&result=error` to the search bar.
https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_dashboard.py#L453

**Comment by oshtaier** [comment]
Should be addressed in https://github.com/SatelliteQE/robottelo/pull/4504

**Comment by rplevka** [comment]
please, close the issue after you make sure it's addressed. That particular pull request is not enough since this is reported for both `6.3` and `6.2`

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
