### ISSUE TITLE
RepositoryTestCase.test_positive_remove_content_by_repo_name failing

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4546]
A test introduced by https://github.com/SatelliteQE/robottelo/pull/4179 fails as the hammer command requires a product-id to be passed.
@svtkachenko, could you possibly fix this if you got time? Also, would it be applicable to backport this test to `6.2`, possibly `6.1`?

**Comment by svtkachenko** [comment]
This test was supposed to autofix itself :) once bug is verified :) But it still in POST.
