### ISSUE TITLE
tests.foreman.cli.test_environment.EnvironmentTestCase failing in setup

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#4569]
The tests are unable to get puppet classes from the puppet capsule <capsulename>/puppet. My guess would be due to fake capsule unable to communicate. 

`Error: ERF12-4115 [ProxyAPI::ProxyException]: Unable to get classes from Puppet for KT_UvEMen_Library_joiDVWoZCx_324 ([Errno::ECONNREFUSED]: Connection refused - connect(2) for "hostname" port...) for Capsule https://hostname:14652/puppet`

**Comment by rplevka** [comment]
Thanks Sanket,
yes, you are very correct. Anyway, we track the issue by a different GH issue:
https://github.com/SatelliteQE/robottelo/issues/4258

would you mind closing this one in a favor of the above issue? thanks
