### ISSUE TITLE
Replace coveralls with codecov

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#4570]
Currently, we use coveralls:

https://coveralls.io/github/SatelliteQE/robottelo

**problem**: it is sometimes buggy when it calculates the increase/decrease of coverage it sometimes fails.

I heard about **codecov** many open-source projects are moving to this, So I am trying codecov and linking it.

**pros:** Looks like it is not annoying on adding comments (need to test more), calculate decrease/increase with more precision, has better UX/UI and a nice diff for Pull Requests.

https://codecov.io/gh/SatelliteQE/robottelo

Thinking about moving from codecov what do you think?

**Comment by abalakh** [comment]
+1 to the idea of moving away from coveralls. I wouldn't say it's *sometimes* buggy, but rather buggy *most of the times*, so we ended up simply ignoring it's messages in all the PR, therefore i can't see any point in it.
I haven't tried codecov though, but since it's not coveralls - i'd give it a chance :)

**Comment by rochacbruno** [comment]
Comment example: https://github.com/SatelliteQE/robottelo/pull/4565#issuecomment-297048092

**Comment by rochacbruno** [comment]
@omaciel @elyezer what do you think?

**Comment by omaciel** [comment]
@rochacbruno I don't have a dog in this fight. If `codecov` is more accurate or makes the pain go away AND there's no technical burden added, I don't see why not.

**Comment by elyezer** [comment]
@rochacbruno it looks promising. It is also new to me but doing a quick overview I think it worth a try.

**Comment by rochacbruno** [comment]
@omaciel @elyezer some of you with admin access to repo settings can please disable coveralls hook and enable codecov?

**Comment by rochacbruno** [comment]
robottelo is already there https://codecov.io/gh/SatelliteQE/robottelo only need to add the integration hook

**Comment by rochacbruno** [comment]
and then I can replace `coveralls` with `codecov` in travis.yaml

**Comment by omaciel** [comment]
@rochacbruno try now
