### ISSUE TITLE
Failures in smartclass parameters due to fake capsule on upgrade boxes

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#4575]
On upgrade boxes, there are lots of failures, due to creation fake capsule and no tear down for it. 
tests.foreman.cli.test_classparameters are failing.
The exact error is 

> 2017-04-18 17:08:16 - robottelo.ssh - INFO - >>> LANG=en_US.UTF-8  hammer -v -u admin -p pass  content-view publish --id="665"
2017-04-18 17:08:28 - robottelo.ssh - INFO - <<< stderr
Task 0ebd8c6a-34b8-4df7-9346-89e576ae67c5 running: 0.0/1, 0%, elapsed: 00:00:00
Task 0ebd8c6a-34b8-4df7-9346-89e576ae67c5 running: 0.36666666666666664/1, 36%, 0.2/s, elapsed: 00:00:02, ETA: 00:00:03
Task 0ebd8c6a-34b8-4df7-9346-89e576ae67c5 running: 0.5333333333333333/1, 53%, 0.1/s, elapsed: 00:00:04, ETA: 00:00:03
Task 0ebd8c6a-34b8-4df7-9346-89e576ae67c5 error: 0.8333333333333334/1, 83%, 0.1/s, elapsed: 00:00:06, ETA: 00:00:01
Task 0ebd8c6a-34b8-4df7-9346-89e576ae67c5 error: 0.8333333333333334/1, 83%, 0.1/s, elapsed: 00:00:06, ETA: 00:00:01
Error: ERF12-4115 [ProxyAPI::ProxyException]: Unable to get classes from Puppet for KT_CQAVqT_Library_irtCMyIrnH_665 ([Errno::ECONNREFUSED]: Connection refused - connect(2) for "qe-sat6-upgrade-rhel6.satqe.lab.eng.rdu2.redhat.co...) for Capsule https://fake-capsule:10673/puppet

When we do a capsule list on the box.

` hammer -v -u admin -p pass capsule list

ID | NAME| URL | FEATURES

5  | 6641462873333152938221673649772205647005  | https://qe-sat6:10673   | TFTP, DNS, DHCP, Puppe...
2  | qe-capsule | https://qe-capsule:9090 | TFTP, DNS, DHCP, Puppe...
1  | qe-sat6   | https://qe-sat6:9090    | TFTP, DNS, DHCP, Puppe...
`
So it seems , the automation pick's up the first capsule(fake one), while trying to get the puppet classes.

**Comment by sghai** [comment]
I think this issue appears because of #4258

**Comment by lpramuk** [comment]
We have solution for it already
https://github.com/SatelliteQE/robottelo/issues/4577

**Comment by sghai** [comment]
@lpramuk Your solution nothing but another issue.. I don't know whats the use case of fake capsule tests ? What's the benefit of keeping them in automation suite when they are affecting other tests ?

@rochacbruno : we need to come up w/ a solid solution to get rid of all issues because of fake capsule tests.
