### ISSUE TITLE
Mitigate fake capsule leakage to orgs

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4577]
Upon internal capsule creation all orgs are assigned to it. You cannot prevent it.
As we are faking the internal capsule it is associated to all orgs but then when the faking is being torn down such fake capsule starts to cause pain in those orgs, e.g. CV publishing/promoting fails due to inaccessible (fake) capsule:
```
Error: ERF12-4115 [ProxyAPI::ProxyException]: Unable to get classes from Puppet for KT_UvEMen_Library_joiDVWoZCx_324 ([Errno::ECONNREFUSED]: Connection refused - connect(2) for "<SAT_FQDN>" port...) for Capsule https://<SAT_FQDN>:14652/puppet
```
Lets mitigate this pain by updating fake capsule right after its creation and associating only with testing org. The relief ensue from that time from creation to update is much lower than time from creation to teardown.

**Comment by svtkachenko** [comment]
AFAIK, external and internal capsules have different behaviour be design. So currently fake capsule covers broken usecase. Maybe we should revert to the idea with separate capsule VM?

**Comment by lpramuk** [comment]
Yeah, this is shorterm,
 long term is to get rid off fake capsules mostly

**Comment by ldjebran** [comment]
@lpramuk I am now working on https://github.com/SatelliteQE/robottelo/issues/4258, perhaps we should join this two issues and update with orgs at the same time with run_in_one_thread, what do you think?

**Comment by lpramuk** [comment]
@ldjebran run_in_one_thread is not sufficient measure
