### ISSUE TITLE
tests in tests.foreman.ui.test_myaccount.MyAccountTestCase are failing

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/robottelo#4582]
Error messages here 

https://gist.github.com/pgagne/5aee08516179e63625b928fbc10fe956

**Comment by renzon** [comment]
Bug introduced in [this refactoring](https://github.com/SatelliteQE/robottelo/commit/637f10ae8625f4d89b32afd90c8bfcbf1e4fbf7c).

But anyway I found another one. Success account update message can appear just over my account button, so we need to wait until it is not visible to navigate into it again.
