### ISSUE TITLE
ui.test_oscapcontent.OpenScapContentTestCase - failing

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4586]
the tests suddenly fail as the uploaded content is nowhere to be found. Might be a bug.

![img](http://storage2.static.itmages.com/i/17/0420/h_1492695696_3576992_39416c5488.png)

affecting:
-  test_positive_create
-  test_positive_delete
-  test_positive_create_with_policy_name
-  test_positive_delete_by_policy_name
-  test_positive_update

**Comment by san7ket** [comment]
Will test this manually , found same thing on upgrade box rhel 6 box , @rplevka on which os was this

**Comment by san7ket** [comment]
Not a bug, Tried manually , will take a closer look on tests.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
