### ISSUE TITLE
Test Red Hat's Bugzilla 5 beta using Robozilla and Python-bugzilla

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#4589]
As announced in e-mail below, we need to check if our scripts are compatible.

-------------
Hello All,

We are pleased to announce Red Hat's Bugzilla 5 beta [1]! We’re inviting all of you to participate. 

We encourage you to test your current scripts against this new version and take part in the beta discussions on the Fedora development list [2]. Partners and customers may also use their existing communications channels to share feedback or questions. We ask that you provide feedback or questions by Wednesday, May 17th.

Here is a short list of some of the changes in Bugzilla 5: 

- Major improvements in the WebServices interface, including a new REST-like endpoint, allowing clients to access data using standard HTTP calls for easy development. 
- The UI has been significantly overhauled for a modern browsing experience.
Performance improvements, including caching improvements to allow faster access to certain types of data.
- Red Hat Associates, Customers and Fedora Account System users can now log in using SAML.
The addition of some of the Bayoteers extensions allowing features such as inline editing of bugs in search results, team management and scrum tools, etc.
- Ye Olde diff viewer has been replaced with the modern diff2html diff viewer
Improved, updated documentation including a rewrite using the reStructuredText format, which allows documentation to be more easily converted into different formats such as HTML and PDF, etc

The official release date for Bugzilla 5 will be determined based on the beta feedback. We will communicate to you as the beta progresses.

For more information refer to:

https://beta-bugzilla.redhat.com/page.cgi?id=whats-new.html
https://beta-bugzilla.redhat.com/page.cgi?id=release-notes.html
https://beta-bugzilla.redhat.com/page.cgi?id=faq.html
https://beta-bugzilla.redhat.com/docs/en/html/using/index.html
https://beta-bugzilla.redhat.com/docs/en/html/api/index.html

Cheers, the Red Hat Bugzilla team.

1: https://beta-bugzilla.redhat.com/
2: https://lists.fedoraproject.org/archives/list/devel%40lists.fedoraproject.org/

**Comment by ldjebran** [comment]
Made some test by scanning robottelo  with (BUGZILLA_URL = 'https://beta-bugzilla.redhat.com/xmlrpc.cgi) and had some NONE data for some bugs , investigated in the new beta site beta-bugzilla.redhat.com seems some bugs are missing there,

from the stable URL (BUGZILLA_URL = 'https://bugzilla.redhat.com/xmlrpc.cgi') they exists  and working as usually

**Comment by rochacbruno** [comment]
@ldjebran maybe during beta the database is not the full one.

**Comment by rochacbruno** [comment]
@ldjebran the item 1 is the most interesting, we can do REST calls instead of RPC, so it will speed up things I guess.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
