### ISSUE TITLE
Failure's on tests.foreman.ui.test_location.LocationTestCase due to different pages for two screnarios

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#4592]
If  there are unassigned hosts, then you get this 'assign host' dialog. If you assign them and then go and create another location, you get the configure location page.

First page, create location
![loc1](https://cloud.githubusercontent.com/assets/14175952/25272608/2d31ca3a-26a6-11e7-82e9-71dc39ac504e.png)

Second page for when host is unassigned
![loc3](https://cloud.githubusercontent.com/assets/14175952/25272648/53f728fe-26a6-11e7-8738-d96f58aa1453.png)

Second page for when host is assigned
![loc2](https://cloud.githubusercontent.com/assets/14175952/25272632/44ec8d36-26a6-11e7-821e-5cb7c181c959.png)

Automation should support both the use-cases.

**Comment by sghai** [comment]
@san7ket : thanks 

Please specify how many tests are affecting w/ this issue as that will help to prioritize

**Comment by san7ket** [comment]
Lastrun: 7/9 failed tests

**Comment by sghai** [comment]
@rochacbruno : could you please ask folks to fix this issue ?

**Comment by san7ket** [comment]
More tests are affected in tier2 - 18 tests
