### ISSUE TITLE
UI - ContentView publish progress checks fails on 'red' progress bar

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4601]
ui.test_contentview.ContentViewTestCase.test_positive_delete_cv_promoted_to_multi_env

there's probably a different xpath locator used for a 'red' progress bar.
It is actually okay for a test to fail, however it would be beneficial to fetch status of a task as a part of debugging info (via API) before it does so. Otherwise it is hard to not possible to find out what was wrong with the task.

```TimeoutException: Waiting for element '//tr/td[contains(., 'Version 1')]/following::td/a/div[@class='progress progress-striped active']' to display. Message: element //tr/td[contains(., 'Version 1')]/following::td/a/div[@class='progress progress-striped active'] is not visible```

![scr](http://storage5.static.itmages.com/i/17/0424/h_1493039629_1516435_888327f045.png)

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
