### ISSUE TITLE
Automate BZ 1445403 disable goferd on managed clients

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#4612]
According to: https://bugzilla.redhat.com/show_bug.cgi?id=1445403#c2

Main Use Case:

1) User registers via subscription-manager normally
2) A user installs katello-agent via yum and by default, goferd is started and enabled as a service daemon
3) User wishes to ensure goferd is not running on the client and runs: 
 `systemctl stop goferd.service`
 `systemctl disable goferd.service`
4) User enables and disables repositories via 'subscription-manager repos' command
5) Applicability and errata updates are correctly displayed in the Satellite UI
6) User utilizes REX as a means to apply errata updates
7) Applicability and errata updates are correctly displayed in the Satellite UI after application of errata

**Comment by ldjebran** [comment]
@rochacbruno is this has some relation with this https://bugzilla.redhat.com/show_bug.cgi?id=1441398

**Comment by rochacbruno** [comment]
@ldjebran yeah this one is a blocker of 1445403 we need to put priority to automate this case.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
