### ISSUE TITLE
ui.test_docker.DockerContainerTestCase - no `latest` tag

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4618]
The above tests started to fail as there seems to be no `latest` tag for `busybox` image any longer.

![](http://storage4.static.itmages.com/i/17/0426/h_1493198380_6877176_c3fcaa56ac.png)

https://bugzilla.redhat.com/show_bug.cgi?id=1347658

**Comment by rplevka** [comment]
this actually seems to be a bug, as the listing of the tag for the same repo seems to change (i guess it only shows the local tags after they are being pulled)

**Comment by san7ket** [comment]
@ntkathole can you take a look at this?

**Comment by ntkathole** [comment]
@rplevka Repository shows me there are 75 tags but all the tags are not listing under create new container...are we having BZ for it?

**Comment by rplevka** [comment]
@ntkathole yes,
https://bugzilla.redhat.com/show_bug.cgi?id=1347658
i've also updated the desc.

**Comment by ntkathole** [comment]
@rplevka I found issue is  listing of docker tags under new container depends on entries per page parameter set in settings...anyway that going to fix with BZ.

**Comment by san7ket** [comment]
@ntkathole can you please skip the test with the BZ ID and raise a PR for 6.2.z and master
@rplevka will this be fixed for 6.2 , any idea? so as to remove the test from upgrade , if it's out of scope for 6.2

**Comment by ntkathole** [comment]
@rplevka and @san7ket the same test case can be fixed if we change parameter under settings :)...will it be fine?

**Comment by rplevka** [comment]
@san7ket i really don't know
@ntkathole I wouldn't go down that path (it is a workaround  but my main concern is that settings are 
 global so we're not just influence the test where we change the setting, but all of them)

**Comment by ntkathole** [comment]
Closing this issue as PR, skipping those test due to BZ, merged!

**Comment by san7ket** [comment]
I see this again , on a test, @ntkathole can you please take a look, tests.foreman.ui.test_docker.DockerContainerTestCase.test_positive_create_with_compresource

@rplevka is it appearing on fresh auto?

**Comment by ntkathole** [comment]
@san7ket and @rplevka The respective bug has been closed and according to comment by @rplevka https://bugzilla.redhat.com/show_bug.cgi?id=1347658#c9, @lpramuk was looking into it. But if that bug is fixed, we might need to skip test due to BZ https://bugzilla.redhat.com/show_bug.cgi?id=1489390 and prioritized it.

**Comment by rplevka** [comment]
@ntkathole @san7ket - the bug is not fixed, it got illegally closed. @lpramuk reopened and failed it.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
