### ISSUE TITLE
Optimize Docker Host infrastructure

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4619]
Painpoints:
- randomly choosing what type of connection will be tested (unix vs. tcp)
- CV published images with local docker (unix or tcp) requires self-registration but with multiple testing workers it severely interfere with other testing
- local docker (unix or tcp) has issue with SELinux as foreman-selinux is not compatible with docker-selinux so lets avoid using local docker for tcp at least (always external tcp vs. local unix socket testing)
- unix socket docker has outstanding bug - 400 malformed header pending (due to outdated ```excon``` gem)

Remedies: 
- separate unix socket vs. tcp docker host tests (by introducing ```UnixSocketDockerTestCase```)
- avoid using unix socket docker with CV published images (as you have to register satellite to itself)
- externalize tcp docker host to avoid registration to itself (resolves #4401)
- external tcp docker will utilize these CV published images testing
- extrenal tcp dockers will be provided the similar way as are client VMs using context manager ```DockerHostMachine``` bound to libvirt image of preconfigured docker/host or better? atomic

**Comment by rplevka** [comment]
![](http://storage1.static.itmages.com/i/17/0426/h_1493203227_9595305_5dd538a8dc.png)

**Comment by lpramuk** [comment]
By using docker host within VM we would have been able to catch regression like this - https://bugzilla.redhat.com/show_bug.cgi?id=1432184 
(24 CU cases = CUs are using docker the very same way)

**Comment by san7ket** [comment]
This also would resolve the failure on upgarde box,  tests.foreman.api.test_docker.DockerContainerTestCase.test_positive_delete

` Making HTTP POST request to https://sada.com/docker/api/v2/containers with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"container": {"repository_name": "busybox", "compute_resource_id": 23, "tag": "latest", "command": "top", "organization_ids": [45], "name": "hCMCp9ohLTx07aY2FriIPbSK"}}.
2017-04-27 06:16:49 - nailgun.client - WARNING - Received HTTP 500 response: {
  "error": {"message":"Cannot start container e9b1ed54a66ebf6e6554bd776a303d7f177ce0e3e95af12209d1eca6831b693d: [8] System error: permission denied\n"}
}`

**Comment by rplevka** [comment]
- [ ] implement support for provisioning a docker host (https://github.com/SatelliteQE/robottelo/pull/4668)
- [ ] refactor CLI tests (https://github.com/SatelliteQE/robottelo/pull/4668)
- [ ] refactor API tests
- [ ] refactor UI tests
