### ISSUE TITLE
Test that streamer streams bits when using On Demand download policy

### ISSUE THREAD

**Issue by dkliban** [SatelliteQE/robottelo#4653]
1. Create a repository repoFoo that contains RPMs similiar to the ones found in https://repos.fedorapeople.org/pulp/pulp/demo_repos/test_bandwidth_repo/ (all are 1 MB)
2. Create an empty repository, repoBar with no RPMs.
2. Register capsule with satellite
3. Create custom productFoo in Satellite and associate repoFoo with it.
4. Update the Download Policy for productFoo repository to 'On Demand'.
5. Update the "Mirror on Sync" for productFoo repository to True.
5. Create lifecycle environment lceFoo.
6. Associate lceFoo with the capsule.
7. Create Content View cvFoo.
8. Associate productFoo repository with cvFoo.
9. Create custom productBar in Satellite and associate repoBar with it.
10. Update the Download Policy for productBar repository to 'On Demand'.
11. Update the "Mirror on Sync" for productBar repository to True.
12. Create lifecycle environment lceBar.
13. Associate lceBar with the capsule.
14. Create Content View cvBar.
15. Associate productBar repository with cvBar.
16. Sync productFoo repository.
17. Publish new version of cvFoo.
18. Promote cvFoo to lceFoo.
19. Assert that a task to sync lceFoo to the capsule is started.
20. Use wondershaper to limit the download speed of eth0 to 10kbps (on the capsule)
     `$ sudo wondershaper eth0 10 50000`
27. On the machine running the test, attempt to install the published RPM from the repository on the capsule: http://capsule-hostname/pulp/repos/Default_Organization/Foo/pulp-large_1mb_test-packageB-0.1.1-1.fc14.noarch.rpm
28. Assert that yum does not timeout (defaults to 30 seconds).
29. Use wondershaper to clear rate limiting on the capsule
      $ sudo wondershaper clear eth0

Wondershaper is available in Fedora and EPEL7. https://github.com/magnific0/wondershaper/

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
