### ISSUE TITLE
Wiki page contains some broken links

### ISSUE THREAD

**Issue by MalloZup** [SatelliteQE/robottelo#4669]
on https://github.com/SatelliteQE/robottelo/wiki/How-To-Contribute
you have 2 broken links, afaisaw

* https://github.com/omaciel/robottelo/blob/master/AUTHORS.rst
* https://github.com/omaciel/robottelo/blob/master/HISTORY.rst

this link has moved : http://twistedmatrix.com/trac/wiki/CompatibilityPolicy

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.

**Comment by MalloZup** [comment]
@ntkathole I don't see it fixed

**Comment by ntkathole** [comment]
Thanks @MalloZup I will get it fixed soon.

**Comment by ntkathole** [comment]
@vikask18 can you please look into this?

**Comment by ntkathole** [comment]
Removed it as we no longer using those pages.
