### ISSUE TITLE
Implement generic skip decorator `skip_if()`

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4672]
Lets have ```skip_if(boolean, reason='')``` that can evaluate any condition and skip a test based on that condition:
- distro=='rhel7'
- **settings.sattools is None (skipping due to not initialized settings)**
- bz_bug_is_open() - can be also however but for this case we have already a specific decorator

Optional string param ```reason``` would be then logged for what reason it was skipped.

Currently we can stack skip decorators:
@skip_if_1
@skip_if_2

But that mean only OR logic skip if 1 or 2. And how would you do AND logic? With generic skip_if :-)

**Comment by lpramuk** [comment]
[6.2] cherrypick is still pending

**Comment by rplevka** [comment]
- [ ] master PR: https://github.com/SatelliteQE/robottelo/pull/4673
- [ ] [6.2.z] cherry-pick: https://github.com/SatelliteQE/robottelo/pull/4684
- [ ] [6.1.z] cherry-pick: https://github.com/SatelliteQE/robottelo/pull/4683
