### ISSUE TITLE
Test for BZ1437150

### ISSUE THREAD

**Issue by dkliban** [SatelliteQE/robottelo#4702]
1. Create a custom product Foo with feed url https://repos.fedorapeople.org/pulp/pulp/demo_repos/large_errata/zoo/.
2. Create a custome product Bar with the same feed url https://repos.fedorapeople.org/pulp/pulp/demo_repos/large_errata/zoo/.
3. Sync repo for product Foo.
4. Sync repo for product Bar.
5. Assert that sync from step 4 finished successfully without error.

**Comment by abalakh** [comment]
BZ for this issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1437150

**Comment by abalakh** [comment]
Findings so far:
Initial RFT included 20 rhel repo syncs and capsule syncs, such test would probably take days.
After modifying steps to sync rhel repo once but do publish/promote/capsule_sync 20 times test took 7.5 hours.
Then we tried doing 20 publish/promotes without capsule and then adding lce with all the CVs to capsule - test took ~3 hours. But it's still not acceptable for a single test.
Putting the task on hold until we find faster reproducer (maybe there's smaller repo with lots of errata or smth)

**Comment by dkliban** [comment]
I created some fixture data that makes this test much easier to implement. The fixture data contains a very large errata that causes Pulp to fail on the second time it is synced. The fix for the problem in Pulp is almost finished. It would be good to have this test in place to verify the fix in Pulp.

**Comment by abalakh** [comment]
@dkliban provided repo got synced in a seconds and returned no errors. I think we are missing some detail here.

**Comment by abalakh** [comment]
Test was automated in #4766 , closing the issue.
