### ISSUE TITLE
Implement one centralized approach for new 'Select Action' mechanism

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#4721]
There is new 'Select Action' mechanism which is added for different entities
![image](https://cloud.githubusercontent.com/assets/10895065/26376852/b3f7fb78-4016-11e7-9518-b52d85d89511.png)
or
![image](https://cloud.githubusercontent.com/assets/10895065/26376884/d2052758-4016-11e7-9f02-588976194c59.png)

Need to think about common method that can be used for that purpose

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
