### ISSUE TITLE
[UI] - UserTestCase.test_positive_create_with_language failing

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4725]
PR: https://github.com/SatelliteQE/robottelo/pull/4660 has introduced the error. It now searches by the abbreviations, but the drop-down contains locales in full-text form
The ![img](http://storage1.static.itmages.com/i/17/0524/h_1495623576_3428936_c72c4afa16.png)

**Comment by renzon** [comment]
I ma closing this because I fixed it on 6.2 and test is passing on 6.3 the way it is now.

**Comment by san7ket** [comment]
I can see the same behavior on a upgrade test.  tests.foreman.ui.test_user.UserTestCase.test_positive_update_language

![usertestcase-test_positive_update_language-screenshot-2017-08-01_11_33_50](https://user-images.githubusercontent.com/14175952/28859056-a99cf1ae-7772-11e7-8072-fe08f50aee78.png)

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
