### ISSUE TITLE
UI DiscoveryRuleTestCase - improper assertions on saving changes

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4737]
almost all tests involving creating/updaing of the discovery rules do not set the organization/location context, which leads to the error dialog on saving.
There is a missing assertion, so the tests ignore any errors and carry on with navgating to DR page, asserting the presence of the newly 'created' DR.

failing tests:

- test_negative_create_with_same_name	
- test_negative_update_hostname
- test_negative_update_limit
- test_negative_update_name
- test_negative_update_priority
- test_positive_create_disabled

Please note, there might be more DR tests with the same issue - especially the negative tests. They pass, but the 'non existence' of the DR might be caused by the above reason.

Note: am marking this `High` as it causes about 18 tests to fail.

**Comment by sghai** [comment]
All 6.2.z tests have been fixed w/ PR https://github.com/SatelliteQE/robottelo/pull/4775

**Comment by ntkathole** [comment]
PR for 6.2.z merged. For 6.3, all discovery rule tests are fixed due to PR #4776  and there is no failure in discovery rule tests according to sat 6.3 snap 26 results. So closing this issue!
