### ISSUE TITLE
installer - SELinuxTestCase.test_positive_check_installer_logfile - should run at the very beginning

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4738]
I'v got problem with this Test class. First of all, it does not match robottelo design, as it depends on the satellite state - in order to run correctly, it requires to be executed just after the installation (this might be somehow hacked by using some marker logic, but one can still run the test suite on a satellite which is not 'clean' anymore).
- As satellite constantly commulates state, it also logs messages to its logfiles.
`test_positive_check_installer_logfile` checks `/var/log/candlepin/error.log` - the time this file is checked, satellite has undergone several tests already and the file contains logs *not only* from the installer. This leads to bogus failures.

- My second concern is - why is this called `SELinuxTestCase`?
- the last concern - https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/installer/test_installer.py#L309-L310 - it seems the installer log always contains the following message:
```
[DEBUG 2017-05-23 14:52:03 main] calling :function_validate_re with [["ERROR", "^(UNKNOWN|FATAL|ERROR|WARN|INFO|DEBUG)$"]]
```
I guess this message will make the statement always positive

**Comment by renzon** [comment]
I think that could be a good subject for Friday's mtg. On simple way to accomplish this would be only running it just after installation would be selecting this exactly test with pytest and after that running the rest of tests. But I am not sure how it would affect test report on Jenkins.

**Comment by rplevka** [comment]
@renzon - bump

**Comment by rochacbruno** [comment]
We can try this http://pytest-ordering.readthedocs.io/en/develop/ but I am not sure how it works on multiple processes, maybe adding a mark `@before` and running it is the best

**Comment by rplevka** [comment]
shouldn't we actually put these asserts directly to a provisioning job?

**Comment by rplevka** [comment]
@renzon @rochacbruno bump. this keeps failing. I'm in a temptation of removing the test entirely

**Comment by rochacbruno** [comment]
We have not discussed this on latest Friday meeting, we can do that this week.

If this is not critical I vote to skip it by now.

**Comment by renzon** [comment]
I agree with you @rplevka

**Comment by rplevka** [comment]
@renzon - okay, could you raise a pr for this, please?
