### ISSUE TITLE
Create new common locator for input validation 

### ISSUE THREAD

**Issue by svtkachenko** [SatelliteQE/robottelo#4785]
Negative UI tests use `common_locators['haserror']` = `(By.XPATH, "//div[contains(@class,'has-error')]")` to verify validation, however now inputs change its CSS instead of class.
Need to find all affected inputs and use something like `(By.CSS_SELECTOR, "input:invalid[value='%s']")`.

Example of affected tests:
```
tests.foreman.ui.test_discoveryrule.test_negative_create_with_too_long_limit
tests.foreman.ui.test_discoveryrule.test_negative_create_with_limit
tests.foreman.ui.test_discoveryrule.test_negative_create_with_invalid_priority
```

**Comment by odovzhenko** [comment]
Was addressed by https://github.com/SatelliteQE/robottelo/pull/4776
