### ISSUE TITLE
factory.py::setup_capsule_virtual_machine executes systemctl on rhel6

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4799]
rhel6 hosts  need to use `service pulp_celerybeat status` instead of `systemctl`.

```
2017-06-07 05:56:33 - robottelo.ssh - INFO - >>> snap-guest -b rhel68-base -t qe-sat62-rhel6-capsule
...
2017-06-07 07:10:23 - robottelo.ssh - INFO - >>> systemctl status pulp_celerybeat.service
2017-06-07 07:10:23 - robottelo.ssh - INFO - <<< stderr
bash: systemctl: command not found
```

Also, we don't check for the ssh command result so we ignore the error and fail further in the test with:
`IndexError: string index out of range` which masks the real issue

**Comment by sghai** [comment]
@ldjebran : Hey, please see if we can fix the mentioned test ?

**Comment by rplevka** [comment]
@ldjebran @sghai this is still happening. Could we prioritize this, please? 
The test takes 1hr 14 min just to fail on this simple error
https://github.com/SatelliteQE/robottelo/blob/6.2.z/robottelo/cli/factory.py#L2894

**Comment by rplevka** [comment]
closing - EOL
