### ISSUE TITLE
UI - SmartVariablesTestCase - several tests failed with 'puppet class not found' on rhel7

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4800]
![](http://storage4.static.itmages.com/i/17/0608/h_1496914375_6685432_460bd550fb.png)

- test_positive_create_matcher_merge_override
- test_positive_impact_delete_attribute
- test_positive_update_hidden_value_in_attribute
- test_positive_update_matcher_from_attribute

**Comment by sghai** [comment]
@svtkachenko : hey Stan, could you please take a look and see if these tests can be fixed quickly.

**Comment by svtkachenko** [comment]
@sghai Looks like some race condition as these tests passed with the next run (but another one failed with same error). However, I'm not able to find while this happening nor to reproduce it locally. So it won't be quickly unfortunately.

**Comment by sghai** [comment]
thanks @svtkachenko Just keep this issue on your radar..

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
