### ISSUE TITLE
Automate https://bugzilla.redhat.com/show_bug.cgi?id=1460793

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#4824]
I checked cli folder https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_discoveryrule.py but could not find a relevant test case.

**Comment by rplevka** [comment]
looking into the above file and checing the test results as well, I can say that pretty much every positive 'create' test case is relevant to the BZ.

almost all run something like:
```
LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv discovery_rule create --hostgroup-id="44" --location-ids="415" --name="duDgMljKlS" --search="cpu_count = 2" --organization-ids="412"
```

What is missing is the whole file in `6.2.z` branch. Also, it's possible that a workaround for the Bz would be to define a hostgroup or use `organization-ids` option.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
