### ISSUE TITLE
Update ui.Repos.remove_content to remove packages from all pages

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#4829]
`ui.Repos.remove_content` uses 'Select all' checkbox to select every package on screen and then proceeds with delete. In 6.3 pagination on packages screen was added and tests started to fail as not all the packages but only first 20 are actually deleted.
#4828 makes helper using 100 items per page which resolves issue for us as currently our fake repos contain only 32 packages. However, that's not proper fix but rather a duct tape and to avoid possible failures in future we should use conditional loop to navigate through all pages and delete all the packages (or maybe not navigate but use that delete while packages are present)

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
