### ISSUE TITLE
Provide jenkins buildtime info (job label, build id) within robottelo

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4830]
If we defined a new section in `robottelo.properties`:
```
[build]
id=0
job_label=standalone
```

We could use the information to add the metadata to the KVM machines and docker containers our run creates. This would help us to quickly identify the origin of _that mysterious container|vm which has been hanging there for 2 weeks_.

What's nice about it is the fact, that our automation can use `sed` to replace these values by the actual jenkins variables:
https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-below

```bash
sed -i "s/id=0/id=${BUILD_NUMBER}/"
sed -i "s/job_label=standalone/id=${JOB_NAME}/"
```
by checking the `virsh info` or `docker inspect` of the domain|container, we could easily identify the person->job->build responsible for it.

**Comment by lpramuk** [comment]
robottelo - Add new settings
robottelo-ci - Add sedding info to robottelo.properties file

**Comment by rplevka** [comment]
If i remember this right, it has been discussed on scrum and didn't get enough votes to be implemented, thus i'm closing it.
