### ISSUE TITLE
UI - el7 - HostTestCase.test_positive_update_name

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4846]
the test case fails every time at the very same situation ONLY on `el7`:
![](http://storage8.static.itmages.com/i/17/0619/h_1497878281_6141378_bafff55bd1.png)

- I'd check whether there's some sort of javascript error, which prevents the menu to get closed.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
