### ISSUE TITLE
[6.1.z] tests.foreman.api.test_hostgroup.HostGroupTestCase.test_positive_clone - missing nailgun cherry-pick

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4900]
PR https://github.com/SatelliteQE/robottelo/pull/4225 has introduced a test that relies on a `HostGroup.clone()` which has been introduced in `master` and `6.2.z` robottelo branches, however not the `6.1.z` one:
https://github.com/SatelliteQE/nailgun/commit/d589cbbabe0e9336c0f7334d16b54a5cc94a08f5

**Comment by omaciel** [comment]
@rplevka why are we touching 6.1 code?

**Comment by rplevka** [comment]
@omaciel,
this issue is about a month old. I filed it based on the automation results for the recent 6.1.z snap we got back then so I could claim the failures.
