### ISSUE TITLE
mock is listed in both requirements files.

### ISSUE THREAD

**Issue by JacobCallahan** [SatelliteQE/robottelo#4932]
As a result, when attempting to install all requirements, the following error happens:

```Double requirement given: mock (from -r requirements-optional.txt (line 4)) (already in mock==2.0.0 (from -r requirements.txt (line 8)), name='mock')```

**Comment by JacobCallahan** [comment]
@SatelliteQE/quality-engineers I think the best way forward is to just remove the mock reference from the optional requirements. What do you guys think?

**Comment by jyejare** [comment]
+1 @JacobCallahan

**Comment by rochacbruno** [comment]
+1 we should remove from -optional
