### ISSUE TITLE
Where to store vmware compute resource values, [properties file or Hardcode]

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#4955]
```
cpus=2,
corespersocket=2,
memory=1024,
cluster='Satellite_Engineering',
folder='vm',
guest_os='Red Hat Enterprise Linux 7 (64-bit)',
scsicontroller='LSI Logic Parallel',
virtualhw_version='Default',
memory_hotadd=True,
cpu_hotadd=True,
cdrom_drive=False,
annotation_notes='apple',
pool='Resources',

network_interfaces=[
name='NET 3',
network=settings.vlan_networking.bridge
],

storage=[
datastore='Local- ()',
size='10',
thin_provision=True,
eager_zero=True,]
```

I am working on automating Vmware remaining T2 , the issue is I cannot decide which of the following settings needed for vmware should go into , robottello.properties and which should be hardcoded.
The problem is with 
```
cluster='Satellite_Engineering',
folder='vm',
guest_os='Red Hat Enterprise Linux 7 (64-bit)',
scsicontroller='LSI Logic Parallel',
virtualhw_version='Default',
pool='Resources',
network_interfaces name='NET 3',
datastore='Local- ()',
```

@kbidarkar @rochacbruno @sghai any thoughts?

**Comment by sghai** [comment]
I don't have any strong opinion. However, I think cluster is something that will vary depending on the infra/environment, otherwise, I feel rest all can be hardcoded. 

In any case, all above settings can be set as default values and such settings should not go to properties file.

**Comment by kbidarkar** [comment]
I agree with what @sghai  said above, but would say those are `constants` and not `hardcoding` stuff. :)
