### ISSUE TITLE
test_host::LibvirtHostTestCase::test_positive_create_libvirt failing with invalid interface

### ISSUE THREAD

**Issue by ldjebran** [SatelliteQE/robottelo#4968]
test is failing because of invalid interface 
tests.foreman.ui.test_host | LibvirtHostTestCase | test_positive_create_libvirt

![task_validation_screenshot](https://user-images.githubusercontent.com/131553/28165374-33338aaa-67dc-11e7-9356-9443667e6605.png)

**Comment by rplevka** [comment]
```
2017-07-23 10:06:57 b99a0c7d [app] [W] Create IPv4 DNS record for 0498421066.x6tleoskpo task failed with the following error: ERF12-2357 [ProxyAPI::ProxyException]: Unable 
to set DNS entry ([RestClient::BadRequest]: 400 Bad Request) for Capsule https://sat6.com:9090/dns
 | ProxyAPI::ProxyException: ERF12-2357 [ProxyAPI::ProxyException]: Unable to set DNS entry ([RestClient::BadRequest]: 400 Bad Request) for Capsule https://sat6.com:9090/dns
```

**Comment by ldjebran** [comment]
@rplevka @san7ket can we close this issue as the test it self was renamed to end_to_end  and seems the problem was resolved, but end to end is failing due to a bug

**Comment by rplevka** [comment]
@ldjebran sure.
