### ISSUE TITLE
OpenScapTestCase.test_positive_upload_to_satellite - using vm._domain, translating the domain to "None"

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5020]
Looks like this change implemented the domain parsing based on the `vm._domain` attribute, which is `None` by default. This later translates the hostname of the host to `hostname.None`, causing the searches and thus the whole test to fail on asserting such host.

https://github.com/SatelliteQE/robottelo/pull/4292/files

**Comment by san7ket** [comment]
Addressed in https://github.com/SatelliteQE/robottelo/pull/5244/
