### ISSUE TITLE
Using tags from saucelabs to identify the tests

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5081]
While Failure analysis, all the UI jobs are run on saucelabs using the same Build Name i.e tier1, tier2, ugrade-tiers etc. This makes it very difficult to know which test was run on what box. 
Upgarde or fresh.We have to go into test and look at the screens or logs to know the box 

Maybe we can use the "Tags" functionality from saucelabs , to identify and group the tests
Here is and example:
```
DesiredCapabilities caps = DesiredCapabilities.firefox();
caps.setCapability("platform", "Windows XP");
caps.setCapability("version", "37.0");
caps.setCapability("name", "Web Driver demo Test");
caps.setCapability("tags", "Tag1");
caps.setCapability("build", "build-1234");
WebDriver driver = new RemoteWebDriver(
new URL("http://YOUR_USERNAME:YOUR_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub"),
    caps);
```
More info: https://wiki.saucelabs.com/display/DOCS/Best+Practice%3A+Use+Build+IDs%2C+Tags%2C+and+Names+to+Identify+Your+Tests

**Comment by kbidarkar** [comment]
This will be mostly a robottelo-ci effort I believe.

**Comment by kbidarkar** [comment]
On second thought, let me also update the robottelo.properties.sample file too, so that it helps quickly.

**Comment by san7ket** [comment]
This is implemented ,thanks @kbidarkar .
