### ISSUE TITLE
improve assertions of syncplan tests by polling the sync task

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5122]
we currently use very unreliable way of asserting that sync plan works correctly (we create a sync plan, then we add some static delays and check for the package counts). That is too vague as many various situations may occur.

what I think would be much more reliable is to check whether a sync task has been created (and check its progress after that).

There's a way of distinguishing  between the tasks created by a user and those created by system.
user-created tasks have `owner` of `admin` and the system ones belong to `foreman_admin`.
We can use this fact and the repository id to our advantage in getting the right task:

``` resource_type = Katello::Repository and resource_id = 42 and owner.login = foreman_admin```

tip: the fastest and the most reliable way of checking for the task state is to use API so please, do not use UI to navigate to the task page back and forth

**Comment by san7ket** [comment]
I have Syncplan CLI and API test failures , due to 
AssertionError: No task was found using query 'resource_type = Katello::Repository and owner.login = foreman_admin and resource_id = 280'
Test those failed are:

```
tests.foreman.cli.test_syncplan.SyncPlanTestCase.test_positive_synchronize_custom_product_daily_recurrence
tests.foreman.cli.test_syncplan.SyncPlanTestCase.test_positive_synchronize_custom_product_future_sync_date
tests.foreman.cli.test_syncplan.SyncPlanTestCase.test_positive_synchronize_custom_product_past_sync_date
tests.foreman.api.test_syncplan.SyncPlanSynchronizeTestCase.test_positive_synchronize_rh_product_future_sync_date
```

**Comment by rplevka** [comment]
already implemented
