### ISSUE TITLE
Run tests as non-superadmin user.

### ISSUE THREAD

**Issue by svtkachenko** [SatelliteQE/robottelo#5142]
Currently we run tests as builtin admin user or creating user with `admin=True`. Unfortunately, this not only not quite valid usecase, but also hides a lot of potential problems as superadmin user omits most of the internal checks of permissions.

Since 6.3 the `Manager` role has all available permissions (both foreman and katello). We can use that for non-admin user but without need to set every permission manually.

**Comment by JacobCallahan** [comment]
Closing this issue since it has not been acted upon up until this point. Future component owners can reopen if they are going to address this.
