### ISSUE TITLE
Implement goferless client test cases

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5218]
sat 6.2.12 has introduced a new way of managing a content host - not installing katello-agent (goferd) but `katello-host-tools` - this pretty much keeps the yum package upload plugin, but does not install & use goferd.

we got to implement at least the following:
- function in vm.py (`install_katello_agent` analogy)
- content management tests using `katello-host-tools`

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
