### ISSUE TITLE
UI - ContentHost - test_positive_search_by_subscription_status - insufficient subscriptions attached to the host

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5223]
This test never passes as we do not provide the rhel-server subscription to the host, so it never receives the subscriptions for all the installed products.

We assert for the 'valid' subscription status, however our setup guarantees 'partially subscribed' at the most.

- either we need to add 'rhel-server' product to the cv -> ak or we need to assert for the 'partial' status.
There might be a chance to hack subscription manager not to report `RHEL-server` as an installed product

There's also 1 more thing that can be done - we install `katello-agent` and we don't need it as we do not use it in the test at all.

**Comment by rplevka** [comment]
please note, that i'm marking this as `high` because the test is critical and we do not seem to test this in any other test (in different endpoints)

**Comment by ldjebran** [comment]
we have to back port https://github.com/SatelliteQE/robottelo/pull/5168 that fix this issue

**Comment by svtkachenko** [comment]
Backported to 6.2 in #5355

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
