### ISSUE TITLE
Manifest Timeout issue and run on one thread failures 

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5233]
For the manifest for UI and API , we are polling the manifest upload task for approx 900 secs. This seems inadequate for upgrade tests , and would wary depending on https://bugzilla.redhat.com/show_bug.cgi?id=1339696. 
Also, if a existing task is timed out(which is actually still running in satellite). The next manifest tasks in the sequence will fail due to race condition for manifest upload.
This defeats the purpose of run on one thread, there are many such occurrences on upgrade tests.

Mitigation: 
1. Have a helper to upload manifest to run via CLI(already present), reduce the upload of manifests from API,UI.
2. Create a Wrapper for tasks , to get the task ID of Import Manifest task for organizations.
Check via CLI `hammer> task progress --id 753a3573-7b6c-4ee8-899e-f593f230c2dc`

Option 2: Can be also used to check CV publish , Repo Sync etc.

**Comment by san7ket** [comment]
@oshtaier the timeout for the saucelab is it for no event,

**Comment by san7ket** [comment]
Trying running seq test's before parallel tests , lets see if this solves/reduces the issue

**Comment by svtkachenko** [comment]
@san7ket Does reversed order helped?

**Comment by san7ket** [comment]
Yes it did help. Closing this
