### ISSUE TITLE
UI - ActiveDirectoryUserGroupTestCase failing due to missed cherry-pick

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5234]
we're missing this fix: https://github.com/SatelliteQE/robottelo/pull/5116
also, there's one other issue with locating the 'search' bar on the hostgroups page - if we're looking for a HG and there are no Hostgorups, the search bar is ~~empty~~ hidden and we fail to locate it.
- also, we do some unnecessary searches in the test `tearDown`:

```python
    def tearDown(self):
        with Session(self) as session:
            set_context(session, org=ANY_CONTEXT['org'])
            if self.user.search(self.ldap_user_name):
                self.user.delete(self.ldap_user_name)
            if self.usergroup.search(self.usergroup_name): # <= first search
                self.usergroup.delete(self.usergroup_name) # <= 2nd search, delete and 3rd search
super(ActiveDirectoryUserGroupTestCase, self).tearDown()
```
the first search is completely unnecessary as it is implemented in the delete call.
the 3rd one is alright, however it is implemented in a way that it goes through all the navigating again.
Let's use api to do the teardown, there is no point to waste time deleting stuff using ui.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
