### ISSUE TITLE
tests.foreman.ui.test_hostcollection failures to get the installed packages on UI

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5236]
`2017-09-23 21:55:34 - robottelo.ui.base - DEBUG - TimeoutException: Waiting for element '//tr[td/a[@ng-click='transitionToErrata(erratum)' and contains(.,'RHEA-2012:0002')]]/td/input[@type='checkbox']' to display. Message: element //tr[td/a[@ng-click='transitionToErrata(erratum)' and contains(.,'RHEA-2012:0002')]]/td/input[@type='checkbox'] is not visible`

- [ ] tests.foreman.ui.test_hostcollection.HostCollectionPackageManagementTest.test_positive_install_errata
![hostcollection](https://user-images.githubusercontent.com/14175952/30806328-faa05b16-a212-11e7-9fb6-ae929db1c570.png)

- [ ] ~~tests.foreman.ui.test_hostcollection.HostCollectionPackageManagementTest.test_positive_install_package_group~~

- [ ]  ~~tests.foreman.ui.test_hostcollection.HostCollectionPackageManagementTest.test_positive_install_package~~

**Comment by rplevka** [comment]
can you post a screenshot? I'm experiencing something that might be related to this issue -> the issue is that the "package" tab is a dropdown containing 3 options and according the logs, robottelo does not expect that and expects the packages page straight away.

**Comment by san7ket** [comment]
@rplevka this seems to something different the test is unable to fetch available errata for the created host , hence, no checkbox

**Comment by rplevka** [comment]
@san7ket thanks, that clears things up
