### ISSUE TITLE
tests.foreman.ui.test_contenthost failures 

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5237]
- [ ] tests.foreman.ui.test_contenthost.ContentHostTestCase.test_positive_install_errata failing to show errata , there is no applicable errata

![contenthosttestcase-test_positive_install_errata-screenshot-2017-09-04_14_47_25](https://user-images.githubusercontent.com/14175952/30118027-8c923dce-933f-11e7-86a6-a5b1b7d022b6.png)

- [ ] ~~tests.foreman.ui.test_contenthost.ContentHostTestCase.test_positive_install_package_group fails to load installed package~~ 

![scontenthosttestcase-test_positive_install_package_group-screenshot-2017-09-04_14_52_03](https://user-images.githubusercontent.com/14175952/30118381-857602ae-9340-11e7-9e1f-e6c987bb31df.png)

**Comment by san7ket** [comment]
tests.foreman.ui.test_contenthost.ContentHostTestCase.test_positive_install_package_group fails to load installed package

**Comment by pgagne** [comment]
@san7ket Is this still valid, can we close this issue?

**Comment by san7ket** [comment]
We can close this,
