### ISSUE TITLE
REX - tests require subnet parameters matching the real provisioning subnet

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5243]
the following commit has added a `subnet creation` to `setUp()`, however it does not pass the NW info, so the factory generates random IP's. That can never work.
We need to pass the parameters to match the real subnet.

https://github.com/SatelliteQE/robottelo/commit/710cf602057b25f1a40b490ac3fb7489b9f97bf8

**Comment by lpramuk** [comment]
Items 
- [ ] new settings to duplicate what we have in ```jenkins-configs / provisioning_environment.conf```
- [ ] changes in robotello-ci to sed env vars into robottelo.properties

**Comment by rplevka** [comment]
+1 to #2

**Comment by rplevka** [comment]
FYI - after consulting this with Foreman developers, we came to conclusion that it would reasonable to pre-create a `Default Subnet` during installation. Have raised an RFE:
https://bugzilla.redhat.com/show_bug.cgi?id=1489398

**Comment by rplevka** [comment]
fixed
