### ISSUE TITLE
WebDriverException: Message: Sauce could not start your job.

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5275]
there is only 1 occurrence of this.
https://saucelabs.com/beta/tests/f1e4860ca3874be79e9663bb1ed1235c/metadata

for the record, the failure occurred on the following test, however i doubt it is related to the test:
tests.foreman.ui.test_product.ProductTestCase.test_positive_update_name
- the setupClass used a sane login for the user (alphanumeric)

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
