### ISSUE TITLE
[6.2] - backport the docker redesign PR to 6.2

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5277]
- [x] https://github.com/SatelliteQE/robottelo/pull/4701
- [x] https://github.com/SatelliteQE/robottelo/pull/5154
- [x] 195a91cd89a7661c8c5eff23ea5446f36212fc8a
- [x] 64569e84a28154a30a2992a5f00f1d8cf6f8db56

**Comment by svtkachenko** [comment]
Closed via #5309
