### ISSUE TITLE
missed cherry-pick for HostTestCase.test_positive_search_by_parameter_with_operator

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5279]
This is required in `6.2.z`
https://github.com/SatelliteQE/robottelo/pull/5176/

**Comment by ldjebran** [comment]
@rplevka perhaps there is an error, the title and PR does not correspond

**Comment by rplevka** [comment]
@ldjebran, hehe, I'm very sorry, had trouble with clipboard. The title is wrong, the correct test is:
`HostTestCase.test_positive_search_by_parameter_with_operator`

**Comment by rplevka** [comment]
`6.2.z` is closed due EOL
