### ISSUE TITLE
UI - ContentHostTestCase.test_positive_remove_package_group using wrong repo

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5298]
URL: https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/
does not contain a `birds` package group.
It exists in  `FAKE_1_YUM_REPO` tho: (http://inecas.fedorapeople.org/fakerepos/zoo3/)

**Comment by svtkachenko** [comment]
Closed via #5344 and #5355
