### ISSUE TITLE
docker - syncing busybox repo from registry-1-docker.io not working

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5302]
This seems to be an upstream (infra) failure, but syncing the repo stopped working due to manifest digest hash mismatch:

repo:
"https://registry-1.docker.io", "docker_upstream_name": "busybox"
sync:
```
"output":"The Manifest digest does not match the expected value. The remote feed announced a digest of sha256:6cb02cbabacf59962d0cd05176e68ae4769e998e8d98f5e3f28fe915de341d6c, but the downloaded digest was sha256:98f12e5b0243774d2767dee77ad15b7cc5a835061e408c3bae9038ccdfa9d955."
```

this causes a lot of tests to fail

**Comment by odovzhenko** [comment]
It worked for me locally today.

**Comment by rplevka** [comment]
this is no longer an issue
