### ISSUE TITLE
UI - The test with session id <id> has already finished, and can't receive further commands.

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5306]
tests.foreman.ui.test_user/UserTestCase.test_positive_create_with_language occassionally fails with this error:
```
WebDriverException: Message: The test with session id d7dabbf937924ca4875bd77c1cb443fb has already finished, and can't receive further commands.
```

I've only seen this happening to just this test (not every time). I guess this will have omething to do with the codestyle.

**Comment by san7ket** [comment]
Got another occurrence of this, `test_syncplan.SyncPlanTestCase.test_positive_synchronize_custom_products_future_sync_date `

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
