### ISSUE TITLE
UI - TestErrata - tests applying errata stuck at confirmation dialog

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5322]
![img](http://storage4.static.itmages.com/i/17/0927/h_1506503865_6156929_803defa5c1.png)

- there's no appropriate action logged on the server so the action has never fired.
2 T3 tests affected
- [ ] test_positive_apply_for_all_hosts
- [ ] test_positive_apply_for_host

**Comment by ldjebran** [comment]
@rplevka this is a bug I have already registered

**Comment by ldjebran** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1485236

**Comment by rplevka** [comment]
@ldjebran thanks, closing then
