### ISSUE TITLE
CLI - hammer user list now contains more fields

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5324]
The assertions for at least these tests need to be updated:

`test_positive_list_email`
`test_positive_list_firstname`
`test_positive_list_surname`
`test_positive_list_username`
```
Id,Login,Name,Email
87,6nh1Ds,𢱲𨷿𠹊𥟀μߢ𦬇앣𥣭𓃦딿𡠳㳘铪𫗾ΰϛ韃𤒮戒ᚧ𤣣쀓輊충쯅䢿𢇾됢嚘𤿗럈𥺻𓉜Å痍𥻐 sees0k0Mpy,6nh1Ds@example.com
```
```
Id,Login,Name,Email,Admin,Last login,Authorized by
87,K5WIB7,872555310951844493906825832510985336 xf9eMDdTHc,K5WIB7@example.com,false,"",Internal
```

**Comment by ntkathole** [comment]
Closing as PR merged!

**Comment by rplevka** [comment]
there's now even more:
```
Id,Login,Name,Email,Admin,Last login,Authorized by
73,13KycK,Wa2RXh79BE 0rCxqWr3jw,íÔÙÊÏêÇØïÐ@somemail.com,false,"",Internal
```

let's not try to catch 'em all, and just assert on an existence and values of specific fields

**Comment by ntkathole** [comment]
@rplevka could you please point me which tests failed?

**Comment by abalakh** [comment]
@ntkathole failure happened in test `test_positive_create_with_email_utf8_latin` which wasn't updated in #5422 btw. I'd suggest to take a careful look at every single test in module and update all the outdated assertions.

**Comment by rplevka** [comment]
thanks @abalakh, yes, that is the one.
I can see @ntkathole actually used the assertion exactly as i wanted to suggest, it's indeed just this test missed from that PR.
- since no other test fails, i guess this will be all. however, who knows :)

**Comment by ntkathole** [comment]
@rplevka thanks for info. I will raise PR for this test and will confirm whether some other tests from cli.test_user fail due to same reason.

**Comment by ntkathole** [comment]
All the test_user tests in CLI passed for snap 28 after fix.  Closing this issue!
