### ISSUE TITLE
[CLI] OpenScapTestCase.test_positive_update_scap_content_with_newtitle - title not updated

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5339]
this is probably a bug, I see @san7ket has decorated it with:
http://projects.theforeman.org/issues/20887 but that bz was only about no confirmation message on stdout.
The bug is now ON_QA, so the test is no longer skipped

**Comment by san7ket** [comment]
PR is already up and this is covered in https://github.com/SatelliteQE/robottelo/pull/5327
https://github.com/SatelliteQE/robottelo/pull/5327/files#diff-73a3e1a7a2352bcb26d5c8b6d86d47f9R457

**Comment by san7ket** [comment]
6.2 doesn't have CLI component for SCAP

**Comment by san7ket** [comment]
Closing this , related PR is merged
