### ISSUE TITLE
Rhev tier3 tests failing, possibly due to locator issue

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5342]
Failing to find the Deploy on - rhev_cr (RHEV) element timing out

**Comment by rplevka** [comment]
i think we should not lookg for exact match of the CR name, as the dropdown contains the name in a format: <cr name> (<provider>).
e.g. "foobar (RHEV)"

**Comment by san7ket** [comment]
Rhev test's are now failing in compute profile page , where there was lot of changes ,like
1) we now no longer have image filed
2) If image based , no longer can edit template
3) locator changes for adding storgae to `.//*[@id='storage_volumes']/div/a[@data-association='volumes']`

**Comment by sghai** [comment]
@san7ket : do we have any issue around compute profile changes, assuming its a new change in snap25 ?

**Comment by san7ket** [comment]
@sghai these changes are due to 
https://bugzilla.redhat.com/show_bug.cgi?id=1467828
https://bugzilla.redhat.com/show_bug.cgi?id=1466645

**Comment by sghai** [comment]
Cool @san7ket . ty for sharing bz ids.

**Comment by san7ket** [comment]
Will raise a PR soon for all the Rhev test's

**Comment by rplevka** [comment]
`test_positive_access_rhev_with_custom_profile` still failing while locating the storage element

**Comment by san7ket** [comment]
I missed this one in last PR

**Comment by san7ket** [comment]
The locators in place are correct, I couldn't get to the root cause of the failure.
looks like https://github.com/SatelliteQE/robottelo/commit/4da9684f26a5c4a97682950a5d2dcc14ecfb93dd#diff-6ca60b613b8d4fa334713d53bfd172f3R825

won't get the first instance of the element , as there are two elements on the page, it is supposed to read the first one which for some reason doesn't happen.
@oshtaier any idea as to what's the issue.

The test is able to assign value using `//fieldset[@id='storage_volumes']//div/input[contains(@id,'size_gb')] `using XPATH , but afterwards unable to find the element

Assignment:
```
2017-11-27 20:29:21 - robottelo.ui.browser - DEBUG - sendKeysToElement:  {'id': u'{acf4f538-bb53-489f-8641-49bac36a969a}', 'value': '20'}
2017-11-27 20:29:21 - robottelo.ui.base - DEBUG - Assigned value 20 to <selenium.webdriver.remote.webelement.WebElement (session="21131537-4bcb-44b1-aedf-c3006360a73e", element="{acf4f538-bb53-489f-8641-49bac36a969a}")>
```

Finding element:
```
2017-11-27 20:29:44 - robottelo.ui.browser - DEBUG - findElement: id: {7d65e6f3-6a10-4ae1-bd83-3786d621a6ee} {'using': 'xpath', 'value': u"//div/span/input[@id='compute_attribute_vm_attrs_memory']"}
**************
input
2017-11-27 20:29:44 - robottelo.ui.browser - DEBUG - findElement: id: {7d65e6f3-6a10-4ae1-bd83-3786d621a6ee} {'using': 'xpath', 'value': u"//div/span/input[@id='compute_attribute_vm_attrs_memory']"}
*****************************
<|strategy=xpath|value=//fieldset[@id='storage_volumes']//div/input[contains(@id,'size_gb')]|>
2017-11-27 20:29:44 - robottelo.ui.browser - DEBUG - findElement: id: {72d9186f-9972-4f66-aeb6-68c690a2d936} {'using': 'xpath', 'value': u"//fieldset[@id='storage_volumes']//div/input[contains(@id,'size_gb')]"}
2017-11-27 20:29:44 - robottelo.ui.browser - DEBUG - findElement: id: {72d9186f-9972-4f66-aeb6-68c690a2d936} {'using': 'xpath', 'value': u"//fieldset[@id='storage_volumes']//div/input[contains(@id,'size_gb')]"}
2017-11-27 20:29:45 - robottelo.ui.browser - DEBUG - findElement: id: {72d9186f-9972-4f66-aeb6-68c690a2d936} {'using': 'xpath', 'value': u"//fieldset[@id='storage_volumes']//div/input[contains(@id,'size_gb')]"}

**************
None

```

**Comment by san7ket** [comment]
All tests fixed , except

- [ ] test_positive_access_rhev_with_custom_profile

**Comment by san7ket** [comment]
There are two more test's failing due to locator issue when selecting arch , while provisioning on RHEV 
@ldjebran any idea's on these ?

- tests.foreman.ui.test_computeresource_rhev.RhevComputeResourceHostTestCase.test_positive_check_provisioned_rhev_os
- tests.foreman.ui.test_computeresource_rhev.RhevComputeResourceHostTestCase.test_positive_check_provisioned_vm_name

![rhevcomputeresourcehosttestcase-test_positive_check_provisioned_rhev_os-screenshot-2018-01-06_03_46_39](https://user-images.githubusercontent.com/14175952/34672430-504be250-f476-11e7-9598-2d4b03d9474c.png)

**Comment by san7ket** [comment]
The problem seems to be because of not using search() with query parameter to pass the search query, this is also a problem on fresh automation.
Currently the code https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_computeresource_rhev.py#L1205 will create a query 
```

2018-02-04 00:26:00 - nailgun.client - DEBUG - Making HTTP GET request to https://sat/api/v2/architectures with options {'verify': False, 'data': '{"name": "x86_64"}', 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}}, no params and no data.
2018-02-04 00:26:00 - nailgun.client - DEBUG - Received HTTP 200 response: {
  "total": 15,
  "subtotal": 15,
  "page": 1,
  "per_page": 20,
  "search": null,
  "sort": {
    "by": null,
    "order": null
  },
  "results": [{"created_at":"2018-02-02 18:42:46 UTC","updated_at":"2018-02-02 18:42:46 UTC","name":"x86_64","id":1},{"created_at":"2018-02-02 18:42:46 UTC","updated_at":"2018-02-02 18:42:46 UTC","name":"i386","id":2},{"created_at":"2018-02-04 04:54:45 UTC","updated_at":"2018-02-04 04:54:45 UTC","name":"rrzRk1Ykvw","id":3},{"created_at":"2018-02-04 04:59:04 UTC","updated_at":"2018-02-04 04:59:04 UTC","name":"oHcyhCEGGHLe","id":4},{"created_at":"2018-02-04 04:59:43 UTC","updated_at":"2018-02-04 04:59:43 UTC","name":"wRaxvMqWHp","id":5},{"created_at":"2018-02-04 04:59:44 UTC","updated_at":"2018-02-04 04:59:44 UTC","name":"KlgLwZNFrJt","id":6},{"created_at":"2018-02-04 04:59:57 UTC","updated_at":"2018-02-04 04:59:57 UTC","name":"jnLwSULMP","id":7},{"created_at":"2018-02-04 05:00:19 UTC","updated_at":"2018-02-04 05:00:19 UTC","name":"VBCzPexPKPfN","id":8},{"created_at":"2018-02-04 05:00:31 UTC","updated_at":"2018-02-04 05:00:31 UTC","name":"uXjUhyGfTvG","id":9},{"created_at":"2018-02-04 05:08:12 UTC","updated_at":"2018-02-04 05:08:12 UTC","name":"kRKTSUJA","id":10},{"created_at":"2018-02-04 05:08:22 UTC","updated_at":"2018-02-04 05:08:22 UTC","name":"PCCOzqzWtNK","id":11},{"created_at":"2018-02-04 05:08:24 UTC","updated_at":"2018-02-04 05:08:24 UTC","name":"FNuhbkaOkg","id":12},{"created_at":"2018-02-04 05:09:06 UTC","updated_at":"2018-02-04 05:09:06 UTC","name":"UfhSecBRyYa","id":13},{"created_at":"2018-02-04 05:09:46 UTC","updated_at":"2018-02-04 05:09:46 UTC","name":"MOELFvyWlLRw","id":14},{"created_at":"2018-02-04 05:23:26 UTC","updated_at":"2018-02-04 05:23:26 UTC","name":"NEEAarmB","id":15}]
}
```
Here, we are lucky enough to have our desired arch type at 0th place , but this is a unordered list and it seems after upgrade the list is shuffled placing the i386 in the 0th place.

We need to update the all such code as it may result in problems at later stages

**Comment by ldjebran** [comment]
@san7ket think we can close this issue fixed in this PR https://github.com/SatelliteQE/robottelo/pull/5820
