### ISSUE TITLE
vm.py - implement qemu-guest-agent support

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5349]
`qemu-guest-agent` is a daemon installed on a virtual guest, which reports some storage and network interface information back to its hypervysor over serial channel.
- I aim to use this to source the IP address information. The main advantage of using a direct serial channel is that there is no network involved, making this method universally work even in the VLAN network environments.

- [x] **snap-guest** - add `--channel` argument to the resulting `virt-install` command in order to define the serial channel for the created domain
- [x] **base-image** - re-create the base images by installing and enabling the `qemu-guest-agent` (available in the base rhel-server repo)
- [ ] **vm.py** - add an option to prefer `virsh domifaddr` source of information over `icmp` method (possibly making it default to preserve test compatibility)

**Comment by lpramuk** [comment]
the first two I've done already
- snap-guest is ready
- base-images are ready too

**Comment by lpramuk** [comment]
@rplevka when implementing changes in vm.py you might find these two commands usefull (run at hypervisor)
```
virsh qemu-agent-command $VM '{"execute":"guest-network-get-interfaces"}'| jq -r '.return[]|select(.name!="lo")."ip-addresses"[]|select(."ip-address-type"=="ipv4")."ip-address"'
```
```
virsh -q domifaddr $VM --source agent
```
I find the first one more usefull as it returns json and you can parse it in python easily without using ```jq```
