### ISSUE TITLE
Automate manifest refresh scenario

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#5363]
```
1) Create a manifest with two subscriptions (A & B) in the customer portal.
It does not matter what type of subscriptions they are.
 2) Import manifest into Satellite organization
 3) Observe both subscriptions A & B in satellite
 4) In the portal remove Subscription B from the manifest
 5) Export a new copy of the manifest
 6) Import the new manifest into Satellite.
 
 Expected Result:
 Satellite Server now shows only Subscription A in the organization.
 
 Observed Result:
 Satellite Server still shows Subscription B as well as Subscription A
```

**Comment by ldjebran** [comment]
@sghai @rplevka PR https://github.com/SatelliteQE/robottelo/pull/4482 with multi-manifests is becoming more and more actual.

**Comment by rplevka** [comment]
@rochacbruno ^

**Comment by ldjebran** [comment]
we have to investigate on portal subscription API also

**Comment by sghai** [comment]
Yes. I feel we need two things here:

a) APIs to play w/ portal to update existing manifest. we have the jenkins job to generate manifest and I think some how we need to reuse the same code to update manifests. Since @rplevka has better idea to play w/ manifest generation, so might can take a peek on this.

b) We need support in robottelo Framework, where we can  support multiple manifest import. May be we can delete the manifest once test is done by teardown ?
There is a PR raised by @rplevka https://github.com/SatelliteQE/robottelo/pull/4482 but this need really some work as its there since long.

c) As @rplevka pointed, may be we can update existing manifest to generate job where we can use to generate a updated/refreshed one. ( same job basically)

Roman will look into option c) as quick way to automate tests around manifest.

**Comment by rplevka** [comment]
@sghai - I'd like to revisit this one - it might be tricky to incorporate the interaction with access.redhat.com into robottelo. perhaps this should have its own jenkins job?
I recently implemented a multi-manifest support in robottelo, so perhaps we could do something like:

```bash
#!/bin/bash
./manifest-download.sh my_manifest.py
py-test test_subscription.py::SubscriptionTestCase::test_positive_upload
./manifest-portal-update.sh my_manifest.py
py-test test_subscription.py::SubscriptionTestCase::test_positive_upload
```

**Comment by JacobCallahan** [comment]
Closing this issue since it has not been acted upon up until this point. Future component owners can reopen if they are going to address this.
