### ISSUE TITLE
ContentViewTestCase.test_positive_remove_cv_version_from_multi_env_capsule_scenario - timeout openning channel

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5366]
There is a ssh timeout on `vm.suspend` and `vm.resume`. I think we might need to tweak the timeout in the test, since our CR is getting slower

- if you stumble upon more tests with the same issue, pls add them here and change the title to turn this issue into a tracker.

thx

**Comment by rochacbruno** [comment]
Lets start moving all the tests to `@destructive` pipeline (by the mtg discussion)

**Comment by ldjebran** [comment]
@rochacbruno @rplevka  why you think this test is a destructive one? 
it use a static vm hostname from settings it try to suspend it and resume, it cannot interfere with any other test as running in one thread.
the result of this move is that we have this test not running at all

**Comment by rplevka** [comment]
it does. It timeouted on resuming the VM several times, which failed the test instantly, with a capsule VM in suspended state. The capsule AR stayed in the satellite and influenced other tests the same way, as the fake capsule did - e.g., while building a pxe default template, the task tried to deploy the template to all TFTP capsules, including the dead one from the previous tests, leading to a failure.

**Comment by ldjebran** [comment]
Fix PR merged
