### ISSUE TITLE
VirtualMachine reuses the same image name

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5369]
This happens rarely.
but sometimes, our tests fail to register a host due this host being already registered in another org by different test.
This is simply because we generate the same name for the host:
https://github.com/SatelliteQE/robottelo/blob/master/robottelo/vm.py#L94

My assumption is, we should not use `id()` to generate the image name:

```python
In [27]: for _ in range(100):
    ...:     print(id(VirtualMachine()))
    ...:     
139763855412432
139763855412688
...
139763855412688
139763855412688
139763855412688
139763855412688
139763855412688
139763855412688
139763855412432
139763855412432
...
139763855412432
139763855412432
139763855412432
```

**Comment by san7ket** [comment]
hit this with last snap, if it is a small fix, could we have this. @ntkathole can you have a look onto this

**Comment by odovzhenko** [comment]
I propose to use uuid:
```
def uuid_test():
    ids = set()
    start_time = time.time()
    for _ in range(1000000):
        _id = uuid.uuid4().hex
        if _id in ids:
            raise Exception("id already in set")
        else:
            ids.add(_id)
    print time.time() - start_time, " seconds"       
    print len(ids)
    
uuid_test()
8.96462416649  seconds
1000000
```
