### ISSUE TITLE
Realm tests cannot use fake capsule/proxy without realm feature

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5370]
Relam tests are creating fake proxy and then CRUD Relam opertaions are performed this fails as the created proxy doesn't have relam feature on it

- [x] tests.foreman.cli.test_realm.RealmTestCase.test_positive_delete_by_name

**Comment by ntkathole** [comment]
_hammer -v -u admin -p changeme --output=csv realm create --realm-type="Active Directory" --name="KVu5LA" --realm-proxy-id="8"
 <<< stderr
 422 Unprocessable Entity
 Realm Capsule does not have the Realm feature
Could not create the realm:
  Realm Capsule does not have the Realm feature_

```
E           CLIFactoryError: Failed to create Realm with data:
E           {
E             "location-ids": null,
E             "locations": null,
E             "name": "KVu5LA",
E             "organization-ids": null,
E             "organizations": null,
E             "realm-proxy-id": "8",
E             "realm-type": "Active Directory"
E           }
E           Command "realm create" finished with return_code 65
E           stderr contains following message:
E           [ERROR 2017-11-06 03:25:27 API] 422 Unprocessable Entity
E           [ERROR 2017-11-06 03:25:27 Exception] Realm Capsule does not have the Realm feature
E           Could not create the realm:
E             Realm Capsule does not have the Realm feature
```

**Comment by san7ket** [comment]
Closing this in favor or https://github.com/SatelliteQE/satellite6-upgrade/issues/127 , only on upgrade
