### ISSUE TITLE
test_positive_ad_basic_roles failing due to syntax error

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5372]
- [ ]  tests.foreman.ui.test_user.ActiveDirectoryUserTestCase.test_positive_ad_basic_roles

            assigned_permissions = self.role.get_permissions(
              role_name, [resource_type])
E           TypeError: get_permissions() takes exactly 2 arguments (3 given)
tests/foreman/ui/test_user.py:1424: TypeError

```
 def get_permissions(self, role_name):
        """Fetch all assigned permissions from role page.

        :param role_name: String with role name.
        :return: Dict with resource name as a key and list of strings with
            permissions names as a values.
        """
```

**Comment by ldjebran** [comment]
@san7ket @ntkathole that function has been renamed to filters_get_permissions
in PR https://github.com/SatelliteQE/robottelo/pull/5289

**Comment by ldjebran** [comment]
so that become 
```python 
   assigned_permissions = self.role.filters_get_permissions( role_name, [resource_type])
```

**Comment by ntkathole** [comment]
@ldjebran thanks...PR raised.

**Comment by ldjebran** [comment]
PR merged

**Comment by san7ket** [comment]
Teamwork++
