### ISSUE TITLE
ContentView test cases working with versions rely on correct version ordering

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5384]
ContentViewPublishPromoteTestCase - test_positive_promote_out_of_sequence 
the test relies on retrieving a list of the version sorted by versions, however this does not necessarily happen.
We don't use nailgun.cv.read with any sorting option, so we should not rely on the order.
This started to happen few builds ago but it happened between the 2 runs for the same build (1 passed, another one failed) so I don't think this has been caused by the change in the product - even if it was, the sorting is not guaranteed (i think backend simply returns the list in a order it got written to the db).
Looks like some additional tests have been added, making some more CV publishing tests running synchronously, which might shuffle the ordering.

**Comment by rplevka** [comment]
happens here too with CLI:
https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_contentview.py#L2409

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
