### ISSUE TITLE
tests.foreman.ui.test_errata tests, unable to find/select content host 

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5401]
This is also a issue for fresh automation , where multiple tests from this class fail due to same reason
For upgrade, 
- [ ]  tests.foreman.ui.test_errata.ErrataTestCase.test_positive_filter
![erratatestcase-test_positive_filter-screenshot-2017-10-20_23_38_13](https://user-images.githubusercontent.com/14175952/31930597-e1744820-b8bd-11e7-8ffc-96774106fc49.png)

~~tests.foreman.ui.test_errata.ErrataTestCase.test_positive_apply_for_all_hosts
Test is unable to find the content hosts to apply errata on~~
~~
![erratatestcase-test_positive_apply_for_all_hosts-screenshot-2017-10-20_23_26_37](https://user-images.githubusercontent.com/14175952/31930558-c39a4e3a-b8bd-11e7-8c22-9a854d7c02b3.png)

**Comment by svtkachenko** [comment]
@san7ket I believe this is a bug:
1. Reproducible manually
2. Test clearly selects 2 hosts when watching its playback.
3. Screenshot says "Apply errata to 2 Content Hosts" so they indeed were selected :)

Can you please close this issue and fill a bug?

**Comment by san7ket** [comment]
This didn't appear on latest snap , but the second issue still present 
tests.foreman.ui.test_errata.ErrataTestCase.test_positive_filter
`Error: ValueError: Provided target <|strategy=xpath|value=//input[@ng-model='detailsTable.searchTerm']|> is not supported by framework`

Looks like an automtion issue?
