### ISSUE TITLE
test_positive_rhel6

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#5429]
stub on file test_virt_who_config

        :id: f0453a2d-fa81-40ae-81a9-330b529a3062

        :steps:
            1. Install VirtWho on a RHEL6 server

        :expectedresults:
            1. Verify a virt-who configuration script can be deployed on
               RHEL6 Server

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
