### ISSUE TITLE
test_positive_restore_after_update

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#5486]
Restore from a backup in updated version of satellite

        :id: 2069b860-43d4-4b65-a8cd-89a8b2feafbe

        :Steps:

            1. Create backup from previous version of satellite
            2. Update satellite to latest version
            3. Restore online backup
            4. Restore offline backup
            5. Restore online incremental backup
            6. Restore offline incremental backup

        :expectedresults: Each backup is fully restored.

        :CaseAutomation: notautomated

        """
        # IS THIS CASE REASONABLE?

**Comment by pondrejk** [comment]
I think this stub is no longer valid, restore tests are covered by https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/sys/test_restore.py, tests are now in place to cover upgrades, and migrating between rhel versions is a domain of sat-clone, so this issue should really be about removing the stubs.
