### ISSUE TITLE
test_positive_restore

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#5487]
Restore to a Satellite with config that has been updated since the
        backup

        :id: 03a47dec-9cd4-4cae-88ec-c19dfaa1d5ad

        :Steps:

            1. Restore online backup
            2. Restore offline backup
            3. Restore online incremental backup
            4. Restore offline incremental backup

        :expectedresults: Each backup is fully restored.

**Comment by pondrejk** [comment]
this is already covered by https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/sys/test_restore.py, so this issue should be probably about removing stubs from the test_hot_backup.py
