### ISSUE TITLE
test_positive_load_backup

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#5488]
Load testing, backup

        :id: b0d7de3a-d1d5-4cb9-8041-47301b658408

        :Steps:
            1. Create load on the Satellite by having multiple host pull
               content.
            2. Run a backup while the Satellite is under load
            3. Restore the backup

        :expectedresults: The backup is successful and the restored
            configuration is correct.

**Comment by pondrejk** [comment]
I'd merge this case with the stub from #5490
