### ISSUE TITLE
test_positive_load_restore

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#5489]
Load testing, restore

        :id: c0347aee-48b4-45da-92ef-1e92397c5543

        :Steps:

            1. Run a backup.
            2. Run a restore.

        :expectedresults: The restore is successful.

**Comment by pondrejk** [comment]
this is altready covered by https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/sys/test_restore.py, so this issue should be probably about removing the stub from the test_hot_backup.py
