### ISSUE TITLE
test_positive_upload_file_to_file_repo

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#5502]
heck arbitrary file can be uploaded to File Repository

        :id: 134d668d-bd63-4475-bf7b-b899bb9fb7bb

        :Steps:
            1. Create a File Repository
            2. Upload an arbitrary file to it

        :expectedresults: uploaded file is available under File Repository

**Comment by sghai** [comment]
@omkarkhatavkar : Please see if you can take this up. Test is defined here:
https://github.com/SatelliteQE/robottelo/blob/347f69962dc4f87174ee19fc45ead40c163ef883/tests/foreman/cli/test_repository.py#L2404

**Comment by omkarkhatavkar** [comment]
This is done @sghai and here is the merge request https://github.com/SatelliteQE/robottelo/pull/6148
