### ISSUE TITLE
Git Templates: test_positive_export_to_branch

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#5531]
Using nailgun or direct API call export templates specifying a git branch e.g: -d {'branch': 'testing'} in POST body. 

Assert result is {'message': 'success'} and templates exportedAssert templates were exported to specified branch on repo

**Comment by JacobCallahan** [comment]
Closing this issue since it has not been acted upon up until this point. Future component owners can reopen if they are going to address this.
