### ISSUE TITLE
Git templates:  test_positive_import_from_branch

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#5536]
Using nailgun or direct API call import templates specifying a git branch e.g: -d {'branch': 'testing'} in POST body. 

Assert result is {'message': 'success'} and templates imported
Assert only templates from that branch were imported

**Comment by JacobCallahan** [comment]
Closing this issue since it has not been acted upon up until this point. Future component owners can reopen if they are going to address this.
