### ISSUE TITLE
Correctly handle passing latin1 encoded strings

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#554]
The latin1 string encode should be specified when calling the `encode` method. Currently all string are encoded as utf-8, is needed a way to specify the string encoding that is wanted when sending data.

**Comment by chbrown13** [comment]
FYI new issue #4864 deals with automating tests for latin1 and multibyte string organization names. How should we handle this?

**Comment by chbrown13** [comment]
cc @JacobCallahan
