### ISSUE TITLE
Git templates: test_positive_import_associated_with_taxonomies

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#5541]
Using nailgun or direct API call import some template containing metadata with Org/Loc specs and specify the associate parameter e.g: -d {'associate': 'always'} in POST body. 

Assert result is {'message': 'success'}
Assert template is imported and org/loc are associated based on template metadata.

**Comment by JacobCallahan** [comment]
Closing this issue since it has not been acted upon up until this point. Future component owners can reopen if they are going to address this.
