### ISSUE TITLE
test_negative_update_login_page_footer_text

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#5554]
Attempt to update parameter "Login_page_footer_text"
            with invalid value(long length) under General tab

        :id: 87ef6b19-fdc5-4541-aba8-e730f1a3caa7

        :steps:

            1. Execute "settings" command with "set" as sub-command
            with invalid string(long length)

        :expectedresults: Parameter is not updated

        :caseautomation: notautomated

        :caseimportance: low

**Comment by ntkathole** [comment]
@renzon This test scenario is changed now due to changes in feature. PR #5419 raised  with automated CLI scenario. Thanks.

**Comment by renzon** [comment]
@ntkathole have this issue been automated on #5419? If yes, can you close this issue?

**Comment by ntkathole** [comment]
@renzon Yes this test case is automated.Closing this issue!
