### ISSUE TITLE
ErrataTestCase.test_positive_user_permission - user needs to be assigned to org

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5595]
the test needs to be updated according:
https://bugzilla.redhat.com/show_bug.cgi?id=1507523

- the user needs to belong to a corresponding org in order to view errata

**Comment by ntkathole** [comment]
@rplevka Looks like same as #5458

**Comment by rplevka** [comment]
@ntkathole thanks! closing this
