### ISSUE TITLE
ContentViewTestCase.test_positive_delete_with_kickstart_repo_and_host_group failing

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5597]
The test introduced in https://github.com/SatelliteQE/robottelo/pull/5548 is not passing in the automation.

@oshtaier could you please check&fix it?

![img](http://storage3.static.itmages.com/i/17/1120/h_1511177498_3106299_4a1497193e.png)

**Comment by oshtaier** [comment]
Then `test_positive_create_with_oscap_capsule` from https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_hostgroup.py should also failing
as some other tests. And if that is true then we need to investigate it more

**Comment by oshtaier** [comment]
Anyway, I will run it

**Comment by odovzhenko** [comment]
Fixed by #5663
