### ISSUE TITLE
UI HostContentHostUnificationTestCase - failing host rename test cases

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5598]
the following test cases have been failing long-term and need some care:

- test_positive_rename_content_host
- test_positive_rename_content_host_cli
- test_positive_rename_foreman_host

**Comment by rplevka** [comment]
- test_positive_rename_foreman_host keeps failing

test_positive_rename_content_host
and
test_positive_rename_content_host_cli

passed for 3 builds but then started to fail again

**Comment by odovzhenko** [comment]
test_positive_rename_content_host and test_positive_rename_content_host_cli passed for m locally and in Sauce Labs. Probably some random issue. For test_positive_rename_foreman_host I opened #5662 for further investigation.

**Comment by odovzhenko** [comment]
Closed as duplicate of #5662
