### ISSUE TITLE
Problem with Rhel69 base images used as content host 

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5627]
I don't know , why or when it started. But the CH created from rhel69 images are unable to be register with Satellite with their hostname, and are registered as localhost.localdomain, which fails tests as all CH will use same hostname.
The hostname of these images used via subscription-manger is localhost.localdomain. Although the hostname -f and hostname returns a valid hostname with fqdn.
On subscription-manager facts output,
```
network.fqdn: localhost.localdomain
network.hostname: 740120779201424.lab.eng.rdu2.redhat.com
network.ipv4_address: 127.0.0.1
network.ipv6_address: ::1
```
On looking further, I noticed the facts of subscription manager which is network.fqdn: localhost.localdomain
on removing the following entries from /etc/hosts seems to fix the issue
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

```
 and after removing the enteries
```

network.fqdn: 740120779201424.domain
network.hostname: 740120779201424.domain
network.hostname-override: 740120779201424.domain
network.ipv4_address: 127.0.0.1
network.ipv6_address: ::1
```

EDIT: I think the hostname -A doesn't return anything on rhel6 , may be causing this.
Only happens with rhel6, @rplevka @lpramuk any idea what's causing this, was something changed?

**Comment by san7ket** [comment]
After investigation, it was a bug indeed , @LP filed it https://bugzilla.redhat.com/show_bug.cgi?id=1519776

**Comment by san7ket** [comment]
We need add a workaround for this problem within snap-guest

**Comment by san7ket** [comment]
Looks like issue is resloved ,

**Comment by lpramuk** [comment]
I modified snap-guest at ginger to see if the record ```127.0.0.1 hostname``` in ```/etc/hosts``` is really needed for some obscure reason
