### ISSUE TITLE
SmartVariablesTestCase - failing

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5659]
the following tests keep consistently failing:

-  test_positive_override_default_value_from_attribute
-  test_positive_override_from_attribute
-  test_positive_update_hidden_value_in_attribute
-  test_positive_update_matcher_from_attribute

**Comment by odovzhenko** [comment]
Duplicate of #5594

**Comment by rplevka** [comment]
@odovzhenko oops :D
