### ISSUE TITLE
[RFE] use Library and DOV in tests which not explicitlely rely on them

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5667]
There might be a lot of boost gained from making content availalbe from the Library env straight away - This makes the Content available straight after syncing a repo, so no `create LCE, create CV, add content to CV, publish CV, promote CV, create AK and associate the env with it` dance is necessary.

This also very nice in the API tests where we get the references to the Library env and Default Organizational View (DOV) straight after we create a new Org.

**Comment by rplevka** [comment]
personal notes:
- there is a unnecessary CV create + publish + promote nested inside `cli.factory::setup_cdn_and_custom_repos_content` method.

I can see this one being indirectly used by `CapsuleVirtualMachine.create()` method.
the call tree looks like:
```
test
|--CapsuleVirtualMachine.create()
  |--_setup_capsule()
    |--cli.factory::setup_capsule_virtual_machine()
      |--cli.factory::setup_cdn_and_custom_repos_content()
```
- I think we should expose an optional `cv_id` to the very top to give user a way of skipping CV creation+publish+promote in case he wants to use the default orgainzation view.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
