### ISSUE TITLE
[RFE] add dogfood repo to client manually instead of syncing it to satellite first

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5668]
We often add&sync a dogfood repo (e.g. capsule, sat_tools) in order to be able to deploy a capsule || katello_agent on a VM in order to test the unrelated things (we just usually need to make the packages available to VM so it can install them).
We might save some time and resources if we simply added the repo pointing to the dogfood to the vm straight away (we might possibly extend the `vm.py` module to make this more comfortable).

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
