### ISSUE TITLE
Some tests install katello-agent without really needing it

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5669]
there are some (mainly content management related) tests which create a vm and apart from subscribing it to the satellite, they also install a katello-agent package to it (this mostly comes with creating&syncing a sat-tools repo and deploying it in a CV in order to make it available to host).

this is a tracker and i will update it with a list of applicable tests.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
