### ISSUE TITLE
Default role no longer returned by api

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5670]
the following tests rely on Default Role being returned on user info:

tests.foreman.api.test_user.UserRoleTestCase:
 - test_positive_create_with_role
 - test_positive_update

tests.foreman.cli.test_user.UserWithCleanUpTestCase:
  - test_positive_update_all_roles (/ not sure about this one)

tests.foreman.cli.test_errata.ErrataTestCase:
  - test_positive_user_permission

however, 
https://bugzilla.redhat.com/show_bug.cgi?id=1518654
changed the behaviour and no longer shows this role (by design)

**Comment by ldjebran** [comment]
one more test for this issue: tests.foreman.cli.test_contentview.ContentViewTestCase.test_positive_user_with_all_cv_permissions
