### ISSUE TITLE
[UI] T3 Host test cases are failing

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5675]
I keep this as a tracker for now, the root causes might differ and require individual issues to be filled.

 test_positive_check_permissions_affect_create_procedure
 test_positive_create_with_inherited_params
 test_positive_set_multi_line_and_with_spaces_parameter_value

 test_positive_remove_parameter_non_admin_user
 test_positive_update_name
 test_positive_update_name_with_prefix

**Comment by odovzhenko** [comment]
test_positive_remove_parameter_non_admin_user and test_positive_check_permissions_affect_create_procedure should be fixed via #5683 
Other tests are failing due to #5662

**Comment by odovzhenko** [comment]
Fixed by #5662
