### ISSUE TITLE
Automate Test for BZ 1498447

### ISSUE THREAD

**Issue by JacobCallahan** [SatelliteQE/robottelo#5700]
Automating this bug will be a big win for PM.

Requires RHEV Compute Resource

Steps:
1. Hosts -> Create Host
2. Fill in the form, using RHEV computing resource as "Deploy on"
3. Submit

Actual results:
Error, traceback, operation fails

Expected results:
New host created

https://bugzilla.redhat.com/show_bug.cgi?id=1498447

**Comment by san7ket** [comment]
We already have this here https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_computeresource_rhev.py#L749

**Comment by ldjebran** [comment]
I provisioned many times with RHEV and never got the change to see this  error, perhaps this happen if dns entry supplied

**Comment by pgagne** [comment]
@JacobCallahan @san7ket @ldjebran is this issue still valid or can we close this?
