### ISSUE TITLE
tests.foreman.ui.test_host.AtomicHostTestCase will fail due to setup phase issues 

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5736]
1. Kickstart Default ptable doesn't belong to the org/loc in which the atomic host is to be created
2. Subnet has IPAM value None , which would prevent box from having an ip address
![atomichosttestcase-test_positive_delete_atomic_host-screenshot-2017-12-22_17_37_51](https://user-images.githubusercontent.com/14175952/34355069-a2df1632-ea2a-11e7-8480-2f3cf9d1a5ad.png)

**Comment by ldjebran** [comment]
fixed in
