### ISSUE TITLE
Refactoring locator for location dropdown

### ISSUE THREAD

**Issue by odovzhenko** [SatelliteQE/robottelo#5789]
Related to #5783
In test_role.py::CannedRoleTestCases::test_positive_create_filter_without_override and test_positive_create_non_overridable_filter tests we create non-admin user with roles. In that case locator for location dropdown changes:  
```
<li class="dropdown-submenu loc-menu">
  <a data-id="aid_not_defined" href="#">xsuyrD</a>
...
</li>
```
while we're expecting:
```
<li class="dropdown-submenu loc-menu">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">xsuyrD</span></a>
...
</li> 
```
so relay on `@data-toggle` in `"//li[contains(@class,'org-switcher')]//li/a[@data-toggle='dropdown'])[2]")` is not good idea.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
