### ISSUE TITLE
Minitest port UI test_location

### ISSUE THREAD

**Issue by odovzhenko** [SatelliteQE/robottelo#5850]
Target project: Foreman

- [ ]  test_positive_auto_search
- [ ]  test_positive_create_with_name
- [ ]  test_negative_create_with_invalid_names
- [ ]  test_negative_create_with_same_name
- [ ]  test_positive_update_name
- [ ]  test_negative_update_with_too_long_name
- [ ]  test_positive_delete
- [ ]  test_positive_check_all_values_hostgroup
- [ ]  test_positive_check_all_values_template

**Comment by ldjebran** [comment]
will not be implemented
