### ISSUE TITLE
[py3.6] AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5882]
This is a issue to track all tests failing with the [subject]

<more details to be provided by @rplevka>

**Comment by rplevka** [comment]
- [ ] tests.foreman.cli.test_activationkey.ActivationKeyTestCase::test_negative_copy_with_same_name
- [ ] tests.foreman.cli.test_activationkey.ActivationKeyTestCase::test_negative_update_name
- [ ] tests.foreman.cli.test_activationkey.ActivationKeyTestCase::test_negative_update_usage_limit
- [ ] tests.foreman.cli.test_architecture.ArchitectureTestCase::test_negative_create_with_name
- [ ] tests.foreman.cli.test_architecture.ArchitectureTestCase::test_negative_delete_by_id
- [ ] tests.foreman.cli.test_architecture.ArchitectureTestCase::test_negative_update_name

**Comment by lhellebr** [comment]
https://github.com/SatelliteQE/robottelo/pull/5899

**Comment by rplevka** [comment]
this is fixed
