### ISSUE TITLE
[py3.6] AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5883]
This is a issue to track all tests failing with the [subject]

<more details to be provided by @rplevka>

**Comment by rplevka** [comment]
- [ ] tests.foreman.cli.test_domain.DomainTestCase::test_positive_update
- [ ] tests.foreman.cli.test_subnet.SubnetTestCase::test_negative_create_with_address_pool
- [ ] tests.foreman.cli.test_subnet.SubnetTestCase::test_negative_update_address_pool

**Comment by lhellebr** [comment]
Taking

**Comment by lhellebr** [comment]
https://github.com/SatelliteQE/robottelo/pull/5903

**Comment by rplevka** [comment]
this is fixed
