### ISSUE TITLE
Refactor RHV tests for python3

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5891]
Since, we have moved RHV from self-signed cert, we need to update the tests to use the new ca.cert

- [ ] https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_computeresource_rhev.py

- [ ] https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_computeresource_rhev.py

**Comment by san7ket** [comment]
Problem is with this line of code https://github.com/SatelliteQE/robottelo/blob/6.3.z/tests/foreman/ui/test_computeresource_rhev.py#L66

For python2, I don't see new line character in the content of the request object, when selenium submits it Web UI
```
-----BEGIN CERTIFICATE-----
MIIDsjC
```
But for python3 , Content has new line character and Satellite cannot handle cert content with new line characters,when selenium submits it to Web UI
`-----BEGIN CERTIFICATE-----\nMIIDsjCCApqgAw`

**Comment by lpramuk** [comment]
I got the clue, wait for my PR
