### ISSUE TITLE
Please fix CLI test test_hammer.py

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#5914]
Failures for `/tests/foreman/cli/test_hammer.py` must be dealt with by:

* Updating CLI tests whenever a new parameter has changed (e.g. `hammer host`'s  *environment* parameter is now called *puppet-environment)
* The file `tests/foreman/data/hammer_commands.json` must also be updated

**Comment by lpramuk** [comment]
The tests will continue failing even with this fix due to another reason 
http://projects.theforeman.org/issues/23167

I found it during testing the PR #5917 :)

**Comment by omaciel** [comment]
@lpramuk do we need a blocker Bugzilla to get it fixed?

**Comment by lpramuk** [comment]
http://projects.theforeman.org/issues/23167 is being closed. Issue was caused by outdated apipie cache. This can happen when enable plugins incrementally, thus fixing withing our realms, taadaa:

https://github.com/SatelliteQE/automation-tools/pull/677
