### ISSUE TITLE
Many tests use hardcoded RHEL 7.4 server rpms

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5928]
Many of the capsule test's virt-who tests use the hardcoded rhel7.4 server rpms to sync and then installs the required product using these synced rpms. This could prove time consuming to move when a new release is here.
I have identified Capsule tests and virt who tests using the same 7.4 and not using distro parameter from robotello.properties

**Comment by alda519** [comment]
Please can you provide list of affected tests, or example of what to fix here?

**Comment by san7ket** [comment]
- tests.foreman.cli.test_contentview.ContentViewTestCase.test_positive_remove_cv_version_from_multi_env_capsule_scenario

**Comment by jhutar** [comment]
@san7ket `...ui...` tests are not supposed to run on 6.4, only `...ui_airgun...`, right?

**Comment by san7ket** [comment]
Yes, but I see the error is in helper function(in setup phase), but you are right it should be tracked separately while automating into airgun.

**Comment by ldjebran** [comment]
@san7ket this is a common problem for all our tests that use VM with distro, that's why I have created a PR solution that have to choose the RHEL distribution that is related to distro automatically.
https://github.com/SatelliteQE/robottelo/pull/5807

**Comment by ldjebran** [comment]
@san7ket will try to find time and finalize that PR, that way we should have no problem when switching default VM images from RHEL 7.4 to RHEL 7.5 or to RHEL 8.0

**Comment by ntkathole** [comment]
`tests.foreman.api.test_contentmanagement::CapsuleContentManagementTestCase`
