### ISSUE TITLE
capsule install requires SCL repos again

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5974]
SSIA

**Comment by rplevka** [comment]
@jhutar 
pretty much all tests involving capsule deployment.

tests.foreman.api.test_contentmanagement::CapsuleContentManagementTestCase::*

**Comment by ntkathole** [comment]
`<tests.foreman.cli.test_contentview.ContentViewTestCase testMethod=test_positive_remove_cv_version_from_multi_env_capsule_scenario>`

**Comment by rplevka** [comment]
@jhutar @ntkathole - FYI, i already have a fix for this, i'm just trying to implement few optimizations before i submit the fix.

**Comment by jhutar** [comment]
@rplevka FYI we probably need to add Ansible Engine repo as well
