### ISSUE TITLE
assertion update needed on CLI actiovation key tests

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5989]
most of the assertions are okay, they just try to strictly match the lower case.

```
AssertionError: "'--auto-attach': value must be one of" not found in "[ERROR 2018-05-12T16:25:43 Exception] Error: Option '--auto-attach': Value must be one of true/false, yes/no, 1/0..\n\nSee: 'hammer activation-key update --help'.\nCould not update the activation key:\n  Error: Option '--auto-attach': Value must be one of true/false, yes/no, 1/0..
```

**Comment by rplevka** [comment]
```
ERROR 2018-05-18T15:27:54 Exception] Validation failed: Name must contain at least 1 character, Name can't be blank
Could not create the activation key:
  Validation failed: Name must contain at least 1 character, Name can't be blank
[ERROR 2018-05-18T15:27:54 Exception] 

RestClient::UnprocessableEntity (422 Unprocessable Entity):
```

**Comment by rplevka** [comment]
AssertionError: "Error: option '--max-hosts': numeric value is required" not found in 'Failed to create ActivationKey with data:\n{\n  "content-view": null,\n  "content-view-id": null,\n  "description": null,\n  "lifecycle-environment": null,\n  "lifecycle-environment-id": null,\n  "max-hosts": "",\n  "name": "2ICmDcBBmc",\n  "organization": null,\n  "organization-id": "334",\n  "organization-label": null,\n  "unlimited-hosts": null\n}\nCommand "activation-key create" finished with return_code 65\nstderr contains following message:\n[ERROR 2018-05-18T15:28:04 API] 422 Unprocessable Entity\n[ERROR 2018-05-18T15:28:04 Exception] Validation failed: Max hosts cannot be nil\nCould not create the activation key:\n  Validation failed: Max hosts cannot be nil\n[ERROR 2018-05-18T15:28:04 Exception] \n\nRestClient::UnprocessableEntity (422 Unprocessable Entity)

**Comment by rplevka** [comment]
there's another problem with the assertions now on passing `--name="\t"`:
```
AssertionError: '\t' not found in 'Failed to create ActivationKey with data...
```

the reason is, that our test treats "\t" as a string with length >0 thus expects different validation-failed message.

**Comment by jhutar** [comment]
Just to be clear, this issue is addressing failures in these two tests:

tests.foreman.cli.test_activationkey.ActivationKeyTestCase.test_negative_create_with_invalid_name
tests.foreman.cli.test_activationkey.ActivationKeyTestCase.test_negative_create_with_usage_limit_with_not_integers
