### ISSUE TITLE
get_applicable_errata timing issues

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#6012]
Under certain circumstances in automation, errata status is queried before it has been calculated, for example in tests.foreman.longrun.test_inc_updates.IncrementalUpdateTestCase.test_positive_noapply_cli (6.4 snap 8)

```
        # Get the applicable errata
        errata_list = self.get_applicable_errata(self.rhva_6_repo)
>       self.assertGreater(len(errata_list), 0)
E       AssertionError: 0 not greater than 0

tests/foreman/longrun/test_inc_updates.py:300: AssertionError
```

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
