### ISSUE TITLE
api.test_permission.PermissionTestCase - new permissions + types added

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#6031]
`tests.foreman.api.test_permission.PermissionTestCase.test_positive_search`
`tests.foreman.api.test_permission.PermissionTestCase.test_positive_search_by_resource_type`

```
AssertionError: {
  "added_names": [
    "import_templates",
    "export_templates"
  ],
  "added_resource_types": [   "Template"  ] }
```
```
AssertionError: {  "Host": {   "added": [    "play_roles_on_host"   ]  },  "HostClass": {   "added": [],   "removed": [    "play_roles_on_host"   ]  } }
```

**Comment by pondrejk** [comment]
needs fixing as it won't be ported to minitest (https://github.com/SatelliteQE/robottelo/issues/5871)
