### ISSUE TITLE
https://sat6.com/api/v2/smart_variables/1046/override_values with correct params

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/robottelo#6087]
There is a bug in our tests:

https://bugzilla.redhat.com/show_bug.cgi?id=1583160#c2 + comment 3 + comment 4

tests.foreman.api.test_classparameters.SmartClassParametersTestCase::test_negative_validate_matcher_and_default_value

If I understand Ori's comments correctly, we need to make the test not to send:

```
{"match": "is_virtual=true", "value": "", "smart_variable_id": 1046}
```

but:

```
{"override_value": {"match": "is_virtual=true", "value": ""}, "smart_variable_id": 1046}
```

**Comment by jhutar** [comment]
Maybe this is a bug in Nailgun?

**Comment by jhutar** [comment]
Also in this test:

tests.foreman.api.test_variables.SmartVariablesTestCase::test_negative_create_matcher_empty_value

we are sending:

```
{"match"=>"is_virtual=true", "value"=>"[FILTERED]", "smart_variable_id"=>"1026", "apiv"=>"v2", "override_value"=>{"match"=>"is_virtual=true", "value"=>"[FILTERED]", "smart_variable_id"=>"1026"}}
```

**Comment by ldjebran** [comment]
@jhutar when ported one of tests to foreman, ported as:
{"override_value": {"match": "is_virtual=true", "value": ""}, "smart_variable_id": 1046}
and the minitest is, passing https://github.com/ldjebran/foreman/blob/2aa03c2b6658f84ba3d282ee4bc43e162b3025e3/test/controllers/api/v2/override_values_controller_test.rb#L85

Think nailgun must be updated accordingly.

But there an other question raising, why they was working in the past ?

**Comment by jhutar** [comment]
@ldjebran Ori in the bug mentioned something was changed on a Foreman side (it was not that strict in the past).

Shall I close this issue and copy it to NailGun pls?
