### ISSUE TITLE
[important][investigation] ErrataTestCase tests failing with incorrect number of errata

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/robottelo#6105]
These tests seems to all fail because of incorrect number of applicable errata in 6.4 automation. It might be a bug in the product, so we need to investigate what is going on.

- [x] tests.foreman.api.test_errata.ErrataTestCase.test_positive_get_diff_for_cv_envs
  
  ```
  StopIteration
  ```
  edit: https://github.com/SatelliteQE/robottelo/issues/6105#issuecomment-410662879 - https://github.com/SatelliteQE/robottelo/pull/6169
- [ ] tests.foreman.api.test_errata.ErrataTestCase.test_positive_install_multiple_in_host
  
  ```
  AssertionError: 3 != 2
  ```

- [ ] tests.foreman.api.test_errata.ErrataTestCase.test_positive_get_count_for_host
  
  ```
  AssertionError: Host ... contains 0 bugfix errata, but expected to contain 1 of them
  ```

- [ ] tests.foreman.api.test_errata.ErrataTestCase.test_positive_get_applicable_for_host
  
  ```
  AssertionError: Host ... contains 1 available errata, but expected to contain 3 of them
  ```

**Comment by jhutar** [comment]
@ntkathole please could you take a look?

**Comment by ntkathole** [comment]
Once https://bugzilla.redhat.com/show_bug.cgi?id=1596049 will ON_QA, tests should pass.

**Comment by san7ket** [comment]
@ntkathole can we add the skip if bz to related BZ's ?

**Comment by rplevka** [comment]
heads up: the bz is already in verified, yet the tests are still failing the same way - i conclude that this is a different issue (most proably the timing one)

**Comment by rplevka** [comment]
the 
```tests.foreman.api.test_errata.ErrataTestCase.test_positive_get_diff_for_cv_envs```
one is a simple failure where we list errata diffs with the default pagination (`per_page`: 20), however, the errata id we're expecting is the 21st, so it's not listed.
submitting an easy fix (specifying `per_page`: 9999)

**Comment by JacobCallahan** [comment]
Closing this issue since it has not been acted upon up until this point. Future component owners can reopen if they are going to address this.
