### ISSUE TITLE
[investigation] DiscoveredTestCase tests are not discovering hosts

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/robottelo#6106]
I need help with investigating this issue which appeared in multiple test results. Might be bug in the product, issue in our infrastructure or in the tests.

tests.foreman.cli.test_discoveredhost.DiscoveredTestCase.test_positive_delete_pxe_host
```
        with LibvirtGuest() as pxe_host:
            hostname = pxe_host.guest_name
            host = self._assertdiscoveredhost(hostname)
>           self.assertIsNotNone(host)
E           AssertionError: unexpectedly None
```

tests.foreman.cli.test_discoveredhost.DiscoveredTestCase.test_positive_provision_pxe_host_with_bios_syslinux
```
        with LibvirtGuest() as pxe_host:
            hostname = pxe_host.guest_name
            # fixme: assertion #2-3
            # assertion #4
            discovered_host = self._assertdiscoveredhost(hostname)
>           self.assertIsNotNone(discovered_host)
E           AssertionError: unexpectedly None
```

tests.foreman.cli.test_discoveredhost.DiscoveredTestCase.test_positive_pxe_based_discovery
```
        with LibvirtGuest() as pxe_host:
            hostname = pxe_host.guest_name
            host = self._assertdiscoveredhost(hostname)
>           self.assertIsNotNone(host)
E           AssertionError: unexpectedly None
```

**Comment by san7ket** [comment]
Me and kedar were discussion this and one possible explanation for this, 
We are creating same boxes with different names in our environment.
When a discovered host is created and come online,it would look for DHCP in envorinment, where it might find more than one DHCP running on qe-sat6-tier1,qe-sat6-tier2,qe-sat6-tier3 boxes and so we are unable to see the host in satellite. 

Need to test this hypothesis though, will do it with current automation.

**Comment by rplevka** [comment]
it's much simpler than that.
the newly created orgs&locs no longer have all subnets assigned by default.
when the PXEless discovery tries to POST facts to satellite, it receives ISE as the org and loc set as default for the discovery have no subnet assigned.

**Comment by rplevka** [comment]
also, the template names changed.
i fixed everything + introduced some improvements to the tests to speed them up:

https://github.com/SatelliteQE/robottelo/pull/6143

**Comment by pgagne** [comment]
@rplevka @jhutar can we close this?

**Comment by rplevka** [comment]
yes.
