### ISSUE TITLE
tests.foreman.api.test_discoveryrule.DiscoveryRuleTestCase: when creating discovery rule via API we have to specify priority != priority of existing rules

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/robottelo#6124]
This is a new restriction in snap 10:

When you do not define priority, discovery with priority 0 is created:

```
$ curl -X POST -H "Content-Type: application/json" --data '{"organization_id": 1, "location_id": 2, "discovery_rule": {"name": "MyDiscoveryRule", "hostgroup_id": 2, "search": "model = KVM"}}' --insecure -u admin:changeme https://sat640snap10.example.com/api/v2/discovery_rules
{"id":1,"name":"MyDiscoveryRule","search":"model = KVM","hostgroup_id":2,"hostname":"","max_count":0,"priority":0,"enabled":true,"created_at":"2018-07-06T21:21:34.221Z","updated_at":"2018-07-06T21:21:34.221Z"}
```

When you attempt to create a new one, it fails now:

```
$ curl -X POST -H "Content-Type: application/json" --data '{"organization_id": 1, "location_id": 2, "discovery_rule": {"name": "MyDiscoveryRule2", "hostgroup_id": 2, "search": "model = KVM"}}' --insecure -u admin:changeme https://sat640snap10.example.com/api/v2/discovery_rules
{
  "error": {"id":null,"errors":{"priority":["has already been taken"]},"full_messages":["Priority has already been taken"]}
}
```

See results of these tests:

* tests.foreman.api.test_discoveryrule.DiscoveryRuleTestCase.test_positive_delete
* tests.foreman.api.test_discoveryrule.DiscoveryRuleTestCase.test_positive_disable
* tests.foreman.api.test_discoveryrule.DiscoveryRuleTestCase.test_positive_update_host_limit
* tests.foreman.api.test_discoveryrule.DiscoveryRuleTestCase.test_positive_update_name
* tests.foreman.api.test_discoveryrule.DiscoveryRuleTestCase.test_positive_update_org_loc
* tests.foreman.api.test_discoveryrule.DiscoveryRuleTestCase.test_positive_update_search_rule
* tests.foreman.api.test_discoveryrule.DiscoveryRuleTestCase.test_positive_create_with_org_loc

**Comment by jhutar** [comment]
* tests.foreman.api.test_multiple_paths.EntityReadTestCase.test_positive_entity_read
* tests.foreman.api.test_multiple_paths.EntityIdTestCase.test_positive_put_status_code
* tests.foreman.api.test_multiple_paths.EntityIdTestCase.test_positive_get_status_code
* tests.foreman.api.test_multiple_paths.EntityIdTestCase.test_positive_delete_status_code
* tests.foreman.api.test_multiple_paths.DoubleCheckTestCase.test_positive_put_and_get_requests
* tests.foreman.api.test_multiple_paths.DoubleCheckTestCase.test_positive_post_and_get_requests
* tests.foreman.api.test_multiple_paths.DoubleCheckTestCase.test_positive_delete_and_get_requests

**Comment by jhutar** [comment]
Also most of the tests here:

* tests.foreman.cli.test_discoveryrule.DiscoveryRuleTestCase.*

**Comment by rplevka** [comment]
@jhutar isn't this a bug?

**Comment by jhutar** [comment]
Tracked as https://bugzilla.redhat.com/show_bug.cgi?id=1600621
