### ISSUE TITLE
Host Collection Creation tests fail on FIPS machine

### ISSUE THREAD

**Issue by chbrown13** [SatelliteQE/robottelo#6168]
'host' not found in dictionary keys when creating a new host collection with entities.HostCollection(...).create()

nailgun.entity_mixins.MissingValueError: Cannot find a value for the "host" field. Searched for keys named ('host_ids', 'host', 'hosts'), but available keys are dict_keys(['name', 'organization_id', 'max_hosts', 'description', 'total_hosts', 'unlimited_hosts', 'created_at', 'updated_at', 'id', 'permissions']).

**Comment by chbrown13** [comment]
ActivationKeyTestCase/test_positive_add_host_collections
ActivationKeyTestCase/test_positive_remove_host_collection
HostCollectionTestCase/test_positive_add_host
HostCollectionTestCase/test_positive_add_hosts
HostCollectionTestCase/test_positive_create_with_description
HostCollectionTestCase/test_positive_create_with_host
HostCollectionTestCase/test_positive_create_with_hosts
HostCollectionTestCase/test_positive_create_with_limit
HostCollectionTestCase/test_positive_create_with_name
HostCollectionTestCase/test_positive_create_with_unlimited_hosts
HostCollectionTestCase/test_positive_delete
HostCollectionTestCase/test_positive_list
HostCollectionTestCase/test_positive_list_for_organization
HostCollectionTestCase/test_positive_read_host_ids
HostCollectionTestCase/test_positive_update_description
HostCollectionTestCase/test_positive_update_host
HostCollectionTestCase/test_positive_update_hosts
HostCollectionTestCase/test_positive_update_limit
HostCollectionTestCase/test_positive_update_name
HostCollectionTestCase/test_positive_update_unlimited_hosts

**Comment by rplevka** [comment]
@chbrown13, thanks for filing the issue.
This smells like a nailgun version mismatch in your setup.
The mentioned tests work just fine on a `6.4` automation and i really doubt the FIPS would cause this.
Can you share the robottelo and nailgun versions you used?

thanks!

**Comment by chbrown13** [comment]
Thanks @rplevka, unfortunately the beaker machines I used for these tests expired so will run again and make sure the versions are the same.

**Comment by chbrown13** [comment]
I'm still seeing this error on a [FIPS-enabled host](http://file.rdu.redhat.com/~dbrownjr/fips_api_test_activationkey.txt) for activation_key test_positive_add_host_collections and test_positive_remove_host_collections.

**Comment by chbrown13** [comment]
Robottelo version 0.1.0

**Comment by rplevka** [comment]
i believe i can close this now
