### ISSUE TITLE
cli.test_repository.FileRepositoryTestCase.test_positive_local_directory_sync - failing since introduction

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#6174]
@omkarkhatavkar, hey, the aforementioned test have never succeeded in our automation.

it got introduced by:
https://github.com/SatelliteQE/robottelo/commit/b18a881739cff47f54271c98df957cd9b5d34db6

Can you revisit it?

**Comment by ntkathole** [comment]
Raised #6173

**Comment by omkarkhatavkar** [comment]
This fix is done and merged https://github.com/SatelliteQE/robottelo/pull/6173, hence closing this Issue.
