### ISSUE TITLE
AssertionError: assert 'QewTFkBIHX' == '[70,80]'   - QewTFkBIHX   + [70,80]

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/robottelo#6223]
Test: `tests.foreman.ui_airgun.test_smartclassparameter.test_negative_create_matcher_avoid_duplicate`

```
>           assert sc_parameter_values[
                'parameter']['matchers']['table'][0]['Value'] == override_value
E           AssertionError: assert 'QewTFkBIHX' == '[70,80]'
E             - QewTFkBIHX
E             + [70,80]

tests/foreman/ui_airgun/test_smartclassparameter.py:570: AssertionError
```

**Comment by jhutar** [comment]
@oshtaier assigned to you as you are the author of the test. Maybe this is a bug in the product, make in AirGun... Please investigate.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
