### ISSUE TITLE
AssertionError: assert 'LkEcjBfUeN' == ['47g1ktdhid', '2c:73:3a:b9:8c:32']

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/robottelo#6224]
Test `tests.foreman.ui_airgun.test_smartclassparameter.test_positive_view_yaml_output_after_resubmit_array_type` fails with:

```
>           assert output_scp == [domain.name, module_host.mac]
E           AssertionError: assert 'LkEcjBfUeN' == ['47g1ktdhid', '2c:73:3a:b9:8c:32']
```

**Comment by jhutar** [comment]
@oshtaier assigned to you as you are the author of the test. Again, maybe this is a bug in the product, make in AirGun... Please investigate.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
