### ISSUE TITLE
FIPS CLI Activation Key tests missing period

### ISSUE THREAD

**Issue by chbrown13** [SatelliteQE/robottelo#6228]
On a FIPS host, two tests (test_positive_copy_by_parent_name and test_positive_update_autoattach) are both failing with an AssertionError because the output is missing a period at the end (i.e. 'Activation key copied.' != 'Activation key copied'). Both tests pass successfully in a non-FIPS environment.

**Comment by chbrown13** [comment]
FIPS test results: http://file.rdu.redhat.com/~dbrownjr/fips_cli_test_activationkey.txt

___________ ActivationKeyTestCase.test_positive_copy_by_parent_name ____________

self = <tests.foreman.cli.test_activationkey.ActivationKeyTestCase testMethod=test_positive_copy_by_parent_name>

    @tier1
    def test_positive_copy_by_parent_name(self):
        """Copy Activation key by passing name of parent
    
            :id: 5d5405e6-3b26-47a3-96ff-f6c0f6c32607
    
            :expectedresults: Activation key is successfully copied
    
            :CaseImportance: Critical
            """
        parent_ak = self._make_activation_key()
        result = ActivationKey.copy({
            u'name': parent_ak['name'],
            u'new-name': gen_string('alpha'),
            u'organization-id': self.org['id'],
        })
>       self.assertEqual(result[0], u'Activation key copied')
E       AssertionError: u'Activation key copied.' != u'Activation key copied'
E       - Activation key copied.
E       ?                      -
E       + Activation key copied

tests/foreman/cli/test_activationkey.py:1235: AssertionError

____________ ActivationKeyTestCase.test_positive_update_autoattach _____________

self = <tests.foreman.cli.test_activationkey.ActivationKeyTestCase testMethod=test_positive_update_autoattach>

    @tier1
    def test_positive_update_autoattach(self):
        """Update Activation key with valid auto-attach values
    
            :id: 9e18b950-6f0f-4f82-a3ac-ef6aba950a78
    
            :expectedresults: Activation key is successfully updated
    
            :CaseImportance: Critical
            """
        new_ak = self._make_activation_key()
        for new_value in (u'1', u'0', u'true', u'false', u'yes', u'no'):
            with self.subTest(new_value):
                result = ActivationKey.update({
                    u'auto-attach': new_value,
                    u'id': new_ak['id'],
                    u'organization-id': self.org['id'],
                })
                self.assertEqual(
>                   u'Activation key updated', result[0]['message'])
E               AssertionError: u'Activation key updated' != u'Activation key updated.'
E               - Activation key updated
E               + Activation key updated.
E               ?                       +

tests/foreman/cli/test_activationkey.py:1354: AssertionError

**Comment by chbrown13** [comment]
non-FIPS test results: http://file.rdu.redhat.com/~dbrownjr/cli_test_activationkey.txt
```
tests/foreman/cli/test_activationkey.py::ActivationKeyTestCase::test_positive_copy_by_parent_name PASSED
...
tests/foreman/cli/test_activationkey.py::ActivationKeyTestCase::test_positive_update_autoattach PASSED
```

**Comment by pondrejk** [comment]
This is more an upstream change that didn't yet land downstream, I have seen this also on non FIPS upstream environment.
