### ISSUE TITLE
Fix all the docstrings on all the tests

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#6291]
This effects our ability to push tests to polarion and reduce our numbers greatly.

`testimony --tokens="bz, caseautomation, casecomponent, caseimportance, caselevel, caseposneg, customerscenario, expectedresults, id, requirement, setup, subtype1, steps, teardown, testtype, upstream" --minimum-tokens="id, requirement, caseautomation, caselevel, casecomponent, testtype, caseimportance, upstream" validate tests/foreman/ui_airgun`

Total number of tests: 244
Total number of invalid docstrings: 70 (28.69%)
Test cases with no docstrings: 47 (19.26%)
Test cases missing minimal docstrings: 70 (28.69%)
Test cases with invalid tags: 0 (0.00%)
Total number of tests with parsing issues: 0 (0.00%)

@SatelliteQE/quality-engineers , In efforts for porting the UI tests , please consider the docstrings

CLI tests
`testimony --tokens="bz, caseautomation, casecomponent, caseimportance, caselevel, caseposneg, customerscenario, expectedresults, id, requirement, setup, subtype1, steps, teardown, testtype, upstream" --minimum-tokens="id, requirement, caseautomation, caselevel, casecomponent, testtype, caseimportance, upstream" validate tests/foreman/cli`

Total number of tests: 1484
Total number of invalid docstrings: 17 (01.15%)
Test cases with no docstrings: 0 (0.00%)
Test cases missing minimal docstrings: 17 (1.15%)
Test cases with invalid tags: 0 (0.00%)
Total number of tests with parsing issues: 0 (0.00%)

Will look into adding these as part of checks for travis

**Comment by sghai** [comment]
@oshtaier @ldjebran @abalakh : hey guys.. could you please take care of these changes ?

**Comment by abalakh** [comment]
@sghai @san7ket 
>Test cases with no docstrings: 47 (19.26%)

Those are the tests with no tier assigned which aren't executed on CI, we've introduced them on early airgun development stage when we were not yet able to port tier2 tests but wanted to ensure at least basic functionality works ok. We can remove them from repo completely if you wish, but are they really affecting you despite the fact they're not even executed anywhere?

>Total number of invalid docstrings: 70 (28.69%)
>Test cases missing minimal docstrings: 70 (28.69%)

These numbers are definitely not ok, we'll take a look at those tests, thanks for pointing.

**Comment by sghai** [comment]
Thanks @abalakh

**Comment by san7ket** [comment]
Thanks @abalakh Yes , I see some of the test, doesn't have a tier assigned and that's ok, not really the problem.
But the test that are been run on CI those needs fixing. I see some are marked to run on CI and are missing some doc strings.
I see this happened due to testimony script didn't had the new folder added, I will try to fix this ASAP. but I am afraid, if I do the travis-ci will break for all current open PR's.

**Comment by oshtaier** [comment]
it is not fixed on 100%, so let's keep it on track. At least, we have CLI tests to fix

**Comment by san7ket** [comment]
@sghai @oshtaier looks like there are no issue with CLI, but the problem was with my local copy, 
For all the airgun issue, we can refer https://travis-ci.org/SatelliteQE/robottelo/builds/437057800?utm_source=github_status&utm_medium=notification.

When the above job is green we are good and we can barnch robottelo

**Comment by san7ket** [comment]
@oshtaier can we mark the tests that we don't want to run as stubbed , as it is required by the checks to have some kind of marker to tests.
