### ISSUE TITLE
HostParameterTestCase/test_positive_set_multi_line_and_with_spaces_parameter_value - looks at 1st parameter

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#6310]
```
&gt; self.assertEqual(host_parameters[0]['name'], param_name)
E AssertionError: 'gxjzoujaed' != 'thumjhkdjj'
E - gxjzoujaed
E + thumjhkdjj
```

- the problem with this is, that the new parameter is there,  but the list contains multiple parameters sorted alphabetically, so if the new parameter is listed as not the first one, the assertion will fail.

**Comment by ldjebran** [comment]
FIx merged
