### ISSUE TITLE
cachetools dependency 

### ISSUE THREAD

**Issue by ldjebran** [SatelliteQE/robottelo#6325]
Investigate to remove cachetools from dependency as seems not used under python 3

**Comment by san7ket** [comment]
I think it's a safe removal, and we need to update it in just one module https://github.com/SatelliteQE/robottelo/blob/2b479afc35a781110ebdeac178842b51ac4ba5ee/robottelo/helpers.py#L24

**Comment by san7ket** [comment]
I can look into testing this.

**Comment by ntkathole** [comment]
Fixed
