### ISSUE TITLE
Remove URL to agent-python-pytest in requirements-optional.txt

### ISSUE THREAD

**Issue by swadeley** [SatelliteQE/robottelo#6326]
Roman Plevka mistakenly added a link to agent-python-pytest, which is not working, in requirements-optional.txt.

In this commit:

commit dac3fc259b5011e29d37cbce75a3bd7118afa063
Author: Roman Plevka <rplevka@redhat.com>
Date:   Wed Sep 5 13:27:14 2018 +0200

    add report_portal logger support

**Comment by ntkathole** [comment]
Closed via #6327
