### ISSUE TITLE
pycurl SSL backend error 

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/robottelo#6340]
When trying to run `pip install -r requirements.txt` we see:
```
Collecting pycurl (from satellite6-upgrade->-r requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/e8/e4/0dbb8735407189f00b33d84122b9be52c790c7c3b25286826f4e1bdb7bde/pycurl-7.43.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Using curl-config (libcurl 7.59.0)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5qu44e03/pycurl/setup.py", line 913, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-build-5qu44e03/pycurl/setup.py", line 582, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-build-5qu44e03/pycurl/setup.py", line 99, in __init__
        self.configure()
      File "/tmp/pip-build-5qu44e03/pycurl/setup.py", line 316, in configure_unix
        specify the SSL backend manually.''')
    __main__.ConfigurationError: Curl is configured to use SSL, but we have not been able to determine which SSL backend it is using. Please see PycURL documentation for how to specify the SSL backend manually.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5qu44e03/pycurl/
```
Commenting out the `satellite6-upgrade` dependency in `requirements.txt` will work around this, but you wont be able to run tests that require that. 

Could this be fixed by https://github.com/pycurl/pycurl/pull/527 ? It looks like they have not done a release yet with that fix.

**Comment by pgagne** [comment]
Per @jyejare and @rplevka this doing this before `pip install -r requirements.txt` should fix it:

```
if [ "$(curl --version | grep NSS 2>/dev/null)" ]; then
         export PYCURL_SSL_LIBRARY=nss
         pip install --compile --install-option="--with-nss" pycurl
else
         export PYCURL_SSL_LIBRARY=openssl
         pip install --compile --install-option="--with-openssl" pycurl
fi
```

But this is also a workaround, we should figure out how to not have to do this.

**Comment by rplevka** [comment]
I can hardly see how this is a robottelo issue. I don't think we should handle environmental issues for the users

**Comment by jyejare** [comment]
@pgagne , @rplevka I think a better thing would be, pycurl should install itself as per the installed library (```openssl``` or ```nss```) on a system it is being installed.

**Comment by san7ket** [comment]
https://github.com/SatelliteQE/satellite6-upgrade/issues/235

**Comment by ntkathole** [comment]
Adding some issue where I think we had same discussion earlier

https://github.com/SatelliteQE/automation-tools/pull/338
https://github.com/SatelliteQE/automation-tools/pull/339

**Comment by rplevka** [comment]
@pgagne - so...any conclusions? :)

**Comment by san7ket** [comment]
It was introduced due to satellite6-upgrade, It is fixed in upgrade and user won't get an error while building robottelo
