### ISSUE TITLE
Allow longer lines

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#6344]
Lets discuss if we could adjust length line, initial PR #6333 from @alda519 was way too aggressive, adjusting to 160 is really overkill. However, time has come to adjust it a bit to avoid spending too much time with formatting finished code. 

I think we can still achieve some sort of consensus. Some thoughts what new number should be:   
- to comply with PEP0008 - up to ```99```
- side by side editing - up to ```89?``` - depends on resolution/font size, who got what resolution?

I'm using mostly 1920x1080 (sometimes 1600x900)
Even 9 chars would help.  
What do you think?

**Comment by alda519** [comment]
:+1: +1

It would be great if the rule was not so strict.
Yes, short lines are easier to read than long ones, but sometimes it makes it much worse.
See an example:
https://github.com/SatelliteQE/robottelo/blob/78fc5f135c86467e192aa70c90822dfeefbd6766/tests/foreman/ui_airgun/test_activationkey.py#L157-L158
I still think that allowing more flexibility would make the code better.

**Comment by jhutar** [comment]
+1

I also find short lines unnecessarily strict limitation. What counts is if code is readable, at least for the owner.

**Comment by rplevka** [comment]
+1 to 99

**Comment by lpramuk** [comment]
(me personally) +1 to 99

**Comment by pondrejk** [comment]
I'm in favor of having 'some' width restriction, I'm ok with widening the current one to 99

**Comment by pgagne** [comment]
I think 99 is too small I think 160 is more realistic
