### ISSUE TITLE
WebUI Test Coverage Improvement Procedure

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#6408]
I want to form few simple rules that we should keep in our porting efforts to new framework. As we get a chance to finally have effective test coverage, lets focus on quality, not a quantity.

1) Test layer should contain **only** test logic. That means no direct locators, interactions with web elements and etc. 
2) It is preferable to use REST API for test setup procedures.
3) Each component that can be treated as isolated functionality entity (like subnet, architecture and etc) should contain one and only one end-to-end scenario that cover all basic properties and operation for that entity
4) Each component should have at least one scenario that test its functionality in integration with other components
5) We do not test different data types, boundary values, entity fields permutations, alerts text and simple negative scenarios. We can do that only in case it is customer found defect
6) Avoid similar scenarios in your implementation as they add small value (for example: 'VM power on/off' and 'VM power off/on'. Create one scenario that will change state to opposite one instead.)
7) We should have next priority per each component:
    a) End-to-end scenario
    b) Customer found defect
    c) Critical importance integration/system tests
    d) Any other tier2/tier3 tests
8) We should provide at least some coverage for all modules first (like 5%) rather than full coverage for one (like 99%)

**Comment by rplevka** [comment]
lgtm

**Comment by sghai** [comment]
Thanks @oshtaier I like the way you outlined the priority per each component. I see more value starting with end_2_end scenario.

**Comment by oshtaier** [comment]
Please refer to
https://github.com/SatelliteQE/robottelo/pull/6418
as an easy example for end-to-end scenario

**Comment by jhutar** [comment]
As per some discussion in https://github.com/SatelliteQE/robottelo/pull/6486 - so we can not merge tier2 tests now?

**Comment by oshtaier** [comment]
right, we cannot merge tier2 tests that are not tier2(integration=few **different** components interaction) tests

**Comment by jhutar** [comment]
We should probably define few things. Most importantly on what level are we talking. For somebody integration can mean "functions talk to each other nicely", for somebody else it can mean "services call to each other nicely" (e.g. Pulp ver.X talks to Katello ver.Y) and for somebody else it means that "products talk to each other nicely" (Satellite and underlying OS or Satellite and RHEV where Satellite is creating compute resource). What is the case in this docs?

**Comment by jhutar** [comment]
And about this component: by component we mean entities (+-) `hammer help` lists? I'm asking because almost every component integrates with organization/location then. What is the definition here?

**Comment by oshtaier** [comment]
from my point of view and as far I understand is point of view of the team, it is "one Satellite functionality entity like organization, operating system, content view talk to another Satellite functionality entity nicely". That means " I create new organization and assign new user to it" is most classical example of integration scenario. And correspondingly "I create new organization with name that contains UTF-8 symbols, description that has value above 255 symbols and etc" is opposite situation and has to be treated as tier1 test case. Like one isolated component, no matter you do with it is tier1, if you combine some of them is tier2.

> by component we mean entities (+-) hammer help lists
(+-) Yes

>I'm asking because almost every component integrates with organization/location then.
If you explicitly test component "cooperation" with organization/location then it is tier2 test

**Comment by ntkathole** [comment]
Closing this as we have completed this process. Thanks!
