### ISSUE TITLE
Add decorator to test_positive_add_rh_repo_by_id 

### ISSUE THREAD

**Issue by swadeley** [SatelliteQE/robottelo#6446]
In robottelo.properties file, if section header [fake_manifest] is not enabled by removing the comment # , then test_positive_add_rh_repo_by_id fails with error:
 requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

A decorator to skip that test if [fake_manifest]  is not enabled would help.

Thank you

**Comment by vikask18** [comment]
Updated this test in PR: https://github.com/SatelliteQE/robottelo/pull/6938
Closing this issue.
