### ISSUE TITLE
Fix preupgrade scenarios tests

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/robottelo#6489]
- tests.upgrades.test_syncplan.ScenarioSyncPlan.test_pre_sync_plan_migration

`AttributeError: 'ScenarioSyncPlan' object has no attribute 'sync_plan_name'`

- tests.upgrades.test_client.Scenario_upgrade_old_client_and_package_installation.test_pre_scenario_preclient_package_installation
`
KeyError: 'module_stream_count'`

**Comment by sghai** [comment]
Is this the only test failure in scenario tests ?

**Comment by ntkathole** [comment]
Yes, in pre upgrade only. Post upgrade not run yet.

**Comment by ntkathole** [comment]
@jyejare just an update here. Both the tests are still failing but this time (snap 7) error changed as below:

- tests.upgrades.test_syncplan.ScenarioSyncPlan.test_pre_sync_plan_migration

`MissingValueError: Cannot find a value for the "foreman_tasks_recurring_logic" field. Searched for keys named ('foreman_tasks_recurring_logic', 'foreman_tasks_recurring_logic_id'), but available keys are [u'description', u'created_at', u'interval', u'enabled', u'updated_at', u'organization_id', u'sync_date', u'next_sync', u'products', u'permissions', u'id', u'name'].`

- tests.upgrades.test_client.Scenario_upgrade_old_client_and_package_installation.test_pre_scenario_preclient_package_installation
`KeyError: 'registry_unauthenticated_pull`

**Comment by jyejare** [comment]
@ntkathole , I think changes are happened in Feature and @omkarkhatavkar  is the best person to handle that.

**Comment by omkarkhatavkar** [comment]
@ntkathole @jyejare : need latest nailgun to solve this

**Comment by ntkathole** [comment]
Update with snap 10, failed tests are:

- tests.upgrades.test_capsule.Scenario_capsule_sync.test_pre_user_scenario_capsule_sync
```
_, env_name = hammer.hammer_determine_cv_and_env_from_ak(
>           self.activation_key, '1')
AttributeError: 'dict' object has no attribute 'iteritems'
```

- tests.upgrades.test_contentview.ScenarioBug1429201.test_pre_user_scenario_bug_1429201

```
 print(hammer.hammer_product_create(self.prd_name, self.org_id))
E           AttributeError: 'dict' object has no attribute 'iteritems'
```

- tests.upgrades.test_client.Scenario_upgrade_old_client_and_package_installation.test_pre_scenario_preclient_package_installation
```
>       client_container_id = rhel7_client.values()[0]
E       TypeError: 'dict_values' object does not support indexing
TypeError: 'dict_values' object does not support indexing
```

**Comment by ntkathole** [comment]
Update with snap 12,

only one test need to fix : tests.upgrades.test_contentview.ScenarioBug1429201.test_pre_user_scenario_bug_1429201

**Comment by vijay8451** [comment]
looks pending covered under #6863

**Comment by ntkathole** [comment]
We can close this!
