### ISSUE TITLE
Port AutomationTools Hammer based Upgrade scenarios to Nailgun

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#6503]
Following Scenarios need to be moved on to nailgun from hammer:

- [x] test_capsule.py
   - [x] Scenario_capsule_sync
   - [x] Scenario_capsule_sync_2
- [x] test_client.py
   - [x] Scenario_upgrade_old_client_and_package_installation
   - [x] Scenario_upgrade_new_client_and_package_installation
- [ ] test_contentview.py
   - [ ] ScenarioBug1429201

**Comment by vijay8451** [comment]
Below Scenarios moved to nailgun from hammer:

1. test_client.py
    - Scenario_upgrade_old_client_and_package_installation
    - Scenario_upgrade_new_client_and_package_installation

PR #6555

**Comment by vijay8451** [comment]
Below Scenario moved to nailgun from hammer:
   2. test_capsule.py
       - Scenario_capsule_sync

PR #6575
