### ISSUE TITLE
automate brute force protection limit configurable function: failed_login_attempts_limit

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/robottelo#6505]
Scenario would be:

1. Make sure login works, e.g. with:
    hammer -u admin -p $PW_GOOD user list | grep '^ID '
2. Save current value and set it to some lower value:
    hammer -u admin -p $PW_GOOD settings set --name failed_login_attempts_limit --value $attempts
3. Trigger it:
    for i in $( seq $attempts ); do   hammer -u admin -p $PW_BAD user list;   done
4. Make sure login now does not work:
    hammer -u admin -p $PW_GOOD user list 2>&1 | grep 'Too many tries, please try again in a few minutes.'
5. Wait timeout - 5 minutes + 1 second
    sleep 301
6. Verify you can now login fine
    hammer -u admin -p $PW_GOOD user list | grep '^ID '
7. Return the setting to previous value

This test would need to be the only one running on satellite.

**Comment by jameerpathan111** [comment]
closed via #6514
