### ISSUE TITLE
test_hammer.py::HammerCommandsTestCase::test_positive_all_options failed due to missing hammer options in satellite 6.5

### ISSUE THREAD

**Issue by surajbora1** [SatelliteQE/robottelo#6526]
test_hammer.py::HammerCommandsTestCase::test_positive_all_options failing due to missing hammer options in satellite 6.5

Similar issue is fixed in satellite 6.4 #6519, Need to merge the changes and add new options available in satellite 6.5.

**Comment by surajbora1** [comment]
Following options are added/removed to/from satellite 6.5:

           hammer compute-resource
             Added subcommands:
               * folders
               * zones
               * flavors
               * storage-domains
               * images
               * clusters
               * resource-pools
               * storage-pods
               * security-groups
           
           hammer compute-resource clusters (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer compute-resource flavors (new command)
             Added options:

               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer compute-resource folders (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer compute-resource images (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer compute-resource resource-pools (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * cluster-id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer compute-resource security-groups (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer compute-resource storage-domains (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * storage-domain
               * help
           
           hammer compute-resource storage-pods (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * storage-pod
               * organization
               * location-title
               * help
           
           hammer compute-resource zones (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help

@san7ket  can you please confirm if options related to compute-resource are correct.

           hammer module-stream (new command)
             Added subcommands:
               * info
               * list
             Added options:
               * help
           
           hammer module-stream info (new command)
             Added options:
               * repository-id
               * id
               * name
               * organization-label
               * product
               * product-id
               * repository
               * organization-id
               * organization
               * help
           
           hammer module-stream list (new command)
             Added options:
               * search
               * full-result
               * environment
               * environment-id
               * organization-label
               * repository
               * product-id
               * page
               * ids
               * organization-id
               * hosts
               * name-stream-only
               * per-page
               * content-view-version
               * help
               * repository-id
               * product
               * order
               * organization
               * content-view-filter-id
               * content-view-version-id
               * host-ids
               * content-view-filter

@omkarkhatavkar  can you please confirm if option related to module-stream are correct.

           hammer report-template (new command)
             Added subcommands:
               * dump
               * info
               * list
               * update
               * delete
               * create
               * clone
               * generate
             Added options:
               * help
           
           hammer report-template clone (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * new-name
               * location-title
               * help
           
           hammer report-template create (new command)
             Added options:
               * location-id
               * organization-titles
               * name
               * organization-ids
               * audit-comment
               * location
               * organization-id
               * location-titles
               * location-title
               * help
               * snippet
               * organization-title
               * organizations
               * locations
               * location-ids
               * locked
               * file
               * organization
               * default
           
           hammer report-template delete (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer report-template dump (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer report-template generate (new command)
             Added options:
               * organization-title
               * location-id
               * inputs
               * id
               * name
               * path
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer report-template info (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer report-template list (new command)
             Added options:
               * search
               * organization-title
               * location-id
               * order
               * location
               * organization-id
               * page
               * organization
               * location-title
               * per-page
               * help
           
           hammer report-template update (new command)
             Added options:
               * location-id
               * organization-titles
               * id
               * name
               * audit-comment
               * organization-ids
               * location
               * organization-id
               * location-titles
               * new-name
               * location-title
               * help
               * snippet
               * organization-title
               * organizations
               * locations
               * location-ids
               * locked
               * file
               * organization
               * default

           hammer template
             Added subcommands:
               * combination
           
           hammer template combination (new command)
             Added subcommands:
               * delete
               * create
               * info
               * list
               * update
             Added options:
               * help
           
           hammer template combination create (new command)
             Added options:
               * organization-title
               * location-id
               * environment
               * provisioning-template-id
               * environment-id
               * location
               * organization-id
               * hostgroup
               * provisioning-template
               * hostgroup-title
               * organization
               * location-title
               * help
               * hostgroup-id
           
           hammer template combination delete (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer template combination info (new command)
             Added options:
               * organization-title
               * location-id
               * environment
               * provisioning-template-id
               * environment-id
               * id
               * location
               * organization-id
               * hostgroup
               * provisioning-template
               * hostgroup-title
               * organization
               * location-title
               * help
               * hostgroup-id
           
           hammer template combination list (new command)
             Added options:
               * organization-title
               * location-id
               * provisioning-template-id
               * location
               * organization-id
               * provisioning-template
               * organization
               * location-title
               * help
           
           hammer template combination update (new command)
             Added options:
               * organization-title
               * location-id
               * environment
               * provisioning-template-id
               * environment-id
               * id
               * location
               * organization-id
               * hostgroup
               * provisioning-template
               * hostgroup-title
               * organization
               * location-title
               * help
               * hostgroup-id
@jyejare  can you please confirm if option related to template and report-template are correct.
           hammer config-report (new command)
             Added subcommands:
               * delete
               * info
               * list
             Added options:
               * help
           
           hammer config-report delete (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer config-report info (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer config-report list (new command)
             Added options:
               * search
               * organization-title
               * location-id
               * order
               * location
               * organization-id
               * page
               * organization
               * location-title
               * per-page
               * help
           
           hammer content-view filter list
             Removed options:
               * by
           
           hammer content-view filter rule list
             Added options:
               * errata-id
               * name
             Removed options:
               * by
           
           hammer content-view list
             Removed options:
               * by
           
           hammer content-view publish
             Added options:
               * minor
               * repos-units
               * major
             Removed options:
               * force-yum-metadata-regeneration
           
           hammer content-view puppet-module list
             Removed options:
               * by
           
           hammer content-view version
             Added subcommands:
               * export-legacy
               * import
           
           hammer content-view version export
             Added options:
               * export-dir
             Removed options:
               * content-view
               * async
               * iso-mb-size
               * environment
               * environment-id
               * organization-label
               * version
               * export-to-iso
               * organization-id
               * since
               * organization
               * content-view-id
           
           hammer content-view version export-legacy (new command)
             Added options:
               * content-view
               * async
               * iso-mb-size
               * environment
               * environment-id
               * id
               * organization-label
               * version
               * export-to-iso
               * organization-id
               * since
               * organization
               * help
               * content-view-id
           
           hammer content-view version import (new command)
             Added options:
               * organization-id
               * async
               * help
               * export-tar
           
           hammer content-view version incremental-update
             Added options:
               * debs
               * deb-ids
           
           hammer content-view version list
             Removed options:
               * by
           
           hammer content-view version promote
             Removed options:
               * force-yum-metadata-regeneration
           
           hammer docker manifest list
             Removed options:
               * by
           
           hammer docker tag list
             Removed options:
               * by
           
           hammer erratum list
             Added options:
               * available-for
               * host
               * host-id
             Removed options:
               * by
           
           hammer export-templates
             Added options:
               * verbose
           
           hammer file list
             Removed options:
               * by
           
           hammer gpg list
             Removed options:
               * by
           
           hammer host
             Added subcommands:
               * boot
               * config-reports
               * disassociate
               * reset
           
           hammer host ansible-roles
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
           
           hammer host boot (new command)
             Added options:
               * device
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer host config-reports (new command)
             Added options:
               * search
               * organization-title
               * location-id
               * id
               * name
               * order
               * location
               * organization-id
               * page
               * organization
               * location-title
               * per-page
               * help
           
           hammer host create
             Added options:
               * purpose-usage
               * purpose-addons
               * purpose-role
           
           hammer host disassociate (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer host errata list
             Removed options:
               * by
           
           hammer host list
             Added options:
               * thin
           
           hammer host package list
             Removed options:
               * by
           
           hammer host reset (new command)
             Added options:
               * organization-title
               * location-id
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
               * help
           
           hammer host update
             Added options:
               * purpose-usage
               * purpose-addons
               * purpose-role
           
           hammer host-collection list
             Removed options:
               * by
           
           hammer hostgroup ansible-roles
             Added options:
               * organization-title
               * location-id
               * title
               * id
               * name
               * location
               * organization-id
               * organization
               * location-title
           
           hammer lifecycle-environment create
             Added options:
               * registry-unauthenticated-pull
           
           hammer lifecycle-environment list
             Removed options:
               * by
           
           hammer lifecycle-environment update
             Added options:
               * registry-unauthenticated-pull
           
           hammer organization list
             Added options:
               * sort-by
               * sort-order
             Removed options:
               * by
           
           hammer ostree-branch list
             Removed options:
               * by
           
           hammer package list
             Added options:
               * packages-restrict-latest
               * available-for
             Removed options:
               * by
           
           hammer package-group list
             Removed options:
               * by
           
           hammer product list
             Removed options:
               * by
           
           hammer puppet-module list
             Removed options:
               * by
          
           hammer repository create
             Added options:
               * docker-tags-whitelist
           
           hammer repository list
             Added options:
               * file-id
               * description
             Removed options:
               * by
           
           hammer repository update
             Added options:
               * docker-tags-whitelist
           
           hammer repository-set list
             Removed options:
               * by
           
           hammer subnet create
             Added options:
               * tftp
               * dhcp
               * dns
               * httpboot-id
           
           hammer subnet update
             Added options:
               * tftp
               * dhcp
               * dns
               * httpboot-id
           
           hammer subscription list
             Removed options:
               * by
           
           hammer sync-plan create
             Added options:
               * cron-expression
           
           hammer sync-plan list
             Removed options:
               * by
           
           hammer sync-plan update
             Added options:
               * cron-expression
           
           hammer task
             Added subcommands:
               * info
           
           hammer task info (new command)
             Added options:
               * organization-id
               * help
               * id
               * location-id
           
           hammer task list
             Removed options:
               * location-title
               * organization-title
               * organization
               * location

           
           hammer template-input create
             Added options:
               * puppet-class-name
             Removed options:
               * puppet-parameter-class

           hammer activation-key host-collections
             Added options:
               * sort-by
               * sort-order
           
           hammer activation-key list
             Removed options:
               * by
           
           hammer activation-key subscriptions
             Removed options:
               * by
           
           hammer ansible roles import
             Added options:
               * role-names

**Comment by jameerpathan111** [comment]
@lhellebr , do you know weather option related to template and report-template are correct?
https://github.com/SatelliteQE/robottelo/issues/6526#issuecomment-444486412

**Comment by lhellebr** [comment]
Help lists --interactive option for "hammer report-template create" and "hammer report-template update". It is not listed here.
Otherwise, report-template related stuff seems fine.

**Comment by jameerpathan111** [comment]
> Help lists --interactive option for "hammer report-template create" and "hammer report-template update". It is not listed here.
> Otherwise, report-template related stuff seems fine.

Thanks @lhellebr

**Comment by ntkathole** [comment]
Fixed!
