### ISSUE TITLE
GPG Keys: test_consume_content

### ISSUE THREAD

**Issue by cswiii** [SatelliteQE/robottelo#655]
test_consume_content_[1-3] : these required package install functionality in place
Refer to issue #340

**Comment by sghai** [comment]
Covered `test_consume_content_1`  in https://github.com/SatelliteQE/robottelo/pull/2075

**Comment by sghai** [comment]
for `test_consume_content_3` we need another custom repo whose packages should be signed with gpgkey. So far I was using fakerepos.

**Comment by sghai** [comment]
similarly, for `test_consume_content_2` we need two repos whose packages should be signed with same key.

**Comment by sghai** [comment]
These stubs are renamed like:
[test_positive_consume_content_using_repos](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_gpgkey.py#L528)
[test_positive_consume_content_using_repos_and_different_keys](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_gpgkey.py#L545)


But we need custom repos with all its packages signed with some gpg-key

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
