### ISSUE TITLE
Fix/remove test_repository.RepositoryTestCase negative_create_non_yum_with_download_policy

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/robottelo#6583]
There is no validation on download policy for non-yum repositories in 6.5. According to https://bugzilla.redhat.com/show_bug.cgi?id=1654944#c5 , Starting 6.5, we are setting the download policy as nil if the content type is non yum.

**Affected test cases:**

- tests.foreman.cli.test_repository.RepositoryTestCase

 testMethod=test_negative_create_non_yum_with_download_policy

- tests.foreman.api.test_repository.RepositoryTestCase

 testMethod=test_negative_create_non_yum_with_download_policy

**Error:**
```
                    entities.Repository(
                        product=self.product,
                        content_type=content_type,
>                       download_policy='on_demand'
                    ).create()
E                   AssertionError: HTTPError not raised
```

**Comment by vijay8451** [comment]
Working further here: https://bugzilla.redhat.com/show_bug.cgi?id=1654944

**Comment by vijay8451** [comment]
Next steps:
- Raising PR to skip both tests until Bug resolve 
- After Bug resolve if requires then shall adjust the exception too.
