### ISSUE TITLE
Test cases fails with "zipfile.BadZipFile: File is not a zip file"

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#6650]
**- Below Test cases fails with "zipfile.BadZipFile: File is not a zip file"**
tests.foreman.api.test_repository_set.RepositorySetTestCase.test_positive_reposet_enable (from tier1-sequential) 
tests.foreman.api.test_repository_set.RepositorySetTestCase.test_positive_reposet_disable (from tier1-sequential)

**Comment by vijay8451** [comment]
- **Test cases are getting passed during manifest upload:**
+++++++++++++++++++++++
client.py                  124 DEBUG    Received HTTP 200 response: {"id":"14bf1f74-2e7e-4665-9fbc-26316f10e3db","label":"Actions::Katello::Organization::ManifestImport","pending":false,"action":"Import Manifest organization 'GLxQUny'","username":"admin","started_at":"2019-01-17 05:54:46 UTC","ended_at":"2019-01-17 05:55:05 UTC","state":"stopped","result":"success","progress":1.0,"input":{"organization":{"id":10,"name":"GLxQUny","label":"GLxQUny"},"remote_user":"admin","remote_cp_user":"admin","current_timezone":"UTC","current_user_id":4,"current_organization_id":10,"current_location_id":null},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization 'GLxQUny'","link":"/organizations/10/edit"}]],"output":"","errors":[]},"cli_example":null}
+++++++++++++++++++++++

**- Test cases are getting failed due to a known Bug #**
+++++++++++++++++++++++
{"displayMessage":"One of parameters [ organization_id ] required but not specified.","errors":["One of parameters [ organization_id ] required but not specified."]}
+++++++++++++++++++++++

**Comment by vijay8451** [comment]
good to skip both tests till Bug fix

**Comment by vijay8451** [comment]
- test cases are passed and not affected by Bug #1655239 .
- Worth to see at next snap run.


(myenv3) [root@vijsingh robottelo]# pytest -v tests/foreman/api/test_repository_set.py -k test_positive_reposet_enable
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.7.0, pluggy-0.6.0 -- /home/vijsingh/my_projects/myenv3/bin/python36
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/robottelo, inifile:
plugins: services-1.3.0, mock-1.10.0
collecting 2 items                                                                                                                                                          2019-01-18 11:23:17 - conftest - DEBUG - Collected 2 test cases

collected 2 items / 1 deselected                                                                                                                                            

tests/foreman/api/test_repository_set.py::RepositorySetTestCase::test_positive_reposet_enable PASSED                                                                  [100%]

================================================================= 1 passed, 1 deselected in 190.62 seconds ==================================================================
(myenv3) [root@vijsingh robottelo]# pytest -v tests/foreman/api/test_repository_set.py -k test_positive_reposet_disable
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.7.0, pluggy-0.6.0 -- /home/vijsingh/my_projects/myenv3/bin/python36
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/robottelo, inifile:
plugins: services-1.3.0, mock-1.10.0
collecting 2 items                                                                                                                                                          2019-01-18 11:26:58 - conftest - DEBUG - Collected 2 test cases

collected 2 items / 1 deselected                                                                                                                                            

tests/foreman/api/test_repository_set.py::RepositorySetTestCase::test_positive_reposet_disable PASSED                                                                 [100%]

================================================================= 1 passed, 1 deselected in 206.64 seconds ==================================================================
(myenv3) [root@vijsingh robottelo]#

**Comment by ntkathole** [comment]
Not reproducible for the latest snap. Closing!
