### ISSUE TITLE
Coordinate performance improvements in CLI tests

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#6727]
This issue is a follow-up to a discussion from  #6721 
The overall goal is to reduce unnecessary performance overhead present in current CLI tests. The target should be tier2+ tests

Steps to achieve the goal (thanks for early suggestions by @rplevka):
1. group related tests to share setup and minimize ssh calls
2. gradually move from using cli factory methods to do setup in favor of API

Predominantly this would not aim to remove assertions, though we could use this opportunity to audit test usefulness or tier membership
Any suggestions welcome @SatelliteQE/collaborators

**Comment by mshriver** [comment]
@pondrejk I think a significant amount of this type of work has been done along with the conversion to pytest.

There are still optimizations to be made - specifically around consolidation of fixture definitions and use.  I'd encourage you to create a card on the internal JIRA for any specific updates you would like to make for fixture use in the CLI tests, for better planning visibility.
