### ISSUE TITLE
tests.upgrades.test_capsule.Scenario_capsule_sync.test_pre_user_scenario_capsule_sync (from test_scenarios-pre)

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#6750]
Error Message

requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://sat6-upgrade-rhel7.example.com/katello/api/v2/products

Stacktrace

self = <tests.upgrades.test_capsule.Scenario_capsule_sync testMethod=test_pre_user_scenario_capsule_sync>

    @pre_upgrade
    def test_pre_user_scenario_capsule_sync(self):
        """Pre-upgrade scenario that creates and sync repository with
        rpm in satellite which will be synced in post upgrade scenario.
    
    
        :id: preupgrade-eb8970fa-98cc-4a99-99fb-1c12c4e319c9
    
        :steps:
            1. Before Satellite upgrade, Sync a repo/rpm in satellite
    
        :expectedresults: The repo/rpm should be synced to satellite
    
         """
        ak = entities.ActivationKey(organization=self.org_id).search(
            query={'search': 'name={}'.format(self.activation_key)})[0]
        ak_env = ak.environment.read()
        product = entities.Product(
>           name=self.prod_name, organization=self.org_id).create()

tests/upgrades/test_capsule.py:89: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../shiningpanda/jobs/87fc9fc8/virtualenvs/d41d8cd9/lib/python3.6/site-packages/blinker_herald/base.py:137: in wrapper
    result = fn(*args, **kwargs)
../../shiningpanda/jobs/87fc9fc8/virtualenvs/d41d8cd9/lib/python3.6/site-packages/nailgun/entity_mixins.py:961: in create
    return self.read(attrs=self.create_json(create_missing))
../../shiningpanda/jobs/87fc9fc8/virtualenvs/d41d8cd9/lib/python3.6/site-packages/nailgun/entity_mixins.py:931: in create_json
    response.raise_for_status()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Response [500]>

    def raise_for_status(self):
        """Raises stored :class:`HTTPError`, if one occurred."""
    
        http_error_msg = ''
        if isinstance(self.reason, bytes):
            # We attempt to decode utf-8 first because some servers
            # choose to localize their reason strings. If the string
            # isn't utf-8, we fall back to iso-8859-1 for all other
            # encodings. (See PR #3538)
            try:
                reason = self.reason.decode('utf-8')
            except UnicodeDecodeError:
                reason = self.reason.decode('iso-8859-1')
        else:
            reason = self.reason
    
        if 400 <= self.status_code < 500:
            http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
    
        elif 500 <= self.status_code < 600:
            http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
    
        if http_error_msg:
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://sat6-upgrade-rhel7.example.com/katello/api/v2/products

../../shiningpanda/jobs/87fc9fc8/virtualenvs/d41d8cd9/lib/python3.6/site-packages/requests/models.py:940: HTTPError

**Comment by vijay8451** [comment]
- Issue was coming due to below service was down that time:

client.py                  122 WARNING  Received HTTP 500 response: {"displayMessage":"There was an issue with the backend service candlepin: Failed to open TCP connection to sat6-upgrade-rhel7.example.com:8443 (Connection refused - connect(2) for \"sat6-upgrade-rhel7.example.com\" port 8443)","errors":["There was an issue with the backend service candlepin: Failed to open TCP connection to sat6-upgrade-rhel7.example.com:8443 (Connection refused - connect(2) for \"sat6-upgrade-rhel7.example.com\" port 8443)"]}

**Comment by ntkathole** [comment]
Fixed
