### ISSUE TITLE
Some tests syncing Fedora Atomic OSTree failing because repo no longer exists

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/robottelo#6770]
We have a fair number of tests failing because they are trying to sync one of the 2 repos

```
FEDORA26_OSTREE_REPO = u'https://kojipkgs.fedoraproject.org/atomic/26/'
FEDORA27_OSTREE_REPO = u'https://kojipkgs.fedoraproject.org/atomic/27/'
```

Some of them seem to be syncing it just cause they need any ostree repo to sync, so we should try to find another repo to use for these tests.
@JacobCallahan Suggests we can use 
```
https://repos.fedorapeople.org/pulp/pulp/fixtures/ostree/small/
```
We still need a second one. 

Still looking into this, but if there are any test that need that repo specifically, we need to find out what the replacement is.

@latran can you add a comment with the test you see failing because of this. I will do the same.

**Comment by latran** [comment]
tests/foreman/cli/test_contentview.py::OstreeContentViewTestCase::test_positive_add_custom_ostree_content

tests/foreman/cli/test_contentview.py::OstreeContentViewTestCase::test_positive_promote_custom_ostree

tests/foreman/cli/test_contentview.py::OstreeContentViewTestCase::test_positive_publish_custom_ostree

tests/foreman/cli/test_contentview.py::OstreeContentViewTestCase::test_positive_publish_promote_with_custom_ostree_and_other

**Comment by vijay8451** [comment]
Facing same issues for following tests too:

tests/foreman/ui_airgun/test_repository.py::test_positive_end_to_end_custom_ostree_crud
tests/foreman/cli/test_repository.py::OstreeRepositoryTestCase::test_positive_synchronize_ostree_repo

**Comment by pgagne** [comment]
Looks like they still are hosting the repos in the old format. https://kojipkgs.fedoraproject.org/compose/ostree-20190207-old/

wonder if we can just change the urls to those for now.
