### ISSUE TITLE
IndexError: list index out of range : tests.upgrades.test_activation_key.scenario_positive_activation_key.test_post_crud_activation_key (from test_scenarios-post) 

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#6784]
Error Message

IndexError: list index out of range

Stacktrace

self = <tests.upgrades.test_activation_key.scenario_positive_activation_key testMethod=test_post_crud_activation_key>

    @post_upgrade
    def test_post_crud_activation_key(self):
        """Activation key is intact post upgrade and update/delete activation key works
    
        :id: postupgrade-a7443b54-eb2e-497b-8a50-92abeae01496
    
        :steps:
    
            1. Postupgrade, Verify activation key has same entities associated.
            2. Update existing activation key with new entities
            3. Delete activation key.
    
        :expectedresults: Activation key should update and delete successfully.
        """
        org = entities.Organization().search(query={
            'search': 'name={0}'.format(self.org_name)
        })
>       ak = entities.ActivationKey(organization=org[0]).search(query={
            'search': 'name={0}'.format(self.ak_name)
        })
E       IndexError: list index out of range

tests/upgrades/test_activation_key.py:96: IndexError

**Comment by ntkathole** [comment]
This was preupgrade scenario failure. Fixed!
