### ISSUE TITLE
How to handle tests that require installer options that could potential break other things?

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/robottelo#6797]
I am starting to think about Infoblox test automation and am trying to figure out what the best way to handle (for automation and CI) the fact that infoblox requires the installer to be run with the following sets of options in order to point the satellite to the infoblox appliance:
```
satellite-installer --enable-foreman-proxy-plugin-dhcp-infoblox \
--foreman-proxy-dhcp-provider infoblox \
--foreman-proxy-plugin-dhcp-infoblox-record-type host \
--foreman-proxy-dhcp-server _IP_address_ \
--foreman-proxy-plugin-dhcp-infoblox-username admin \
--foreman-proxy-plugin-dhcp-infoblox-password infoblox \
--foreman-proxy-plugin-dhcp-infoblox-network-view default \
--foreman-proxy-plugin-dhcp-infoblox-dns-view default
```
and/or
```
satellite-installer --enable-foreman-proxy-plugin-dns-infoblox \
--foreman-proxy-dns-provider infoblox \
--foreman-proxy-plugin-dns-infoblox-dns-server _IP_address_ \
--foreman-proxy-plugin-dns-infoblox-username admin \
--foreman-proxy-plugin-dns-infoblox-password infoblox
```

How do usually handle this when writing automation and for CI runs? 

Also, one thing to point out is by running the above, trying to do any other provisioning using DHCP/DNS on that capsule will be done using the Infoblox DHCP and DNS plugins and not the BIND/ISC-DHCP ones, so it has the potential to break other provisioning tests. 

How should I go about writing the tests and CI bits to make sure this is all handled properly?

**Comment by mshriver** [comment]
With the advent of `broker` and better `xdist` integration, these tests are handled as destructive tests, and can deploy additional VM's as necessary to isolate tests of this nature.
