### ISSUE TITLE
OST0005: Fetch summary failed. Reason: GLib.Error('Unacceptable TLS certificate', 'g-tls-error-quark'

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#6803]
self = <tests.upgrades.test_capsule.Scenario_capsule_sync_2 testMethod=test_post_user_scenario_capsule_sync_2>

    @post_upgrade
    def test_post_user_scenario_capsule_sync_2(self):
        """Post-upgrade scenario that creates and sync repository with
        rpm, sync capsule with satellite and verifies if the repo/rpm in
        satellite is synced to capsule.
    
    
        :id: postupgrade-7c1d3441-3e8d-4ac2-8102-30e18274658c
    
        :steps:
            1. Post Upgrade , Sync a repo/rpm in satellite.
            2. Run capsule sync.
            3. Check if the repo/rpm is been synced to capsule.
    
        :expectedresults:
            1. The repo/rpm should be synced to satellite
            2. Capsule sync should be successful
            3. The repo/rpm from satellite should be synced to capsule
    
        """
        ak = entities.ActivationKey(organization=self.org_id).search(
            query={'search': 'name={}'.format(self.activation_key)})[0]
        ak_env = ak.environment.read()
        product = entities.Product(
            name=self.prod_name, organization=self.org_id).create()
        self.create_repo()
        repo = entities.Repository(
            product=product.id, name=self.repo_name,
            url=self.repo_url).create()
        repo.sync()
        content_view = entities.ContentView(
            name=self.cv_name, organization=self.org_id).create()
        content_view.repository = [repo]
        content_view = content_view.update(['repository'])
        content_view.publish()
        promote(content_view.read().version[0], ak_env.id)
        self.assertEqual(content_view.read().environment[-1].id, ak_env.id)
>       wait_untill_capsule_sync(self.cap_host)

tests/upgrades/test_capsule.py:218: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../shiningpanda/jobs/5164179e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/upgrade/helpers/tasks.py:804: in wait_untill_capsule_sync
    entities.ForemanTask(id=task['id']).poll(timeout=2700)
../../shiningpanda/jobs/5164179e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/nailgun/entities.py:3163: in poll
    timeout
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

task_id = 'a500b967-749f-4cff-a114-b255ce7e185d'
server_config = nailgun.config.ServerConfig(url='https://qe-sat6-upgrade-rhel7.satqe.lab.eng.rdu2.redhat.com', auth=('admin', 'changeme'), verify=False)
poll_rate = 5, timeout = 2700

    def _poll_task(task_id, server_config, poll_rate=None, timeout=None):
        """Implement :meth:`nailgun.entities.ForemanTask.poll`.
    
        See :meth:`nailgun.entities.ForemanTask.poll` for a full description of how
        this method acts. Other methods may also call this method, such as
        :meth:`nailgun.entity_mixins.EntityDeleteMixin.delete`.
    
        Certain mixins benefit from being able to poll the server after performing
        an operation. However, this module cannot use
        :meth:`nailgun.entities.ForemanTask.poll`, as that would be a circular
        import. Placing the implementation of
        :meth:`nailgun.entities.ForemanTask.poll` here allows both that method and
        the mixins in this module to use the same logic.
    
        """
        if poll_rate is None:
            poll_rate = TASK_POLL_RATE
        if timeout is None:
            timeout = TASK_TIMEOUT
    
        # Implement the timeout.
        def raise_task_timeout():  # pragma: no cover
            """Raise a KeyboardInterrupt exception in the main thread."""
            thread.interrupt_main()
    
        timer = threading.Timer(timeout, raise_task_timeout)
    
        # Poll until the task finishes. The timeout prevents an infinite loop.
        path = '{0}/foreman_tasks/api/tasks/{1}'.format(server_config.url, task_id)
        try:
            timer.start()
            while True:
                response = client.get(path, **server_config.get_client_kwargs())
                response.raise_for_status()
                task_info = response.json()
                if task_info['state'] in ('paused', 'stopped'):
                    break
                time.sleep(poll_rate)
        except KeyboardInterrupt:  # pragma: no cover
            # raise_task_timeout will raise a KeyboardInterrupt when the timeout
            # expires. Catch the exception and raise TaskTimedOutError
            raise TaskTimedOutError(
                'Timed out polling task {0}. Task information: {1}'
                .format(task_id, task_info)
            )
        finally:
            timer.cancel()
    
        # Check for task success or failure.
        if task_info['result'] != 'success':
            raise TaskFailedError(
                'Task {0} did not succeed. Task information: {1}'
>               .format(task_id, task_info)
            )
E           nailgun.entity_mixins.TaskFailedError: Task a500b967-749f-4cff-a114-b255ce7e185d did not succeed. Task information: {'id': 'a500b967-749f-4cff-a114-b255ce7e185d', 'label': 'Actions::Katello::CapsuleContent::Sync', 'pending': False, 'action': "Synchronize capsule 'Ca'", 'username': 'admin', 'started_at': '2019-03-12 15:14:54 UTC', 'ended_at': '2019-03-12 15:58:34 UTC', 'state': 'stopped', 'result': 'warning', 'progress': 1.0, 'input': {'smart_proxy': 
**', 'errors': ["OST0005: Fetch summary failed. Reason: GLib.Error('Unacceptable TLS certificate', 'g-tls-error-quark', 2)"]}, 'cli_example': None}**

../../shiningpanda/jobs/5164179e/virtualenvs/d41d8cd9/lib/python3.6/site-packages/nailgun/entity_mixins.py:115: TaskFailedError

**Comment by vijay8451** [comment]
This one also has the same issue: tests.upgrades.test_capsule.Scenario_capsule_sync.test_post_user_scenario_capsule_sync (from test_scenarios-post

**Comment by ntkathole** [comment]
Issue : https://bugzilla.redhat.com/show_bug.cgi?id=1690109
