### ISSUE TITLE
Fake/cloned manifest causes 404 on "Manage Manifest" and breaks tests. 

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/robottelo#6820]
This test seems to be failing due to not being able to find the customer on the upstream customer portal.

https://github.com/SatelliteQE/robottelo/blob/9ba00e4fdc460749f7571fc12514e3be7a72a20e/tests/foreman/ui_airgun/test_activationkey.py#L1277-L1320

 Its causing a 404 error on the manage manifest screen, digging into foreman production.log I found:
```
2019-03-18T15:06:32 [E|app|2b1c56e7] Unable to find upstream owner for consumer
2019-03-18T15:06:32 [E|app|2b1c56e7] exception when talking to a remote client: 404 Not Found RestClient::NotFound: 404 Not Found
Body: {"displayMessage":"Consumer with id REDACTED could not be found.","requestUuid":"REDACTED"}
```

Need to find a way to handle this.

**Comment by san7ket** [comment]
Manifest re-created
