### ISSUE TITLE
tests/foreman/api/test_repository.py::OstreeRepositoryTestCase::test_positive_sync_rh_atomic fails with 'undefined method `to_datetime' for nil:NilClass'

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#6830]
self = <tests.foreman.api.test_repository.OstreeRepositoryTestCase testMethod=test_positive_sync_rh_atomic>

    @tier2
    @run_in_one_thread
    @skip_if_not_set('fake_manifest')
    @upgrade
    def test_positive_sync_rh_atomic(self):
        """Sync RH Atomic Ostree Repository.
    
        :id: 38c8aeaa-5ad2-40cb-b1d2-f0ac604f9fdd
    
        :expectedresults: Synced repo should fetch the data successfully.
    
        :CaseLevel: Integration
        """
        org = entities.Organization().create()
        with manifests.clone() as manifest:
            upload_manifest(org.id, manifest.content)
        repo_id = enable_rhrepo_and_fetchid(
            org_id=org.id,
            product=PRDS['rhah'],
            repo=REPOS['rhaht']['name'],
            reposet=REPOSET['rhaht'],
            releasever=None,
            basearch=None,
        )
        call_entity_method_with_timeout(
> entities.Repository(id=repo_id).sync, timeout=1500)

tests/foreman/api/test_repository.py:1729:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
robottelo/api/utils.py:39: in call_entity_method_with_timeout
    entity_callable(**kwargs)
../../shiningpanda/jobs/e29ba9b0/virtualenvs/d41d8cd9/lib/python3.6/site-packages/nailgun/entities.py:6029: in sync
    return _handle_response(response, self._server_config, synchronous)
../../shiningpanda/jobs/e29ba9b0/virtualenvs/d41d8cd9/lib/python3.6/site-packages/nailgun/entities.py:121: in _handle_response
    server_config, id=response.json()['id']).poll(timeout=timeout)
../../shiningpanda/jobs/e29ba9b0/virtualenvs/d41d8cd9/lib/python3.6/site-packages/nailgun/entities.py:3151: in poll
    timeout
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

**Task fails as below on satellite:**

'33e0c2bc-6f5d-4f64-8e5c-9ca6c90eaa7c', 'num_processed': 1}, {'num_success': 1, 'description': 'Making files available via web.', 'step_type': 'ostree_publish_over_http', 'items_total': 1, 'state': 'FINISHED', 'error_details': [], 'details': '', 'num_failures': 0, 'step_id': 'c3c64953-d0bb-4c96-8fcc-d401f9f9084a', 'num_processed': 1}]}, 'error': None, '_id': {'$oid': '5c95fe4ce812aef4649b2e4f'}, 'id': '5c95fe4ce812aef4649b2e4f'}], 'contents_changed': True, 'poll_attempts': {'total': 9, 'failed': 0}}, 'skip_metadata_check': False, 'validate_contents': False, 'contents_changed': True, 'current_timezone': 'UTC', 'current_user_id': 4, 'current_organization_id': None, 'current_location_id': None}, 'output': {}, 'humanized': {'action': 'Synchronize', 'input': [['repository', {'text': "repository 'Red Hat Enterprise Linux Atomic Host Trees'", 'link': None}], ['product', {'text': "product 'Red Hat Enterprise Linux Atomic Host'", 'link': '/products/955/'}], ['organization', {'text': "organization 'gbLIawy'", 'link': '/organizations/56/edit'}]], 'output': 'Branches updated', 'errors': **["undefined method `to_datetime' for nil:NilClass"]**}, 'cli_example': None}

**Comment by ntkathole** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1689504
