### ISSUE TITLE
test_hostgroup.py::test_positive_create_with_synced_content synchronization task is cancelled

### ISSUE THREAD

**Issue by mirekdlugosz** [SatelliteQE/robottelo#6840]
`tests/foreman/cli/test_hostgroup.py::HostGroupTestCase::test_positive_create_with_synced_content` failed during last couple of runs due to "task canceled" during synchronization:

```
Task d39a552e-82cc-4dc2-9122-1d1c833d874d running: 0.004761904761904762/1, 0%, 0.0/s, elapsed: 00:02:15
Task d39a552e-82cc-4dc2-9122-1d1c833d874d running: 0.004761904761904762/1, 0%, 0.0/s, elapsed: 00:02:17
Task d39a552e-82cc-4dc2-9122-1d1c833d874d running: 0.004761904761904762/1, 0%, 0.0/s, elapsed: 00:02:19
Task d39a552e-82cc-4dc2-9122-1d1c833d874d warning: 1.0/1, 100%, 0.0/s, elapsed: 00:02:21
Task d39a552e-82cc-4dc2-9122-1d1c833d874d warning: 1.0/1, 100%, 0.0/s, elapsed: 00:02:21
Error: Task canceled
```

Of course, it does pass when run locally.

It might be that another test is running at the same time and it cancels all the tasks. But every single time? Hard to believe.

It might be that `Repository.synchronize({'id': repo['id']})` line is at fault. But I would expect a lot of failures all over the place, not in one very specific test that hasn't been changed in long time.

So I'm kind of lost here. @san7ket @rplevka , any idea where I should look?

**Comment by san7ket** [comment]
@mirzal You can find more info , by trying to get in the box it was failed on and look into what went wrong with the task

**Comment by mirzal** [comment]
@san7ket thanks. Test was run on qe-sat6-upgrade-rhel7.\<redacted\>. This box now has Satellite 6.2 installed (instead of 6.5). Looks like someone re-provisioned it yesterday. I guess we won't find anything useful now?

**Comment by rplevka** [comment]
@mirzal looking into this.

**Comment by mshriver** [comment]
This test case no longer exists, and the historical result is no longer relevant, closing.
