### ISSUE TITLE
Update the scap files and profile names in tests

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#6849]
Affected upgrade tests: tests.foreman.longrun.test_oscap.OpenScapTestCase

These test will pass for regression suite as it uploads a older version of scap-content files and we have older profile names in constants.py so tests passes which is acceptable 

These tests will fail in upgrade, where it will have latest scap-contents and constants.py has older name.

**Comment by san7ket** [comment]
Refcator the constants used https://github.com/SatelliteQE/robottelo/pull/6850
and in tests/foreman/longrun

**Comment by JacobCallahan** [comment]
Closing this issue since it has not been acted upon up until this point. Future component owners can reopen if they are going to address this.
