### ISSUE TITLE
Automate test_positive_upload_file_to_file_repo

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#6894]
Automate test_positive_upload_file_to_file_repo

For more details around steps , please refer[1]

[1]https://github.com/SatelliteQE/robottelo/blob/6.5.z/tests/foreman/cli/test_repository.py

**Comment by mshriver** [comment]
CLI test case has been automated, API test case has not. closing issues related to automation of singular stubbed test cases.
