### ISSUE TITLE
Write tests for Content View cloning via API

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#690]
Please write the tests for the following (already written) stubs:

* test_cv_clone_within_same_env
* test_cv_clone_within_diff_env

**Comment by omaciel** [comment]
The feature is called ``Copy View`` now in the web ui (see screenshot below). The call is ``POST katello/api/v2/content_views/2/copy`` and the parameters ``{"id":2,"content_view":{"name":"Cloned RHEL 7"}}`` where ``id`` is the ID for the content view to be copied.

![screenshot 2015-04-06 15 06 04](https://cloud.githubusercontent.com/assets/53362/7010354/791a6d1e-dc6e-11e4-9ed6-525cbbbff1ea.png)

**Comment by oshtaier** [comment]
Thanks. What about 'within_same_env' and 'within_diff_env' statements? 'Copy View' functionality does not provide opportunity to do that. Should I copy existing view and then publish it to a different environments?

**Comment by omaciel** [comment]
So a ``content view`` is associated with a ``lifecycle-environment``, so the test for 'within_same_env' would mean that the cloned/copied ``content view`` would still be associated to the same ``lifecycle-environment`` as the 'original' one. The test for 'woth_diff_env' would copy/clone it to a different ``lifecycle-environment`` but still associated to the same organization, etc.

**Comment by oshtaier** [comment]
But anyway, I need to publish copied environment as Lifecycle-environment is starting to be associated with Content View only after publish, right?

**Comment by oshtaier** [comment]
Still don't understand why we need to test 'within_same_env' and 'within_diff_env' as we will not test cloning, but publishing procedure. Copy functionality has nothing about with 'lifecycle-environments' as it is not copying information from 'Version' tab as far as I see. Please correct, if I am wrong

**Comment by omaciel** [comment]
Sorry @oshtaier for (my) confusion. I took a look at the test stub and I believe I can now provide you with the correct information. These tests are not related to **publishing** but **promoting**. So the test would be:

```python
    def test_cv_clone_within_same_env(self):
        """
        @test: attempt to create, publish and promote new content view based on existing
        view within the same environment as the original content view
        @feature: Content Views
        @assert: Cloned content view can be published and promoted to the same environment as the original content view
        @status: Manual
        """

The test then would be:
* Create the following lifecycle environments:
  * Library > (random name 1)
* Create new content view **CV1** (real name should be random)
  * publish it
  * promote it to (random name 1) lifecycle 
* Clone **CV1** and name it **CV2** (real name should be random)
  * Publish it
  * Promote it to (random name 1) lifecycle

```python
    def test_cv_clone_within_diff_env(self):
        """
        @test: attempt to create, publish and promote new content view based on existing
        view but promoted to a different environment
        @feature: Content Views
        @assert: Cloned content view can be published and promoted to a different environment than the original content view
        @status: Manual
        """
```

The test then would be:
* Create the following **parallel** lifecycle environments:
  * Library > (random name 1)
  * Library > (random name 2)
* Create new content view **CV1** (real name should be random)
  * publish it
  * promote it to (random name 1) lifecycle 
* Clone **CV1** and name it **CV2** (real name should be random)
  * Publish it
  * Promote it to (random name 2) lifecycle
