### ISSUE TITLE
tests.foreman.installer.test_installer.test_installer_options_and_flags (from tier1-parallel) AssertionError: ###Removed options:

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#6913]
tests.foreman.installer.test_installer.test_installer_options_and_flags (from tier1-parallel) 

@upgrade
    @tier1
    def test_installer_options_and_flags():
        """Look for changes on installer options and flags
    
        :id: a51d3b9f-f347-4a96-a31a-770349db08c7
    
        :Steps:
            1. parse installer options and flags
            2. compare with last options
    
        :expectedresults: Ideally options should not change on zstreams.
            Documentation must be updated accordingly when such changes occur.
            So when this test fail we QE can act on it, asking dev if
            changes occurs on zstream and checking docs are up to date.
        """
        stdout = ssh.command('satellite-installer --full-help').stdout
    
        current_installer_options = set(extract_params(stdout or []))
        removed_options = list(
            PREVIOUS_INSTALLER_OPTIONS - current_installer_options)
        removed_options.sort()
        added_options = list(
            current_installer_options - PREVIOUS_INSTALLER_OPTIONS)
        added_options.sort()
        msg = "###Removed options:\n{}\n###Added options:\n{}".format(
            removed_options, added_options
        )
>       assert PREVIOUS_INSTALLER_OPTIONS == current_installer_options, msg
E       AssertionError: ###Removed options:

**Comment by vijay8451** [comment]
Following up with devs on it ..

**Comment by ntkathole** [comment]
Fixed
