### ISSUE TITLE
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#6915]
Stacktrace

self = <tests.foreman.api.test_operatingsystem.OperatingSystemTestCase testMethod=test_positive_create_with_os_family>

    @tier1
    @run_only_on('sat')
    def test_positive_create_with_os_family(self):
        """Create operating system with every OS family possible
    
        :id: 6ad32d22-53cc-4bab-ac10-f466f75d7cc6
    
        :expectedresults: Operating system entity is created and has proper OS
            family assigned
    
        :CaseImportance: Critical
        """
        for os_family in OPERATING_SYSTEMS:
            with self.subTest(os_family):
>               os = entities.OperatingSystem(family=os_family).create()

tests/foreman/api/test_operatingsystem.py:118: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../shiningpanda/jobs/97b613ea/virtualenvs/d41d8cd9/lib/python3.6/site-packages/blinker_herald/base.py:137: in wrapper
    result = fn(*args, **kwargs)
../../shiningpanda/jobs/97b613ea/virtualenvs/d41d8cd9/lib/python3.6/site-packages/nailgun/entity_mixins.py:964: in create
    return self.read(attrs=self.create_json(create_missing))
../../shiningpanda/jobs/97b613ea/virtualenvs/d41d8cd9/lib/python3.6/site-packages/nailgun/entity_mixins.py:934: in create_json
    response.raise_for_status()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Response [422]>

    def raise_for_status(self):
        """Raises stored :class:`HTTPError`, if one occurred."""
    
        http_error_msg = ''
        if isinstance(self.reason, bytes):
            # We attempt to decode utf-8 first because some servers
            # choose to localize their reason strings. If the string
            # isn't utf-8, we fall back to iso-8859-1 for all other
            # encodings. (See PR #3538)
            try:
                reason = self.reason.decode('utf-8')
            except UnicodeDecodeError:
                reason = self.reason.decode('iso-8859-1')
        else:
            reason = self.reason
    
        if 400 <= self.status_code < 500:
            http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
    
        elif 500 <= self.status_code < 600:
            http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
    
        if http_error_msg:
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url:

**Comment by vikask18** [comment]
Closing this issue, as this has been fixed (provided a workaround) for a dependency on OS family Debian and release name.

Refer bugzilla id - 1709683 for more details.
