### ISSUE TITLE
tests/foreman/ui_airgun/test_architecture fails RowNotFound

### ISSUE THREAD

**Issue by swadeley** [SatelliteQE/robottelo#6951]
Hello

While getting my test setup working, I was running some random airgun tests, and saw this:

>               'Row not found when using filters {!r}/{!r}'.format(extra_filters, filters))
E           widgetastic.exceptions.RowNotFound: Row not found when using filters ()/{'name': 'CFzJrKBNuV'}

../../.virtualenvs/robottelo-master/lib/python3.6/site-packages/widgetastic/widget/table.py:469: RowNotFound

**Comment by ntkathole** [comment]
Passed with snap 20. Closing!
