### ISSUE TITLE
Add upgrade test for bulk Action update all packages(via katello agent)

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/robottelo#6956]
Steps:
1. Select 1 or N hosts on the content host page
2. Click on "Select Action" button.
3. Click on "Manage Packages" button.
4. Click on "Update All Packages"

For more details :
https://bugzilla.redhat.com/show_bug.cgi?id=1712069

**Comment by swadeley** [comment]
Hello @ntkathole 

I could not find code to access the menu with the "Update All Packages" button from Content Hosts view. I found there was existing code[1] to access that menu from Host Collections view.

I am asking jturel in bugzilla [2] if testing that Update All Packages function via Host Collections would test the code path that caused this issue. 

[1] manage_packages https://github.com/SatelliteQE/airgun/blob/4ae23257a7f5ad3a722dd0ac521de6d292d15961/airgun/entities/hostcollection.py#L68
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1712069#c9

**Comment by swadeley** [comment]
Still need to cherry-pick to 6.5 branch

**Comment by swadeley** [comment]
Hello, the test is now merged into the 6.5.z branch.
