### ISSUE TITLE
Test Failing because of timeout tests.upgrades.test_errata.Scenario_errata_count.test_pre_scenario_generate_errata_for_client (from test_scenarios-pre)

### ISSUE THREAD

**Issue by omkarkhatavkar** [SatelliteQE/robottelo#6961]
Test Failing because of timeout tests.upgrades.test_errata.Scenario_errata_count.test_pre_scenario_generate_errata_for_client (from test_scenarios-pre)

Currently, it is 1400 secs. It may require more time to sync.

**Comment by ntkathole** [comment]
Fixed
