### ISSUE TITLE
VirtualMachine.create() has hardcoded top-level domain name

### ISSUE THREAD

**Issue by mirzal** [SatelliteQE/robottelo#7013]
VirtualMachine.create() success depends on pinging new vm based on hardcoded domain name (
https://github.com/SatelliteQE/robottelo/blob/master/robottelo/vm.py#L236 ). This passes on our testing environment, but will fail everywhere else - unless you configure your local environment to mirror testing environment.

This class should be re-worked to be more robust. Any libvirt domain setting should be allowed. VirtualMachine class already has `hostname` and `domain` properties that might come in handy.

**Comment by jhutar** [comment]
Hello. To get that `ping xxx.local` working, this is what Lukas advised me few days back:
```
rlPhaseStartSetup "Avahi discovery"
rlRun "yum -y install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
rlRun "yum -y install nss-mdns" # pulls in avahi
rlRun "rpm -e epel-release"
rlRun "service firewalld restart"
rlRun "firewall-cmd --add-service mdns && firewall-cmd --add-service mdns --permanent"
rlRun "service avahi-daemon restart"
rlAssertGrep mdns4_minimal /etc/nsswitch.conf
rlPhaseEnd
```
(ignore these `rlRun` wrappers, code copy&pasted from Lukas's Beaker task)

**Comment by mirzal** [comment]
There is PR for using different approach to obtaining host IP address, one that does not depend on any particular network setup - https://github.com/SatelliteQE/robottelo/pull/7018
