### ISSUE TITLE
Make Upgrade Scenaios fully independent of Environement Variables

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#7030]
Recently, Some initiatives and efforts have been taken to make upgrade scenarios fully independent of environment Variables such as #6908. 

But I still see there is a dependency on environment variables, in case of:-

- [ ] Helpers for upgrade scenarios are being used from the satellite6-upgrade repo, where those helpers need values from environment variables. 
**Solution** - Move all upgrade scenario helpers to robottelo utils and replace environment vars with robottelo settings.

**Comment by jyejare** [comment]
More thoughts folks ?

**Comment by omkarkhatavkar** [comment]
@jyejare I like the plan, we should move all dynamic variables getting instead evaluated from satellite-upgrade. This will give good control removing and adding new variables. One more suggestion from my side, we should keep a separate file for upgrade-related functions in robottelo-utils. It is good to have segregation.

**Comment by jyejare** [comment]
Yes @omkarkhatavkar , +1 for having a separate helper package and module for upgrade specific.

**Comment by vijay8451** [comment]
+1 @jyejare to remove env vars dependency, and  keep all in `robottelo` as that would help us to easy /centralized  manage them.

**Comment by jyejare** [comment]
Thanks guys , Final thoughts from @san7ket @ntkathole  ??

**Comment by ntkathole** [comment]
@jyejare +1

**Comment by ntkathole** [comment]
@jyejare where are we on this?

**Comment by jyejare** [comment]
@ntkathole, Nowhere :) , We need to start on this!

**Comment by mshriver** [comment]
With the introduction of dynaconf, settings and environment variable use and standards have changed.  Closing this, as both robottelo and satellite6-upgrade repositories are now using dynaconf.
