### ISSUE TITLE
Automate BZ #1627642

### ISSUE THREAD

**Issue by appuk** [SatelliteQE/robottelo#7084]
[Bug 1627642](https://bugzilla.redhat.com/show_bug.cgi?id=1627642) - Apply correct spelling to "Create a User" labels

Steps to verify:
1. From the navigation bar, go to Administer and click on Users
2. Click on Create User button
3. Verify whether the spellings of labels, "First Name" and "Surname" are correct

**Comment by mshriver** [comment]
Going to close this, although its 'low hanging fruit' when it comes to test coverage, its also very low level coverage that doesn't provide much value for the 'cost' of a UI test.
