### ISSUE TITLE
Implement code to handle Systems registration

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#710]
Write the code to handle dealing with Systems registration. This will most likely require the use of ``Paramiko`` and the existing ``SSHCommand`` class as you'll have to ssh to the client and run a series of command.

**Comment by sghai** [comment]
Pending two tests requires provisioning in place.. Provisioning via foreman

**Comment by sghai** [comment]
Closing this as its just a Issue tracker.. The open issues are already being tracked separately and assigned to me..
