### ISSUE TITLE
Write UI test for test_end_to_end_activation_key

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#714]
Please write the automation code that handles the `test for test_end_to_end_activation_key` test for **Activation Keys** via the UI. This requires #710 to be completed.

**Comment by sghai** [comment]
This test requires provisioning via foreman in place.

**Comment by sghai** [comment]
This can be done now. Adding it to next sprint.

**Comment by sghai** [comment]
Test Steps:
- Add a product/repo & sync it
- Create a CV
- add the created repo to CV and publish/promote the CV to next env
- create an activation key
- provision the host and associate the key
- Assert: host should be registered w/ server using same activation-key and can fetch the contents from subscribed product/repo.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
