### ISSUE TITLE
Automate Upgrade Scenario for n-1 client

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#7167]
Add scenario in [1] for :

-  Satellite and/or Capsule both upgraded, client on an older version of katello-agent still should be able to communicate with satellite/capsule. 

[1]: https://github.com/SatelliteQE/robottelo/blob/master/tests/upgrades/test_client.py

Also, cherrypick for all branches.

**Comment by ntkathole** [comment]
Reference : https://bugzilla.redhat.com/show_bug.cgi?id=1529682#c1

**Comment by vijay8451** [comment]
@jyejare I'll see this one :)

**Comment by vijay8451** [comment]
@sghai PR has been raised for it .
