### ISSUE TITLE
tests.foreman.ui.test_host.test_positive_inherit_puppet_env_from_host_group_when_action (from tier3-parallel)

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#7172]
Error Message
selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator='.//table')
Stacktrace
session = <airgun.session.Session object at 0x7f90915be358>

    @tier3
    def test_positive_inherit_puppet_env_from_host_group_when_action(session):
        """Host group puppet environment is inherited to already created
        host when corresponding action is applied to that host
    
        :id: 3f5af54e-e259-46ad-a2af-7dc1850891f5
    
        :customerscenario: true
    
        :expectedresults: Expected puppet environment is inherited to the host
    
        :BZ: 1414914
    
        :CaseLevel: System
        """
        org = entities.Organization().create()
        loc = entities.Location().create()
        host = entities.Host(organization=org, location=loc).create()
        env = entities.Environment(
            organization=[org], location=[loc]).create()
        hostgroup = entities.HostGroup(
            environment=env, organization=[org], location=[loc]).create()
        with session:
            session.organization.select(org_name=org.name)
            session.location.select(loc_name=loc.name)
            session.host.apply_action(
                'Change Environment',
                [host.name],
                {'environment': '*Clear environment*'})
            host_values = session.host.search(host.name)
            assert host_values[0]['Host group'] == ''
            assert host_values[0]['Puppet Environment'] == ''
            session.host.apply_action(
                'Change Group',
                [host.name],
                {'host_group': hostgroup.name})
            host_values = session.host.search(host.name)
            assert host_values[0]['Host group'] == hostgroup.name
            assert host_values[0]['Puppet Environment'] == ''
            session.host.apply_action(
                'Change Environment',
                [host.name],
                {'environment': '*Inherit from host group*'})
>           host_values = session.host.search(host.name)

tests/foreman/ui/test_host.py:557:

**Comment by vijay8451** [comment]
Looks a element was not loaded when checked or may be came due to slowness as manually works fine:
tests/foreman/ui/test_host.py::test_positive_inherit_puppet_env_from_host_group_when_action PASSED                                                               [100%]

**Comment by ntkathole** [comment]
Fixed in snap 19.1. Feel free to re-open, if it failed again.
