### ISSUE TITLE
test_positive_create_update_delete location test fails with obottelo.cli.factory.CLIFactoryError: Failed to create Location with data

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#7175]
From the last snap the  tests.foreman.cli.test_location.LocationTestCase.test_positive_create_update_delete fails with obottelo.cli.factory.CLIFactoryError: Failed to create Location with data

Test log output here:
https://satellite-jenkins/view/Satellite6.6/job/automation-6.6-tier2-rhel7/13/testReport/tests.foreman.cli.test_location/LocationTestCase/test_positive_create_update_delete/

**Comment by pondrejk** [comment]
https://satellite-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Satellite6.6/job/automation-6.6-tier2-rhel7/13/testReport/tests.foreman.cli.test_location/LocationTestCase/test_positive_create_update_delete/

**Comment by ntkathole** [comment]
Test passing since last 4 snaps
