### ISSUE TITLE
E           selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator=".//div[@class='list-view-pf-expand']/span")

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#7183]
tests.foreman.ui.test_audit.test_positive_delete_event (from tier2-sequential) 
self = <BrowserParentWrapper for <airgun.views.audit.AuditEntry object at 0x7f1859d36e48>>
locator = Locator(by='xpath', locator=".//div[@class='list-view-pf-expand']/span")
args = (), kwargs = {}, vcheck = None, elements = []

    def element(self, locator, *args, **kwargs):
        """Returns one :py:class:`selenium.webdriver.remote.webelement.WebElement`
    
        See: :py:meth:`elements`
    
        Returns:
            :py:class:`selenium.webdriver.remote.webelement.WebElement`
    
        Raises:
            :py:class:`selenium.common.exceptions.NoSuchElementException`
        """
        try:
            vcheck = self._locator_force_visibility_check(locator)
            if vcheck is not None:
                kwargs['check_visibility'] = vcheck
            elements = self.elements(locator, *args, **kwargs)
            if len(elements) > 1:
                visible_elements = [e for e in elements if self.is_displayed(e)]
                if visible_elements:
                    return visible_elements[0]
                else:
                    return elements[0]
            else:
>               return elements[0]
E               IndexError: list index out of range

**Comment by ntkathole** [comment]
Snap 20 test passed
