### ISSUE TITLE
make OSCAP tests to fetch the xml file from satellite

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#7203]
currently they use `robottelo.properties`:
```
[oscap]
content_path=/local/path/to.xml
```

this relies on something or someone to put the file on the jenkins slave before executing the test. This might get tricky with dynamic dockerized jenkins slaves as they are created on a session start. 

We should make this a part of the test `setUp`

**Comment by san7ket** [comment]
thanks , will find time for this

**Comment by ntkathole** [comment]
gitlab PR 247
