### ISSUE TITLE
test_positive_update_interval fails due to filtered_datapoint(func)

### ISSUE THREAD

**Issue by swadeley** [SatelliteQE/robottelo#7231]
Hello

this test sometimes fails:
tests/foreman/api/test_syncplan.py::SyncPlanUpdateTestCase::test_positive_update_interval

Example of fail:
            valid_intervals = valid_sync_interval()
> self.assertIn(interval, valid_intervals)
E AssertionError: 'weekly' not found in ['daily']

tests/foreman/api/test_syncplan.py:369: AssertionError

Issue is that when calling valid_sync_interval() it is not returning a full list of valid intervals as you might expect[1]. There is a decorator,  filtered_datapoint(func) [2] , and because this is called,  only one interval is returned, not a list. 

This is my newbie mistake, not reading all the dependent code when writing the test.[3]

[1] https://github.com/SatelliteQE/robottelo/blob/2041346f32b98181d6ac86044156a44f9858a011/tests/foreman/api/test_syncplan.py#L70

[2] https://github.com/SatelliteQE/robottelo/blob/2041346f32b98181d6ac86044156a44f9858a011/robottelo/datafactory.py#L19

[3] https://github.com/SatelliteQE/robottelo/issues/6679

**Comment by swadeley** [comment]
If I remove that decorator, this test passes 20 times:

robottelo]$ for i in {1..20}; do pytest --dist=each --tx=5*popen --show-capture=no  tests/foreman/api/test_syncplan.py::SyncPlanUpdateTestCase::test_positive_update_interval; done
2019-08-05 10:33:17 - conftest - DEBUG - Registering custom pytest_configure

=================== test session starts ===================================
platform linux -- Python 3.6.6, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo
plugins: services-1.3.1, forked-1.0.2, xdist-1.28.0, cov-2.7.1, mock-1.10.4
gw0 [1] / gw1 [1] / gw2 [1] / gw3 [1] / gw4 [1]
.                                                                                                                                                      [100%]. [100%]. [100%]. [100%]. [100%]
========================= 5 passed in 18.79 seconds =====================

**Comment by vijay8451** [comment]
@swadeley I re-write this test a bit and now it looks more happy as I tired 20+ times and all Passed :)

```
        interval = valid_sync_interval()[0]
        sync_plan = entities.SyncPlan(
            description=gen_string('alpha'),
            organization=self.org,
            interval=interval
        )
        if interval == SYNC_INTERVAL['custom']:
            sync_plan.cron_expression = gen_choice(valid_cron_expressions())
        sync_plan = sync_plan.create()

        # Update Interval
        new_interval = valid_sync_interval()[0]
        sync_plan.interval = new_interval
        if new_interval == SYNC_INTERVAL['custom']:
            sync_plan.cron_expression = gen_choice(valid_cron_expressions())
            sync_plan = sync_plan.update(['interval', 'cron_expression'])
        else:
            sync_plan.interval = new_interval
            sync_plan = sync_plan.update(['interval'])
        self.assertEqual(sync_plan.interval, new_interval)
```
let me know if you see any related issue again ...

**Comment by vijay8451** [comment]
Just to add more ... If you plan to remove ` filtered_datapoint` from `valid_sync_interval()` then would suggests to keep the `for` loop as it is.

**Comment by swadeley** [comment]
Hello @vijay8451 

I think the important point is that the second part of the test should have a radom but different interval to the first part of the test. So I will try this: 

   
    -            valid_intervals = valid_sync_interval()
    -            self.assertIn(interval, valid_intervals)
    -            valid_intervals.remove(interval)
    -            new_interval = gen_choice(valid_intervals)
    +            # get another random interval and workaround issue #7231
    +            new_interval = valid_sync_interval()[0]
    +            while new_interval == interval:
    +                    new_interval = valid_sync_interval()[0]
                 sync_plan.interval = new_interval

**Comment by swadeley** [comment]
Nope, that creates an infinite loop. But this works:

    -            valid_intervals = valid_sync_interval()
    -            self.assertIn(interval, valid_intervals)
    -            valid_intervals.remove(interval)
    -            new_interval = gen_choice(valid_intervals)
    +            # get another random interval and workaround issue #7231
    +            new_interval = gen_choice(valid_sync_interval())
    +            while new_interval == interval:
    +                new_interval = gen_choice(valid_sync_interval())
                 sync_plan.interval = new_interval
