### ISSUE TITLE
VirtWhoConfigApiTestCase failing due to virt-who version issue.

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/robottelo#7248]
Need to look into whats going on here. The deploy script one version is needed, but apparently it doesn't have access to this. Might be that the satellite doesn't have the tools repo enabled?

```
2019-07-26 11:51:53 - robottelo.ssh - INFO - <<< stdout

== [1/5] Installing virt-who ==
Package virt-who-0.22.5-1.el7.noarch already installed and latest version
virt-who 0.22.5 does not meet minimum requirements, please make sure this host is properly subscribed and has access to satellite-tools repository, minimal virt-who version is 0.24.2

== Finished ==
There were some errors during configuration:
Newer version of virt-who is required, minimum version is 0.24.2
```

**Comment by pgagne** [comment]
@eko999 FYI is this something you or virt-who people want to look into? I am pretty sure I went over this test with you guys when I handed over the virt-who stuff, but if not might be a good opportunity to learn about it.

**Comment by eko999** [comment]
Let's look forward to the new version in RHEL7.7 GA as the bug comment: https://bugzilla.redhat.com/show_bug.cgi?id=1707271#c4

**Comment by ntkathole** [comment]
Tests passed in latest snap 20
