### ISSUE TITLE
tests.foreman.cli.test_satellitesync.ContentViewSync test failing due to tars being deleted

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/robottelo#7255]
Tars are being deleted because the teardown does `rm -rf <exported dir>/*` and there are test being run in multiple threads.

**Comment by pgagne** [comment]
https://github.com/SatelliteQE/robottelo/blob/b8c1d036139dee3e11a7e7ff0f1863feed466978/tests/foreman/cli/test_satellitesync.py#L401-L404

@jyejare was there a reason you did the teardown method this way. It seems to break due to the multithreading. I am trying to decide how to fix it. First this should probably be in teardownClass. But even then i will probably need to add code to delete every exported tar created using its name as opposed to a wildcard 

Is there some case I am missing here that caused you to delete the whole directory. If so we will probably have to make this `@run_in_one_thread` test case.

**Comment by jyejare** [comment]
Hello @pgagne, Good Find!

We need to fix that my removing the tar file asap we finished with it and maybe by naming now :(
