### ISSUE TITLE
more thread safety for robottelo asserts

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#7272]
Quite a bunch of tests contain asserts that rely on getting the first element in the list, see git grep "assert.*\[0\]" tests/foreman/

This can cause problems with parallel runs where tests can interfere, and the first element in the list gets occupied by another list.
IMO best fix is to change these assert to check if element is contained in the list rather than looking at the first occurrence. Other option is to check the length of the list first. Also there is run_in_one_thread decorator, but that shouldn't be misused.

This issue is to start a consolidated effort to find and fix these asserts where it makes sense

**Comment by rplevka** [comment]
related to https://github.com/SatelliteQE/robottelo/issues/6868
