### ISSUE TITLE
Test for mod errata and package profile upload

### ISSUE THREAD

**Issue by swadeley** [SatelliteQE/robottelo#7288]
Hello

Some time ago I wanted to write a test for modular errata, which includes package profile upload, but @omkarkhatavkar beat me to it, but that test uses a forced upload. I wanted to test without force profile upload, so I adapted omkarkhatavkar's other wise excellent test.

**Comment by omkarkhatavkar** [comment]
@swadeley actually dnf upload profile should be run in the background if there is any problem we have to run dnf profile. I would say running without dnf profile add real value

**Comment by swadeley** [comment]
Hello

github missed this PR:

module status update without force package package profile #7289

So its done.

Thank you
