### ISSUE TITLE
Setting more user control for "Show All" and "Limit to Env" checkboxes in RepoSets

### ISSUE THREAD

**Issue by latran** [SatelliteQE/robottelo#7333]
Runs that I've come across have made it the default to check "Show All" checkbox under Repository Sets for content hosts.  We need a way for users to have more control on which checkboxes to check instead of the default.  Currently there's no implementation and it's affecting a test case.

**Comment by JacobCallahan** [comment]
This might have to dig further down into Airgun (and the libraries it inherits from) in order to come up with a solution broad enough for other cases.

**Comment by latran** [comment]
@JacobCallahan There's a workaround that Mirek came up with that I'm able to successfully run so we can use that for the time being.
