### ISSUE TITLE
Replace Pyup with Dependabot 

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#7371]
What if we remove @pyup-bot and add @dependabot https://dependabot.com/

Dependabot is acquired by Github and looks like better maintained, also it can do automated actions based on PR comments.

Looks like Pyup is not being very helpful, any comment?

**Comment by rochacbruno** [comment]
Also: Pyup has a problem, it creates lots of branches on the repo.

Dependabot maintains own fork, so we have no extra branch

**Comment by mirzal** [comment]
Problem with our pyup-bot usage is not lack of support for automatic actions, but that travis tests for robottelo don't cover even 10% of things that we care about. We want to ensure that upgrading dependencies doesn't impact Satellite snaps automation runs, and travis is hopelessly helpless here. @ntkathole experimented with triggering automation runs on Jenkins based on GitHub comments over at nailgun, but human intervention is still required there (to analyze results and hit "merge").

So we end up with pyup-bot nagging us, us ignoring him and coordinating dependency updates whenever someone feels they are important (read: once or twice a year). I'm not sure if dependabot could improve anything.

> Also: Pyup has a problem, it creates lots of branches on the repo.
> 
> Dependabot maintains own fork, so we have no extra branch

OK, you convinced me. I vote for dependabot.

**Comment by ntkathole** [comment]
As both the bot serves same purpose, we can replace  pyup with dependabot **if there are no major efforts required** else the problem of pyup bot creating branches on the repo is not big issue.

**Comment by mshriver** [comment]
This hasn't been discussed in a while, but I too have been annoyed by pyup-bot's integration.

We have robottelo-runner in place now, and can trigger an internal pipeline to do more thorough validation of the package updates.

I'd also vote for switching to dependabot.

**Comment by JacobCallahan** [comment]
I'm certainly up for hearing this case
