### ISSUE TITLE
BZ skip doesn't work if there is nothing to skip

### ISSUE THREAD

**Issue by peterdragun** [SatelliteQE/robottelo#7444]
Our [new BZ](https://github.com/SatelliteQE/robottelo/pull/7404) skip is trying to send request to BZ api even if there aren't any BZ decorators in file. This results in getting error message from server : "You may not search, or create saved searches, without any search terms." and key error exception.
We should not send requests to BZ api if 'bz_numbers' are empty. And maybe we should add some error handling when bugzilla rest api response does not contain [bugs](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/issue_handlers/bugzilla.py#L267).

**Comment by rochacbruno** [comment]
Good catch! thanks @kersommoura
