### ISSUE TITLE
E TypeError: expected string or bytes-like object: tests.foreman.cli.test_hammer.HammerCommandsTestCase testMethod=test_positive_all_options

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#7513]
self = <tests.foreman.cli.test_hammer.HammerCommandsTestCase testMethod=test_positive_all_options>

    @tier1
    @upgrade
    def test_positive_all_options(self):
        """check all provided options for every hammer command
    
        :id: 1203ab9f-896d-4039-a166-9e2d36925b5b
    
        :expectedresults: All expected options are present
    
        :CaseImportance: Critical
        """
        self.maxDiff = None
> self._traverse_command_tree()

tests/foreman/cli/test_hammer.py:158:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/foreman/cli/test_hammer.py:95: in _traverse_command_tree
    commands = re.split('.*\n(?=hammer.*\n^[-]+)', raw_output, flags=re.M)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

pattern = '.*\n(?=hammer.*\n^[-]+)'
string = ['Hammer CLI help', '===============', 'hammer', '------', '', '', ...]
maxsplit = 0, flags = <RegexFlag.MULTILINE: 8>

    def split(pattern, string, maxsplit=0, flags=0):
        """Split the source string by the occurrences of the pattern,
        returning a list containing the resulting substrings. If
        capturing parentheses are used in pattern, then the text of all
        groups in the pattern are also returned as part of the resulting
        list. If maxsplit is nonzero, at most maxsplit splits occur,
        and the remainder of the string is returned as the final element
        of the list."""
> return _compile(pattern, flags).split(string, maxsplit)
E TypeError: expected string or bytes-like object

/usr/lib64/python3.7/re.py:213: TypeError
2019-11-26 22:21:56

**Comment by mirekdlugosz** [comment]
I think this is the problem that is fixed by https://github.com/SatelliteQE/robottelo/pull/7510 (not yet merged)
