### ISSUE TITLE
(snap9) DockerRepositoryTestCase  fails with error

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#7591]
tests/foreman/ui/test_repository.py::test_positive_delete_random_docker_repo
```
E wait_for.TimedOutError: Could not do 'lambda defined as `lambda: view.search('name = "{0}"'.format(entity_name)) == [],`' at /home/jenkins/workspace/automation-6.7-tier2-rhel7/.env/lib64/python3.7/site-packages/airgun/entities/repository.py:70 in time
```

tests/foreman/api/test_repository.py::DockerRepositoryTestCase::test_positive_synchronize
tests/foreman/cli/test_docker.py::DockerRepositoryTestCase::test_positive_sync

```
Error: PLP0000: Too Many Requests
```

**Comment by vijay8451** [comment]
tests/foreman/cli/test_hammer.py::HammerTestCase::test_positive_disable_hammer_defaults PASSED                                                                        [100%]

**Comment by mirekdlugosz** [comment]
All passed in snap 10 without any changes in code. Closing this for now - if they start failing consistently, or are proven to be unreliable, we should take another look.
