### ISSUE TITLE
client settings not read from the module scoped fixture

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#7596]
Affecting the whole cli rex testclass in 6.7, that fail with:

```
request = <SubRequest 'fixture_vmsetup' for <Function test_positive_run_custom_job_template_by_ip>>
fixture_org = nailgun.entities.Organization(compute_resource=[], config_template=[nailgun.entities.ConfigTemplate(id=31), nailgun.en...fault_content_view=nailgun.entities.ContentView(id=173), library=nailgun.entities.LifecycleEnvironment(id=163), id=131)

    @pytest.fixture(params=distros, scope="module")
    def fixture_vmsetup(request, fixture_org):
        """Create Org, Lifecycle Environment, Content View, Activation key,
        VM, install katello-ca, register it, add remote execution key
        """
        # Create VM and register content host
> client = VirtualMachine(distro=request.param)
E AttributeError: 'SubRequest' object has no attribute 'param'
```
Furthermore, it is not reproducible locally or via standalone job. Even if clients distros is not specified in robottelo.properties, the value is defaulted to 'rhel7' by ClientsSettings class in robottelo/config/base.py. (commenting out the code passing the default value leads to the above error locally)

This doesn't happen anywhere else across the the test suite, using settings in the fixture happens just here. It happens for quite some time (sorry, been out). The start coincides with changes in #7451 though the connection is just my hypothesis for now

Quick workaround would be getting the distro value from constants.

**Comment by JacobCallahan** [comment]
Closing this issue since it has not been acted upon up until this point. Future component owners can reopen if they are going to address this.
