### ISSUE TITLE
pytest crashes when uses xdist due settings not being initialized

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#7598]
There is a regression introduced by [this action](https://github.com/SatelliteQE/robottelo/pull/7404/files?file-filters%5B%5D=.py#diff-97afc38f8ef2897f27f1d37c219f3645R167).
The method requires a settings to be initializaed (`settings.configure()`) at that point, otherwise it fails to connect to the satellite.

Since [we use](https://github.com/SatelliteQE/robottelo/pull/7404/files#diff-97afc38f8ef2897f27f1d37c219f3645R170) the `SAT_VERSION` env var in our CI, the error slipped unnoticed, as robottelo doesn't try to ssh to the server at that stage.

__to reproduce the error__:
- simply run any robottelo test with xdist (e.g. `-n1`)
- in contrast, run the same test without xdist - the error shouldn't be invoked
- or use the xdist, but pass the `SAT_VERSION` env variable - this shouldn't crash either

**Comment by rochacbruno** [comment]
Just for the record, the problem happens because Paramiko is not Thread Safe

```bash
INTERNALERROR>   File "/home/rochacbruno/Projects/satqe/robottelo/robottelo/host_info.py", line 69, in _extract_sat_version
INTERNALERROR>     ssh_result = ssh.command(ssh_cmd)
INTERNALERROR>   File "/home/rochacbruno/Projects/satqe/robottelo/robottelo/ssh.py", line 367, in command
INTERNALERROR>     timeout=connection_timeout, port=port) as connection:
INTERNALERROR>   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File "/home/rochacbruno/Projects/satqe/robottelo/robottelo/ssh.py", line 151, in get_connection
INTERNALERROR>     hostname, username, password, key_filename, timeout, port
INTERNALERROR>   File "/home/rochacbruno/Projects/satqe/robottelo/robottelo/ssh.py", line 109, in get_client
INTERNALERROR>     port=port,
INTERNALERROR>   File "/home/rochacbruno/.virtualenvs/robottelo/lib/python3.6/site-packages/paramiko/client.py", line 362, in connect
INTERNALERROR>     raise NoValidConnectionsError(errors)
INTERNALERROR> paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 127.0.0.1 or ::1
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/rochacbruno/.virtualenvs/robottelo/lib/python3.6/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0


```

**Comment by rochacbruno** [comment]
Found the real problem, to generate the report `bz_cache.json` and include the version there `.version` was being called before initialization of settings.
