### ISSUE TITLE
tox_ini update python version

### ISSUE THREAD

**Issue by tstrych** [SatelliteQE/robottelo#7636]
Do we want to update [envlist](https://github.com/SatelliteQE/robottelo/blob/master/tox.ini#L2) from `py36` to `py37` or even `py38`.

**Comment by mirekdlugosz** [comment]
Looks like Fedora 31 has Python 3.7, and I would say that's the maximum version we could use. We don't want to force people to install non-standard Python on their systems.

I'm probably the only person here who uses RHEL. In RHEL 7, RHSCL has Python 3.6. Recently I switched my robottelo to non-standard 3.7, and I take it on myself to follow up whatever group has decided.

You might have get more responses by asking that question on satqe list. Not sure how many people actively follow github issues.

**Comment by lpramuk** [comment]
What issue are we trying to solve here? 
I'm against updating it just like that

All future jenkins node will be RHEL7s (with Python 3.6) so I'm curious what troubles we have with current ```py36```?  (To balance outcomes what it solves what it could break)

**Comment by lpramuk** [comment]
@tstrych you can still install ```python36``` rpm to your F31

**Comment by tstrych** [comment]
I just want to know if there is a reason behind py36, and thanks to you @lpramuk I understand now.
