### ISSUE TITLE
content view tests to publish and promote Red Hat and Red Hat Custom (Filtered) stuff.

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#766]
Please write tests for the below content-view tests.

Pre-requisites

a) work/check functions required for manifest CRUD
b) manifest <-> stageportal integration 

test_cv_publish_rh
test_cv_publish_rh_custom_spin
test_cv_promote_rh
test_cv_promote_rh_custom_spin

**Comment by elyezer** [comment]
The tests `test_cv_publish_rh` and `test_cv_promote_rh` are already implemented.

Missing just `test_cv_publish_rh_custom_spin` and `test_cv_promote_rh_custom_spin`

**Comment by sghai** [comment]
Both of the pending tests are now renamed and has been automated.
- [test_positive_publish_with_rh_custom_spin](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_contentview.py#L1196)
- [test_positive_promote_with_rh_custom_spin](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_contentview.py#L1031)

**Comment by sghai** [comment]
Closing this issue.
