### ISSUE TITLE
UI: [test_cv_composite_create] needs to be updated with RH contents

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#769]
This test is partially implemented with custom content(puppet repo) however it needs to be updated with RH contents too. And need to remove this TODO too.

https://github.com/omaciel/robottelo/blob/master/tests/foreman/ui/test_contentviews.py#L251

**Comment by abalakh** [comment]
This issue was resolved in PR #1703. I've checked - it's working, so i'm closing the issue.

**Comment by elyezer** [comment]
:+1:
