### ISSUE TITLE
UI: Implementation to update package filter

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#778]
This should include:
- add/remove packages to/from existing filter
- edit package version
- edit affected repos

**Comment by sghai** [comment]
@ldjebran : Since you'r already working on content-views so I think you can cover this as well. Just see if this can be done in next sprint.

**Comment by abalakh** [comment]
@sghai should i just cover adding/removing/updating packages in filter or i should also publish a new version of cv and check if filter updates have any effect? Or maybe even both, e.g. tier1 tests to just update the filter, tier2 to update & publish cv?

**Comment by abalakh** [comment]
Also what exactly means `edit affected repos`?
My first idea is to automate following scenario
* have 2 repos with some packages inside 1 cv
* create filter to exclude some packages, update `affected repos` to include only 1 repo
* publish new version of cv
* check packages, only packages from not affected repo are present.

Is it good enough? As there can be much more scenarios automated, e.g. create filter for both repos, publish new version, then update the filter and check wheter updated filter works correctly?

**Comment by sghai** [comment]
@abalakh I would like to see filter published promoted with CV and we need to check if filters are really applied when we promote the repo with filters to next environment. 

I'll see the stubs in detail and get back here if something needs to be added to cover more scenarios.

**Comment by abalakh** [comment]
@sghai we don't have stubs for that, that's why i'm asking :)

**Comment by sghai** [comment]
Oh.. I didn't realize that we don't have stubs but functionality is pretty straight. In any case, if you need something just let me know.

**Comment by sghai** [comment]
Please see if we can cover scenarios like: while including/excluding packages to/from filters, user should not be able to add same package twice.

**Comment by abalakh** [comment]
@sghai that was really good suggestion as mentioned scenario fails in 6.2.z :)

**Comment by abalakh** [comment]
Resolved in #4059 and #4074
