### ISSUE TITLE
Creation automation to check OS name without a family selected

### ISSUE THREAD

**Issue by latran** [SatelliteQE/robottelo#7833]
Steps to Reproduce:
1. Hosts -> Operating Systems -> Create Operating Systems
2. Populate Name and Major Version field, but leave Family field blank.
3. Click submit

Actual results:
"icons16x16/black-%23.png"+os_name

Expected results:
os_name is present

**Comment by swadeley** [comment]
[Bug 1778503 - Prepended text on OS name creation](https://bugzilla.redhat.com/show_bug.cgi?id=1778503)
