### ISSUE TITLE
New structure for virt-who plugin cases

### ISSUE THREAD

**Issue by hkx303** [SatelliteQE/robottelo#7871]
The existing test cases for the virt-who plugin is in [test/foreman/virtwho](https://github.com/SatelliteQE/robottelo/tree/master/tests/foreman/virtwho), and its structure is as follows:
```
──test/foreman/virtwho
    ├──test_api_virtwho.py (15 cases)
    ├──test_cli_virtwho.py (10 cases)
    └──test_ui_virtwho.py (8 cases)
```

We are considering to optimize our cases to the new structure:  
```
── test/foreman/virtwho
    └── ui
        ├── test_esx.py
        ├── test_hyperv.py
        ├── test_kubevirt.py
        ├── test_libvirt.py
        ├── test_rhevm.py
        └── test_xen.py
    └── cli
        ├── test_esx.py
        ├── test_hyperv.py
        ├── test_kubevirt.py
        ├── test_libvirt.py
        ├── test_rhevm.py
        └── test_xen.py
    └── api
        ├── test_esx.py
        ├── test_hyperv.py
        ├── test_kubevirt.py
        ├── test_libvirt.py
        ├── test_rhevm.py
        └── test_xen.py
```
The reasons are:
1. We have a total of 33 cases for our existing structure. We run our test cases for 6 hypervisors, we use the `for` loop to execute the same test cases with 6 different environments. , but for the testing result, we have 33(cases)*6(hypervisors) = 198 cases. We upload the test result to Polarion, but only show 33 cases as we only have 33 different UUID.

2. We would like to make the cases more prominent for each hypervisor, such as we want to run some specific cases for the kubevirt hypervisor, then we can only add them in test_kubevirt.py file to avoid the complex decorator in the existing structure.

3. With the optimization of the structure, our test cases would be clear for some people who have not to know the virt-who plugin, it would also make it easier to integrate the plugin to Satellite Jenkins.

Do you guys have any concern or suggestion about this action, please feel free to let me know what's your opinion. Thanks.

**Comment by hkx303** [comment]
@eko999 @mirekdlugosz @vijay8451 @mshriver ^

**Comment by eko999** [comment]
Absolutely agree with you， different hypervisors should have different specific cases, this new structure not only can help to optimize the cases organization, but also to reduce the test time for our testing.

**Comment by eko999** [comment]
@hkx303 It's not a quick implement because many new changes involved,  we may create a new branch for this and then do it step by step.

**Comment by hkx303** [comment]
> @hkx303 It's not a quick implement because many new changes involved, we may create a new branch for this and then do it step by step.

ok:)

**Comment by hkx303** [comment]
Created the new branch: [new_struc_for_virtwho_plugin](https://github.com/SatelliteQE/robottelo/tree/new_struc_for_virtwho_plugin)
