### ISSUE TITLE
Cannot select keys from dict for a CRUD test

### ISSUE THREAD

**Issue by latran** [SatelliteQE/robottelo#7931]
There's a test case `tests/foreman/cli/test_product.py::ProductTestCase::test_positive_CRUD` that fails at `valid_data_list()[0]`.  For some reason, it's returning a random key from the the dict so you cannot choose which key to process.  I'm not entire sure of what to do or how to fix this at all.  Does anybody have any suggestions?

**Comment by swadeley** [comment]
Hello

I believe this is due to changes made in:
https://github.com/SatelliteQE/robottelo/pull/7824

See some examples of how to overcome that:
https://github.com/SatelliteQE/robottelo/pull/7901/files
https://github.com/SatelliteQE/robottelo/pull/7922

**Comment by mshriver** [comment]
Fixed by #7934

**Comment by latran** [comment]
This is fixed.
