### ISSUE TITLE
Revert merge of Filter: Resourch Type changes for roles #7928

### ISSUE THREAD

**Issue by swadeley** [SatelliteQE/robottelo#7958]
Hello @latran @mirekdlugosz 

this change needs to be reverted:
https://github.com/SatelliteQE/robottelo/pull/7928

git commit in master is:

    `robottelo]$ git show 8496a8c0439fe37baf478e94fe08aa66c8bf994e
    commit 8496a8c0439fe37baf478e94fe08aa66c8bf994e
    Author: ltran <ltran@redhat.com>
    Date:   Mon Aug 10 19:37:49 2020 -0400

    Filter: Resourch Type changes for roles
    Resource Type does not have blank selection anymore.  It's changed to '(Miscellaneous)'`

These tests fail with the change in master:
tests/foreman/ui/test_lifecycleenvironment.py::test_positive_custom_user_view_lce
tests/foreman/ui/test_repository.py::test_positive_create_as_non_admin_user_with_cv_published
tests/foreman/ui/test_repository.py::test_positive_create_as_non_admin_user

In all cases you will see "results": []

    `DEBUG    nailgun.client:client.py:121 Received HTTP 200 response: {
                                        "total": 312,
                                        "subtotal": 0,
                                        "page": 1,
                                        "per_page": 350,
                                        "search": "resource_type=\"(Miscellaneous)\"",
                                        "sort": {
                                          "by": null,
                                          "order": null
                                        },
                                        "results": []
                                      }
`

**Comment by swadeley** [comment]
If I revert the change:

    robottelo]$ git revert 8496a8c0439fe37baf478e94fe08aa66c8bf994e
    Auto-merging tests/foreman/ui/test_repository.py
    [master 4feb2bf2] Revert "Filter: Resourch Type changes for roles"
     3 files changed, 4 insertions(+), 4 deletions(-)


then all  three tests pass:

robottelo]$ pytest tests/foreman/ui/test_lifecycleenvironment.py::test_positive_custom_user_view_lce
============================================== test session starts ===============================================
platform linux -- Python 3.7.8, pytest-4.6.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/sjw/sat6/robottelo_1/robottelo
plugins: xdist-2.0.0, services-1.3.1, mock-1.10.4, forked-1.3.0, cov-2.10.1
collecting ... 2020-08-27 08:22:34 - conftest - DEBUG - Collected 1 test cases
collected 1 item                                                                                                 

tests/foreman/ui/test_lifecycleenvironment.py .                                                            [100%]
==== 1 passed, 3 warnings in 93.12 seconds ====


robottelo]$ pytest tests/foreman/ui/test_repository.py::test_positive_create_as_non_admin_user_with_cv_published


============================================== test session starts ===============================================
platform linux -- Python 3.7.8, pytest-4.6.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/sjw/sat6/robottelo_1/robottelo
plugins: xdist-2.0.0, services-1.3.1, mock-1.10.4, forked-1.3.0, cov-2.10.1
collecting ... 2020-08-27 08:22:36 - conftest - DEBUG - Collected 1 test cases
collected 1 item                                                                                                 

tests/foreman/ui/test_repository.py .                                                                      [100%]
======== 1 passed, 5 warnings in 157.44 seconds =========

robottelo]$ pytest tests/foreman/ui/test_repository.py::test_positive_create_as_non_admin_user
============================================== test session starts ===============================================
platform linux -- Python 3.7.8, pytest-4.6.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/sjw/sat6/robottelo_1/robottelo
plugins: xdist-2.0.0, services-1.3.1, mock-1.10.4, forked-1.3.0, cov-2.10.1
collecting ... 2020-08-27 08:22:39 - conftest - DEBUG - Collected 1 test cases
collected 1 item                                                                                                 

tests/foreman/ui/test_repository.py .                                                                      [100%]
====== 1 passed, 5 warnings in 90.68 seconds =====

**Comment by mirekdlugosz** [comment]
Tests were failing, we introduced #7928 to fix them and they passed, and 2 weeks later they are failing again, but will pass if we revert #7928 ? Is that fair summary, or am I missing something?

**Comment by swadeley** [comment]
> Tests were failing, we introduced #7928 to fix them and they passed, and 2 weeks later they are failing again, but will pass if we revert #7928 ? Is that fair summary, or am I missing something?

Yes, you are missing what I wrote here https://github.com/SatelliteQE/robottelo/pull/7928#issuecomment-672866301

**Comment by mirekdlugosz** [comment]
I guess comments made after PR was merged don't get much attention...

I see all tests modified in #7928 are failing in latest report portal run. If reverting this PR can help, I'll ACK that. If you need further help in analysis and debugging, let's talk outside of business.

**Comment by swadeley** [comment]
> I guess comments made after PR was merged don't get much attention...
> 
A bit like making comments on a closed bugzilla, except that I did tag people by name, so I was expecting e-mails to work; seems not. 

> I see all tests modified in #7928 are failing in latest report portal run. If reverting this PR can help, I'll ACK that. If you need further help in analysis and debugging, let's talk outside of business.

I will create PR using revert link in https://github.com/SatelliteQE/robottelo/pull/7928
