### ISSUE TITLE
Fix failing test api.test_ldapauthsource.test_positive_endtoend[AD] 

### ISSUE THREAD

**Issue by JacobCallahan** [SatelliteQE/robottelo#8581]
tests.foreman.api.test_ldapauthsource.test_positive_endtoend[AD] is newly failing in the latest snap

Most relevant error:
`2021-05-06 01:00:41 - nailgun.client - WARNING - Received HTTP 422 response: {
  "error": {"id":null,"errors":{"host":["can't be blank"]},"full_messages":["Server can't be blank"]}
}`

**Comment by omkarkhatavkar** [comment]
This will be fix automatically after merge of https://github.com/SatelliteQE/robottelo/pull/8535,

we can see the test result for this test is passing. This is currently happening because the configuration PR got merge but implementation PR still in review.

**Comment by Gauravtalreja1** [comment]
Above PR seems to fix mentioned test, and it passes in latest runs, this issue can be closed.
