### ISSUE TITLE
Failure in test_positive_assign_http_proxy_to_products for automation

### ISSUE THREAD

**Issue by latran** [SatelliteQE/robottelo#8748]
Something may have failed in the http_proxy setup.  @jameerpathan111 can you please check this since you've written this?  It would help in keeping this test file pass with all green.  Thanks!

**Comment by jameerpathan111** [comment]
@latran The test is failing because of https://bugzilla.redhat.com/show_bug.cgi?id=1992967. I will skip it till the bz is fixed or add a workaround.
