### ISSUE TITLE
Support for email functionaity

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#9]
Support for sending / reviewing user emails
Example: Forgot Password scenario, Forgot Username scenario

**Comment by elyezer** [comment]
I've done more investigation on this and have found the following:

* "Play with email without worrying about sending to live addresses! " - https://github.com/pboling/sanitize_email
* We can also add a script on Satellite server and make rails use it to deliver email like demonstrated on http://stackoverflow.com/a/25393945/1606777

**Comment by elyezer** [comment]
I will close this issue for the following reasons:

* Is not easy to change Satellite 6 email configuration on the fly.
* Will require a SMTP server that will act as a service capturing all email received during a test case.

With the above said, we will need to develop/find a SMTP server where we can get all emails sent to it thru a API, configure Satellite server to send emails to that service (automation-tools job).

Other option is to make Satellite save the emails on files on the server and inspect/retrieve them using ssh. Again this is something that is more automation-tools related than robottelo.
