### ISSUE TITLE
Skip decorators should allow skip an entire TestCase

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#936]
When trying to skip a entire TestCase by decorating it with `skip_if_bz_bug_open` (the same could happen for `skip_if_rm_bug_open`) the following exception occurs:

```
Traceback (most recent call last):
  File "/.virtualenvs/robotello/lib/python2.7/site-packages/nose/case.py", line 267, in setUp
    try_run(self.test, names)
  File "/.virtualenvs/robotello/lib/python2.7/site-packages/nose/util.py", line 470, in try_run
    return func()
TypeError: setUp() takes exactly 1 argument (0 given)
```

As the standard `unittest.skip` the skips decorators should allow skipping an entire TestCase.

**Comment by rochacbruno** [comment]
@elyezer @Ichimonji10 is this still opened issue to work on?

**Comment by Ichimonji10** [comment]
I'm out of touch with the state of Robottelo.

**Comment by rochacbruno** [comment]
@oshtaier @abalakh do you know if this issue still valid or if we can close? (I remember I saw some decorators to skip entire class)

**Comment by elyezer** [comment]
As far as I remember, there are some classes which required some entire class skip and the proposed solution was to apply the decorator on the setUp method or setUpClass. I don't know if this still needed or not, few free to close if you find it is not needed anymore.

**Comment by rochacbruno** [comment]
I confirmed this is not an issue anymore, example of working case: https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_hostgroup.py#L1063
