### ISSUE TITLE
CLI boundary testing

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#981]
Assure proper positive and negative testing of each parameter
   * Non-exhaustive examples of Positive: 
       - [ ] UTF-8 data entered as parameter
       - [ ] Proper/expected field data CRUD
   * Non-exhaustive examples of Negative
       - [ ] ascii text in a numeric parameter and vice versa
       - [ ] real values in an integer parameter?
       - [ ] Very large numbers entered where integer parameter is expected
       - [ ] Negative numbers entered where integer parameter is expected
   * TASK (break into digestible pieces)
       1. [P1] Compute Resource CRUD
       2. [P1] Subnet CRUD
       3. [P1] Domains CRUD
       4. [Px] Unspecified others, the P1s above ought to be plenty for now.

**Comment by elyezer** [comment]
The specified entities boundary tests was handled by #1178 and #1335. Closing this as more issues will be open for other entities as needed.
